### ISSUE TITLE
Number of listed OSCAL identifier types on models introduction page

### ISSUE THREAD

**Issue by zbraiterman** [usnistgov/OSCAL#1019]
The “Identifier Use” section of the “Introduction to the OSCAL Models” page ( https://github.com/usnistgov/OSCAL/blob/main/docs/content/concepts/layer/overview.md ) states that “The OSCAL models make use of three types of identifiers”.  However, only 2 are listed in that section.

**Comment by david-waltermire-nist** [comment]
This will be addressed by #860 and PR #941. Closing this in favor of the other issue/PR.
