### ISSUE TITLE
JSON to XML converter issue

### ISSUE THREAD

**Issue by vikas-agarwal76** [usnistgov/OSCAL#1020]
The command mentioned on https://github.com/usnistgov/OSCAL/tree/v1.0.0/xml for converting from JSON to XML format -

java -jar "saxon9he.jar" -xsl:"oscal_catalog_json-to-xml-converter.xsl" -o:"oscal-catalog.xml" -it json-file="oscal-catalog.json"

 is not working. It seems the xsl files in https://github.com/usnistgov/OSCAL/tree/v1.0.0/xml/convert where updated in recent releases and the above command needs to be updated.

Kindly provide the updated command.

**Comment by david-waltermire-nist** [comment]
@wendellpiez Please provide a PR that updates the XML and JSON readmes as needed.

**Comment by wendellpiez** [comment]
Apologies @vikas-agarwal76 this fell behind.

For now, try (with adjustments for quote marks)

```
> java -jar "saxon9he.jar" -xsl:"oscal_catalog_json-to-xml-converter.xsl" -o:"oscal-catalog.xml" -it:from-json file=yourjsonfile.json
```

But I am looking at the source; tomorrow I will test and update the readme.

Detail: the `-it` flag on the command line identifies the initial template https://github.com/usnistgov/OSCAL/blob/6246c5f4f4d879dcd5ff17e861ffdea0951fa76d/xml/convert/oscal_catalog_json-to-xml-converter.xsl#L17

the `file` parameter gives the path to your JSON file (relative or absolute URI) https://github.com/usnistgov/OSCAL/blob/6246c5f4f4d879dcd5ff17e861ffdea0951fa76d/xml/convert/oscal_catalog_json-to-xml-converter.xsl#L14

Saxon command line syntax is given in detail at https://www.saxonica.com/documentation10/index.html#!using-xsl/commandline

**Comment by vikas-agarwal76** [comment]
Thanks @wendellpiez The above command works.

But when I run the SSP json to xml convertor - 
https://github.com/usnistgov/OSCAL/blob/v1.0.0/xml/convert/oscal_ssp_json-to-xml-converter.xsl 
on a FedRAMP template SSP from -
https://github.com/GSA/fedramp-automation/blob/master/dist/content/templates/ssp/json/FedRAMP-SSP-OSCAL-Template.json
I get some exceptions even though the file gets converted to XML  -

Warning 
  XTDE0540: Ambiguous rule match for /map/map[1]/map[1]/array[6]/map[1]/string[1]
Matches both
  "element(Q{http://www.w3.org/2005/xpath-functions}array)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}key)))) eq "responsible-parties"]/element(Q{http://www.w3.org/2005/xpath-functions}map)/element(Q{http://www.w3.org/2005/xpath-functions}string)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}key)))) eq "role-id"]" on line 799 of file:/Users/admin/Documents/MyData/data/Projects/fedramp-validation/nist-source/xml/convert/oscal_ssp_json-to-xml-converter.xsl
and "element(Q{http://www.w3.org/2005/xpath-functions}string)[(Q{http://www.w3.org/2001/XMLSchema}string(data(@key))) eq "role-id"]" on line 550 of file:/Users/admin/Documents/MyData/data/Projects/fedramp-validation/nist-source/xml/convert/oscal_ssp_json-to-xml-converter.xsl
Warning 
  XTDE0540: Ambiguous rule match for /map/map[1]/map[1]/array[6]/map[2]/string[1]
Matches both
  "element(Q{http://www.w3.org/2005/xpath-functions}array)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}key)))) eq "responsible-parties"]/element(Q{http://www.w3.org/2005/xpath-functions}map)/element(Q{http://www.w3.org/2005/xpath-functions}string)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}key)))) eq "role-id"]" on line 799 of file:/Users/admin/Documents/MyData/data/Projects/fedramp-validation/nist-source/xml/convert/oscal_ssp_json-to-xml-converter.xsl
and "element(Q{http://www.w3.org/2005/xpath-functions}string)[(Q{http://www.w3.org/2001/XMLSchema}string(data(@key))) eq "role-id"]" on line 550 of file:/Users/admin/Documents/MyData/data/Projects/fedramp-validation/nist-source/xml/convert/oscal_ssp_json-to-xml-converter.xsl
Warning 
  XTDE0540: Ambiguous rule match for /map/map[1]/map[1]/array[6]/map[3]/string[1]
Matches both
  "element(Q{http://www.w3.org/2005/xpath-functions}array)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}key)))) eq "responsible-parties"]/element(Q{http://www.w3.org/2005/xpath-functions}map)/element(Q{http://www.w3.org/2005/xpath-functions}string)[(Q{http://www.w3.org/2001/XMLSchema}string(data(attribute::attribute(Q{}key)))) eq "role-id"]" on line 799 of file:/Users/admin/Documents/MyData/data/Projects/fedramp-validation/nist-source/xml/convert/oscal_ssp_json-to-xml-converter.xsl
and "element(Q{http://www.w3.org/2005/xpath-functions}string)[(Q{http://www.w3.org/2001/XMLSchema}string(data(@key))) eq "role-id"]" on line 550 of file:/Users/admin/Documents/MyData/data/Projects/fedramp-validation/nist-source/xml/convert/oscal_ssp_json-to-xml-converter.xsl

and so on.

**Comment by wendellpiez** [comment]
@vikas-agarwal76 @david-waltermire-nist that appears to be an honest bug in the converter. We will have to look at this separately.

We are currently developing alternate pathways supporting JSON-XML conversion so there may (also) be an interim solution to offer while we do so (what do you think DW)?

**Comment by vikas-agarwal76** [comment]
@wendellpiez Based on our chat on gitter, here is the python code fragment that I am using to do the JSON to XML conversion programmatically (instead of from command line) -
```
           xslt_proc = saxon_proc.new_xslt30_processor()

            # set initial template name in XSL file
            xslt_proc.set_property('it', 'from-json')
            # Set the input json file parameter for conversion
            xslt_proc.set_parameter(
                'file', saxon_proc.make_string_value(str(file_path))
            )

            xml_str = xslt_proc.transform_to_string(
                stylesheet_file=str(xsl_path)
            )
            print(xml_str)
```
but I get "None" as output and there are no errors reported.
The "file_path" and "xsl_path" variables are same as I am using on the command line (which works).

**Comment by wendellpiez** [comment]
As I understand it, we have not only interface enhancements (see usnistgov/metaschema#174) but a possible bug in the SSP (related to role-id), inasmuch as no runtime warning messages from template clashes should ever be emitted.

To close this issue we should ensure that the SSP converter in particular works with all valid inputs we have tried and that they come through cleanly and correctly without useless warnings.
