### ISSUE TITLE
Approval Status and Date for Specific Portions of an OSCAL Document Instance

### ISSUE THREAD

**Issue by ohsh6o** [usnistgov/OSCAL#1034]
# User Story:

As an OSCAL tool developer, in order to allow my tools to show that different stakeholders from the organization authoring the information system's security documentation (SSP, SAP, SAR, and/or POA&M) had approved specific portions of a document, I want to add metadata to show the responsible parties for approval and dates of these approvals for these specific portions.

## Goals:

Per discussion during the last week's model meeting, we will want to take the work of usnistgov/OSCAL#1033 and then make the approver and date tracking to be made more specific to not the overall document instance, but specific portions of the document (that was presumably updated).

See GSA/fedramp-automation#162 for more context.

## Dependencies:

Completion of usnistgov/OSCAL#1033 prior to starting this work.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
Talked with @ohsh6o / @aj-stein-nist. he is good with closing this issue.
