### ISSUE TITLE
Markdown documentation glitch in datatypes page

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#1037]
# Describe the bug

On the page https://pages.nist.gov/OSCAL/reference/datatypes/#markup-data-types the subsection **Parameter Insertion** is out of date. For one thing, `<insert>` no longer carries a `param-id` but rather an `id-ref` along with a `type`. The Markdown syntax representation has also changed from simple `{{ targetID }}` to `{{ insert: type, targetID }}`.

This spec is also a bit hard to find.

# Who is the bug affecting?

Users of the docs who need to understand insertions and parameters.

# What is affected by this bug?

Potentially anyone reading the docs especially learners.

# Expected behavior (i.e. solution)

- Document the current models and expected usage(s).
- Perhaps talk about other types of insert targets, not parameters? Or state that as a tbd.
- Spinoff: a tutorial specifically about how to use insertions?

**Comment by aj-stein-nist** [comment]
I talked to Dave and I will quickly pick this one up so we can prep for it for 1.0.1 release.
