### ISSUE TITLE
Profile Spec - Intro rewrite/trim

### ISSUE THREAD

**Issue by stephenbanghart** [usnistgov/OSCAL#1043]
https://github.com/usnistgov/OSCAL/pull/1017#discussion_r707455138
https://github.com/usnistgov/OSCAL/pull/1017#discussion_r703616823
https://github.com/usnistgov/OSCAL/pull/1017#discussion_r720275113
https://github.com/usnistgov/OSCAL/pull/1017#discussion_r720335188
https://github.com/usnistgov/OSCAL/pull/1017#discussion_r720341313
https://github.com/usnistgov/OSCAL/pull/1017#discussion_r720342241
https://github.com/usnistgov/OSCAL/pull/1017#discussion_r720347236

Address above comments and finish rework and trim of intro section. May overlap with #1039 as some text can be moved to a containing page on the website.

**Comment by david-waltermire-nist** [comment]
@david-waltermire-nist will review the comments above to make sure they are addressed in PR #1089.

**Comment by david-waltermire-nist** [comment]
Addressed by PR #1089.
