### ISSUE TITLE
Profile parameter interpretation

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#106]
Currently, "Profile" parameter values are completely ambiguous. The schema also only allows simple text values (`value = element value { text }`). As such, it is left up to "Implementation" to interpret, parse and implement these parameter values. I'm curious if there's a way we can mitigate the level of effort that a system "Implementer" would have to put in to interpret these values by also allowing numeric types. This would simplify parsing of param values that can be easily represented numerically.

@wendellpiez, thoughts?

**Comment by anweiss** [comment]
On the JSON side of things, something that might help and that we can already take advantage today with JSON schema draft-07  is that of conditional schema evaluation provided by the `if`, `then` and `else` keywords. Here's an example (courtesy of https://stackoverflow.com/a/38781027):

```
{
  "type": "object",
  "properties": {
    "foo": { "type": "string" },
    "bar": { "type": "string" }
  },
  "if": {
    "properties": {
      "foo": { "enum": ["bar"] }
    }
  },
  "then": { "required": ["bar"] }
}
```

If the `foo` property equals `bar`, then the `bar` property is required.

Granted, this only applies to property names and not there actual values. Conditions based on property values won't be made available until draft-09 of JSON schema which is due in November.

**Comment by david-waltermire-nist** [comment]
These requirements should be considered as part of #474. Closing this issue in favor of the new issue.
