### ISSUE TITLE
Grouping of Properties in OSCAL documents other than Catalog

### ISSUE THREAD

**Issue by degenaro** [usnistgov/OSCAL#1064]
# User Story:

As an OSCAL tool developer, I would like `Properties` to be optionally groupable in order to differentiate different sets of `Properties` from each other.

For example: one set of `Properties` may apply at integration time while another set of `Properties` may apply at deployment time; or one set of `Properties` may apply during development while a different set of `Properties` may apply during production.

An existing grouping example is under OSCAL `Catalog`, where `Group` is permitted to contain `params, props...groups`. It would be useful to have a grouping mechanism especially for `Properties` in other documents such as `Component Definition`, `Profile` and `Assessment Results`. 

## Goals:

The ability to group Properties in in OSCAL documents besides Catalog, such as Component Definition, Profile and Assessment Results.

- [x] Add a `group` flag to the property Metaschema definition
- [ ] Develop a concrete example
- [ ] Socialize this during an OSCAL model review.
- [ ] Collect feedback, and identify any follow-on work if needed.

## Dependencies:

N/A

## Acceptance Criteria

- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
It was proposed on the 12/10/2021 model review to add a new flag that would allow for grouping of related properties. This grouping would be scoped to the containing object. A UUID can be used as the grouping value (or maybe a token).

We need some concrete XML, JSON, or YAML examples of what this would look like. @degenaro can you provide some?

**Comment by degenaro** [comment]
Here's an example of using remarks to form groups (thanks, Vikas).

[profile.json.zip](https://github.com/usnistgov/OSCAL/files/7728615/profile.json.zip)

**Comment by aj-stein-nist** [comment]
Thanks for the contribution, @degenaro and @vikas-agarwal76. We shall take a look. In the future, you might benefit from using [GitHub Gists like this to post examples](https://gist.github.com/aj-stein-nist/46f3e50373622c90b6f684b6deb22a73) for issues to refine samples!

**Comment by david-waltermire-nist** [comment]
This has been discussed on a previous OSCAL model review. An option that was discussed was to add a grouping flag to a property and link to allow grouped properties and links to identify their grouping. We should work up a proposal for how this might work.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist, where should I set up a concrete example so I can socialize and work down the goals and AC checklist for the issue?

**Comment by david-waltermire-nist** [comment]
This has been merged into develop and will be included in OSCAL 1.1.
