### ISSUE TITLE
Component types in presentation of leveraged authorization do not exist in standards enumerated list of component types

### ISSUE THREAD

**Issue by gregelin** [usnistgov/OSCAL#1083]
# Describe the bug

A NIST presentation on component types includes SSP code examples that show component type as "leveraged-system" and other types that do not exist in the OSCAL 1.0.0 standard enumerated list of accepted values for component types.

# Who is the bug affecting?

This bug effects all developers working with OSCAL, particularly vendors working to implement the code.

# What is affected by this bug?

Contradictory examples between presentation/documentation and standard creates great confusion in organizations seeking to adopt OSCAL.

# How do we replicate the issue?

Just cross reference the pages. See images below.

From code example on GitHub demonstrating leveraged authorizations.

<img width="989" alt="Screen Shot 2022-01-12 at 4 34 52 PM" src="https://user-images.githubusercontent.com/24979/149234427-f6ead3c9-8e40-4c25-bed4-261b7ad191c7.png">

OSCAL 1.0.0 list of component types
<img width="960" alt="Screen Shot 2022-01-12 at 4 35 12 PM" src="https://user-images.githubusercontent.com/24979/149234544-33bf8ae1-8e14-4050-acfe-8674221a8458.png">

# Acceptance Criteria

- [x] Modify examples, specifically [this one](https://github.com/usnistgov/oscal-content/blob/a3231bb614510cd0832895a1e30fa7716add22a3/examples/ssp/xml/oscal_leveraging-example_ssp.xml#L137) and others to use the correct `component/@type`.
- [x] Update the presentation if applicable.
- [ ] If assigned developer(s) decide to, clarify wording in the documentation string [for the model](https://github.com/usnistgov/OSCAL/blob/b41b5da4798a1f7fd184385cd145bb0be7f1935c/src/metaschema/oscal_implementation-common_metaschema.xml#L240) around "other side of interconnection"

**Comment by aj-stein-nist** [comment]
Good catch! FYI, the way the words are written in the constraint spec are determined by the Metaschema definition, and that references [a shared entity that gets rendered into the form you show in the later screenshot](https://github.com/usnistgov/OSCAL/blob/eaf1bf51d546dc0a21e6b98c1cdd0cb63f499057/src/metaschema/shared-constraints/allowed-values-component-type.ent) [and is de-referenced here](https://github.com/usnistgov/OSCAL/blob/b41b5da4798a1f7fd184385cd145bb0be7f1935c/src/metaschema/oscal_implementation-common_metaschema.xml#L234-L245) for the final product with `allow-other="yes"`. That means the list enumeration _is not strict_, and you _are not limited_ to only things in that list. You can put other things too.

Doesn't mean adding it back isn't helpful, but not a major issue.

**Comment by david-waltermire-nist** [comment]
We need to figure out which component types to add to the OSCAL component definition and SSP metaschemas. We can then make any updates to the related slides and examples.

**Comment by gregelin** [comment]
@aj-stein-nist May have been one of these two presentations:

- https://pages.nist.gov/OSCAL/presentations/oscal-leveraged-authorizations-v6a.pdf
- https://pages.nist.gov/OSCAL/presentations/oscal-leveraged-authorizations-v2.pdf

**Comment by iMichaela** [comment]
@aj-stein-nist and @gregelin - the specification indicates the component type for a leveraged-authorization should be `system`. The simplest way to fix it, would be to update the presentation. But I wonder if you, @gregelin , see a need for a specific type `leveraged-authorization` vs the type `system` which would be an interconnected system in the security assessment automation process (for leveraging system, the ATO depends on the ATO of the leveraged system - see FedRAMP market place; for the interconnected system the control provided is deficient if the ATO of the interconnected system is not in good standing).  
Also - where and how will the CRM/SSRM be used ? Will the SSRM be a SSRM component or it will simply be a `leveraged-authorization` component and the chosen solution here will fit the CRM/SSRM too? (food for thoughts, for @Compton-NIST and @nbg84 )

**Comment by aj-stein-nist** [comment]
> The simplest way to fix it, would be to update the presentation.

That and aligning the examples. I can add updating the presentation to the AC. The other questions and comments are meaningful, they are just beyond the scope of this fix, right?

**Comment by gregelin** [comment]
@aj-stein-nist @iMichaela The simplest clarifying change that can be made to bring all content into alignment for the primary use case is seems the right choice. (I've been adopting a "Take the win," approach to things lately.)

FedRAMP Data Bites (Volpes) gave a presentation recently on leveraging systems and availability of leveraged SSP. Probably wise to confirm that OSCAL and FedRAMP presentations and materials are also well-aligned on the type. Important for closing this issue to not create new divergence.

I think additional types of leveraging is suitable for additional issue tickets and discussions. It is interesting to think about other configurations as per @vmangat [observation in #1729](https://github.com/usnistgov/OSCAL/pull/1729#issuecomment-1494336395). And I think the larger topic of CRM is a separate issue relating to complexity issue that [I mentioned in #1729](https://github.com/usnistgov/OSCAL/pull/1729#issuecomment-1492798117). Important topics for separate research and discussion.

**Comment by aj-stein-nist** [comment]
This issue should be completed once the team reviews and the two connected PRs are merged. Setting this issue to "under review."
