### ISSUE TITLE
Profile Resolution Requirement Tagging

### ISSUE THREAD

**Issue by stephenbanghart** [usnistgov/OSCAL#1086]
# User Story:

For both internal NIST development and ease of use by downstream, the Profile Resolution Specification could provide inline tagging that identifies requirements. Tagging each requirement (using surrounding XML tags) allows for requirement indexing and breakouts.

Dependency for #1087  to create the requirement index.

## Goals:

All requirements, that is, any phrase or sentence that contains MUST, SHOULD, MAY, RECOMMENDED, or NOT, is tagged in the source XML of the Profile Resolution Specification.

**Comment by david-waltermire-nist** [comment]
Addressed by PR #1089.
