### ISSUE TITLE
Content Upgrade Converters Do Not Check or Fix Up xsi:schemaLocation

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1093]
# Describe the bug

Given a well-formed OSCAL document instance (`catalog`, `profile`, `system-security-plan`) with a valid `xsi:schemaLocation` for a particular version of OSCAL pinned and not using the development tags (`main` or `master` or `develop`), a document instance can be upgraded by any of the converters and will attempt to validate the upgraded document (now `<oscal-version>1.0.0</oscal-version>` using) that is purportedly validating against the schema of a previous version (previously `<oscal-version>1.0.0-rc2</oscal-version>`), leading to confusing errors.

# Who is the bug affecting?

Downstream tool developers using OSCAL who will convert existing content from prior versions to OSCAL 1.0.0.

# What is affected by this bug?

Holistic end-to-end upgrades of content when using the content-upgrade converters.

# When does this occur?

Consistently when `xsi:schemaLocation` is defined in a document.

# How do we replicate the issue?

1. Add `xsi:schemaLocation` to a document model in `v1.0.0-rc2` defined as `xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/1.0 https://raw.githubusercontent.com/usnistgov/OSCAL/v1.0.0-rc2/xml/schema/oscal_catalog_schema.xsd"`
1. Use the content upgrade converter [`oscal-rc2-v1-0-0-update.xsl`](https://github.com/usnistgov/OSCAL/blob/cf9693ce4ecdef184ca3c857b030ce8582620275/src/release/content-upgrade/oscal-rc2-v1-0-0-update.xsl) for the document in oXygenXML
1. See errors from using the old schema location

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

The schema location is fixed or a warning message is displayed.

# Other Comments

This may appear to be an edge case but we should be encouraging everyone to have invalid schema validation as a best practice to catch errors as soon as possible, especially in the case of ad hoc editing in the many text editors that, by default or with low-effort configuration, will perform XSD validation on the fly.

See related request here in usnistgov/oscal-content#89.

**Comment by wendellpiez** [comment]
@aj-stein-nist by "schema location is fixed" you mean that the directive in the xsi:schemaLocation attribute should be rewritten to point to the new schema, or should be removed altogether?

Perhaps a good solution for users would be to support a runtime parameter designating the attribute value for the (nominal) schema location. `schemaLocation` would be rewritten or removed if no value is given. (I agree that preserving it can lead to confusion but I also agree that the deeper solution will be in user education. Nonetheless,  it seems right to me to remove a setting that we know is likely to be wrong.)

That sound right? Care to look over my shoulder when I do this?

**Comment by aj-stein-nist** [comment]
> `schemaLocation` would be rewritten or removed if no value is given.

Rewritten for the public URL on raw.githubusercontent.com.

> That sound right? Care to look over my shoulder when I do this?

Yes, I would definitely like to look over your shoulder or help author it myself.

**Comment by wendellpiez** [comment]
@aj-stein-nist I discussed this with @david-waltermire-nist today and propose (consistent with his guidance):

- accept a runtime string parameter `schemaLocation`
- when parameter is set, replace or add `xsi:schemaLocation` with parameter value given
- when it is not set, remove any `xsi:schemaLocation` given
  - with a warning
  - (or not, if another runtime parameter is set to silence it?)
- document how to set up to bind results to any schema, including raw file on Github

Suggest we put this in a standalone bit of XSLT that can be included from each of the discrete update filter XSLTs.

Let's schedule a time at mutual convenience when we can work this?

**Comment by aj-stein-nist** [comment]
> Let's schedule a time at mutual convenience when we can work this?

Yessir, I look forward to it. Will look for some time on our calendar, maybe early next week? I don't have a good block of contiguous time tomorrow and probably should work some other things in the queue first. :-)
