### ISSUE TITLE
Metaschema Schematron Validation Checks Issues

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1107]
# Describe the bug

As part of usnistgov/metaschema#164, usnistgov/metaschema#172 removed (actually renamed, but the `git` commands did not detect a move, not just a delete) from `metaschema-check.sch` -> `metaschema-composition-check.sch`. The embedded `xml-model` processing instructions point to the old files, which is why I was missing some validation errors. When using oXygenXML, this means the validations are not running by default.

Additionally, it seems the `validate-schema.sh` file only validates the composite 7 final model documents, but the Schematron is not being run on the `import`ed library Metaschema modules (such as `oscal_control-common_metaschema.xml`). Will need to determine if that is intentional or not.

# Who is the bug affecting?

NIST OSCAL developers

# What is affected by this bug?

Local development of model changes with oXygenXML for sanity checks before running through CI/CD pipelines or pushing up to GitHub for review.

# When does this occur?

Consistently

# How do we replicate the issue?

1. Make an intentionally malformed update to any Metaschema model
2. Observe in OxygenXML when editing there always be 1 error, that "The system cannot find the specified file" for `metaschema-check.sch`. 

![image](https://user-images.githubusercontent.com/94922603/151058677-5c749b55-024b-42e0-b6d4-5ebd7d2fe898.png)

# Expected behavior (i.e. solution)

It validates correctly with the proper Schematron file.

# Other Comments

N/A

**Comment by aj-stein-nist** [comment]
This should be closed by #1108. Talking to Dave, not sure why linked PRs with `closes #XYZ` commits and PR messages are not closing properly. This wasn't the only one.

**Comment by GaryGapinski** [comment]
\<oXygen/\> XML Editor has an `Options->Preferences->XML->XML Catalog->Verbosity->Unresolved entities` setting that will indicate failures (though it can be rather prolix).
