### ISSUE TITLE
Remarks fields in SSP defined as `string` instead of `#field_oscal-metadata_remarks`

### ISSUE THREAD

**Issue by guyzyl** [usnistgov/OSCAL#1130]
# Describe the bug

In the SSP schema, there are a 2 models that contain a `remarks` field that is defined with `"type": "string"` instead of `"$ref": "#field_oscal-metadata_remarks"`

The places are:
- `#assembly_oscal-ssp_diagram`
- `#assembly_oscal-ssp_authorization-boundary`

They should be updated to use `#field_oscal-metadata_remarks`.

# What is affected by this bug?

The bug doesn't have a critical effect since `#field_oscal-metadata_remarks` is defined as a `string`, therefore there's no type mismatch.
It does however harm the conformity of the schema, and should be fixed.

# Other Comments

I'd be happy to open a PR for this if this if this is approved as a bug.

**Comment by david-waltermire-nist** [comment]
@guyzyl The [SSP Metaschema](https://github.com/usnistgov/OSCAL/blob/main/src/metaschema/oscal_ssp_metaschema.xml) needs to be updated for these. This will cause the JSON schema to be generated properly.

- https://github.com/usnistgov/OSCAL/blob/c221bb1fd85455f61ba9b66c3290efbfa3d9266c/src/metaschema/oscal_ssp_metaschema.xml#L401
- https://github.com/usnistgov/OSCAL/blob/c221bb1fd85455f61ba9b66c3290efbfa3d9266c/src/metaschema/oscal_ssp_metaschema.xml#L442

You interested in submitting a PR to do this? Would you also be interested in checking and fixing any similar issues in the other metaschemas?
