### ISSUE TITLE
`include-all` type mismatch between Profile and Assessment Plan

### ISSUE THREAD

**Issue by guyzyl** [usnistgov/OSCAL#1137]
# Describe the bug

Both the Profile and the Assessment Plan schemas have models that contain an `include-all` field.

In the Profile schema they are:
- `#assembly_oscal-profile_insert-controls`
- `#assembly_oscal-profile_import`

In Assessment Plan they are:
- `#assembly_oscal-assessment-common_reviewed-controls.control-selection`
- `#assembly_oscal-assessment-common_reviewed-controls.control-objective-selections`
- `#assembly_oscal-assessment-common_assessment-subject`

The problem is that there's a mismatch in the `include-all` field's types between the Profile and Assessment Plan.
In the Profile schema they are of type `#assembly_oscal-profile_include-all`, compared to Assessment Plan where they defined as `object`.

The solution to this issue is to convert the Assessment Plan's `include-all` fields to be of type `#assembly_oscal-profile_include-all`.
Since they're currently accepting type `object` and `#assembly_oscal-profile_include-all` is an `object`, this solution is backwards compatible.

# Expected behavior (i.e. solution)

Uniformal types between the different OSCAL layers.

# Other Comments

I'd be more than happy to open a PR for this in case this bug gets "accepted".

**Comment by david-waltermire-nist** [comment]
I am looking at PR #1144 and this issue.

I believe we can reuse the `include-all` from the profile model as you suggest, since their syntax is the same. I'd like to cleanup a few small things with PR #1144. I'll provide feedback on the PR regarding these issues.
