### ISSUE TITLE
Profile Resolution Specification for Back-Matter Resources Only with rlinks?

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1140]
# Describe the bug

The current draft of the profile resolution spec in #1089 (and [currently published on the website](https://pages.nist.gov/OSCAL/concepts/processing/profile-resolution/#d2e300-head), before the #1089 PR) suggest that given an internal reference to a resource in the `profile`'s `import` `@href`, the specification states that it resolve `back-matter` `resource` with `rlink` `@href`s, but it is implied `base64` (and its `@filename`) can be ignored.

> In the context of the Import Phase, internal references will only appear as a reference to a profile or catalog that is in the resources section of the source. When tools encounter such a reference, they MUST locate the object in resources with the matching ID value, and resolve the import using the rlinkURI and the above resolution requirements.

https://github.com/usnistgov/OSCAL/blob/7e0ec3655062dacdf887b9cfb46ccb59c7b1e05a/src/specifications/profile-resolution/profile-resolution-specml.xml#L289-L316

# Who is the bug affecting?

Developers who implement a profile resolver.

# What is affected by this bug?

Whether or not to properly resolve an internal reference to imports with `base64` only elements.

# When does this occur?

Consistently, if literally following the specification to make a conformant profile resolver.

# How do we replicate the issue?

1. Read the specification.
2. Implement the profile resolver per current draft spec.
3. Implement or not implement support to process `resource` with a `base64` element.

# Expected behavior (i.e. solution)

Unclear, depends on what we decide for the specification. 🙃

# Other Comments

I reviewed the spec when developing IBM/compliance-trestle#1023 for IBM/compliance-trestle#1019.

**Comment by wendellpiez** [comment]
The `base64` feature was envisioned to support not the dynamic information network represented by an OSCAL document (or set of documents) in a processing context, but rather appendages to that network (e.g., jpeg binaries). To use it for a catalog import or indeed a baseline import for an SSP would seem to violate the design premise of OSCAL. Such resources are typically not discoverable or checkable (or validable) until runtime, hence potentially a security issue as well (since data loss or variation is harder to detect and prevent).

As an alternative to permitting it as an option, we might consider forbidding it. It also raises a wide range of issues e.g. regarding character encodings of text-based resources (such as XML or JSON) represented in Base64.

**Comment by stephenbanghart** [comment]
Profiles carrying entire Catalogs in Base64 to then import into itself does go against the intended usage pattern, but shouldn't be strictly prohibited IMO

Suggestion: Change the requirement to "**IF** an RLink is present, it MUST be used to resolve it, otherwise do what you want"

**Comment by david-waltermire-nist** [comment]
@stephenbanghart The model allows both rlinks [0-∞] and base64 [0-1] to appear. There is a Metaschema constraint that requires at least one of the two appear. This means that you can have either or both in a given resource.

The Profile resolution spec should have well-defined behavior for utilizing any rlink or the base64 entry. In the case of the rlink, an HTTP client request can be made to retrieve a byte stream to retrieve the resource. In the base64 case, the byte stream can be generated by decoding the base64 content based on the algorithm defined in [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648). Decoding of a base64 resource would also follow this RFC. The decoded base64 text should be considered a byte stream, just like a resolved rlink. If the implementation cannot parse either resulting byte stream, it should produce an error.

 requires either an rlink or a base64. See . Both should be

**Comment by GaryGapinski** [comment]
Given _"If the implementation cannot parse either resulting byte stream, it MUST produce an error."_ , I'll make a suggestion.

Both of the `filename` and `media-type` attributes of `<base64>` are optional in the OSCAL XML Schema. The absence of a declared `media-type` greatly increases the difficulty of parsing the (successfully decoded) "resulting byte stream" as considerable knowledge of byte stream signatures would be required.

The `media-type` attribute will likely be considered mandatory for applications which can deal with a subset of [IANA media type](https://www.iana.org/assignments/media-types/media-types.xhtml) byte streams. Such applications will likely expect that `<rlink>` references for which no media type can be expected upon retrieval will also require a `media-type` attribute.
