### ISSUE TITLE
Profile Resolution handling groups

### ISSUE THREAD

**Issue by stephenbanghart** [usnistgov/OSCAL#1141]
`<p>Some source catalogs use <src>group</src> objects to place controls into arbitrary groupings. Tools will need to be aware of these groups when executing the "merge" phase below, as they will duplicated into the output under the "as-is" mode and can be referenced in "custom" mode. The naïve intermediate approach would keep all groups until all other phases are complete, but implementations may find it more performant to look ahead and prune unused groups early.</p>`

This section in the Import phase of Profile Resolution is potentially under specified. Further requirements clarifying the fate of non-control, non-group elements under a group are probably needed to ensure deterministic output. This is particularly notable for the "custom" merge mode with ID matched group importing.

 Ongoing work on requirement driven testing should provide further insight. #1087

**Comment by david-waltermire-nist** [comment]
@stephenbanghart is scheduling a meeting with the NIST design team for the week of 3/7/2022.
