### ISSUE TITLE
Profile Resolution Output Namespaces

### ISSUE THREAD

**Issue by stephenbanghart** [usnistgov/OSCAL#1142]
In the "Dealing with Multiple Formats" section of the specification, we do not specify any name spacing requirements for any of the formats.

Is this covered by requirements elsewhere in OSCAL, or do we need to establish requirements here?

**Comment by david-waltermire-nist** [comment]
@stephenbanghart is scheduling a meeting with the NIST design team for the week of 3/7/2022.
