### ISSUE TITLE
Documentation on Validation Capabilites for Different Parts of the OSCAL Toolchain

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1153]
# User Story:

As an OSCAL tool developer, in order to understand what the NIST OSCAL team means in documentation when citing validation of different OSCAL document instances and how it informs my own development work, I want definitions of well-formedness, syntactic validation, semantic validation, and what specific parts of the OSCAL toolchain (Metaschema `constraint`s, XML/JSON schema, et cetera) support that capability, if any.

This came up during issue triage of usnistgov/OSCAL#1145 and making clear documentation to explain what can and cannot be implemented for future questions about validation capabilities with current and future OSCAL.

## Goals:

Clear documentation for NIST team and external community contributors to clarify what is possible, what is not possible, and what could be possible in the future dependent upon roadmap.

## Dependencies:

N/A

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
Starting [a draft of the page of that page here](https://hackmd.io/BQCtEwgLSjq6mB6LNCKiIg?both) to discuss generally approach and content, then will soon convert to a PR for final review once general approach and topics are agreed upon.

**Comment by wendellpiez** [comment]
Working on a fresh draft with @aj-stein-nist, we think we can make something short and sweet, offering a succinct and high-level view, without details.

AJ is editing that draft and will post it here. Basically the goal is a reference we can point to, for users still learning their way around the tech who are confused by the meanings of these terms outside XML/JSON, intended not to answer all their questions, but merely state things definitively, with links.

We are also discussing a follow-up treatment that goes into more detail, with examples offering concrete assistance to beginners.

**Comment by aj-stein-nist** [comment]
Reviewing Wendell's drafts based on the previous comment:

- [Well-formed vs/and valid](https://hackmd.io/XhEtfmmSS3Gb2nbAkghcvQ)
- [How to validate OSCAL?](https://hackmd.io/-J3wkICdQG-foZinA0WmbA)

Wendell and I am are aiming to slim that down. Wendell provided some excellent source content, so I am trying to figure out the best way to work that into the previous draft in a more slimmed down sense, and then determine where to cut it down into two pages.

Also, I am thinking of drafting a PR to the terminology page to explain: well-formed, valid, and validating parser, to link the deeper explanatory two pages we are proposing here once we have merged our HackMD page edits.
