### ISSUE TITLE
`NEW CONTENT` comment in metaschemas

### ISSUE THREAD

**Issue by guyzyl** [usnistgov/OSCAL#1176]
I came across the following block comment in the `oscal_assessment-comment_metaschema.xml` file:

```
   <!-- ===============================  -->
   <!-- ========= NEW CONTENT =========  -->
   <!-- ===============================  -->
```

From a quick search, it exists in a few other metaschemas.

Can it be removed it? (I'll open a PR if the answer is yes)
Its purpose isn't clear (not to me at least) and isn't explained in the commit message.

**Comment by aj-stein-nist** [comment]
Consider yourself assigned! :-)

Feel free to draft a PR.
