### ISSUE TITLE
Profile resolution how-to readmes

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#1178]
# Describe the bug

Examining improvements to profile resolution code (#1175) we are finding the readmes directing users in operating the profile resolver are defective.

The readmes explaining how to operate the XSLT profile resolver, with dependencies, limitations, and options, need to be updated.

# Who is the bug affecting?

Anyone who wants to use the profile resolver and can't figure it out for themselves.

# What is affected by this bug?

XSLT profile resolver is harder to (figure out how to) use.

# Expected behavior (i.e. solution)

Update the readmes to be more helpful.

**Comment by galtm** [comment]
Addressed in 0d0c508f0b072a8cc2cec02893ad39a2e1322282 as part of #1175

**Comment by david-waltermire-nist** [comment]
This was a follow-on to an OSCAL 1.1.0 task, which was marked as 1.0.3. Moved this to the 1.1.0 milestone.

**Comment by nikitawootten-nist** [comment]
I'll take this one over. As someone who has no idea how the XSLT profile resolution workflow works, I can probably understand the audience.

**Comment by galtm** [comment]
@nikitawootten-nist , I'm not sure what branch you plan to work on, but I just wanted to mention that the develop branch has some updates that aren't on the main branch.

**Comment by nikitawootten-nist** [comment]
I'll be working out of the develop branch, thanks.

@galtm Unless https://github.com/usnistgov/OSCAL/pull/1639 merges before I am ready, I'll also add a note specifying that Saxon 11 and 12 are not currently supported to the readme.

**Comment by nikitawootten-nist** [comment]
Also contingent on #1639, I added a nice helper script that should assist users living in https://github.com/nikitawootten-nist/OSCAL/blob/nikitawootten-nist/issue1178_wrapper-script/src/utils/util/resolver-pipeline/oscal-profile-resolve.sh

**Comment by aj-stein-nist** [comment]
> Also contingent on #1639, I added a nice helper script that should assist users living in https://github.com/nikitawootten-nist/OSCAL/blob/nikitawootten-nist/issue1178_wrapper-script/src/utils/util/resolver-pipeline/oscal-profile-resolve.sh

I am working down the review and merge of that PR to see if we can get this all in, thanks for the reminder last week.

**Comment by aj-stein-nist** [comment]
Relevant code was merged early so this could get pulled in as completed.
