### ISSUE TITLE
Patching Metaschema (XSLT M4 implementation) datatypes with new definitions

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#1186]
# User Story:

Datatype support in the XSLT M4 Metaschema implementation needs to be updated to conform to latest work, so that XML and JSON schemas for OSCAL can take advantage of new definitions.

The work is being tracked in usnistgov/metaschema#191. New datatype definitions there must be integrated into the M4 pipeline.

This will also help address issues #1127, #1132, and #1105.

This Issue addresses changes supporting OSCAL 1.0.3, not a more thorough refactoring for 1.1.

## Goals:

Capture new improved work on datatype definitions in schema generation from XSLT M4.

## Dependencies:

New datatype definitions must be stable.

## Acceptance Criteria

Note: the PR for this work will be in the usnistgov/metaschema repository.

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
As advised by @david-waltermire-nist , work proceeds in WIP branch: https://github.com/usnistgov/metaschema/compare/develop...wendellpiez:issue181-tokendatatype

JSON Schema and XSD look good so far.

**Comment by wendellpiez** [comment]
For alignment (from usnistgov/metaschema#191) the following new names are supported:

- [x]  nonNegativeInteger -> non-negative-integer
- [x]  positiveInteger -> positive-integer
- [x]  dateTime -> date-time
- [x]  base64Binary -> base64
- [x]  dateTime-with-timezone -> date-time-with-timezone
- [x]  email -> email-address

See most recent commit.

**Comment by david-waltermire-nist** [comment]
PR #1161 needs to be merged to complete this.
