### ISSUE TITLE
Links in parameter settings

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#119]
# User Story: Links in parameter settings

As a OSCAL profile user, when setting a parameter, I can provide a citation to a relevant authority.

This requirement is mentioned in the (markdown) User Stories for Profiles mentioned in Issue #112, which gives real-world examples.

## Goals:

Extend the parameter model to support citations in some form, preferably simple, possibly as simple as permitting a `link` element to appear.

## Dependencies:

Examples and/or more specific requirement definition for schema extension in parameter settings and/or (if this feature is needed in catalogs) parameter declarations.

## Acceptance Criteria

A working example (validating the new structure and handling it in resolution) with documentation

**Comment by david-waltermire-nist** [comment]
This has been completed in PR #277.
