### ISSUE TITLE
Misleading XML Schema documentation for control-implementation implemented-requirement

### ISSUE THREAD

**Issue by GaryGapinski** [usnistgov/OSCAL#1194]
# Describe the bug

This was recently discussed and an issue was requested.

See the 1.0.2 complete XML schema line [2672](https://github.com/usnistgov/OSCAL/blob/v1.0.2/xml/schema/oscal_complete_schema.xsd#L2672).

The prose statement implies semantic equivalency of `<implemented-requirement>` in both `<system-security-plan>` and `<component-definition>`. The element name assists with such an interpretation.

# Who is the bug affecting?

Developers who rely on XML Schema documentation.

# What is affected by this bug?

Despite the element name equality, the semantic import is supposedly different.

# When does this occur?

Durably (unless the documentation were to be changed).

# Expected behavior (i.e. solution)

Identically named elements in different OSCAL documents have identical semantic import.

**Comment by david-waltermire-nist** [comment]
The relevant objects in the component definition need to be clarified that the control details are suggestions for possible implementations in the component definition. In the SSP, the relevant objects document what was actually implemented.

This needs to be clarified in the relevant metaschemas.
