### ISSUE TITLE
Profile unit tests for normal and edge cases

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#121]
# User Story:

As an OSCAL user, I can be confident that profile resolution is working as specified - and I can find examples in the form of unit tests (XML documents, document fragments and/or documentation) that demonstrate profiling semantics in operation, with examples.

NB we already have files in place for (some) unit testing (of schemas, Schematrons, XSLTs including profile resolution); these need to be extended and put to work.

## Goals:

- Test profile resolution. Expose issues in design and implementation for remedy. Continue to extend unit tests. (@wendellpiez)

- It is not a goal that the unit tests all pass (all functionality has been demonstrated).

## Dependencies:

Models and specified semantics (functionality) stable enough to warrant testing.

## Acceptance Criteria

We have more and better unit tests in place. They are tied better to documentation.

In particular, we can demonstrate unit tests for "classic" errors and use cases such as import chains; multiple (clashing) control imports; loose and orphan subcontrols; broken links to controls or control components including parameters etc.

**Comment by david-waltermire-nist** [comment]
This relates to #153 .

**Comment by wendellpiez** [comment]
See #508, #561, and PR #559 for current work on this. When unit testing is in place we can close this.
