### ISSUE TITLE
Update SSP reference documentation for import-profile element

### ISSUE THREAD

**Issue by Rene2mt** [usnistgov/OSCAL#1211]
# Describe the bug

Reference documentation for ```import-profile``` element ambiguous about what can be referenced by this element (e.g. ***profile*** vs ***resolved profile*** vs ***catalog***):

- XML: https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/xml-reference/#/system-security-plan/import-profile
- JSON: https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/import-profile

# Who is the bug affecting?

OSCAL SSP authors

# What is affected by this bug?

OSCAL SSP authors are not certain about what can be referenced by ```import-profile```.

# When does this occur?

n/a

# How do we replicate the issue?

n/a

# Expected behavior (i.e. solution)

Clarify element description in reference documentation so its clear what source OSCAL can be referenced for this element:

- XML: https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/xml-reference/#/system-security-plan/import-profile
- JSON: https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/import-profile

# Other Comments

n/a

**Comment by wendellpiez** [comment]
@galtm not as such, although for various reasons including analysis or forensics, I can well imagine the recipient of a profile  document (or SSP) processing it with a proxy catalog or profile, if only for comparison purposes. In such a use case, that data point as represented in the metadata of the resulting catalog could be useful.

In a plain vanilla use case, I would imagine that the recipient of a profile would have a great interest in ensuring not only that any OSCAL document's representation of its upstream sources is adequate (i.e. ultimately real-world meaningful and correct), but that those upstream sources both as stated and when used should be what I think they are and should be. Nothing switching out without my knowing about it. Exposing a nominal URI along the way helps with this.

Generally, if I contract to receive profiles (or SSPs), I would also expect to contract some kind of understanding (if not chain of custody) for its upstream sources, to complement and verify (validate) its internal representation ("what it says"). At the low end, this is done by exchanging and caching reliable copies of upstream sources themselves, in advance. So if you say your profile works against catalog X, it works just as well on my copy of catalog X as on yours. But that only works when the configurations of those upstream sources can be pinned down.

In my view, we need more than clarification of the docs here: we also need a specification of exception handling. In my view that breaks out more or less like this:

1. `href` or binary (resource) is not given or not retrievable
2. resource does not parse as nominal format (XML, JSON, YAML)
3. resource parses but is the wrong format (e.g. JSON for an XML processor)
  - optionally, handle by attempting to convert?
4. resource parses but is not recognizable (e.g., not OSCAL)
5. resource parses but is recognizable as the wrong thing (e.g. an SSP when we require a catalog)
6. resource is recognizable but not valid to its stated model (schema+constraints)
7. resource is recognizable and valid, process accordingly
  - `catalog` do this...
  - `profile` do this...
  - etc.

The issue raised here pertains only to the last step. The others come up in Issue #1173.

**Comment by GaryGapinski** [comment]
> * resource does not parse as nominal format (XML, JSON, YAML)

There are additional shortcomings in `import-profile`:
- The schema documentation asserts "Import Profile: Used to import the OSCAL **profile** representing the system's control baseline.". An OSCAL instance document would have a root element `profile`.
- `profile` provenance is not rigorous.
- Were a `catalog` instance document to be the target, it would have ambiguous `profile` provenance.
- Pure XPath cannot be used to verify the target of an `@href` is reachable (compare the results of `doc-available()` to `unparsed-text-available` when fed various inputs.
- The absence of a `@media-type` attribute affords no hint of expected media type.

**Comment by wendellpiez** [comment]
Awesome. Noting only -

- while I think we need a detailed spec, I'm not sure it has to be in OSCAL, as some/all of this could be up to an implementation
- on point 1 the language is not wrong, it is just tautological hence not useful (hanging on the meaning of "import").
- on points of provenance and traceability - backing up with use cases is useful
- nominal support for @media-type (as a validation point?) also adds at least a line does it not?
