### ISSUE TITLE
Mapping Schema Language for Relationships

### ISSUE THREAD

**Issue by tsagerCIS** [usnistgov/OSCAL#1221]
https://github.com/usnistgov/OSCAL/blob/7869eab8485d17128500f8b2580a9f6dfe3d812a/src/metaschema/oscal_mapping-common_metaschema.xml#L40
@david-waltermire-nist 
Something we had touched on before, the language around the relationships in mapping.  Currently, in addition to the "subset/superset/equivalent" options we have here we are also using "intersects."  This is the most recent addition and isn't exactly gospel yet, but is mostly used when describing similar or related policies that cannot be said to be "contained" within the other.  For instance, consider policies like incident response, disaster recovery, and backup recovery.  All related enough that not mapping them feels a bit wrong, but certainly not a "part" of the other.  There's an argument to be made against "intersects" but that is where our thinking is at currently.

**Comment by iMichaela** [comment]
@tsagerCIS - `intersect` must clearly identify without any doubt the information in common vs the disjoined information. They policies you listed will `intersect` only if they contain identical statements but also each have other statements.
```
Policy1: 
-stm_a 
-stm_b
-stm_c
```
```
Policy 2:
-stm_a
-stm_d
-stm_e
```
The `intersect` of `Policy1` with `Policy2` will be `stm_a` and the rest of the statements need to be clearly marked/identified as disjoined for traceability reasons when the mapping is used for the implementations and for assessments.

In the same way one can define a `union` `U` and then allow mapping like:  `CatalogA:control1` be mapped as (`identical-to`, `equivalent-to`, `superset-of`, `subset-of`) to [`CatalogB:control5` `U` `CatalogB:control7`] OR to [`CatalogB:control5` `intersect` `CatalogB:control7`] 

Thoughts?

**Comment by david-waltermire-nist** [comment]
It seems that `intersect` is a way to be vague about the relation, when there is not statement level granularity to be more specific. For instance, if you have two controls that contain only a single text block as a statement.

For example:

```
control1:
- smt1: Text describing requirements A, B, and C.

control2
- smt2: Text describing requirements B, C, and D.
```

In such a case you cannot break out the statements, so expressing `Control1 ∩ Control2` is a way of saying `{ A, B, C } ∩ { B, C, D }`.

 If you can mark which statement's intersect, then it would be better to use "subset/superset/equivalent" on the intersecting set members.

For example:

Given:
```
control1: 
-stm_1a 
-stm_1b
-stm_1c

control2:
-stm_2b
-stm_2c
-stm_2d
```

If `Control1 ∩ Control2`, this can better expressed as something like `{ stm_1b, stm_1c } ≡ { stm_2b, stm_2c }` based on the above, assuming that the Bs and Cs are equivalent.

Is this the right way to think about the need for intersect?

**Comment by iMichaela** [comment]
@tsagerCIS - Please note that mathematically speaking, the `intersect` part of the 2 controls must be identical (word by word) to qualify for an `intersect` relation. Otherwise it will be some level of equivalence between them and additional functionality around the information coverage (one control cover network monitoring, incident response, etc.. while the equivalent control covers logging) and information richness/entropy (one control requires monitoring or logging the other one provides requirements around which events need to be monitored) needs to be evaluated.
Please see similar discussion in #1150
