### ISSUE TITLE
Review Error Behavior in OSCAL CI/CD Scripts and GitHub Actions Automation

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1222]
# User Story:

As an OSCAL tool developer, in order to ensure I can confidently reuse GitHub Actions automation from the core NIST OSCAL developer team in the OSCAL core repos in my own automation to precisely and consistently determine success and error state of overall workflows and individual steps' operations, I want to ensure error behavior is consistently managed in a documented and consistent way.

## Goals:

One of the members of the OSCAL tool developer community from the 10x team working on the FedRAMP Automation project requested use of [shell behavior in GNU `bash`](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html) to set `-e` and `+e` accordingly to properly exit if any command in a pipeline returns a non-zero status in a specific step of our CI/CD automation around file conversion, per usnistgov/OSCAL#1216.

After discussion with Dave, he has been fairly intentional thus far of not using this approach for proper flow control and logging. He agreed he would like to review this in light of how scripts work when run locally in Docker (with `run-all.sh`) and also when orchestrated without Docker currently in GitHub Actions in a holistic way, separate of fixing the immediate bug in usnistgov/OSCAL#1216.

## Dependencies:

None at this time.

## Acceptance Criteria

- [x] Review official GNU `bash` documentation re exit status behavior:
  - [x] with subshells and other features of the language we use in our "in Docker" bash script only orchestration 
  - [x] when orchestrated via GitHub Actions
- [x] Synchronize with Dave and dev team and determine if we want want to change to no, partial, or complete use of this approach
- [x] If changes are required, update the CI/CD scripts accordingly
- [x] If changes are required, update the GitHub Actions `run` directives accordingly
- [x] Document this change, impacts, and relevant debugging steps for failure conditions accordingly
- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
May potentially do this before/during usnistgov/OSCAL#1223.

**Comment by aj-stein-nist** [comment]
So, I didn't know exactly where to start with this, but I reviewed current guidance on trapping error codes more generally in `bash` scripts and there are two schools of thought around this, with some nuance in between about not using absolutely at the complete shellscript level:

- You can rely on `set -e` and `set +e` to liberally protect you from unexpected errors and flow management.
- Relying for the top-level script on `set -e` and `set +e` and not managing error codes and exceptions in pipelines and error codes is risky and ill-advised. Doing it for certain subsets functions or code blocks in a script is OK, but do not rely on it and it expect it to break stuff often.

Some advice on this (for a collection of good resources curated in this context, [the relevant StackOverflow question](https://serverfault.com/a/847016)):

- ["Why doesn't set -e (or set -o errexit, or trap ERR) do what I expected?" on the well-known wiki bash FAQ](http://mywiki.wooledge.org/BashFAQ/105)
- [Guidelines for init shell scripts in the Debian Policy Manual, warning about their OS packaging recommendation to not rely on `-e`](https://www.debian.org/doc/debian-policy/ch-opersys.html#writing-the-scripts)

Good summary wrap-up from the relevant StackOverflow poster: "`set -e` is no substitute for education." That said, we have a couple of dimensions to this problem.

1. We have to understand different internal steps within a given script and how control flow and error handling works.
2. We have to understand the greater context of relationships and control flow with library functions and scripts invoking one another and invoking themselves recursively.

2 is kind of hard to do, I did a small spike and did not find anything compelling to visualize or instrument `bash` call graphs, which is kind of a bummer as there are no good tooling around this _for `bash`. I found a lot of research around this topic with custom-built languages and runtimes, like [`dgsh`](https://github.com/dspinellis/dgsh) and [its documentation with generated graphs](https://www.spinellis.gr/sw/dgsh/).

For the more immediate life re 1, I did decide to use `shellcheck` for some level of informed static analysis around where our weak points are around the subset of warnings around error handling and control flow (conditionals that check error outputs and the like). From reviewing [the `shellcheck` wiki](https://www.shellcheck.net/wiki/), that got me to this list.

- [SC1014](https://www.shellcheck.net/wiki/SC1014)
- [SC1139](https://www.shellcheck.net/wiki/SC1139)
- [SC1140](https://www.shellcheck.net/wiki/SC1140)
- [SC1141](https://www.shellcheck.net/wiki/SC1141)
- [SC1142](https://www.shellcheck.net/wiki/SC1142)
- [SC2015](https://www.shellcheck.net/wiki/SC2015)
- [SC2067](https://www.shellcheck.net/wiki/SC2067)
- [SC2069](https://www.shellcheck.net/wiki/SC2069)
- [SC2107](https://www.shellcheck.net/wiki/SC2107)
- [SC2108](https://www.shellcheck.net/wiki/SC2108)
- [SC2109](https://www.shellcheck.net/wiki/SC2109)
- [SC2110](https://www.shellcheck.net/wiki/SC2110)
- [SC2151](https://www.shellcheck.net/wiki/SC2151)
- [SC2152](https://www.shellcheck.net/wiki/SC2152)
- [SC2155](https://www.shellcheck.net/wiki/SC2155)
- [SC2159](https://www.shellcheck.net/wiki/SC2159)
- [SC2164](https://www.shellcheck.net/wiki/SC2164)
- [SC2166](https://www.shellcheck.net/wiki/SC2166)
- [SC2181](https://www.shellcheck.net/wiki/SC2181)
- [SC2242](https://www.shellcheck.net/wiki/SC2242)
- [SC2251](https://www.shellcheck.net/wiki/SC2251)
- [SC2252](https://www.shellcheck.net/wiki/SC2252)
- [SC2310](https://www.shellcheck.net/wiki/SC2310)
- [SC2311](https://www.shellcheck.net/wiki/SC2311)
- [SC2312](https://www.shellcheck.net/wiki/SC2312)

I applied the following command to only check existing scripts and target these warnings and report back on them in JSON.

```sh
git clone git@github.com:usnistgov/OSCAL.git
cd OSCAL
find ./build/ci-cd -type f -iname *.sh -exec sh -c 'shellcheck --include=SC1014,SC1139,SC1140,SC1141,SC1142,SC2015,SC2067,SC2069,SC2107,SC2108,SC2109,SC2110,SC2151,SC2152,SC2155,SC2159,SC2164,SC2166,SC2181,SC2242,SC2251,SC2252,SC2310,SC2311,SC2312 --format=json {} | jq | tee {}.json' \;
```

So I would like to digest this output and then talk with Dave. Also, I would like to talk to @wesley-dean-gsa (or he can reply here) to sync up with me and talk about the FedRAMP (and 18F fork) use of these scripts and error stand concerns and needs around error control before making any significant changes here. (18F is at https://github.com/usnistgov/OSCAL/tree/bfcd0082bd4c08e16c7d5f5515adc5c858e8308e and GSA upstream is farther behind). Thoughts?

**Comment by wesley-dean-gsa** [comment]
@aj-stein-nist happy to help

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist happy to help

You have any block of time on Tuesday?

**Comment by wesley-dean-gsa** [comment]
@aj-stein-nist any time after 10am Eastern works for me.

**Comment by aj-stein-nist** [comment]
I talked with @wesley-dean-gsa today and determined the 10x/FedRAMP validations developers' current and future plans around CI/CD and release automation. From their end, there is no need for significant changes, so on my end we will move forward with touch-ups around error logic as I see fit here, and move along to #1223 once any needed improvements and documentation additions here are completed.

**Comment by aj-stein-nist** [comment]
Completed within/as part of usnistgov/OSCAL#1223.
