### ISSUE TITLE
Identify how to represent OSCAL YAML media types

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#1255]
# User Story:

As a OSCAL developer, I would like [`/catalog/back-matter/resource/rlink/@media-type`](https://pages.nist.gov/OSCAL/reference/latest/catalog/xml-reference/#/catalog/back-matter/resource/rlink/@media-type) model documentation to clearly define how `YAML` resource link should be represented.

## Goals:

Update the OSCAL documentation to provide guidance around the representation of a `YAML` resource link, in order to provide clarity and consistency across implementations. It is noted that the Internet Assigned Numbers Authority (IANA) [Media Types Registry](https://www.iana.org/assignments/media-types/media-types.xhtml) does not a define specific type for `YAML`, but YAML is a key OSCAL supported data format.

## Dependencies:

None

## Acceptance Criteria

- [x] All website and readme documentation affected by the changes in this issue have been updated.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

# Other Comments

See https://stackoverflow.com/questions/332129/yaml-media-type for related information.

**Comment by aj-stein-nist** [comment]
I vote for `application/yaml` per discussion with Dave. Research notes to follow!

**Comment by david-waltermire-nist** [comment]
After reviewing [RFC 6838](https://www.rfc-editor.org/rfc/rfc6838.html) it is clear that using `x-yaml` is not allowed, and `x.yaml` is [discouraged](https://www.rfc-editor.org/rfc/rfc6838.html#section-3.4).

There was a [proposal](https://mailarchive.ietf.org/arch/msg/media-types/e9ZNC0hDXKXeFlAVRWxLCCaG9GI/) for early IANA registration around `vnd.yaml`, for which the response was that YAML is not vendor sepcific.

JSON is currently registered as `application/json`.

I believe it would be best to use `application/yaml`. There is some [work](https://github.com/ioggstream/draft-polli-rest-api-mediatypes) to do [this](https://github.com/yaml/yaml-spec/issues/49).

**Comment by aj-stein-nist** [comment]
Short and sweet, this one is done and merged for 1.0.4 release. Closing.

/cc @david-waltermire-nist sadly yet again this did not get auto-closed even though in PR message and in the Development link UI feature I added this issue to close. Not sure what gives there.
