### ISSUE TITLE
Why does implicit OSCAL namespace lack a version number?

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#1259]
### Discussed in https://github.com/usnistgov/OSCAL/discussions/1258

<div type='discussions-op-text'>

<sup>Originally posted by **galtm** May 10, 2022</sup>
Related to #1247 : Why is the implicitly assumed OSCAL namespace `http://csrc.nist.gov/ns/oscal` with no version number, when the OSCAL elements are in namespace `http://csrc.nist.gov/ns/oscal/1.0` with a version number?</div>

**Comment by david-waltermire-nist** [comment]
This was answered in #1258.
