### ISSUE TITLE
Update the OSCAL control layer catalog model content example page to SP 800-53 Rev. 5

### ISSUE THREAD

**Issue by Ikendiken** [usnistgov/OSCAL#1270]
# User Story:

As an OSCAL Catalog Content model user, I would like to see the [content example](https://pages.nist.gov/OSCAL/concepts/layer/control/catalog/#nist-sp-800-53-revision-4-annotated-example) provided on the [OSCAL Control Layer: Catalog Model](https://pages.nist.gov/OSCAL/concepts/layer/control/catalog/) page updated to reflect NIST SP 800-53 Revision 5 content.

## Goals:

The [NIST SP 800-53 Revision 4 Annotated Example](https://pages.nist.gov/OSCAL/concepts/layer/control/catalog/#nist-sp-800-53-revision-4-annotated-example) uses NIST SP 800-53 Revision 4 content. When clicking the link provided within the section to the [NIST SP 800-53 Rev 4 Document](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf), the user is presented a coversheet warning of content withdrawal and suggesting instead the user use [NIST SP 800-53 Rev 5](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5.pdf). This suggests to the user that the content within the example may be out of date, or stale.

The Content Examples section of the [OSCAL Control Layer: Catalog Model](https://pages.nist.gov/OSCAL/concepts/layer/control/catalog/#content-examples) should be improved to Revision 5, any links updated, and all content examples reviewed to ensure that they are using the latest data models.

## Acceptance Criteria
- [ ] OSCAL catalog model example page content updated to SP 800-53 Rev. 5
- [ ]  Links updated to point to Rev5 version of the documents
- [ ]  Data model examples updated to reflect latest data model revisions
- [ ] All readme documentation affected by the changes in this issue have been updated.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
@usnistgov/itl-oscal Please submit feedback on this ASAP. I'd like to wrap this up by 7/6. I'll give it a final review and merge it then.

**Comment by wendellpiez** [comment]
This is now ready in PR #1295 please take a look --
