### ISSUE TITLE
Ampersand in string causes schema validation error

### ISSUE THREAD

**Issue by telosBA** [usnistgov/OSCAL#1278]
# Describe the bug
Strings that include an ampersand, "&," cause an error upon schema validation. 
e.g. 
`<description>`
    `<p>`Sample & Text`</p>`
`</description>`

{A clear and concise description of what the bug is.}

# Who is the bug affecting?
Telos

# What is affected by this bug?
Schema validation

{Describe the impact the bug is having.}

# When does this occur?
Validating schema with ampersand present in any string.

{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?
1. Populate a string element within XML with an ampersand.
2. Attempt schema validation.
3. Note output errors.

**Sample Error:**
TCM-13503:~ 13503$ xmllint --schema /Users/13503/PycharmProjects/OSCAL/oscal.xsd /Users/13503/PycharmProjects/OSCAL/NewXacta.xml --noout
/Users/13503/PycharmProjects/OSCAL/NewXacta.xml:202: parser error : xmlParseEntityRef: no name
      <prop class="pta" name="sorn-id"  value="If yes, please provide the& SORN

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by aj-stein-nist** [comment]
This is actually part of the core syntax of XML, [per the spec](https://www.w3.org/TR/xml/#syntax). As we joke in the software industry: it's not a bug, it's a feature.

`&` unto itself means indicates the presence of an entity, exactly like that error message tells you, so you need to declare it correctly. `&amp;`. This is not even specific to XML, but HTML and (Wendell might correct me here) most SGML-based languages. It is a reserved part of the syntax and you have to specify you want an ampersand, not to declare a XML entity using the special character that prefixes one.

More details about reserved characters [can be found in popular documentation for developers on this topic](https://developer.mozilla.org/en-US/docs/Glossary/Entity#reserved_characters). Also, this is why we strongly encourage developers to check XML/JSON/YAML is well-formed, then check if it is well-formed _OSCAL XML/OSCAL YAML/OSCAL JSON_. I hope this helps.
