### ISSUE TITLE
Create issue templates for the OSCAL repo using the new form feature

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#1330]
# User Story:

As an OSCAL issue submitter, I need an easier form for submitting issues.
As an OSCAL issue resolver, I need issue that are more complete and have the desired information filled in.

## Goals:

Create issue templates using the form template features.
- [ ] Update [bug report](https://github.com/usnistgov/OSCAL/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) template
- [ ] Update [feature request](https://github.com/usnistgov/OSCAL/blob/main/.github/ISSUE_TEMPLATE/feature_request.md) template
- [ ] Update [question](https://github.com/usnistgov/OSCAL/blob/main/.github/ISSUE_TEMPLATE/question.md) template

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by nikitawootten-nist** [comment]
@david-waltermire-nist  as we migrate to a unified project board, would it make sense for the bug and user story templates to contain guidance suggesting the user to report their issue to the respective repository that the issue pertains to? Maybe a `PROJECTS.md` that lists all of the "core" OSCAL repositories?
