### ISSUE TITLE
Review Website Documentation Structure and Content

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1334]
# User Story:

As any OSCAL stakeholder, I want to better understand the OSCAL documentation as it relates to my professional background (technical/non-technical, executive/non-executive) through its structure and the content itself.

## Goals:

- [x] Review the current organization and HTML content used to provide OSCAL reference documentation. Identify ways to improve the usability and performance of these pages.
  - [x] Benchmark the loading of these pages. Identify where the slowdown is occurring
  - [x] Report to the team about where the problems are. Collect feedback on the way forward.
  - [x] Identify and create the specific user stories for completing any follow-on work.

**NOTE:** We are deferring on any implementation choices until we better understand the lag problem and how it might be fixed. Once this is known we will have a better sense of if it is possible to update the existing code, or start on a larger redesign.

## Dependencies:

N/A

## Acceptance Criteria

- ~All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.~
- ~A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.~
- ~The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.~

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist and I began work on this yesterday in the afternoon. A brief summary update.

1. We focused on the examine of reference [JSON](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/) and [XML](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/xml-reference/) reference, using Chrome and Firefox developer tools to record and measure performance.
2. We observed two phenomena we want to further examine and potentially address:
  - The HTML document model has a tree hierarchy that closes matches the hierarchical outline of the data elements of OSCAL as a XML tree (with nested, embedded `<div/>` sections that reflect that. This does appear to have a performance impact.
  - The right-hand side of the page has the interactive table of contents outline [with the tocbot library](https://github.com/tscanlin/tocbot/) as used in [our hugo-uswds page templates](https://github.com/usnistgov/hugo-uswds/blob/631e1143c32fbcfb8a6d7d5ed7d9e093f51a1c2b/layouts/_default/baseof.html#L142-L172) that fire off many events frequently as a user scrolls on this page. We need to analyze the performance impact of 1) changing the configuration of tocbot 2) writing a custom event handler for the scroll event to improve performance or 3) switching out this library for an alternative or changing tact.
3. To consider approaches around 2, we reviewed [the Golang community's pkg documentation website](https://github.com/golang/pkgsite/) and particular pages [like the `http`'s libs many functions, variables, and properties index](https://pkg.go.dev/net/http#pkg-index) which is similarly long, but more performant from casual observation and interaction. This page exhibits a less hierarchical HTML document model and a different novel approach in [TS/JS for handling the outline TOC placeholder](https://github.com/golang/pkgsite/blob/2717a634e1e7d4bc46e5784db873fd701f92d5e1/static/shared/outline/tree.ts).

Next steps are to further analysis of 3 to help with 1 and potentially 2 (improvements in 1 may or may not mitigate further work on 2).
- [ ] Set up current OSCAL reference page measurement in a repeatable way
- [ ] Prototype a different HTML document model for the reference page and measure performance
- [ ] Measure and consider next work on TOC, whether or not we need to change tocbot or tentative solutions to 2 if further HTML document model does not improve perf sufficiently

**Comment by aj-stein-nist** [comment]
Dave and I continued to work on analysis of the website performance yesterday, and we have some updates.

- Dave has created some locally copies modified with different modifications to reflect different performance improvements
  - Approach 1: A version of reference docs with a flattened HTML document model (re point 2's first bullet above) and it does seem to create a noticeable improvement
  - Approach 2: A version of the reference docs with the tocbot library enabled but experimenting with a number of performance improvements by changing the tocbot default around smooth scrolling, its timeouts, whether it was enabled, how it looks in nested `<div/>s` and other changes.
  - Approach 3: A version of the reference docs with the tocbot library completed disabled and see it's performance.
- Approach 3 through casual experimentation was significantly faster. It seems tocbot needs overhaul/removal. It is not clear we should keep the right-hand side table of contents/outline at all.
- Additionally, Dave had presented his feedback  that the [anchorjs library's performance](https://github.com/bryanbraun/anchorjs) in dynamically generating the anchors for each element in the reference pages index to deeplink seems problematic with performance. We should consider generating the deeplink anchors in the static site generator pipeline "at build time" and not use this dynamic anchor generation approach.
- We decided to bring up and discuss two approaches around enhancements/alternatives to the tocbot performance issues: 1) breadcumbs for each element at the top or bottom and/or 2) linking those breadcumbs directly to the outline view of XML/JSON/YAML for easy skipping back and forth.
- Dave will brief the community in the next OSCAL Lunch with the Devs meeting and we will act accordingly with these inputs to account.

**Comment by aj-stein-nist** [comment]
OK, I need to make some issues to wrap up this spike issue.

# Improvements to the outline pages
1. Fix CSS for choice elements in reference docs
1. Javascript that expands outline nodes based on anchors after redirects
1. Add buttons to expand and collapse the whole tree in outline view

# Reference page
1. Support Implementation of Allowed Values in Reference Pages
1. Flatten the Document Structure to Make the Page Load Faster
1. Add Breadcrumbing for Navigation
1. Add Linkage to Reference Entries and Outline
1. Disable Table of Contents on Pages

# Index pages
1. Verify performance of Table of Contents

**Comment by aj-stein-nist** [comment]
All issues created as requested during the weekly status meeting. Closing the spike as complete now as agreed during the meeting.

**Comment by nikitawootten-nist** [comment]
> Dave and I continued to work on analysis of the website performance yesterday, and we have some updates.
> 
>     * Dave has created some locally copies modified with different modifications to reflect different performance improvements
>       
>       * Approach 1: A version of reference docs with a flattened HTML document model (re point 2's first bullet above) and it does seem to create a noticeable improvement
>       * Approach 2: A version of the reference docs with the tocbot library enabled but experimenting with a number of performance improvements by changing the tocbot default around smooth scrolling, its timeouts, whether it was enabled, how it looks in nested `<div/>s` and other changes.
>       * Approach 3: A version of the reference docs with the tocbot library completed disabled and see it's performance.
> 
>     * Approach 3 through casual experimentation was significantly faster. It seems tocbot needs overhaul/removal. It is not clear we should keep the right-hand side table of contents/outline at all.
> 
>     * Additionally, Dave had presented his feedback  that the [anchorjs library's performance](https://github.com/bryanbraun/anchorjs) in dynamically generating the anchors for each element in the reference pages index to deeplink seems problematic with performance. We should consider generating the deeplink anchors in the static site generator pipeline "at build time" and not use this dynamic anchor generation approach.
> 
>     * We decided to bring up and discuss two approaches around enhancements/alternatives to the tocbot performance issues: 1) breadcumbs for each element at the top or bottom and/or 2) linking those breadcumbs directly to the outline view of XML/JSON/YAML for easy skipping back and forth.
> 
>     * Dave will brief the community in the next OSCAL Lunch with the Devs meeting and we will act accordingly with these inputs to account.

@david-waltermire-nist @aj-stein-nist could you share with me the prototypes that Dave came up with?

**Comment by aj-stein-nist** [comment]
> @david-waltermire-nist @aj-stein-nist could you share with me the prototypes that Dave came up with?

Re the question, I am not sure there was an explicit design made with files committed in a WIP branch, but we experimented with removing the many nested `<div/>`s as many of them may be superfluous (IIRC in the index files but way more so in the reference details pages (not so much the outline). Do you know what I mean by that? Can we sync up next week to revive this and commit it somewhere?
