### ISSUE TITLE
Nesting `params` versus use of `aggregates`

### ISSUE THREAD

**Issue by egyptiankarim** [usnistgov/OSCAL#1342]
Currently the OSCAL schema allows for [`props`](https://pages.nist.gov/OSCAL/reference/latest/catalog/json-reference/#/catalog/params) within [`params`](https://pages.nist.gov/OSCAL/reference/latest/catalog/json-reference/#/catalog/params).

Throughout Rev 5, we use prop entries with an `@name` of `aggregates` to reflect parameters encompassing other parameters. All parameters themselves are hierarchically lateral to each other within their `controls`, which belies their nested nature.

The question: Could we modify the schema to allow for nested params and update Rev 5 content to ditch aggregates inside of props?

This nested params approach would more explicitly self-document the parent-child relationships and allow for cleaner programmatic parsing of content (i.e., you could easily recurse down a tree of parameters). This would also allow us to more tightly constrain the use of props for name-value pairs that are self-referential (i.e., how we use them everywhere other than in the aggregates use case).

**Comment by david-waltermire-nist** [comment]
A parent-child relationship is an implicit 1-to-1 relationship between the parent and child.

The `aggregates` relationship allows for many-to-many relations between parameters. For example a given parameter1 can be aggregated by more than one other parameters. It is not possible to represent this in a parent-child relationship without duplicating the child. This makes `aggregates` more powerful and expressive than a parent-child relationship would be between params.

**Comment by egyptiankarim** [comment]
> A parent-child relationship is an implicit 1-to-1 relationship between the parent and child.

Hrmm... Consider how we nest the control enhancements as an array of controls within a single parent control:

```
   "groups": [
      {
        "id": "ac",
        "class": "family",
        "title": "Access Control",
        "controls": [
          {
            "id": "ac-2",
            "class": "SP800-53",
            "title": "Account Management",
            "controls": [
              {
                "id": "ac-2.2",
                "class": "SP800-53-enhancement",
                "title": "Automated Temporary and Emergency Account Management"
              },
              {
                "id": "ac-2.3",
                "class": "SP800-53-enhancement",
                "title": "Disable Accounts"
               },
               [...]
            ]
```

We can see there are many "children" controls nested within a single "parent" control. The schema for `control` allows for this sort of nesting, which is convenient because it allows me to programmatically recurse down a tree of controls.

I'm proposing a similar set up for parameters. The issue I have with the `aggregates` approach is that we're using it to express a nested relationship. Why rely on attributes among lateral chunks of content to express relationships, when we could instead do so implicitly with the structure of the schema?

**Comment by egyptiankarim** [comment]
@david-waltermire-nist re-reading your comment, I think I understand what you're saying now. Parameters are potentially aggregated by any number of other parameters; I glossed over that part initially.

Okay, well this has me reconsidering my entire proposal. I'll just have to think of a more effective way to parse content. Closing out for now. Thanks!
