### ISSUE TITLE
Scheduled Link Checks Check History to Limit False Positives

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1348]
# User Story:

As a NIST OSCAL developer, to ensure the scheduled link checking only surfaces truly broken links and not transient, intermittent network errors, I would like the scheduled link check action to look at the history of GitHub Actions and fail properly: only when one or more past jobs failed on the same URLs.

## Goals:

The [scheduled link check workflow](https://github.com/usnistgov/OSCAL/blob/833a646ce98188fc17d029723e5a34bc08c72e5f/.github/workflows/link-check.yml) works reliably, but every once in a while a remote web server is offline or in a degraded state at certain hours, leading to a small but frustrating amount of false positives.

See the last few below.

- usnistgov/OSCAL#1322
- usnistgov/OSCAL#1325
- usnistgov/OSCAL#1345
- usnistgov/OSCAL#1347

@david-waltermire-nist had suggested this before, but we need to look into caching and more importantly how to look at the last job that completed, and only open an issue for a broken link iff that last complete job and this current one failed on those links, adding a strong heuristic that the link is certainly broken and it is not a common transient network/server error.

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by nikitawootten-nist** [comment]
I'd like to propose a much simpler fix for this issue. Instead of persisting some history of broken links, have the linkchecker action default to searching for the last open issue with the same title and air its grievance as a comment on that issue. Only if no linkcheck issues are open will it open a new one.

**Comment by aj-stein-nist** [comment]
> I'd like to propose a much simpler fix for this issue.

Revised as you suggest and please proceed, sir!
