### ISSUE TITLE
Fix CSS for choice elements in outline docs

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1365]
### User Story

As an OSCAL tools developer, in order to better understand the use of `choice` in outline documentation, I want better layout so I can better understand hierarchical options of `choice`s and their relationships to sibling elements that are siblings (even though they look like children).

### Goals

We want to adjust the `choice` so, per the example below, `condition` and `test-reference` are on the same level of the hierarchy as `pre-condition` not indented as children of it.

<img width="379" alt="oscal_reference_docs_choice_layout" src="https://user-images.githubusercontent.com/94922603/179103548-51fb7634-c352-4d10-9b2b-7e675270c42e.png">

### Acceptance Criteria

- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-nist** [comment]
Assigning from Dave to myself as he rolled off the project. Will review backlog and consider priority and whether to include in next sprint or backlog.

**Comment by aj-stein-nist** [comment]
Talked with @david-waltermire-nist Friday. Dave still likely has some WIP code for this issue on his workstation he can get over to us on Tuesday.

**Comment by nikitawootten-nist** [comment]
I'm picking this up for the current sprint.

**Comment by nikitawootten-nist** [comment]
Below are a few options I've come up with that maintain the same indentation while clearly showing which children belong to a choice. I'm personally leaning towards option 2.

## Option 1:

Deindent the choices to the same position as the other entries using a negative margin, and set a background color to convey which children belong to the choice.

<img width="849" alt="Screenshot 2023-03-02 at 12 03 15 PM" src="https://user-images.githubusercontent.com/63109766/222501081-66eb4be2-fcf8-4f26-81a5-3bbdff25a5a8.png">

## Option 2:

Same as option 1, but prevent the background from overflowing to the right.

<img width="496" alt="Screenshot 2023-03-02 at 12 06 36 PM" src="https://user-images.githubusercontent.com/63109766/222501215-b73d6c40-eb40-4278-9d3e-83d2619380a0.png">

## Option 3:

Add a horizontal line at the same point of indentation, conveying that the elements are not children of the previous elements while maintaining the "cascading" design.

<img width="496" alt="Screenshot 2023-03-02 at 11 59 58 AM" src="https://user-images.githubusercontent.com/63109766/222501251-7c7a7f71-d9d2-4b05-bc37-fa1846a0766e.png">
