### ISSUE TITLE
Disable Table of Contents on Pages

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1372]
### User Story

As an OSCAL tool developer, in order to efficiently review reference model docs efficiently with browser hangs as part of the current implementation, I want the right-hand side table of contents on these pages removed/disabled (they are from dynamic content).

### Goals

- [ ] [Disable the tocbot table of contents in the page configuration like in these examples](https://github.com/usnistgov/OSCAL/search?l=Markdown&q=toc%3A) to increase performance

### Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-nist** [comment]
As Dave has rolled of the project, I will re-assign this to myself in the interim until I can update it.

**Comment by aj-stein-nist** [comment]
@nikitawootten-nist and @wendellpiez, I was reviewing notes for this task. Given what we surmised in https://github.com/usnistgov/OSCAL/issues/1373#issuecomment-1423242308, is removing TOC generated by tocbot worth considering as high priority? Worth doing at a lower priority, not worth doing at all? I re-read the notes in HackMD and saw your follow-on steps, but was not100% clear if I should purse this or not.

**Comment by wendellpiez** [comment]
If we remove it we need to live without a ToC or provide one by other means, which requires some engineering.

As @nikitawootten-nist will see when we get to the XSLT, the generated HTML includes quite a bit of overhead and redundancy, in part specifically to meet its own requirements for internal linking while at the same time not getting in the way of Hugo, tocbot or any other 'interested' party.

(If you think one static site generator is fun, link two or three together then slap some Javascript on top.)

Some smart design in the context of what should be produced in the back end vs what left to Hugo might help things all around. So :+1: for returning to tocbot later.

**Comment by aj-stein-nist** [comment]
Alright, I am going to potentially remove that issue from the sprint, but we can discuss that on Thursday when we all sync anyway.

**Comment by aj-stein-nist** [comment]
> Alright, I am going to potentially remove that issue from the sprint, but we can discuss that on Thursday when we all sync anyway.

@nikitawootten-nist, re your feedback on other issues, you think this is safe to drop to moderate/low priority and move from the sprint? We have plenty of other priorities for now. Thanks in advance.

**Comment by nikitawootten-nist** [comment]
@aj-stein-nist has this issue been superseded by #1682 ?

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist has this issue been superseded by #1682 ?

Agreed, closing because it is obsolete. Thanks, Nikita.
