### ISSUE TITLE
Cleanup OSCAL Repo

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#138]
# User Story:

As an OSCAL user, I have access to a well structured, clearly documented repository.

## Goals:

- Document the contents of all directories
   - Ensure all directories have a README.md with a paragraph describing each file and directory located within the same (@wendellpiez @kscarf1)
   - Paragraph should explain the function of the file and its purpose
- Relocate powerpoint presentations.
   1. Create a NIST CSRC project page (@david-waltermire-nist)
   1. Move Powerpoint presentations out of the master branch to csrc.nist.gov (@kscarf1)

## Dependencies:

None

## Acceptance Criteria

- Verify that all directories have a README.MD with a clear, concise description of their purpose and corresponding content
- Ensure PowerPoint presentations are published to csrc.nist.gov

**Comment by david-waltermire-nist** [comment]
4/26/2018 - Sprint 10 Progress Report

Goal: Create a NIST CSRC project page.
Progress: I have a draft page created, but not published.
% Complete: 50%
Open Issues: @kscarf1 Can you send me a quick OSCAL summary for the CSRC page? This should briefly introduce the project and provide links to the pages.nist.gov site and GitHub repo.

**Comment by kscarf1** [comment]
4/26/2018 - Sprint 10 Progress Report

Goal: Add and standardize README.md files for each GitHub directory.
Progress: I have revised the root README.md and the README.md in the /docs directory as models for people to review and provide feedback on. I have also removed the presentations and a few old files that aren't needed any more from GitHub. Wendell is standing by to provide support on adding README.md content as needed.
% Complete: 10%
Open Issues: @david-waltermire-nist Please review the PR when you have a few minutes. If it looks OK, please accept it so others can review the model README.md files.

**Comment by wendellpiez** [comment]
**4/26/2018 - Sprint 10 Progress Report**

Goal: Add and standardize README.md files for each GitHub directory.
Progress: As noted, I'm standing by to help @kscarf1 when/as questions come up, with both info and technical support
% Complete: 10%
Open Issues: none

**Comment by kscarf1** [comment]
5/3/2018 - Sprint 10 Progress Report

Goal: Add and standardize README.md files for each GitHub directory.
Progress: I have revised several existing README.md files and created several new ones. I have sent Wendell a short list of files and directories I need summaries for so far. I'm continuing to go through all the subdirectories in the repository. 
% Complete: 40%
Open Issues: @wendellpiez Need summaries from Wendell as his time permits. Not a rush.

**Comment by david-waltermire-nist** [comment]
5/3/2018 - Sprint 10 Progress Report

Goal: Relocate powerpoint presentations.
Progress: The CSRC [OSCAL site](Relocate powerpoint presentations. ) has been published. For some reason the powerpoint is not visible or linked to on the site. I'll need to figure out how to fix this.
% Complete: 90%
Open Issues: @kscarf1 The powerpoint can be [found](https://csrc.nist.gov/CSRC/media/Presentations/The-Open-Security-Control-Assessment-Language-A-h/images-media/OSCAL%20-%20High%20Level%20Overview.pptx) on the CSRC site however.

**Comment by kscarf1** [comment]
**5/10/2018 - Sprint 10 Progress Report**

Goal: Add and standardize README.md files for each GitHub directory.
Progress: I have completed most of the README.md file creation and editing for the first two levels of subdirectories. Wendell has filled in the blanks from the initial list I sent him, and I have just sent him a second list of files and directories I need summaries for so far. By early next week I should have all README.md files completed.
% Complete: 60%
Open Issues: @wendellpiez Need additional summaries from Wendell as his time permits.

**Comment by kscarf1** [comment]
**5/17/2018 - Sprint 10 Progress Report**

Goal: Add and standardize README.md files for each GitHub directory.
Progress: Wendell provided information on the second list of files and directories, and I have updated the README.md files accordingly. I have sent a third list to Wendell. I should have all README.md files completed before Monday.
% Complete: 70%
Open Issues: @wendellpiez Need additional summaries from Wendell as his time permits.

**Comment by kscarf1** [comment]
**5/24/2018 - Sprint 10 Progress Report**

Goal: Add and standardize README.md files for each GitHub directory.
Progress: Wendell has provided all the requested information. I have final edits to make to the README.md files, and I expect to commit the remaining changes before the sprint 10 acceptance meeting.
% Complete: 90%
Open Issues: None

**Comment by wendellpiez** [comment]
**5/24/2018 - Sprint 10 Progress Report**

See Karen's report. Standing by to help as needed.
