### ISSUE TITLE
Tutorial: Creating a basic component definition - 404

### ISSUE THREAD

**Issue by brandtkeller** [usnistgov/OSCAL#1389]
### Describe the bug

I believe this may be the location to point out that attempts to resolve: https://pages.nist.gov/OSCAL/learn/tutorials/implementation/basic-component-definition/ result in a 404 being returned. 

### Who is the bug affecting

All users of the pages.nist.gov/OSCAL/learn/tutorials

### What is affected by this bug

Website

### How do we replicate this issue

Attempt to resolve: https://pages.nist.gov/OSCAL/learn/tutorials/implementation/basic-component-definition/ in a browser

### Expected behavior (i.e. solution)

The document that is located in this repository should be presented to users.

**Comment by brandtkeller** [comment]
Further investigation and it looks like it's just a broken link

If you use the sidebar - you can reach the page: https://pages.nist.gov/OSCAL/learn/tutorials/implementation/simple-component-definition/

note the use of `simple-component-definition` vs `basic-component-definition`

**Comment by david-waltermire-nist** [comment]
@brandtkeller Thanks for pointing this out. The broken link is now fixed.
