### ISSUE TITLE
OSCAL Tools: Update C2 Labs Atlasity to RegScale

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#1395]
On pages.nist.gov/OSCAL/tools, please update the listing for C2 Labs Atlasity to the following:

Name: [RegScale](https://regscale.com) (formerly Atlasity)
Provider/Developer:  RegScale (spun out of C2 Labs)
Description:  RegScale Community Edition is a free to use, API-centric real-time Governance, Risk and Compliance (GRC) platform that deploys in any environment, integrating with security and compliance tools via API to keep compliance documentation continuously up to date.  GRC staff can work in the UI, engineers can write scripts to feed the API, and both human- and machine-readable (OSCAL) content is automatically generated on demand.  Additional information can be found here:  https://regscale.com/oscal
Type:  Community Edition

**Comment by bradh** [comment]
You can make a PR against https://github.com/usnistgov/OSCAL/blob/main/docs/content/tools/_index.md

**Comment by akarmel** [comment]
Thanks @bradh!    PR #1399 created with this change.
