### ISSUE TITLE
Fix OSCAL overview graphic in pages.nist.gov/OSCAL

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#140]
# User Story:

As a OSCAL consumer, I have access to a clear OSCAL overview graphic published to pages.nist.gov/OSCAL

## Goals:

OSCAL overview graphic is clear and published to pages.nist.gov (@david-waltermire-nist)

## Dependencies:

None

## Acceptance Criteria

No cursor appears in the OSCAL overview graphic published to pages.nist.gov

**Comment by evelynmitchell** [comment]
There is also a cropping error at the top and bottom of the image, which could be fixed at the same time.

**Comment by david-waltermire-nist** [comment]
4/26/2018 - Sprint 10 Progress Report

Goal: OSCAL overview graphic is clear and published to pages.nist.gov
Progress: none.
% Complete: 0%
Open Issues: @iMichaela Can you send me the graphic with the adjusted wording?

**Comment by iMichaela** [comment]
4/26/2018 - Sprint 10 Progress Report

Goal: OSCAL overview graphic is clear and published to pages.nist.gov
Progress: the graphic with the adjusted wording was delivered.
Complete: 100% (ONLY graphic updated/re-generated)
Open Issues: none.

**Comment by david-waltermire-nist** [comment]
5/3/2018 - Sprint 10 Progress Report

Goal: OSCAL overview graphic is clear and published to pages.nist.gov
Progress: I have the graphic from @iMichaela. Still need to update the Visio and post the graphic.
Complete: 0%
Open Issues: none.

**Comment by david-waltermire-nist** [comment]
5/10/2018 - Sprint 10 Progress Report

Goal: OSCAL overview graphic is clear and published to pages.nist.gov
Progress: I have created the graphic and emailed it around to the team. I have incorporated feedback as well. Next step is to post it to the site.
Complete: 90%
Open Issues: none.

**Comment by david-waltermire-nist** [comment]
5/17/2018 - Sprint 10 Progress Report

Goal: OSCAL overview graphic is clear and published to pages.nist.gov
Progress: I have posted the graphic to the docs site. Need to update the pages.nist.gov site.
Complete: 95%
Open Issues: none.

**Comment by david-waltermire-nist** [comment]
5/24/2018 - Sprint 10 Progress Report

Goal: OSCAL overview graphic is clear and published to pages.nist.gov
Progress: I have posted the graphic to the pages.nist.gov site.
Complete: 100%
Open Issues: none.
