### ISSUE TITLE
Automation is difficult with OSCAL catalog named parameters

### ISSUE THREAD

**Issue by degenaro** [usnistgov/OSCAL#1426]
### Describe the bug

References:

1. https://www.fedramp.gov/assets/resources/templates/FedRAMP-SSP-Moderate-Baseline-Template.docx
2. https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_catalog.json

`Good case`:

In FedRAMP-SSP-Moderate-Baseline-Template we see:

![image-1 1](https://user-images.githubusercontent.com/520029/186452909-90897b3f-60c1-449b-9dbe-f5c71f0d2b09.png)

Correspondingly in NIST 800-53 we see:

![image-1 2](https://user-images.githubusercontent.com/520029/186452907-072ec082-1807-4a88-982d-714fe395fc33.png)

This allows for easy mapping between:

*PS-7(d)-1* : *ps-7_prm_1*

*PS-7(d)-2* : *ps-7_prm_2*

`Bad case:`

In FedRAMP-SSP-Moderate-Baseline-Template we see:

![image-2 1](https://user-images.githubusercontent.com/520029/186452905-2d19ac1e-07ee-4112-80b5-f416199b0b49.png)

Correspondingly in NIST 800-53 we see:

![image-2 2](https://user-images.githubusercontent.com/520029/186452901-5020ec30-dd5d-4275-9319-c2cdbe4e472f.png)

This does not allow for easy mapping between:

*SI-6(d)-2* : *si-6_prm_7*

### Who is the bug affecting

Those who wish to use the documentation (ref 1) to describe that parameters used by OSCAL catalog (ref 2).

### What is affected by this bug

OSCAL Content, Documentation

### How do we replicate this issue

Try to use the description `SI-6(d)-2` to derive the OSCAL parameter named `si-6_prm_7`.

### Expected behavior (i.e. solution)

The documentation (ref 1) and/or the OSCAL catalog (ref 2) should provide means to easily map parameters, such as `SI-6(d)-2` to `si-6_prm_7`.

### Other comments

If this is not the right place to complain, would appreciate pointer to the right place and help in effecting change to facilitate the desired mapping automation.

**Comment by GaryGapinski** [comment]
It appears that FedRAMP may have attempted to map parameters to control _statements_; not a good idea as parameters (in OSCAL) can be defined at the [catalog, group, and control](https://pages.nist.gov/OSCAL/reference/latest/complete/xml-index/#/param) level: **not** at the control statement level. Parameters can be _referenced_ by control statements as well as by parameters, but cannot be _defined_ by control statements or parameters (in OSCAL).

Related: https://github.com/usnistgov/oscal-content/issues/113.

**Comment by david-waltermire-nist** [comment]
I agree with @GaryGapinski that this is is a FedRAMP problem, not an OSCAL problem. The FedRAMP documentation is ambiguous at best considering that some statements can have multiple parameters in SP 800-53.

@Rene2mt FedRAMP should consider using ODPs in the SP 800-53 rev5 guidance to avoid this issue.

@degenaro You might want to open an issue in [GSA/fedramp-automation](https://github.com/GSA/fedramp-automation) about this.

**Comment by wendellpiez** [comment]
:+1: on using normative ODP identifiers (created by FISM) such as those given in Rev 5. For Rev 4, it should be noted that the FedRAMP identifier for a parameter (keyed to where it is first referenced) is not the same as the OSCAL identifier for the same parameter (assigned in the context of the control).

**Comment by Rene2mt** [comment]
This appears to be an issue with the FedRAMP rev 4 baselines.  @degenaro would you mind creating an issue in the [GSA/FedRAMP-automation](https://github.com/GSA/fedramp-automation/issues) repo?

FedRAMP is using ODP identifiers for in the rev 5 baselines

**Comment by GaryGapinski** [comment]
If the **800-53A** "ODP" identifiers are used (from [oscal-content)](https://github.com/usnistgov/oscal-content), be aware that any mapping to or from **800-53** and its ODPs will be _quite_ awkward. Control AC-1 is an example. [800-53 rev5](https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final) has seven ODPs for AC-1; the [oscal-content main branch](https://github.com/usnistgov/oscal-content/tree/main) [catalog](https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5_catalog.xml) on the main branch has eight. The PDF document is normative.

Contrast with the [oscal-content v1.0.0 branch](https://github.com/usnistgov/oscal-content/tree/v1.0.0) [catalog](https://raw.githubusercontent.com/usnistgov/oscal-content/v1.0.0/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5_catalog.xml) and make a choice. One's choice of branch may be aided by a look at the main and v1.0.0 branch resolved catalogs which exhibit the same ODP disparity in number.

I have not yet had the fortitude to create a rationalization transform for the current oscal-content main branch.

**Comment by degenaro** [comment]
Sure. I did send e-mail as I understood the instructions there, but will go
ahead a create an issue per your suggestion.

**Comment by wendellpiez** [comment]
@GaryGapinski I am afraid this is a case of the complexity of the solution having to reflect the complexity of the problem. If 800-53A contents are not used, parameters that are referenced only from those contents can also be ignored. Parameters referenced from the main contents should still work, whether 'new' or 'old'. If 800-53A contents are used, their greater granularity of assessment must be accommodated either by more parameters, or some sort of more complex (nested?) parameter, which we decided was a bad idea. (And we decided combination was also better than duplication, where possible.)

It is clear however that this "two-layered" model already poses issues for implementors, and further discussion on parameter modeling and best practices is sure to be had. I expect such a discussion and airing of ideas, including new ideas, will be welcome, assuming the relevant stakeholders can be represented.

**Comment by GaryGapinski** [comment]
> If 800-53A contents are not used, parameters that are referenced only from those contents can also be ignored.

Is that the same as asserting
```
//param[@id = parent::control/part[@name eq 'statement']/descendant::insert/@id-ref]
```
or
```
//param[@id = //control/part[@name eq 'statement']/descendant::insert/@id-ref]
```
identify the actual (as opposed to faux 800-53A) ODPs?
