### ISSUE TITLE
Cleanup FedRAMP low/moderate/high baselines

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#144]
# User Story:

As a OSCAL consumer that needs 800.53 data, I have an accurate and usable OSCAL profiles for each FedRAMP baseline (low/moderate/high).

## Goals:

1. Improve the data quality of the FedRAMP low/moderate/high profiles (@wendellpiez)
   - Design, document and implement a clean ID naming scheme
   - Adjust IDs based on the catalog changes

        The following format will be used for IDs
        > {control-id|subcontrol-id}_{part}_{outline level}
        >
        > [part] - smt (statement), obj (Assessement Objectives), prm (Parameter)
        >
        > Examples:
        > ac-1_smt_a
        > ac-1_smt_a.1
        > ac-1_smt_a.1
        > ac-2.6_obj_a
        > ac-2.6_obj_a.1
        > ac-1_prm_1
        > ac-1.1_prm_1
        > 
        > - No terminal dots
        > - Use outline level letters and/or numbers (in lowercase) separated by dots
        > - Implicit number for top level objectives will use letters explicitly.
        > - Underscores will separate fields 
    - Support the following parameter fields:
       - label (1)(required) - text from SP800-53rev4
       - desc (0-to-many:catalog + profile) - a textual description of the parameter
       - requirement (0-to-1:profile) - A textual description of a constraint on the allowed values (e.g., every 3 months)
       - value (0-to-1:catalog + profile) - The actual value(s) to be used for the parameter.

1. Base the FedRAMP profiles on the respective 800.53 profile (@wendellpiez)

1. Incorporate all parameters and guidance found in low/moderate/high FedRAMP baseline spreadsheets (@brianrufgsa)
 
1. Review updated FedRAMP low/moderate/high profiles for any remaining anomalies (@iMichaela)
   - Cleanup any paragraph or other anomalies 

## Dependencies:

Starting this issue requires that we stabilize the IDs within the 800.53 baselines
Completing this issue requires completion of issue #143 

## Acceptance Criteria

- All content changes defined under the goal 1 have been made
- FedRAMP profiles accurately reflect the data in the FedRAMP baseline spreadsheets
- All anomalies identified during team reviews under goal 2 have been fixed

**Comment by iMichaela** [comment]
04/26/2018 - Sprint 10 Progress Report
Goal: Review updated FedRAMP low/moderate/high profiles for any remaining anomalies
Progress: Waiting for the dependencies to be completed (goals 1-3)
Complete: 0%
Open Issues: none at this time

**Comment by wendellpiez** [comment]
**04/26/2018 - Sprint 10 Progress Report**
Goal: Improve the data quality of the FedRAMP low/moderate/high profiles 
Progress: We've done significant work at the foundations, clarifying the issues with @brianrufgsa and @PCrayton (with much more to be done), and assessing (for example) suitability of MS-Access based data sets describing FedRAMP as sources for data enhancement. However, actually incorporating such (or any) data awaits the dependency on #143, followed by specification.
Percentage Complete: 5%
Open Issues: None at this time

**Comment by wendellpiez** [comment]
**5/2/2018 - Sprint 10 Progress Report**
Progress: Pending review and acceptance, identifiers in the underlying catalog may be stable cf #143. Also, insertion points have been mentioned in parameter labels, which should make the mapping easier and more robust from external data sources describing the FedRAMP profiles.
Percentage Complete: 5% (but no longer blocked)
Open Issues: None at this time

@brianrufgsa has already made some experiments extracting XML from MS Access DB.

**Comment by brianrufgsa** [comment]
5/2: Matching FedRAMP prescribed parameters to 800-53 parameters using parameter labeling standard, including nested parameters. (90%) Finalizing batch report of differences between 800-53 and FedRAMP baselines. (60%). Working in database with plan to export to XML when ready.

**Comment by iMichaela** [comment]
**5/2/2018 - Sprint 10 Progress Report**
Goal: Review updated FedRAMP low/moderate/high profiles for any remaining anomalies
Progress: Waiting for the dependencies to be completed (goals 1-3) @brianrufgsa and @PCrayton 
Complete: 0%
Open Issues: none at this time

**Comment by david-waltermire-nist** [comment]
I modified the user story to incorporate notes from our engineering meeting.

**Comment by PCrayton** [comment]
5/3/2018 - Sprint 10 Progress Report
Goal: Incorporate all parameters and guidance found in low/moderate/high FedRAMP baseline spreadsheets 
Progress: Worked on matching up FedRAMP parameters across the low/moderate/high baselines and identifying the delta between them
Completion: 67%
Open Issues: none at this time

**Comment by wendellpiez** [comment]
5/9/2018 - Sprint 10 Progress Report
Progress:

cf #143 for progress on dependencies. The underlying SP800-53 catalog and its baselines should be stable. Now obsolete (but still valid) FedRAMP profiles are marked (commented) as such (they are non-functional due to broken IDs) -- but have been retained as examples of usage. A new "stub" FedRAMP profile, `FedRAMP-HIGH-calls-only.xml` is functional, as it references correct IDs for controls and subcontrols. But it does not include any parameter settings. (Parameter IDs have also been updated in the underlying catalog.)

Percentage Complete (items 1 and 2): 90%
Open Issues:
- Verifying the current HIGH FedRAMP profile as it stands (especially, is the control set correct?)
- Similarly migrating the MODERATE and LOW profiles? Stubbing out parameters? Maybe we have enough info to go on without (since the ID scheme is static) - it depends on how we intend to produce data out of the FedRAMP db sources.

**Comment by brianrufgsa** [comment]
Had an all-day FedRAMP commitment Friday, and was on personal travel Mon - Wed, so not much progress for me this week. 

Matching FedRAMP prescribed parameters to 800-53 parameters using parameter labeling standard, including nested parameters. (100%) Finalizing batch report of differences between 800-53 and FedRAMP baselines. (80%). Working in database with plan to export to XML when ready.

**Comment by PCrayton** [comment]
Sprint 10 Status - 5/10/18
Goal: Incorporate all parameters and guidance found in low/moderate/high FedRAMP baseline spreadsheets
Progress: Identified all changes in descriptions/parameters/guidance between FedRAMP low/moderate/high baselines(100%)
Issues: none at this time

**Comment by iMichaela** [comment]
**5/10/2018 - Sprint 10 Progress Report** 
Goal: Review updated FedRAMP low/moderate/high profiles for any remaining anomalies
Progress: Waiting for the dependencies to be completed (goals 1-3) @brianrufgsa and @PCrayton
Complete: 0%
Open Issues: I was waiting on @brianrufgsa to complete Incorporating all parameters and guidance found in low/moderate/high FedRAMP baseline spreadsheets (3.) @PCrayton just reported finishing this task about 3 hours ago. Will focus on it starting today.

**Comment by david-waltermire-nist** [comment]
@brianrufgsa @PCrayton Please be sure to report against the goals in the user story. I am good with you discussing interim work as well, but we need to draw attention to the final deliverables in the user story (US). Let's talk in our meeting today on how to incorporate your analysis into a set of FedRAMP OSCAL profiles.

**Comment by wendellpiez** [comment]
**May 16 Sprint 10 Progress Report**
Goals: 1-2 (stability of underlying SP800-53 catalog and baselines)

Progress: The underlying catalogs and profiles have all been updated, as have schemas thereto related. Numerous small adjustments have been made in the schemas as well as resources).

Complete: 100% pending acceptance as noted above

Open Issues: Schema (tag set) documentation now lags somewhat behind current schemas.

**Comment by brianrufgsa** [comment]
Scripts now output FedRAMP low/moderate/high guidance and parameters into OSCAL-compliant XML from the database. This includes the correct FedRAMP-selected controls for each of the three major baselines. (FedRAMP Tailored has unique needs and will need to be addressed in a future sprint.) 

Outstanding items:
- Ensure parameter id's in database match those in the revised 800-53 catalog.
- Based on 15-May discussion, revise tags for FedRAMP parameter "constraints" and value "assignments".
- Adjust scripts to include profile source elements (author, publisher, date, etc.)
- address formatting within content data.

On track to wrap up for end of sprint next week.

**Comment by PCrayton** [comment]
5/17/2018 - Sprint 10 Progress Report
Goal: Incorporate all parameters and guidance found in low/moderate/high FedRAMP baseline spreadsheets 
Progress: Working on verifying all parameters in the FedRAMP XML profiles @brianrufgsa match with the 800-53 catalog.
Completion: 50%
Open Issues: None at this time.

**Comment by brianrufgsa** [comment]
@david-waltermire-nist and @iMichaela - I sent you both an email earlier this afternoon where I let you know I'm pushing to get this done today or tomorrow so you have time to review.

**Comment by iMichaela** [comment]
**5/24/2018 Sprint 10 Progress Report**
**Goal**: Review updated FedRAMP low/moderate/high profiles for any remaining anomalies
**Progress**: Completed - summary of findings is below (minor issues)
Complete: 100%
Open Issues: None

![image](https://user-images.githubusercontent.com/13984545/40466938-da9ea8ea-5ef5-11e8-960c-4e3f29f7c550.png)

<set-param param-id="ia-5.1_prm_2">
--
  | <constraint>at   least one</constraint>
  | </set-param>
  | <set-param param-id="ia-5.1_prm_1">
  | <constraint>case sensitive, minimum of twelve characters, and at least   one each of upper-case letters, lower-case letters, numbers, and special   characters</constraint>
  | </set-param>
  | <set-param param-id="ia-5.1_prm_3">
  | <constraint>one day minimum, sixty day maximum</constraint>
  | </set-param>
  | <set-param param-id="ia-5.1_prm_4">                 <constraint>twenty four</constraint>     </set-param> | <constraint>twenty four</constraint>     </set-param> |   |  
<constraint>twenty four</constraint>     </set-param>
  |  
![image](https://user-images.githubusercontent.com/13984545/40466957-ec53f1c6-5ef5-11e8-99ee-be0ed290ed02.png)

![image](https://user-images.githubusercontent.com/13984545/40466967-f54939ee-5ef5-11e8-8d2d-278114fe5beb.png)

![image](https://user-images.githubusercontent.com/13984545/40466988-00d3effc-5ef6-11e8-8703-b0bf88152655.png)

**Comment by PCrayton** [comment]
Sprint 10 Progress Report 5/24/18
Goal: Incorporate all parameters and guidance found in low/moderate/high FedRAMP baseline spreadsheets 
Progress: Verified the entries in the FedRAMP low/moderate/high baseline schemas created by @brianrufgsa 
Complete: 100%
Open Issues: none

**Comment by brianrufgsa** [comment]
Supported Goals 1 and 2. Both are complete.
Goal 3: Incorporate all parameters and guidance found in low/moderate/high FedRAMP baseline spreadsheets.
Complete: 100%

Delivered High, Moderate, Low FedRAMP Profiles in XML via Pull Request #173.

**Comment by david-waltermire-nist** [comment]
PR #188 addressed updating the README.md to reflect these changes.
