### ISSUE TITLE
Implement SemVer-based comparison on oscal-version in XSLT Profile Resolver

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#1440]
### User Story

Picking up #1313 and #1272, this Issue tracks complete implementation of `oscal-version` property (including value comparison) in the XSLT-based profile resolver. This requires supporting Semantic Versioning.

When complete, this functionality will be validated via unit tests.

### Goals

- [ ] Complete and test implementation
- [ ] Merge working code into `develop`
- [ ] Provide top-level unit testing cf #1076 and #1087 (over rebase) - either merged, or on track to be merged

### Dependencies

TBD: clarify dependency between merging this code and merging unit tests now in working branches.

### Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-nist** [comment]
Seems there is a nice PR ready for review and to potentially close this out. Assigned @david-waltermire-nist and @wendellpiez to take a look during weekly status update.
