### ISSUE TITLE
Race Condition in Model Docs and Website Updates in Same CI/CD Workflow

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1447]
### User Story

As a NIST OSCAL developer, in order to efficiently build updated reference model docs and website updates at the same time, I would like the CI/CD system to detect model update commits in the same workflow and `git pull` only under those conditions as to not fail the build.

### Goals

- [ ] Determine risk of automatically `git pull`ing on branches where the model `workflow-generate-website-reference.yml` workflow step successfully executes and adds commits that are not detected by `workflow-generate-website.yml` steps that have not pulled in current changes.
  - [ ] Document risk decision.
- [ ] Implement a check in CD `workflow-generate-website.yml` to `git pull` if `workflow-generate-website-reference.yml` did commit to the target main branch.

### Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
Doing a `git pull --ff-only` would be an easy fix.

**Comment by aj-stein-nist** [comment]
Discussed this with @nikitawootten-nist and lo and behold, this issue is obsolete.
