### ISSUE TITLE
System boundary constructs as part of implementation

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#152]
# User Story:

As an OSCAL user, I would like to be able to define more explicit system boundaries as part of my "implementation" artifacts. With "great flexibility in determining what constitutes an information system (i.e., major application or general support system)" that agencies have, per [NIST 800-18 Rev. 1](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-18r1.pdf), comes ambiguity in regards to the explicit technical and non-technical system boundaries. Classifying something as a "general support system", "major application", and "minor application", per OMB A-130, can be difficult when it comes to new technologies. Furthermore, net-centric architectures, as defined by [800-37 Rev 1.](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-37r1.pdf), are becoming more commonplace, making it challenging to identify these boundaries and keep these boundaries updated as the system evolves. While [800-37 Rev. 2](https://csrc.nist.gov/CSRC/media/Publications/sp/800-37/rev-2/draft/documents/sp800-37r2-discussion-draft.pdf) looks to be changing up some of these constructs, the task of identifying a system boundary becomes no less clear-cut.

## Goals:

One can more explicitly denote a technical or non-technical component as being part of a system, dynamic subsystem, or external subsystem (or system-of-interest, enabling system, system element, or other system per 800-37 Rev. 2). In addition, one can equate a specific technical or non-technical system change to a more refined update to the authorization boundary.

## Dependencies:

- #216, #215, #214 
- 800-37 Rev. 2 updates
- Future revision to 800-18

## Acceptance Criteria

- System boundaries can be expressed in "implementation" artifacts
- Changes to system components are reflected dynamically in system boundary in "implementation"

**Comment by david-waltermire-nist** [comment]
This is being worked in #363, #364, and #329. Closing.
