### ISSUE TITLE
Create Weekly Status Report Template for Issues

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#154]
**WEEKLY STATUS REPORTING PROCESS**
- Each goal in the issue will be assigned to an assignee
- Each team member enters their own status update weekly with percentage complete against the goals to which they are assigned
  - Numbered goals are worked on sequentially
  - Bulleted goals are worked on in parallel
- Pull request must be submitted for all goals before an issue is moved to under review
- Raise active, unresolved issues on the status calls

**ACTION ITEM**
Create weekly status report template for issues assigned to a Sprint per the following:

**4/23/2018 - Sprint 10 Progress Report**
- GOAL: 
- PROGRESS TO DATE:
- PERCENTAGE COMPLETE:
- OUTSTANDING ISSUES:
  - @mention the individual who needs to respond to the issue

**Comment by david-waltermire-nist** [comment]
4/26/2018 - Sprint 10 Progress Report

Goal: All
Progress: The pull request for this issue has been reviewed and merged.
% Complete: 100^%
Open Issues: none.
