### ISSUE TITLE
Creating a Component Definition - 404

### ISSUE THREAD

**Issue by paulJRCurtis** [usnistgov/OSCAL#1557]
### Describe the bug

The [Creating a Component Definition](https://pages.nist.gov/OSCAL/learn/tutorials/component-definition/) link on 
https://pages.nist.gov/OSCAL/concepts/layer/implementation/component-definition/ 

I believe the link should be to https://pages.nist.gov/OSCAL/learn/tutorials/implementation/simple-component-definition/

### Who is the bug affecting

Anyone attempting to find the Creating a Component Definition tutorial

### What is affected by this bug

Documentation

### How do we replicate this issue

select the the [Creating a Component Definition](https://pages.nist.gov/OSCAL/learn/tutorials/component-definition/) link on 
https://pages.nist.gov/OSCAL/concepts/layer/implementation/component-definition/ 

### Expected behavior (i.e. solution)

link should go to https://pages.nist.gov/OSCAL/learn/tutorials/implementation/simple-component-definition/

**Comment by aj-stein-nist** [comment]
Nice find, thanks! I am a little confused how the link checker did not pick this one up before, but I will add a PR to fix this soon. I appreciate the report.
