### ISSUE TITLE
Update Community Meetings Pages

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1560]
### User Story

As an OSCAL community member, in order to understand different opportunities for me to engage with the NIST OSCAL Team and collaborate, I want an updated meeting inventory on the public with relevant BlueJeans/Team invitation details, intended audience, themes, and the agenda of upcoming meetings.

### Goals

- [x] Modify [the OSCAL Lunch with the Devs meeting page accordingly](https://pages.nist.gov/OSCAL/contribute/dev-lunch/).
- [x] Modify [the Model Review meeting page accordingly](https://pages.nist.gov/OSCAL/contribute/model-review/).
- [x] Add or remove pages accordingly to align with newly slated inventory of NIST OSCAL Team meetings, intended audience, and other important data.

### Dependencies

N/A

### Acceptance Criteria

- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-nist** [comment]
@david-waltermire-nist per discussion today during our weekly sync, let me know if you want this pulled into Sprint 60 or Sprint 61 or not.

**Comment by aj-stein-nist** [comment]
I might hold off on this because I reviewed the spreadsheet and I am not clear I have to change one or both significantly based on the updated names and notes associated.

**Comment by iMichaela** [comment]
@aj-stein-nist I am suggesting to generate new BlueJeans rooms to allow for transcripts if recordings are approved (feature we did not have years back when the rooms were generated) and to name the rooms properly, per hosts' desire or per the Strategic Plan.

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist I am suggesting to generate new BlueJeans rooms to allow for transcripts if recordings are approved (feature we did not have years back when the rooms were generated) and to name the rooms properly, per hosts' desire or per the Strategic Plan.

That aside, I didn't know what we want to call the reformed meetings and if the summaries should change. I can put placeholders for the meeting invite info. I assume we can discuss as a group this week.

**Comment by aj-stein-nist** [comment]
@Compton-NIST I was told you have an updated description for the DEFINE meeting you were proposing. I would like to quickly pick up a draft of the web page in a PR, can you send it to me, in a Gist, or Gitter DM, or something? Thanks.

**Comment by aj-stein-nist** [comment]
@Compton-NIST could I get that description or will you need me to catch up with you later in the week?

**Comment by Compton-NIST** [comment]
@aj-stein-nist Will follow up with you.  Saw this comment this morning and need to verify.

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist Will follow up with you. Saw this comment this morning and need to verify.

@Compton-NIST I am going to draft the page as needed today and stub in the info the meeting for the description you are working on. Later today can you give me your current working copy so we can get it on the website? Thank you.

**Comment by aj-stein-nist** [comment]
Due to popular demand, I am moving this forward today. 😆

**Comment by iMichaela** [comment]
@aj-stein-nist and @Compton-NIST - How can I help?

**Comment by Compton-NIST** [comment]
@aj-stein-nist Hot off the press and sorry for the delay:

```
OSCAL DEFINE - Develop Enhancements, Future Implementations and New Education
 
OSCAL DEFINE is a new discussion related to the research and educational pursuits of the OSCAL program using an iterative and collaborative approach with the community.  Our goal is to establish an OSCAL research framework that allows topics to receive the necessary definition and understanding sufficient to create educational content, demonstrate usage in practice, gain community’s endorsement, and serve as a catalyst for continued development of OSCAL.
```
