### ISSUE TITLE
Relocation of the OSCAL Tools page

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#1599]
### User Story

As an OSCAL user, I would like to have access to a central source of resources, ideally maintained by the community. For this reason, the NIST OSCAL Tools page should point to the community-maintained resources like [OSCAL Club](https://github.com/oscal-club) that provides a more comprehensive list - see [Awesome OSCAL](https://github.com/oscal-club/awesome-oscal).

### Goals

Remove the list of tools maintained by NIST in favor of larger repositories of tools, examples, etc. maintained by the community. If more than one repository exists, NIST can point to the more comprehensive resource or to more than one resource if they are complimentary.

Justification: NIST did not request any proof that the listed tools are truly supporting OSCAL formats and it came to our attention that some of them do not list such information on their website nor did they demonstrate the OSCAL implementation/support by presenting and demonstrating the tool during one of the NIST-facilitated OSCAL mini workshops. Without documenting on the tool's website and demonstrating how it supports OSCAL, and without presenting such support of OSCAL during an OSCAL workshop, the community can not trust the claims made and the listing on NIST's website is not justified.  

NIST aims to be fair and to not discriminate against any of OSCAL community entities, and therefore will continue to host OSCAL mini workshops to allow tool vendors (and OSCAL users in general) to demonstrate to our community members the work done towards OSCAL adoption, but NIST will not maintain any longer the list of OSCAL tools.

### Dependencies

none

### Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
This would be fine with me *if* our community understands that we will happily link to anyone else's OSCAL Tools; indeed this is a placeholder for a list of links to other *lists*.

This probably needs to be explicitly stated.

**Comment by aj-stein-nist** [comment]
Similar to https://github.com/usnistgov/OSCAL/issues/1294#issuecomment-1410931072, I need someone to volunteer to take care of this in the upcoming sprint, will discuss it during sprint planning tomorrow.

**Comment by aj-stein-nist** [comment]
> ### 02/09/2023 Update:
> 
> Started working on this issue. Met with Armita and Ned to explain the process. I will address all OSCAL pages related issues in one PR (including the OSCAL mini workshops update)

Thanks for the status update. I appreciate it. I will ask that you keep the page content change for each PR separate and I will work with you to merge them efficiently, but still separately. If you need assistance and have concerns. Let me know. Thanks to both of you.
