### ISSUE TITLE
XSLT profile resolver does not work with Saxon version 11

### ISSUE THREAD

**Issue by galtm** [usnistgov/OSCAL#1629]
### Describe the bug

The XSLT profile resolver errors out with Saxon version 11. See the comments in #1596 .

### Who is the bug affecting

Users of the XSLT profile resolver who want to use version 11 or later of the Saxon XSLT engine.

### What is affected by this bug

Tooling & API

### How do we replicate this issue

java -cp _path-to-saxon_/saxon-he-12.0.jar net.sf.saxon.Transform -xsl:oscal-profile-RESOLVE.xsl -s:_path-to-profile.xml_ -o:resolved-catalog.xml

Error message:
```
Type error at char 50 in expression in xsl:variable/@select on line 49 column 89 of oscal-profile-resolve-metadata.xsl:
  XTTE0570  An empty sequence is not allowed as the value of variable $source-profile
at variable source-profile on line 49 column 89 of oscal-profile-resolve-metadata.xsl
```

### Expected behavior (i.e. solution)

Command should produce a catalog file, resolved-catalog.xml

### Other comments

Works with Saxon 10 but not 11 or 12. See https://saxonica.plan.io/issues/5339 for information about changes in document-uri function in Saxon 11.

**Comment by galtm** [comment]
@wendellpiez / @aj-stein-nist : Please assign this issue to me.

**Comment by nikitawootten-nist** [comment]
Update: #1685 has been merged, need to get an update from @aj-stein-nist about this issue being closable.

**Comment by aj-stein-nist** [comment]
> Update: #1685 has been merged, need to get an update from @aj-stein-nist about this issue being closable.

Closable to me, marked it done.
