### ISSUE TITLE
Is there documentation describing the different NIST OSCAL repos?

### ISSUE THREAD

**Issue by gregelin** [usnistgov/OSCAL#1649]
### Question

Is there any description of what the different OSCAL repositories are and which one should be used for what?

**Comment by hahsan-ti** [comment]
All OSCAL repositories or the ones owned by NIST?

**Comment by aj-stein-nist** [comment]
> All OSCAL repositories or the ones owned by NIST?

Owned by NIST for the scope of this conversation. It might be beneficial for the larger community to know more, but we have been asked in consultation with our counsel not to go too far into that for the time being. See https://github.com/usnistgov/OSCAL/issues/1294.

I am going to follow up with some comments about what we discussed with this issue as it pertains to even NIST repos for OSCAL. There are a few. :-)

**Comment by aj-stein-nist** [comment]
@gregelin thanks again for bringing this to our attention. I think we had a wonderful, constructive talk today during the Model Engineering Meeting on this topic.

Moving forward, I think the staff and the community agreed there are two focuses to documenting an accessible and easy to understand answer to your question.

1. I had asked that we have a more cohesive explanation of what OSCAL repos are and how they relate to each other on both the website. Additionally, repos at the top-level should link very closely at the top-level README to this high-level portfolio view such that newcomers can arrive on any one repo and when unclear, they quickly can look up what they arrived upon and why.
2. Michaela recommended, and I agree, that we would benefit from a presentation at a subsequent Model Engineering Meeting on this topic. Potentially, we could look into recording it.

Given the general approach and certain logistical details, I think this is important work in the near-term, but I do not want to burden the team in the current sprint as we are allocated. I would like to adapt the information in the original issue description as you provided, edit with these points and this parenthetical information about prioritziation, and convert it from a question to actionable story work for later. Is that acceptable to you?

**Comment by gregelin** [comment]
@aj-stein-nist Glad the information was useful. I think breaking this down into smaller actionable stories makes sense.

**Comment by aj-stein-nist** [comment]
@nikitawootten-nist, can you share your page draft with @Arminta-Jenkins-NIST to get some thoughts on what she thinks and have her work on this with us? Thanks!

**Comment by aj-stein-nist** [comment]
OK I gave my initial reviews for now. I am also thinking maybe we should have a think about defining what maintenance and support mean if you ask about something in one of the different categories, but maybe we ought to wait on public feedback about that. The acceptance criteria here are minimal, so let's start small. Nice work, @nikitawootten-nist.

**Comment by nikitawootten-nist** [comment]
@gregelin please take a look at #1702, let me know what you think, and if that clears things up.

**Comment by GaryGapinski** [comment]
I'm a bit puzzled where `oscal-cli` is acquiring Schematron constraints for OSCAL XML instance documents. I noticed this [here](https://github.com/usnistgov/oscal-cli/issues/109#issuecomment-1454725794).

**Comment by gregelin** [comment]
> @gregelin please take a look at #1702, let me know what you think, and if that clears things up.

@aj-stein-nist I'm commenting over on #1702
