### ISSUE TITLE
Example/Sample OSCAL Documents

### ISSUE THREAD

**Issue by hahsan-ti** [usnistgov/OSCAL#1652]
### Question

As someone learning the OSCAL model or its use cases, I want to see a complete OSCAL example in any format. This example will be an OSCAL document "filled out" for a fictitious organization with SSP, Assessment, and possibly POA&M data for one or more Systems -- maybe using Lorem Ipsum text. 

This example will be helpful in the following:
* Learning OSCAL
* Identifying Improvements in the Model
* Testing of Verification Scripts/Tools

This issue's rationale comes from a [Gitter conversation](https://gitter.im/usnistgov-OSCAL/Lobby).

**Comment by aj-stein-nist** [comment]
Thanks for your request. This one I would like to add to the backlog so the team discusses it. So this is more of a general request? We have some of these docs and have samples and tutorials around the SSP less so the other models. I thought the interesting perspective I was hoping we address in an issue is the case of providing and generating **purposefully invalid** examples. That was the specific topic of thread, no?

**Comment by hahsan-ti** [comment]
@aj-stein-nist I am interested in examples of invalid documents for testing validators. IMO, software testing without fail cases is no fun. I was alluding to the need for invalid documents with my point of testing verification scripts or tools.

**Comment by aj-stein-nist** [comment]
At this time, the NIST OSCAL Team cannot work on this in the recently started Sprint 64 or the upcoming 2 or 3 sprints. I [appreciate your collaboration with a community member in the channel](https://app.gitter.im/#/room/#usnistgov-OSCAL_Lobby:gitter.im/$dPSdJzqE7flrMBVKzUU1vzaIWrlGpyIJEUHYOn8nXas). Like Michaela and others, I welcome your collaboration with external community members.

If there is a renewed need and interest for involvement from NIST staff or requirements change, please feel free to re-open the issue at any time. For now, I am going to close the issue. Thanks for reaching out and do not hesitate to do so again in the future. Resources and situations change on a case by case basis!
