### ISSUE TITLE
Catalog and profile metadata

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#167]
# User Story:

As an OSCAL user, I can see (in a catalog or profile) at least some minimal metadata helping me to understand the resource (as a whole), its publication, creators, publication status (draft/final), etc. etc. The metadata model is also clean and well-defined enough to help describe the document in the context of automated retrieval, for example by an indexer or in a CMS.

## Goals:

There are some conflicting goals here. The metadata model needs to be small enough to be manageable. Metadata for published documents can get hairy and we cannot afford much complexity. However, it must also be serviceable. The broader goal as usual is both doing it, and showing how it is done.

## Dependencies:

A clearer understanding of requirements and a strategy for how to manage this issue going forward.

## Acceptance Criteria

Published examples show at least enough metadata to meet minimal requirements tbd. These are valid to appropriate schemas and Schematrons.

## Background

@brianrufgsa has volunteered to sketch out "minimal" and "useful" collections of document-level metadata he anticipates for FedRAMP, in case we cab stub something out quickly.

While we should not go overboard, prior art such as http://niso-sts.org/TagLibrary/niso-sts-TL-1-0-html/element/std-doc-meta.html might be considered for ideas/alignment.

**Comment by wendellpiez** [comment]
Models for metadata were included in PR #339. Issue can be closed.

**Comment by david-waltermire-nist** [comment]
Ok. Considering this closed.
