### ISSUE TITLE
Statically generate anchor tags in model documentation

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/OSCAL#1681]
### User Story

Following the work of #1373 it was discovered that the dynamic insertion of anchor tags degraded the performance of larger pages (such as the complete documentation for models), contributing to a frustrating "time to interactive" of over 12 seconds.

When a page loads, a script runs that crawls the site for header tags, and inserts anchors besides each header. This is useful for collaboration as it allows users to pass links to others that refer to specific sections of the site, but there is no need to do this dynamically when we already have a static model generation pipeline doing a lot of the heavy lifting.

As a consumer of model documentation, I would like the documentation to utilize static generation wherever possible so that the pages are usable as the complexity of the models increase.

### Goals

- [x] Discover (or create) a mechanism to toggle the dynamic anchor insertion script.
- [x] Measure the performance gain (specifically the "time to interactive" metric) when dynamic anchor insertion is disabled.
- [x] Adjust the model documentation pipeline to generate anchors statically.

### Dependencies

Created off of guidance in #1373.

### Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by nikitawootten-nist** [comment]
Update: I found the culprit that generates anchors. It is located here: https://github.com/usnistgov/OSCAL/blob/f87dcb1fdbc5352c761954298829ec96bb11c80c/docs/layouts/partials/foot.html#L11

It is supposed to be toggleable via a page parameter `generateanchors`, though the current implementation **does not work**.

Disabling anchor generation makes the page interactive almost instantly on page loads, and is a much better experience!

**Comment by aj-stein-nist** [comment]
I like where you are headed with this, let's schedule it for next sprint in the second half of the month.

**Comment by aj-stein-nist** [comment]
@JustKuzya has volunteered to drive this issue. @wendellpiez is also interested in working on this and supporting Dmitry and Nikita.

**Comment by aj-stein-nist** [comment]
@JustKuzya I started to review you branch. Do you have time to talk about your branch later today?

**Comment by aj-stein-nist** [comment]
3 PM?
________________________________

**Comment by aj-stein-nist** [comment]
@JustKuzya thanks for your time today. Glad we could find the relevant location and test.

https://github.com/usnistgov/metaschema/blob/70085548fec75de999eebb480a0be7d7b1abdada/toolchains/xslt-M4/document/xml/element-reference-html.xsl#L53-L118

I am still having trouble with some of my local edits I sent to you working, and why the ID is different slightly based on calling it in the same location, but let me know if you want more pairing time. You probably will advance at this point fast without me.

**Comment by aj-stein-nist** [comment]
@JustKuzya @nikitawootten-nist  I will presume this work is incomplete but significant progress was made on Friday, can we please get a status update? This is important, I intend to move it forward in the sprint.

**Comment by aj-stein-nist** [comment]
@JustKuzya, @nikitawootten-nist and I missed you yesterday. Let's set aside some today to wrap this up with usnistgov/metaschema#362 closed. Can you move up the submodule in the interim as requested on the PR and we close out with some before-and-after perf testing numbers?

**Comment by aj-stein-nist** [comment]
We have reviewed this issue and it was completed in a previous sprint and should be closed.
