### ISSUE TITLE
Profile resolution metadata resolution chooses a difficult to obtain value for metadata/last-modified

### ISSUE THREAD

**Issue by GaryGapinski** [usnistgov/OSCAL#1699]
### Describe the bug

The fourth bullet ["Metadata Resolution"](https://pages.nist.gov/OSCAL/concepts/processing/profile-resolution/#d2e1433-head) in ["OSCAL Profile Resolution Specification Draft"](https://pages.nist.gov/OSCAL/concepts/processing/profile-resolution/) asserts "The value of metadata:last-modified in the target MUST be set with a valid timestamp representing **the time the profile resolution completed**." [emphasis mine]. This requires extraordinary effort to achieve when using pure XSLT for profile resolution. Use of XPath `current-dateTime()` during a transformation will typically provide the time of transformation _initiation_.

### Who is the bug affecting

Implementors of OSCAL profile resolution.

### What is affected by this bug

Documentation

### How do we replicate this issue

A pure XSLT profile resolution implementation will likely use the XPath [`current-dateTime()`](https://www.w3.org/TR/xpath-functions-31/#func-current-dateTime) function to obtain the date+time+timezone at the time of profile resolution. This is often (but not always) the point in time at which the XSLT transformation **commenced**. The actual time of resolution _completion_ cannot be obtained without extraordinary effort.

### Expected behavior (i.e. solution)

If profile resolution is considered an atomic operation the actual time of completion could instead be the time of resolution initiation, a time during resolution, or the time of resolution completion, or an arbitrary time elected by the _rainha da resolução_. Some latitude in the precise choice of _asserted_ completion time would be gratefully received.

If for some reason the time of completion is important, a strict definition of _completion_ is lacking and elusive.

**Comment by galtm** [comment]
@GaryGapinski , I like your point about latitude in the precise choice. I think it makes sense in light of the part of the [`current-dateTime`](https://www.w3.org/TR/xpath-functions-31/#func-current-dateTime) function's spec that says, "This function is  deterministic. The precise instant during the query or transformation represented by the value of fn:current-dateTime() is implementation-dependent." I am not aware of a situation where the time of completion would be important by itself. If an end user were concerned about an imported catalog changing during the resolution process and not knowing whether the resolved profile reflects the latest catalog changes, such a user would need more timestamps than merely when the profile resolution process completed.

On the other hand, if the OSCAL community decides that the profile resolution spec draft shouldn't change this bullet after all, the XSLT profile resolver could get a fresher timestamp by executing a second transform (identity plus setting the timestamp) after the existing profile resolution pipeline ends. The second transform could be mentioned in the [manual instructions](https://github.com/usnistgov/OSCAL/tree/develop/src/utils/util/resolver-pipeline#using-saxon-manually-from-the-command-line) and added to the [wrapper script](https://github.com/usnistgov/OSCAL/blob/develop/src/utils/util/resolver-pipeline/oscal-profile-resolve.sh).

**Comment by aj-stein-nist** [comment]
The team is in favor loosening the wording of the specification, will consider this a potential issue for an upcoming sprint.

**Comment by wendellpiez** [comment]
I concur the language should be loosened. Like @GaryGapinski , I am used to a world in which everything-happens-all-at-once.

To meet the *nominal* requirement in XSLT one could always produce the timestamp in a post-process and say the resolution isn't actually accomplished until this is done (maybe the instance is not valid till then).

Yet I am also not sure how a test could determine that a timestamp had been "prematurely" applied (reflecting initiation rather than conclusion of a black-box process). I.e. to validate conformance to a strict reading of this line of the spec. So it may be an unenforceable rule.

**Comment by nikitawootten-nist** [comment]
Fixed via #1900

**Comment by aj-stein-nist** [comment]
We need to prioritize work to include processing specifications (now profile resolution only) for generating them like before, as the content site and reference site are no longer managed within the same repo. We need to get generated specs automatically deploying like reference material, even in OSCAL-Reference perhaps. :-)

We need to move on https://github.com/usnistgov/OSCAL-Reference/issues/16 in short order. Thanks for pointing this out during sprint review @nikitawootten-nist.
