### ISSUE TITLE
Create a testing framework to validate regressions

### ISSUE THREAD

**Issue by kscarfone** [usnistgov/OSCAL#17]
User story candidate: Create a testing framework to validate regressions.
Required resources:
- TBD
Goals:
1. TBD
Acceptance Criteria:
1. TBD

**Comment by anweiss** [comment]
@david-waltermire-nist can this be closed as it's being addressed by the metaschema work?

**Comment by david-waltermire-nist** [comment]
To be handled by #321. Closing.
