### ISSUE TITLE
OSCAL website - Events has a typo and 2 not working hyperlinks

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#1711]
### Describe the bug

Page: [OSCAL -> Events](https://github.com/usnistgov/OSCAL/tree/main/docs/content/events)/_index.md has a typo in the Calendar section (see: a**ppp**lication) . Also the 2 hyperlinks for the OSCAL DEFINE and OSCAL Model Engineering pages (bottom of the page) are wrong.

Need to either correct the links as follows or move the files in the `events` subdirectory.

https://pages.nist.gov/OSCAL/events/model-engineering-meeting/ should be https://pages.nist.gov/OSCAL/contribute/model-engineering-meeting/ 
https://pages.nist.gov/OSCAL/events/define-meeting/ should be https://pages.nist.gov/OSCAL/contribute/define-meeting/

### Who is the bug affecting

readers

### What is affected by this bug

Website

### How do we replicate this issue

Clink on the links described above

### Expected behavior (i.e. solution)

Need to either correct the links as follows or move the files in the `events` subdirectory.

https://pages.nist.gov/OSCAL/events/model-engineering-meeting/ should be https://pages.nist.gov/OSCAL/contribute/model-engineering-meeting/ 
https://pages.nist.gov/OSCAL/events/define-meeting/ should be https://pages.nist.gov/OSCAL/contribute/define-meeting/

**Comment by aj-stein-nist** [comment]
I will work on this to clear my head at the end of the day. It is likely blocked by #1698 for the actual publication to the site, but still a quick thing to fix.
