### ISSUE TITLE
Sprint 65 Discussion Questions Review

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1715]
### User Story

As a NIST OSCAL Team member, in order to make sure our communities members get timely, clear answers to recently asked questions, I want two or more team members to review the questions listed in the goals section.

For each question, a NIST OSCAL Team member should either select a pre-existing answer (from the community or a NIST OSCAL Team member colleague) as the correct answer, or draft an appropriate answer with consultation from the team.

### Goals

- [x] Select or draft an official answer to https://github.com/usnistgov/OSCAL/discussions/1705
- [x] Select or draft an official answer to https://github.com/usnistgov/OSCAL/discussions/1706

### Acceptance Criteria

- [x] A new or a preexisting answer has been marked as the official answer (instructions [from the GitHub Docs website](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/participating-in-a-discussion#marking-a-comment-as-an-answer))

**Comment by aj-stein-nist** [comment]
@aj-stein-nist will help with the second one, per request for assistance from @nikitawootten-nist. If others want to pitch in from the team, the more, the merrier.

**Comment by GaryGapinski** [comment]
Regarding #1706:

I'll caution that a repository might imply the access mechanism of a service. OSCAL does not prescribe that.

What might suffice is a sufficiently expository crafted instance document (or several).

[This comment](https://github.com/usnistgov/OSCAL/discussions/1706#discussioncomment-5350067) asks for something more; an exposition of a reusable component.
