### ISSUE TITLE
SPIKE: Site Organization and Page Layout

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1733]
### User Story

As an OSCAL community member, in order to find efficiently and effectively find information within the website, I want to know the current page content and the organization of the site's pages is the best possible, and if, it be improved.

### Goals

- [x] Review the website sections (About, Learn, Concepts, et cetera)
  - [x] Is their order on the header of the site pages effective? Should they be reorganized? Should some be added/removed?
          - Analysis was performed, and pages need reorganization. See below the issues created
  - [X] Is the page content for each page in the section aligned with its section?
          - Analysis was performed and content is not always aligned with the tab/section
- [x] Are the different page layouts [in the repo](https://github.com/usnistgov/OSCAL/tree/7d9a11c66da7de1f04148eb02c2c6c4499c2d750/docs/layouts) and the [`hugo-uswds` project to make USWDS easy to use with our `hugo` configuration](https://github.com/usnistgov/hugo-uswds/) sufficient? Is there room for improvement?
          - Analysis was performed and several new page layouts are suggested. A new SPIKE will further research the necessary changes.

### Dependencies

- N/A

### Acceptance Criteria
- [x] A written or verbal presentation to the NIST OSCAL Team with findings from the analysis to be presented before or during the sprint review
See https://miro.com/app/board/uXjVMSk8bvA=/ for a diagram and information flow of the current site.
- [x] One or more issues added to the backlog for any actionable findings from the report the team can integrate into website enhancements, either before or during the sprint review

### Created Issues 

-  #1764
-  #1765
-  #1769
-  #1775

**Comment by aj-stein-nist** [comment]
@Arminta-Jenkins-NIST also volunteered, I nominate her as driver. :-)

**Comment by iMichaela** [comment]
See https://miro.com/app/board/uXjVMSk8bvA=/ for a diagram and data flow.
