### ISSUE TITLE
SPIKE: Implementation-agnostic testing

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/OSCAL#1771]
### User Story

As developers supporting OSCAL tooling, I need the OSCAL descriptions and specification documents to be backed by machine-readable documents so that developers can test OSCAL tooling.

For now this issue should be scoped specifically to profile resolution to keep things lean.

### Goals

- [x] An ADR entry describing the testing format, built specifically to profile resolution
- [x] A set of example tests in the described format
- [x] A generic test runner that can, given a harness, test an implementation against the suite of tests
- [x] An implementation of the testing harness for the XML profile resolution pipeline

### Dependencies

This is follow up work from #1735 

### Acceptance Criteria

- ~All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.~ N/A
- ~A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.~ N/A
- ~The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.~ N/A

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

**Comment by aj-stein-nist** [comment]
This is a very ambitious set of goals for a spike for Sprint 75 with reduced team allocation. A.J. will break this spike into two parts. Those interested discussed this first part being in Sprint 75 as doable with the following goals in the first half.

- [ ] An ADR entry describing the testing format, built specifically to profile resolution
- [ ] A set of example tests in the described format

A.J. will edit after planning meeting.

**Comment by aj-stein-nist** [comment]
Provisionally moving to Sprint 77 for review, will discuss with @nikitawootten-nist if there is still bandwidth in this sprint to continue with this work.

**Comment by aj-stein-nist** [comment]
I discussed this during Sprint 78 planning, and I believe that more members of team should review this PR and consider the ADR before approving it and I (since I am the only one who reviewed and approved thus far after meeting with Nikita during his demo last week). I will move forward and put this at the top of the board, asking itl-oscal to review.
