### ISSUE TITLE
Include-controls property no longer available under imports on Profile schema

### ISSUE THREAD

**Issue by AleJo2995** [usnistgov/OSCAL#1782]
### Describe the bug

I´m working currently for `compliance-trestle` effort you can checkout [here](https://github.com/IBM/compliance-trestle). Right now I´m in the middle of updating models to what is being specified to newer model version for new release of OSCAL happening soon (control mapping stuff and so on). While updating models, I´ve found out that previously profile schema had include-controls property behind imports and our code currently works assuming it is still there. The current documentation still have that in place for include-controls under imports for a profile BUT the actual schema is not. So, I´d like to know if this a known issue for you at this point or if the removal was intentional and documentation is out of date. And if so, then please provide an explanation on how the schema is tending to handle this property from now on.

### Who is the bug affecting

`compliance-trestle ` current functioning code affecting profile classes

### What is affected by this bug

Metaschema

### How do we replicate this issue

1. Go to NIST´s Oscal reference documentation for develop branch. Here : https://pages.nist.gov/OSCAL/reference/develop/profile/json-reference/#/profile/imports/include-controls
2. Verify that current schema under develop has no include-controls property under imports here: https://github.com/usnistgov/OSCAL/blob/develop/json/schema/oscal_profile_schema.json#L35

### Expected behavior (i.e. solution)

Either include-controls need to be reestablished under imports for a profile or there´s a reason for why that was removed and if there´s anything else related for solving the issue somewhere else around in profile schema.

**Comment by AleJo2995** [comment]
@aj-stein-nist Hi! I just wanted to know if you had a chance to see this. I can explain further if you like. Thanks :)

**Comment by GaryGapinski** [comment]
I looked at this earlier today. The `main` branch looks OK; the `develop` branch does not.

**Comment by aj-stein-nist** [comment]
We should review the artifacts of the 1.1.0 release to validate this, but current `develop` appears to not have the discrepancy anymore. I will ask for other team members to review with/for me.

**Comment by iMichaela** [comment]
@aj-stein-nist - OSCAL 1.1.0 does not experience this bug. 

**Proof:** 
[JSON schema released with OSCAL 1.1.0 - see assets](https://github.com/usnistgov/OSCAL/releases/download/v1.1.0/oscal_profile_schema.json)  - lists in line 49 ```include-controls``` as a property of ```"oscal-profile-oscal-profile:import```

![Screenshot 2023-08-04 at 7 36 07 AM](https://github.com/usnistgov/OSCAL/assets/13984545/92d90fcf-4207-4820-a69b-6a182d1e76ce)

Online documentation is aligned:
![Screenshot 2023-08-04 at 7 20 35 AM](https://github.com/usnistgov/OSCAL/assets/13984545/59a51e79-9fdb-4d62-be86-0d224f09f5d6)

![Screenshot 2023-08-04 at 7 18 42 AM](https://github.com/usnistgov/OSCAL/assets/13984545/129db153-f9f5-4407-b553-6758d831916f)
