### ISSUE TITLE
Allow local definition of "asset-type" prop values

### ISSUE THREAD

**Issue by Rene2mt** [usnistgov/OSCAL#1797]
### User Story

As an OSCAL developer, I need to be able to locally define "asset-type" values (for components and/or inventory items) that currently are not defined in core OSCAL.

### Goals

Systems can be comprised of a variety of physical and/or virtual components (e.g., gateway devices, load balancers, object storage, cloud-based services, etc.) that cannot be categorized by the current defined list of asset types (see [documentation](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/xml-definitions/#/assembly/oscal-implementation-common/inventory-item:~:text=for%20the%20system.-,ALLOWED%20VALUES%20for%20prop%5B%40name%3D%27asset%2Dtype%27%5D/%40value,-The%20value%20must)). 

The goals of this issue are as follows:
- Allow ability to locally define values for "asset-type".  This should apply on 
  - [all components](https://pages.nist.gov/OSCAL/reference/latest/complete/xml-index/#/component)
  - [all inventory items](https://pages.nist.gov/OSCAL/reference/latest/complete/xml-index/#/inventory-item)
- Make the ```<prop name='asset-type' value='...'/>``` prop optional on components.  Certain components (e.g. "this-system", leveraged systems, documentation, etc.) may not require an "asset-type".

### Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

**Comment by aj-stein-nist** [comment]
OK @Arminta-Jenkins-NIST you should be set to start your PR, let me know if you have additional questions, comments, or concerns with what we reviewed. I am here to help!

**Comment by aj-stein-nist** [comment]
This was released as part of 1.1.0, closing.
