### ISSUE TITLE
Where is fedramp-profile.sch?

### ISSUE THREAD

**Issue by shawndwells** [usnistgov/OSCAL#180]
Most of the profiles have an xml-model reference to a fedramp-profile.sch:

https://github.com/usnistgov/OSCAL/blob/master/examples/FedRAMP/FedRAMP_HIGH-baseline_profile.xml#L1
`````
<?xml-model href='fedramp-profile.sch' type='application/xml' schematypens='http://purl.oclc.org/dsdl/schematron'?>
`````

The ``fedramp-profile.sch`` does not appear to exist in the repo:
`````
$ find ./ -name fedramp-profile.sch

`````

**Comment by david-waltermire-nist** [comment]
See #185. We are working to cleanup these dangling references. The are intended to be resolvable and will be either removed or fixed in the near future as is appropriate.

**Comment by shawndwells** [comment]
Thanks! Closing this then.
