### ISSUE TITLE
OSCAL image improvements for local developer environments

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/OSCAL#1814]
### User Story

As an OSCAL developer or community member, I need to be able to rely on the OSCAL docker image to perform OSCAL devops tasks (model documentation generation, schema generation, hugo builds, etc).

Currently the OSCAL image suffers from some usability issues:
- [ ] The build script does not produce targets for arm64 (rosetta translation seems to be very slow for XSLT operations)
- [ ] The image is currently too large and too slow to build
- [ ] GitHub actions relying on the pre-built docker image will not work for forks.

The speed and size of builds must be improved enough to avoid having to host prebuilt images, or infrastructure needs to be put in place to allow forks to build the image on the fly as needed.

### Goals

- [ ] Adjust the build script to build for multiple targets (arm64 is a must)
- [ ] Bring over some of the speed and size improvements from the [oscal workshop image](https://github.com/aj-stein-nist/oscal-2023-workshop)
- [ ] Improve the XSpec action to build the image as needed (for forks?)
- [ ] Investigate the creation of a second "XSLT environment" image that can be split out at a later date for the metaschema-xslt repo

### Dependencies

N/A

### Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

**Comment by aj-stein-nist** [comment]
@nikitawootten-nist notified we should paused this and consider defering it to next sprint given fast movement and impending #1802 changes that may obsolete this work, as briefed today during standup.

**Comment by aj-stein-nist** [comment]
We are moving this out of the sprint as blocked after stats counting and then mark it for re-review until as usnistgov/OSCAL#1847 is started and/or completed.

**Comment by aj-stein-nist** [comment]
I believe we opted to close this and migrate tooling to appropriate metaschema implementation repositories. @nikitawootten-nist, feel free to re-open and clarify if I am mistaken.
