### ISSUE TITLE
XSLT profile resolver excludes param props from resolved profile catalogs

### ISSUE THREAD

**Issue by Rene2mt** [usnistgov/OSCAL#1818]
### Describe the bug

When using the XSLT profile resolver (v1.0.4), the produced resolved profile catalogs does not include any of the ```param``` props that are defined in the imported source catalog (e.g., missing props:  **aggregates**, **alt-identifier**, **label**, and **alt-label**). 

### Who is the bug affecting

FedRAMP and anyone using [NIST's XSLT profile resolver v1.0.4](https://raw.githubusercontent.com/usnistgov/OSCAL/main/src/utils/util/resolver-pipeline/oscal-profile-RESOLVE.xsl)

### What is affected by this bug

CI/CD

### How do we replicate this issue

NOTE - the issue is when using [XSLT profile resolver (version 1.0.4)](https://raw.githubusercontent.com/usnistgov/OSCAL/develop/src/utils/util/resolver-pipeline/oscal-profile-RESOLVE.xsl)

1. Find a catalog that has ```param``` elements with props (e.g. [NIST 800-53rev5 Catalog](https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5_catalog.xml)).  Notice the props for AC-1 in the catalog
```
         <param id="ac-1_prm_1">
            <prop name="aggregates" ns="http://csrc.nist.gov/ns/rmf" value="ac-01_odp.01"/>
            <prop name="aggregates" ns="http://csrc.nist.gov/ns/rmf" value="ac-01_odp.02"/>
            <label>organization-defined personnel or roles</label>
         </param>
         <param id="ac-01_odp.01">
            <prop name="label" class="sp800-53a" value="AC-01_ODP[01]"/>
            <label>personnel or roles</label>
            <guideline>
               <p>personnel or roles to whom the access control policy is to be disseminated is/are defined;</p>
            </guideline>
         </param>
```
2. Create a profile that imports this catalog (e.g., [FedRAMP profile for moderate baseline](https://github.com/GSA/fedramp-automation/blob/master/dist/content/rev5/baselines/xml/FedRAMP_rev5_MODERATE-baseline_profile.xml))
4. Conduct profile resolution (e.g. could be via CI/CD or directly through a tool like Oxygen XML).  The resolved profile catalog is available [here](https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/rev5/baselines/xml/FedRAMP_rev5_MODERATE-baseline-resolved-profile_catalog.xml).  Notice AC-1 in the resulting profile is missing the props:
```
         <param id="ac-1_prm_1">
            <label>organization-defined personnel or roles</label>
         </param>
         <param id="ac-01_odp.01">
            <label>personnel or roles</label>
            <guideline>
               <p>personnel or roles to whom the access control policy is to be disseminated is/are defined;</p>
            </guideline>
         </param>
```

### Expected behavior (i.e. solution)

Using the [XSLT profile resolver (develop branch)](https://raw.githubusercontent.com/usnistgov/OSCAL/develop/src/utils/util/resolver-pipeline/oscal-profile-RESOLVE.xsl) seems to produce the expected output, where the resolved profile catalog ```param``` includes any child props from the imported source catalog:
```
         <param id="ac-1_prm_1">
            <label>organization-defined personnel or roles</label>
         </param>
         <param id="ac-01_odp.01">
            <label>personnel or roles</label>
            <guideline>
               <p>personnel or roles to whom the access control policy is to be disseminated is/are defined;</p>
            </guideline>
         </param>
```

**Comment by galtm** [comment]
@aj-stein-nist and @wendellpiez , following up on our conversation about this issue: I believe the following is the specific piece of code on the develop branch that preserves the param props.

- From https://github.com/usnistgov/OSCAL/pull/1321 (which includes "Handle more types of children of param"), see the definition and use of "all-props" on lines 63-71 in https://github.com/usnistgov/OSCAL/blob/develop/src/utils/util/resolver-pipeline/oscal-profile-resolve-modify.xsl
- A related XSpec test is the scenario labeled "Override prop with same uuid, and insert prop with distinct uuid" in the XSpec file in that same pull request, #1321.

**Comment by aj-stein-nist** [comment]
Thanks @galtm that saves me a good deal of time. 😅

**Comment by aj-stein-nist** [comment]
Apologies for the delay on not updating this issue. We are in the process of releasing 1.1.0 and the relevant profile resolver changes will be included in that release, and you will be able to use the enhance resolved on a tagged release branch.
