### ISSUE TITLE
Update src/metaschema readme

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#1830]
### Describe the bug

Readme page content in `src/metaschema` is largely out of date and (in any case), should be referencing the [Metaschema repo](https://pages.nist.gov/metaschema), not explaining Metaschema.

Pointed out by helpful community member @galtm.

### Who is the bug affecting

Users of OSCAL metaschema source needing current information.

### What is affected by this bug

Documentation, Metaschema

### How do we replicate this issue

The page be here: https://github.com/usnistgov/OSCAL/blob/main/src/metaschema/readme.md

### Expected behavior (i.e. solution)

Links and explanation oriented toward OSCAL, not Metaschema as such.

**Comment by galtm** [comment]
I made a few minor suggestions in #1831.

Besides that, I thought the part about `valid-values` might benefit from some work. Is that outdated markup? If `value` permits data content to use as documentation, can the example illustrate that? I'm sure you know better than I do what else might benefit from improvement.
