### ISSUE TITLE
Create a Capability to Maintain FedRAMP Profiles

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#184]
# User Story:

As as FedRAMP practitioner, I have the ability to manage changes and publish updates to FedRAMP OSCAL profiles.

## Goals:

1. Establish a change management plan/process for FedRAMP OSCAL files. This includes version control management of publications.

2. Establish tools to manage and publish FedRAMP OSCAL files, consistent with the plan/process defined in Goal 1.

## Dependencies:

None

## Acceptance Criteria

- [ ] Clearly documented plan and/or process.
- [ ] Basic tool(s) exist.
- [ ] Capability (plan, process and/or tool) ensures all published versions are tracked.

**Comment by david-waltermire-nist** [comment]
2018-06-07 Meeting Notes
@brianrufgsa and @PCrayton will advance this issue starting the week of 6/18.

**Comment by brianrufgsa** [comment]
I continue to develop a tool for managing catalog and profile content generally, with the idea that FedRAMP will adopt this tool to address this issue. 
The tool is in PHP and can be run on a stand-alone computer (individual use) or on a web server (shared use). 

It will be open-source and available to all. It will also continue to grow as handling of additional OSCAL layers gets added later. 
I will add a comment here, when this tool is available for public use.

**Comment by david-waltermire-nist** [comment]
@brianrufgsa This has been open for a while. Should this be closed? If so, can you add a link in a comment to the tool?

**Comment by brianrufgsa** [comment]
@david-waltermire-nist I never got this far on the OSCAL GUI. I'm fine with closing this issue here, and moving it to that repo.
