### ISSUE TITLE
Remove references to "biblio"

### ISSUE THREAD

**Issue by RS-Credentive** [usnistgov/OSCAL#1841]
https://github.com/usnistgov/OSCAL/blob/ff6a37495955cca4c6205ff243332468564e6f33/src/metaschema/oscal_metadata_metaschema.xml#L471C37-L471C37

In back-matter/resource/citation, there is a reference to a "biblio" type that no longer exists. This definition should be rewritten to eliminate this reference.

**Comment by aj-stein-nist** [comment]
Having reviewed this, I would recommend this one stay in this repo, since the change will be in the Metaschema module. That stayed here post migration.

**Comment by RS-Credentive** [comment]
Makes sense to me
