### ISSUE TITLE
Revise branching and forking in contributions and versioning markdown.

### ISSUE THREAD

**Issue by Compton-NIST** [usnistgov/OSCAL#1846]
This was identified as an item needing correction/revision with guidance on when someone should create a personal fork of OSCAL versus a feature branch directly in OSCAL.

The file ./versioning-and-branching.md in the https://github.com/usnistgov/OSCAL/tree/feature-1802-oscal-pages branch reads:
 
_All individual work will be done in branches **in a personal fork of this repository.** 
Personal branches should be named using the convention <issue #>-brief-dashed-name.
Once work is complete on a personal branch, the branch should be interactively rebased to tidy any commits. Then a PR should be opened against the target feature-*  branch or the develop branch if the changes are to be included in the next release._ 

During my chat with AJ today around #1798, he indicated that working on a personal fork is no longer mandated. Should this file be updated?

Similar guidance exists in the CONTRIBUTING.md file, the block starting at line 72.

_Originally posted by @iMichaela in https://github.com/usnistgov/OSCAL/issues/1824#issuecomment-1626376378_

**Comment by aj-stein-nist** [comment]
I had some weirdness where the commits addressing feedback were not pushed correctly as I merged with my itchy trigger finger, but I push it on top of develop as discussed. This work is done and ready for sprint review.
