### ISSUE TITLE
Cleanup FedRAMP Profile Content

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#185]
# User Story:

The published FedRAMP profiles have minor issues and obsolete metadata that must be cleaned up. This will involve a combination of updates to the data in the tool, as well as the scripts in the tool that convert the data to an OSCAL-compliant profile.

## Goals:
The following will be addressed by @brianrufgsa and @PCrayton:
1. Fix HREF references
2. Remove the two processing directive lines at the top of each FR profile
3. Remove comments about the tool that created the file.
4. Ensure parameters appear in an appropriate sequence
5. Fix/remove inconsistent control references in the data.

## Dependencies:

None

## Acceptance Criteria

- [ ] HREF references resolved (includes accurate relative references to SP800-53 profiles and catalog).
- [ ] The two processing directive lines no longer exist in the FR profiles.
- [ ] The comments about the tool that created the file are no longer present in the FR profile.
- [ ] All parameters consistent appear in the correct sequence in all FR profiles.
- [ ] All data content inconsistencies/anomalies resolved.

**Comment by anweiss** [comment]
I'll also add that the examples need to be updated to reflect the latest `param_setting` model defined at https://github.com/usnistgov/OSCAL/blob/master/schema/xml/RNC/oscal-profile.rnc#L57. The model now allows for a more extensive set of elements.

**Comment by david-waltermire-nist** [comment]
#190 will need to address the comment from @anweiss above. @wendellpiez will also need to check that the RNC and metaschema are consistent with this.

**Comment by brianrufgsa** [comment]
Status: Complete
Peter and Brian have modified the Tool and internal data for generating FedRAMP baseline profiles. The profiles are now resolved with respect to the issues listed here.

** JUST NEED TO RE-PUBLISH / MERGE

**Comment by david-waltermire-nist** [comment]
# 6/21/2018 Status
This is ready to be pushed once PR #201 is accepted.

**Comment by iMichaela** [comment]
## June 28 Status Meeting Update ##
This issue is done as much as possible at this time. Some publication characteristics need to be settled.

**Comment by iMichaela** [comment]
## July 18 Status Update (Sprint 12 Acceptance Meeting) ##
PR #201 is awaiting review from @david-waltermire-nist and/or @iMichaela

**Comment by david-waltermire-nist** [comment]
@PCrayton and @brianrufgsa will review this issue to verify that the work has been completed. Once verified, we will move this to under review.

**Comment by iMichaela** [comment]
## Status Meeting: 8/23/2018 ##
This user story was addressed in the PR submitted by @brianrufgsa on August 6.
