### ISSUE TITLE
Complete Metaschema Implementation

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#186]
# User Story:

As an OSCAL stakeholder, I can validate that OSCAL metaschema components work correctly by consulting unit tests.

## Goals:

OSCAL metaschema functionality has (at least) three discrete areas:

* Produce and publish functioning and correct XSD and JSON schemas for OSCAL from metaschema source. (@wendellpiez)
* Support bidirectional conversion between XML and JSON via metaschema configuration. Inasmuch as metaschema contains all the info needed for a complete XML-JSON element-to-object mapping, a conversion tool can be dynamically generated or configured and doesn't have to be hard wired. (@wendellpiez)
* Document a user story for supporting bidirectional conversion of text markup (e.g., bold, italics, lists) as follow-on work. (@david-waltermire-nist)

The first two of these would benefit from unit testing to ensure requirements are met and functionality is stable under maintenance. We now have unit testing in place for the XSD production (first half of item 1).

## Non-Goals

* Support for bidirectional conversion of text markup (e.g., bold, italics, lists) will not be addressed in this issue for XML or JSON.

## Dependencies:

- #194 is about designing an approach for parameter insertion in JSON Markdown OSCAL content. Documenting this design is a precursor for this issue. 
- Build out the functionality to the point where testing makes sense. (At time of writing this is in progress.)

## Acceptance Criteria:

- Schema generation for Catalog and Profile XML and JSON schemas can be scripted, and up-to-date schemas are published.
- Conversion of XML to JSON, and JSON to XML can be demonstrated, also using a scripted approach.
- Unit tests are in place (1) for production of XSD and JSON Schema from metaschema source and (2) for bidirectional conversion of OSCAL-conformant XML or JSON into its "counterpart" format.

Note: the unit tests do not all have to pass for acceptance of this user story.

**Comment by wendellpiez** [comment]
**Sprint 11 Progress Report June 7 2018**

Progress on goals

1. Produce XSD and JSON schemas reflecting metaschema models - 100%
1. Develop support for bidirectional XML-JSON conversion on basis of metaschema mapping - 5%

**Comment by david-waltermire-nist** [comment]
# 2018-08-07 Meeting Notes
@wendellpiez will create a new feature branch and PR to post the update schema files ASAP.

**Comment by wendellpiez** [comment]
The `feature-metaschema` branch was so close, that I opted to clean it up and post the PR from there.

**Comment by david-waltermire-nist** [comment]
# 6/21/2018 Status

- The README in #201 build/metaschema needs to be updated on how to use the stylesheets for this.
- We also need to document the features of the metaschema.

**Comment by wendellpiez** [comment]
**Sprint 11 Progress Report, June 28 2018**

The readme.md file looks better than it did. Also, there is a new markdown file with an initial cut at some metaschema documentation.

https://github.com/wendellpiez/OSCAL/blob/feature-metaschema/build/metaschema/readme.md
https://github.com/wendellpiez/OSCAL/blob/feature-metaschema/schema/metaschema/design-notes.md

Both are included in PR #201. However, there is (plenty) more work to do on documentation, perhaps with a new User Story (since docs are not actually mentioned as acceptance criteria on this one).

Percent complete: ? - depending on how you read the Issue :smile:

**Comment by iMichaela** [comment]
July 18 Status Update (Sprint 12 Acceptance Meeting)
The issue is waiting for a review from @david-waltermire-nist and/or @iMichaela
