### ISSUE TITLE
Broken links to Commodity Tooling

### ISSUE THREAD

**Issue by joshualubell** [usnistgov/OSCAL#1873]
### Describe the bug

"Commodity Tooling - Basic Operations" links on the [OSCAL Tools](https://pages.nist.gov/OSCAL/tools/) page are broken. 

### Who is the bug affecting

Readers of the [OSCAL NIST Pages site](https://pages.nist.gov/OSCAL/).

### What is affected by this bug

Documentation

### How do we replicate this issue

Clicking on any of the links results in a 404 error.

### Expected behavior (i.e. solution)

These links need updating to point to assets in the current OSCAL release, in accordance with Discussion [#1852](https://github.com/usnistgov/OSCAL/discussions/1852).

**Comment by nikitawootten-nist** [comment]
Hi, thank you for the bug report! This issue will be fixed by https://github.com/usnistgov/OSCAL-Pages/pull/28

**Comment by aj-stein-nist** [comment]
The work above has been completed, so I will close this issue as fixed.
