### ISSUE TITLE
Broken links in README_validation.md and README.md

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#1877]
### Describe the bug

The following broken links in the [README_validation.md](https://github.com/usnistgov/OSCAL/blob/main/README_validations.md) need to be updated. Content of the file might need update to indicate schemas are part of the assets of a release, and point to the latest release.

https://github.com/usnistgov/OSCAL/tree/main/xml/schema
https://github.com/usnistgov/OSCAL/tree/main/json/schema
https://github.com/usnistgov/OSCAL/blob/main/docs/content/downloads/_index.md#oscal-releases

The following broken link in the [README.md](https://github.com/usnistgov/OSCAL/blob/main/README.md) need to be updated:

https://github.com/usnistgov/OSCAL/actions/workflows/status-ci-cd.yml/badge.svg

### Who is the bug affecting

All OSCAL users 

### What is affected by this bug

Documentation, Website

### How do we replicate this issue

Click on the links provided above

### Expected behavior (i.e. solution)

README_validation.md: Content of the file might need update to indicate schemas are part of the assets of a release, and point to the latest release.

**Comment by aj-stein-nist** [comment]
This was handled as part of https://github.com/usnistgov/OSCAL-Pages/pull/28 and it's related issue, closing as duplicate.
