### ISSUE TITLE
Schema links for validation are broken.

### ISSUE THREAD

**Issue by Compton-NIST** [usnistgov/OSCAL#1883]
### Describe the bug

I noticed that the references to the schematron files and metaschema.xsd pointed to the old metaschema submodule instead of the new metaschema-xslt.  This resulted in validations passing when there were possible issues in metaschema documents.

### Who is the bug affecting

All developers, and ultimately the schemas and converters in OSCAL.

### What is affected by this bug

Modeling, Tooling & API

### How do we replicate this issue

See the following references for an example:
 - https://github.com/usnistgov/OSCAL/blob/ef4df067c280e718e107c646f7567c053c2abfc8/src/metaschema/oscal_component_metaschema.xml#L2
- https://github.com/usnistgov/OSCAL/blob/ef4df067c280e718e107c646f7567c053c2abfc8/src/metaschema/oscal_component_metaschema.xml#L15

### Expected behavior (i.e. solution)

Validations should fail when problems are encountered in documents.

### Other comments

I already have a PR ready to push.  Will push shortly for review.

**Comment by nikitawootten-nist** [comment]
I'm not sure https://github.com/usnistgov/OSCAL/pull/1872 fixes this (but will likely not be merged soon), should I break out 0c7d1eb526e8e185f47e333c05a6cabb842d1da7 into its own PR?

**Comment by Compton-NIST** [comment]
@nikitawootten-nist the PR I just pushed covers the broken `xml-model` references too.

**Comment by Compton-NIST** [comment]
Also for awareness, in CI, if there are errors in metaschema, then validation might still pass in some cases.  May need to prioritize this.

**Comment by aj-stein-nist** [comment]
Quickly discussed this in issue review today and we need to make sure we prioritize this correctly especially if we are not making a release in the near future.
