### ISSUE TITLE
Design example system for new tutorials

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL#1892]
### User Story

As a developer or system engineer writing software using OSCAL for security automation, I would like a simple, example system used throughout tutorials to represent different features and use cases of OSCAL.

In this issue, we will design an architecture of simple web application as the example system that hosts static pages, with an example hosting service, with no dynamic server backend or database for persistence. It will only host a website.

(**NOTE:** This issue is part of a value stream for tutorial improvements.)

### Goals

# Goals

1. Let's model systems and relate to controls.
2. Let's focus on use cases for a simplified lifecycle.
3. We will commit to 1 and 2, but not dogmatically. (We will make tutorials for specific data, tools, methodologies as the need comes up, but that comes up later as advanced material.)
4. Design the tutorials and simplified lifecycle around OSCAL models' features.

# Non-goals

1. Building a complex, real-world example system.
2. Designing tutorials around an actual control framework or technical stack (see Goal 3).
3. Building contextual examples into our reference model docs (great idea, separate of this).

(**NOTE:** This issue is part of a value stream for tutorial improvements, these goals and non-goals apply to the value stream overall, not just this issue. It has been copy-pasted for convenience.)

### Acceptance Criteria

- [ ] A design document in HackMD with minimally viable details for the system.
- [ ] Socialization with the NIST OSCAL Team.
- [ ] Presentation of this design in a sprint review for the sprint in which this work is allocated.

(For reviewers: [The wiki has guidance](https://github.com/usnistgov/OSCAL/wiki/Issue-Review) on code review and overall issue review for completeness.)

**Comment by Compton-NIST** [comment]
I'm going to self-assign this as a contributor, but not necessarily the lead.  I need to do quite a bit of example work for the mapping and responsibility modeling efforts, and I can probably check some of these items off along the way.  I can outline a couple of systems based on my past experiences.

**Comment by Compton-NIST** [comment]
I'll take lead and close this out based on the discusssion with @iMichaela and @nikitawootten-nist last week.

**Comment by aj-stein-nist** [comment]
Work on this issue is ongoing but incomplete. It will be needed to move onto the next sprint.

**Comment by Compton-NIST** [comment]
I put this in a repo so we could look at it and potentially adjust.  Would also need to find a permanent home somewhere in our repositories.  For input: https://github.com/Compton-NIST/oscal-systems/blob/main/simple/README.md

**Comment by wendellpiez** [comment]
Looking nice so far.

Is it on the list to clarify what is not in the system? For example, in the plainest-vanilla system, no consideration is given to how the HTML to be served is created, validated or defended against (since not all HTML is equally safe) -- the risks here are simply passed upstream, presumably to the content creator/uploader.

I guess asking this shows that even the simplest system description can provoke useful questions ... so far, so good.

**Comment by iMichaela** [comment]
@Compton-NIST - the system is simple enough to be understood. Have you decided on the 3-5 controls we should use or the controls will be decided later.

**Comment by Compton-NIST** [comment]
Will move this under oscal-content in a feature branch.

**Comment by Compton-NIST** [comment]
Published to: https://github.com/usnistgov/oscal-content/tree/feature-simple-network/systems/simple

This is a feature branch that we can merge once we achieve consensus.
