### ISSUE TITLE
Unit tests for Schematrons

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#19]
So far we have been validating Schematron functionality as we go.

Thorough regression testing requires that we can demonstrate not only that valid documents pass appropriate Schematron checks, but also that erroneous cases fail Schematrons "correctly" (no-go tests), while valid edge cases pass them (go tests).

We could do this less formally (less overhead) with simple examples (real and pathological) or more formally (more effort but easier to run) with XSpec-for-Schematron -- which would also permit us to enumerate and document the requirements they address and even push them out into Markdown for the Github repo. See https://github.com/xspec/xspec.

**Comment by anweiss** [comment]
@david-waltermire-nist this can probably be closed in favor of #186

**Comment by anweiss** [comment]
@david-waltermire-nist @wendellpiez suggest closing this in favor of newer related tracking issues.

**Comment by wendellpiez** [comment]
@anweiss and @david-waltermire-nist -- I agree. Since this Issue was created we have learned that without a robust infrastructure, testing must always be haphazard. We are now building the infrastructure.

**Comment by david-waltermire-nist** [comment]
Agreed. Closing.
