### ISSUE TITLE
Add OSCAL topic to this repo

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [usnistgov/OSCAL#1930]
### Describe the bug

The OSCAL repo doesn't have the OSCAL topic listed in the repo. This makes it harder to find and navigate to and to get to other repos that share similiar topics. 

### Who is the bug affecting

Anybody wanting to find the repos based on using topics to find it. 

### What is affected by this bug

OSCAL Content

### How do we replicate this issue

Go to GitHub and the OSCAL repo and realize that OSCAL isn't a topic or go to the link and realize that this NIST repo doesn't show up https://github.com/topics/oscal

### Expected behavior (i.e. solution)

When I am on the OSCAL topic in GitHub I would see this repo

**Comment by aj-stein-nist** [comment]
Hi @its-a-lisa-at-work, I don't disagree it is important to consider but I am not sure we should consider this a bug in the core OSCAL artifacts from this repo. That said, I assume the team will be 100% supportive that adding this topic to the repo (and others) in their configuration is a problem given how it hinders developers. Adding is a value-add. I should run such decisions by the team and not decide unilaterally. This is a fast one and doesn't need to wait until weekly issue triage I think.

Thanks for the request!

**Comment by aj-stein-nist** [comment]
I talked to the team and those on the call supported it. I will be adding the label [to core projects and other NIST-maintained OSCAL tools](https://pages.nist.gov/OSCAL/about/projects/). I will close this out accordingly once done. It was just added to this repo you posted in.

**Comment by aj-stein-nist** [comment]
OK so I quickly checked this is another meeting and added the label accordingly. Once all are added in the checklist below I shall close this.

- [ ] usnistgov/OSCAL
- [ ] usnistgov/oscal-content
- [x] usnistgov/OSCAL-Pages (previously added)
- [x] usnistgov/OSCAL-Reference (previously added)
- [ ] usnistgov/oscal-cli
- [ ] usnistgov/liboscal-java
- [x] usnistgov/oscal-deep-diff (previously added)
- [ ] usnistgov/oscal-xslt

**Comment by aj-stein-nist** [comment]
And, we're done. Below is the filtered list for the usnistgov org.

https://github.com/search?q=topic%3Aoscal+org%3Ausnistgov+fork%3Atrue&type=repositories
