### ISSUE TITLE
Update JSON examples to sync with the latest XML examples

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#197]
# User Story:

As an OSCAL maintainer, I've updated the JSON examples to be in sync with the latest XML examples in `master`.

## Goals:

Update the JSON examples based on the latest XML examples in `master` in `examples/SP800-53` and `examples/FedRAMP`.

## Dependencies:

Dependent on #185 and #143. Also requires updates to [`oscalkit`](https://github.com/opencontrol/oscalkit) which are being tracked at https://github.com/opencontrol/oscalkit/issues/1.

## Acceptance Criteria

All JSON examples are updated against the latest XML content.

To note, #125 and its supporting issues will provide an automated solution to keeping the data models in sync automatically.

**Comment by anweiss** [comment]
**June 21 Status:** PR #195 includes updated examples for 800-53 catalog and profiles. Waiting on #144 before pushing updated FedRAMP profile examples.

**Comment by iMichaela** [comment]
## June 28 Meeting Status Update ##
The issue moved to review. 
A user story might be needed to verify the different JSON tools align

**Comment by anweiss** [comment]
**August 9 Status:** This is still being worked on. Tweaks to the external `oscalkit` tool are being made to account for changes to the schemas merged in #201. At the moment, `oscalkit` creates JSON examples by ingesting the original XML examples. Unlike some of the utility XSLT that's been developmed, `oscalkit` doesn't yet have the capability to take raw data and produce XML or JSON examples.

**Comment by iMichaela** [comment]
## Status Meeting: 8/23/2018 ##
@anweiss will submit a PR

**Comment by anweiss** [comment]
This can be closed once #233 is merged.

**Comment by david-waltermire-nist** [comment]
#342 will address this.
