### ISSUE TITLE
Refine and Clarify Terminology

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#198]
# User Story:

As a new OSCAL user, I can clearly understand what is intended by the terminology used int he OSCAL overview diagram without explanation from the OSCAL Team. The intention of words such as "Profile" is clear to me.

## Goals:

1. Revisit the terminology in the overview diagram and adjust if necessary for broadest foreseeable applicability. (Based on what we know now, are these still reasonable terms?)
1. Revisit the documented definition of each term to ensure new OSCAL users clearly understand the intention of each term used in the OSCAL overview diagram.

## Dependencies:

None

## Acceptance Criteria

- [ ] The terms used in the OSCAL Model are reasonable based on what we know now about the diversity of semantics across compliance regimes. 
- [ ] The definitions for each term is clear, such that a new OSCAL users, with reasonable cyber security background, can clearly understand what is intended by each term.

**Comment by david-waltermire-nist** [comment]
We should review the latest site contents to make sure this is addressed.

**Comment by wendellpiez** [comment]
@brianrufgsa feel free to comment. While there is much to be done I think this is closable in view of PR #326.

**Comment by david-waltermire-nist** [comment]
This should be closed based on the work in PR #326 and #341. If more website enhancements are needed, additional specific issues should be opened.
