### ISSUE TITLE
Develop Requirements for the Implementation Layer (focus: System Security Planning)

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#199]
# User Story:

As an author of OSCAL implementation layer content , I need a format that is sufficient to capture the data in a System Security Plan (SSP).

## Goals:

Identify goals and requirements for the implementation layer.

## Dependencies:

None.

## Acceptance Criteria

A path forward for development of the OSCAL implementation layer is identified, with a clear description of what work needs to occur.

#### Profile Layer

1. Are control marked as to their implementation requirement (e.g., MAY=optional, SHOULD=recommended, MUST=required)?
1. Are all critical controls (as defined and/or selected by the authorizing official) marked accordingly?
1. Is the profile valid according to the data requirements of the baseline?
1. Are changes to a referenced catalog/profile detectable (e.g., hash)? Can a specific version be referenced (e.g., specific resource)?
1. How do I verify the integrity and the originator of the profile? How do I protect the confidentiality of the profile?
1. How do I identify the author and other document metadata related to the profile?
1. If a baseline applies to a specific administrative domain, how do I identify that domain?

#### Implementation Layer

1. Is a control identified in a baseline profile implemented? Is this implementation consistent with the baseline (see MAY and SHOULD above)?
1. Have all required controls (see MUST above) been implemented for a given implementation or by a referenced implementation? Are these controls consistent with the referenced baseline profile?
1. Is there a description of the mechanism used to implement the control (e.g., configuration, the policy) in the target system? Is the description sufficient to apply the implementation to the system (e.g., take the action(s) need to configure)? How will the mechanism be verified? Can the mechanism be verified automatically?
1. Is the implementation data partitioned in a way to support granular access controls over specific aspects of the data?
1. How do I verify the integrity and the originator of the implementation?  How do I protect the confidentiality of the implementation?
1. How do I identify the author, source, and other document metadata related to the implementation?
1. How do I identify the specific administrative domain for the implementation?
1. How do I define the system boundary of a given implementation? How I detect a change in the system boundary?
1. Can a level of confidence (e.g., Readiness Assessment Report) be determined when reviewing a given implementation?
1. How do I identify sub-scopes of a given system?

#### General Needs

1. Add support for signing Catalog, Profile, and Implementation layer content using XMLDsig for XML and JSON Web Signatures (JWS) (RFC7515) for JSON.
1. Add support for digests in resource references to Catalogs, Profiles, etc to allow change detection in referenced content.
1. Identify a mechanism for content encryption - JSON Web Encryption (JWE) (RFC 7516) and XML Encryption
1. Add support for content metadata in Catalog, Profile, and Implementation layer content (i.e. version, publication/creation date, authors, etc.)

#### Adjustments to the Profile Layer

1. Add requirement markings to the FedRAMP content to support FedRAMP critical controls (e.g., MAY=optional, SHOULD=recommended, MUST=required). Identify a standardized property name for this purpose.
1. Add support for profile declarations that are additive over the Catalog model declarations to cover additional content requirements.
1. Document profile resolution sufficiently to support independent implementation.
1. If a baseline applies to a specific administrative domain, determine how to identify that domain.

#### Features for the Implementation Layer

1. Identify components of a system.
1. Associate controls via a reference to a baseline for each component. The specific controls and control statements implemented by the component are identified.
1. Support analysis of controls documented by a system implementation and by any referenced (inherited) implementation.
   - Identify gaps between the implemented controls and any referenced OSCAL baseline Profiles.
   - Support use of control requirements in OSCAL baseline Profiles, if present, to identify any required controls which are not addressed.
   - Determine if use of the controls is consistent(?) with the referenced baseline Profile.
1. Support machine readable descriptions of mechanism used to implement a control (e.g., configuration, the policy) for a given component. Where possible, ensure each description is sufficient to apply the implementation to the system (e.g., take the action(s) need to configure)?
1. Consider ways to partition the formats to support multiple stakeholders providing and accessing the data (e.g., product/service vendor, system owners, assessors, etc.). This will also support tool-based access control over the information.
1. Determine how to identify the specific administrative domain for the implementation.
1. Determine how to define the system boundary of a given implementation?
   - Demonstrate how to detect a change in the system boundary.
1. Determine how a level of confidence (e.g., Readiness Assessment Report) can be automatically determined when reviewing a given implementation.

#### Features for the Assessment Layer

1. Support machine readable descriptions of mechanism used to assess a control (e.g., configuration, the policy) for a given component. Where possible, ensure each description is sufficient to verify the implementation automatically.

### Implementation Approach

1. What are the key features of an SSP that we need to support?
1. Who can provide the information associated with these features?

### Test Case

- Demonstrate support for automated review of a Readiness Assessment Report.

**Comment by JJediny** [comment]
For discussion only:
the `Component` modularity could adopt the concepts from OASIS TOSCA topology and relationship types:
http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.2/TOSCA-Simple-Profile-YAML-v1.2.html

**Comment by david-waltermire-nist** [comment]
We should validate that all the questions in this issue are addressed by the implementation layer before closing this.

**Comment by david-waltermire-nist** [comment]
This issue is overcome given recent work on SSP and component models.
