### ISSUE TITLE
The example files contain many typos

### ISSUE THREAD

**Issue by bzarboni1** [usnistgov/OSCAL#2032]
### Describe the bug

While browsing the example files, it was noted that there are many typos and spelling errors. For example:

- `examples\ap\*\ifa_assessment-plan-example.[json|xml|yaml]`:
```diff
-                 <title>Obtain Applcation Access Provided by Product Team</title>
+                <title>Obtain Application Access Provided by Product Team</title>
```

- `examples\ap\*\ifa_assessment-results-example.[json|xml|yaml]`:
```diff
-                <p>If such an insider threat existed and acted with this misconfigruatio, the
+                <p>If such an insider threat existed and acted with this misconfiguration, the
```

- `examples\ap\*\ifa_assessment-results-example.[json|xml|yaml]`:
```diff
-                title: 'IFA-GOODREAD-RISK1-RESPONSE: IFA GoodRead Prouct Team Response'
+               title: 'IFA-GOODREAD-RISK1-RESPONSE: IFA GoodRead Product Team Response'
```

### Who is the bug affecting

Users reading the documentation

### What is affected by this bug

Documentation

### How do we replicate this issue

See the repository files

### Expected behavior (i.e. solution)

Updated text with spelling corrected

**Comment by iMichaela** [comment]
@bzarboni1  - Ben, thank you for reporting the typos. We are excited that someone finally read the example :). I will move the issue to the proper repository (oscal-content) and close it here. I saw the [PR 2032](https://github.com/usnistgov/oscal-content/pull/274/files) you submitted in the `oscal-content` repo.
