### ISSUE TITLE
Erroneous warnings raised for not providing a start or end for components>protocols>port-ranges

### ISSUE THREAD

**Issue by Telos-sa** [usnistgov/OSCAL#2045]
### Describe the bug

When validating an SSP with the oscal-cli, a warning is raised saying that a start port exists but an end doesn't and vice versa, when both start and end are present in the OSCAL being validated.

Warning:
<img width="624" alt="Screenshot 2024-09-16 at 10 28 12 AM" src="https://github.com/user-attachments/assets/5f887290-61be-4329-8368-d30208e301f7">

OSCAL SSP section being flagged:
<img width="238" alt="Screenshot 2024-09-16 at 10 28 53 AM" src="https://github.com/user-attachments/assets/c5c97aa1-fed9-497b-9bbf-c4b32e157c11">

### Who is the bug affecting

Any user looking to validate their OSCAL SSP with port-ranges provided.

### What is affected by this bug

OSCAL Content

### How do we replicate this issue

1. Create an OSCAL SSP with a component>protocol>port-ranges element (with start and end provided).
2. Validate the OSCAL SSP with the oscal-cli

### Expected behavior (i.e. solution)

No warning should be raised (clutters the error log) when there is no actual issue with the port-ranges structure.

**Comment by iMichaela** [comment]
This is fixed by the commit  751e2d7b581d11930e69109629966538ebc73472 in develop branch and will be released with all other fixies in develop as soon as we address the camelCase data type issue which was removed but it is being requested back by GSA.
