### ISSUE TITLE
FedRAMP Profile Content Enhancements

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#208]
# User Story:

As an OSCAL publisher, I would like to differentiate a "guideline" from an added "requirement" using different part @class references, so that users of the OSCAL file can more clearly understand what they must do vs what they are encouraged to do.

I would like to do this for the whole control, a part of a control (ie. a. 1.), and/or an individual parameter.

## Goals:

1. Establish a "requirement" @class 
1. Re-work the data to separate guidance statements from requirement statements at the control, control-part, and parameter levels.
1. Re-publish the FedRAMP baseline profiles with this differentiation.

## Dependencies:

None.

## Acceptance Criteria

- [ ] <part class="requirement"> is valid syntax
- [ ] data is re-worked to separate guidance statements from requirement statements.
- [ ] FedRAMP profiles reflect these changes.

**Comment by trevor-vaughan** [comment]
@brianrufgsa Would it be feasible to map these to [RFC-2119](https://www.ietf.org/rfc/rfc2119.txt) for automated ontology processing in the future?

**Comment by brianrufgsa** [comment]
@trevor-vaughan - that's an interesting idea. I typically align with this terminology in prose for policy and process documentation. The OSCAL classes I suggested here are consistent with classes used in several other areas of OSCAL. Adopting it would mean re-working other OSCAL areas as well. That said, I can certainly raise your suggestion with the larger team, to see if there is interest.

**Comment by trevor-vaughan** [comment]
@brianrufgsa My biggest concern is that the project would be creating another set of terms that don't match what has been used and expected in industry per the referenced RFC. If there's another NIST document that defines a different set of terms, then that makes sense but, to me, having a new set of terms does not make sense.

**Comment by david-waltermire-nist** [comment]
@brianrufgsa Has this been addressed to your satisfaction? Please comment and transfer back to me.

**Comment by david-waltermire-nist** [comment]
@brianrufgsa You can use part and prop in alter statements to accomplish this.

**Comment by brianrufgsa** [comment]
@david-waltermire-nist, @wendellpiez - we have discussed this and I am satisfied, this can be accomplished with existing OSCAL structure and capabilities as described above. Closing this issue.
