### ISSUE TITLE
OSCAL Documentation Guidelines

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#211]
# User Story:

As an OSCAL developer, I have clear guidelines around how I should produce and publish documentation to describe my contribution.

## Goals:

- Ensure clear, consise guidance exists for OSCAL developers on how code should be documented (@david-waltermire-nist)

## Dependencies:

None

## Acceptance Criteria

1. Documentation guidelines have been reviewed by the OSCAL Team
1. Documentation guidelines have been published to the OSCAL GitHub repository

**Comment by iMichaela** [comment]
## 6/28/2018 Status ##
Reviewed the user story to reflect the scenario discussed during the meeting.

**Comment by david-waltermire-nist** [comment]
This issue is no longer needed. We have an existing pattern for documentation, which is being continuously improved.
