### ISSUE TITLE
Update OSCAL Catalog and Profile schema documentation

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#212]
# User Story:

As an OSCAL content consumer, I have clear, concise and descriptive documentation describing the Catalog and Profile layers of OSCAL.

## Goals:

1. Develop clear, concise and descriptive documentation describing the OSCAL Catalog with input from the OSCAL Team (@PCrayton with review from @david-waltermire-nist @wendellpiez )
1. Develop clear, concise and descriptive documentation describing the OSCAL Profile with input from the OSCAL Team (@PCrayton with review from @david-waltermire-nist @wendellpiez )
1. Develop XML (e.g., element, attribute) and JSON (e.g, arrays, maps, objects, names/labels, members/values) specific terminology (@david-waltermire-nist @wendellpiez)
1. Technical Edit OSCAL Catalog and Profile documentation (@bbattaglini)
1. Develop more comprehensive descriptions of the OSCAL model and each data structure, the semantics, content requirements and valid values (@bbattaglini)
 
## Dependencies:

None

## Acceptance Criteria

1. OSCAL Catalog and Profile documentation exists, has been technically edited and reviewed by the OSCAL Team
1. OSCAL Catalog and Profile documentation has been published in the OSCAL GitHub repository

**Comment by kscarf1** [comment]
June 27, 2018 status: Standing by to help when needed.

**Comment by iMichaela** [comment]
# 6/28/2018 Status #
Reviewed the user story to reflect the scenario discussed during the meeting.

**Comment by iMichaela** [comment]
## July 18 Status Update (Sprint 12 Acceptance Meeting) ##
The issue was not assigned to any member of the team in Sprint 12 and we will push the issue to Sprint 13

**Comment by PCrayton** [comment]
8/9/18 Status
1. Created a rough draft of the catalog documentation. 40% Complete
2. Created outline of the profile documentation. 20% Complete
Issues: None at this time.

**Comment by PCrayton** [comment]
8/23/18 Status
Worked today with @wendellpiez on the documentation of catalog elements. Will incorporate Wendell's input into the catalog draft and forward it to @david-waltermire-nist for his review
Issues: None at this time.

**Comment by PCrayton** [comment]
8/30/18 Status
Working on incorporating input from @wendellpiez and properly documenting the usage of parameters as per Issue #190 
Issues: None at this time

**Comment by PCrayton** [comment]
# 9/6/18 Status
Shared documentation efforts with @david-waltermire-nist and received his input. Will incorporate it and work with @wendellpiez to set up a proper Github pipeline for production.

**Comment by PCrayton** [comment]
# 9/13/18 Status
Worked with @wendellpiez to set up a Github pipeline for production of documentation. Working on incorporating input from @david-waltermire-nist and @wendellpiez on the catalog and profile schemas.

**Comment by iMichaela** [comment]
##9/26/2018##
@PCrayton received feedback from @wendellpiez and need just a little more time (low effort) in Sprint 14.

**Comment by iMichaela** [comment]
## 10/4/2018 ##
This issue is related to #190 . @PCrayton Peter can wrap it by the end of next week. @david-waltermire-nist will review tomorrow the drafts.

**Comment by david-waltermire-nist** [comment]
# 10/11/18 Status
---
@PCrayton Will open a PR with the completed catalog and profile documentation in their respective metamodels. @wendellpiez and @david-waltermire-nist will review this.

**Comment by david-waltermire-nist** [comment]
11/15/2018
---
@david-waltermire-nist will accept PR #255 and we will plan new documentation activities to further improve the documentation in sprint 16.

**Comment by david-waltermire-nist** [comment]
Need to review schema docs and make sure they are clear enough. Might be able to use some docs from PR #255. Make updates as needed.

**Comment by iMichaela** [comment]
## 5/23/2019
Needs update from @david-waltermire-nist . The issue will require coordination.

**Comment by david-waltermire-nist** [comment]
This work is happening in #387.
