### ISSUE TITLE
OSCAL Implementation: Core System Metadata

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#213]
# User Story:

As an OSCAL system owner and/or administrator, I can capture the core metadata of my system to include contact details, identifying information, and other system characterization details.
 
## Goals:

Develop a OSCAL Implementation schema that supports the capture of core system metadata

```
Defined by the system owner/administrator
+----------------------------------+
| System Specification             |    
| + -----------------------------+ |
| | Aggregated into Capabilities | |        
| | +-------------------------+  | |
| | | Component Specification |  | |
| | +------|------------------+  | |
| +--------|---------------------+ |
+----------|-----------------------+
           |
          \/
+----------------------+
| Component Definition |
+----------------------+
Provided by the component owner or provider
```
## Dependencies:

None

## Acceptance Criteria

1. OSCAL Implementation schema has been developed to support the capture of core system metadata including contact details, identifying information, and other system characterization details.  
1. OSCAL Implementation schema has been sufficiently documented to describe the functions contained therein
1. OSCAL Implementation schema PR has been reviewed by the OSCAL Team and merged into the OSCAL GitHub repo

**Comment by iMichaela** [comment]
## July 18 Status Update (Sprint 12 Acceptance Meeting) ##
The issue was not assigned to any member of the team in Sprint 12 and we will push the issue to Sprint 13

**Comment by david-waltermire-nist** [comment]
The concepts in this issue will be document on the OSCAL website in issue #363. Closing this issue.
