### ISSUE TITLE
OSCAL Implementation: System Specification

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#214]
# User Story:

As an OSCAL system owner and/or administrator, I am able to use an OSCAL implementation "_System Specification_" (per the diagram below) to define the components of my system. A component is an element of a system that performs a standalone function that implements a specific set of controls or parts of controls. A component can be a technical element, policy, process, or procedure. A technical element is implemented by hardware, firmware, and/or software. A policy, process, or procedure is defined by documentation.

## Goals:

1. Per the following representative diagram describing the elements of the OSCAL implementation schema, develop an OSCAL implementation "_System Specification_" (per the diagram below) to define the components of a system.   

```
Defined by the system owner/administrator
+----------------------------------+
| System Specification             |    
| + -----------------------------+ |
| | Aggregated into Capabilities | |        
| | +-------------------------+  | |
| | | Component Specification |  | |
| | +------|------------------+  | |
| +--------|---------------------+ |
+----------|-----------------------+
           |
          \/
+----------------------+
| Component Definition |
+----------------------+
Provided by the component owner or provider
```

## Dependencies:

None.

## Acceptance Criteria

1. OSCAL Implementation schema has been developed to support the OSCAL System Specification defining the components of a system.
1. OSCAL Implementation schema has been sufficiently documented to describe the functions contained therein.
1. OSCAL Implementation schema PR has been reviewed by the OSCAL Team and merged into the OSCAL GitHub repo.

**Comment by iMichaela** [comment]
## 6/28/2018 Status ##
Reviewed the user story to reflect the scenario discussed during the meeting.

**Comment by iMichaela** [comment]
## July 18 Status Update (Sprint 12 Acceptance Meeting) ##
The issue was not assigned to any member of the team in Sprint 12 and we will push the issue to Sprint 13

**Comment by david-waltermire-nist** [comment]
The concepts in this issue will be document on the OSCAL website in issue #363. Closing this issue.
