### ISSUE TITLE
OSCAL Implementation: Component Specification

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#215]
# User Story:

As an OSCAL system owner and/or administrator, I am able to use an OSCAL implementation "_Component Specification_" (as per the diagram below) that identifies the specific controls or parts of controls from an OSCAL Profile supported by a component in an OSCAL implementation. These controls will align with the OSCAL Profile selected for the system or capability.

## Goals:

1. Per the following representative diagram describing the elements of the OSCAL implementation schema, develop an OSCAL implementation "_Component Specification_" to identify the specific controls or parts of controls from an OSCAL Profile supported by a component in an OSCAL implementation. 

```
Defined by the system owner/administrator
+----------------------------------+
| System Specification             |    
| + -----------------------------+ |
| | Aggregated into Capabilities | |        
| | +-------------------------+  | |
| | | Component Specification |  | |
| | +------|------------------+  | |
| +--------|---------------------+ |
+----------|-----------------------+
           |
          \/
+----------------------+
| Component Definition |
+----------------------+
Provided by the component owner or provider
```

## Dependencies:

None.

## Acceptance Criteria

1. OSCAL Implementation schema has been developed to support the OSCAL Component Specification defining the components of a system.
1. OSCAL Implementation schema has been sufficiently documented to describe the functions contained therein.
1. OSCAL Implementation schema PR has been reviewed by the OSCAL Team and merged into the OSCAL GitHub repo.

**Comment by iMichaela** [comment]
## 6/28/2018 Status ##
Reviewed the user story to reflect the scenario discussed during the meeting.

**Comment by david-waltermire-nist** [comment]
The concepts in this issue will be document on the OSCAL website in issue #363. Closing this issue.
