### ISSUE TITLE
OSCAL Implementation: Capability Specification

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#217]
# User Story:

As an OSCAL system owner and/or administrator, I am able to compose/aggregate a set of defined "_Components_" into a "_Capability_" (as per the diagram below). "_Capabilities_" implement a specific set of controls or parts of controls, which may include controls not addressed completely by an underlying "_Component_".

## Goals:

1. Per the following representative diagram describing the elements of the OSCAL implementation schema, develop an OSCAL implementation "_Capability_" that is comprised of a set of defined "_Components_" of a system.
1. Ensure OSCAL "_Capability_" supports the implementation of a specific set of controls or parts of controls, which may include controls not addressed completely by an underlying "_Component_".

```
Defined by the system owner/administrator
+----------------------------------+
| System Specification             |    
| + -----------------------------+ |
| | Aggregated into Capabilities | |        
| | +-------------------------+  | |
| | | Component Specification |  | |
| | +------|------------------+  | |
| +--------|---------------------+ |
+----------|-----------------------+
           |
          \/
+----------------------+
| Component Definition |
+----------------------+
Provided by the component owner or provider
```

## Dependencies:

None.

## Acceptance Criteria

1. OSCAL Implementation schema has been developed to support the OSCAL Capability. 
1. OSCAL Implementation schema has been sufficiently documented to describe the functions contained therein.
1. OSCAL Implementation schema PR has been reviewed by the OSCAL Team and merged into the OSCAL GitHub repo.

**Comment by iMichaela** [comment]
## 6/28/2018 Status ##
Reviewed the user story to reflect the scenario discussed during the meeting.

**Comment by iMichaela** [comment]
## July 18 Status Update (Sprint 12 Acceptance Meeting) ##
The issue was not assigned to any member of the team in Sprint 12 and we will push the issue to Sprint 13

**Comment by david-waltermire-nist** [comment]
The concepts in this issue will be document on the OSCAL website in issue #363. Closing this issue.
