### ISSUE TITLE
Metaschema supports common text markup across XML and JSON

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#224]
# User Story:

As an OSCAL producer, I can include the same text markup that is lossless in its representation across both XML and JSON OSCAL documents.

## Goals:

The metaschema should support lossless text markup conversions between XML and JSON OSCAL documents. It should produce XSD and JSON schema that can validate the same text markup in both XML and JSON.

## Dependencies:

Follow on to #186.

## Acceptance Criteria

The metaschema can be used to produce XSD and JSON schemas that validate text markup across both XML and JSON documents respectively.

**Comment by david-waltermire-nist** [comment]
This is addressed in #200, #283, and #284.
