### ISSUE TITLE
Making links (dependencies) within SP800-53 explicit?

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#226]
# User Story:

As an OSCAL user and system builder, I should be able to see how the different parts of SP800-53 catalog relate to one another. And the most important of those relationships should be explicit, consistenly expressed, and machine-processable.

## Goals:

The SP 800-53 catalog is structurally complex, in that Assessments and Objectives are described separately (in an appendix) but structurally, are interwoven. So, for example, within AC-3(3), objectives [6](a), [6](b) and [6](c) correspond to statement items (a), (b) and (c). Presently, if these relations are represented at all, it is only implicitly by way of correspondences. And we do not know how consistent these are.

Given a better understanding of these relationships, we can decide how to represent them in the model.

## Dependencies:

Stable IDs on all relevant components (#221)

## Acceptance Criteria

To the extent these relations are discoverable and systematic, they should (arguably) also be explicit. We will have addressed this user story when we have (a) made these links more explicit, or (b) produced better documentation describing relations and (implicit) links.

**Comment by wendellpiez** [comment]
This may have (should have) been addressed by PR #229.

**Comment by wendellpiez** [comment]
The current SP800-53 catalog has assessments and objectives interwoven (each control or subcontrol has its own), and IDs are rationalized. This issue is closable.

**Comment by david-waltermire-nist** [comment]
Ok. Considering this closed.
