### ISSUE TITLE
OSCAL profile metaschema is missing an href field definition for the import assembly

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#230]
The `import` assembly [defined](https://github.com/usnistgov/OSCAL/blob/master/schema/metaschema/oscal-profile-metaschema.xml#L38) in `oscal-profile-metaschema.xml` is missing an `href` (or equivalent) field definition. As a result, the generated `oscal-profile-schema.xsd` and `oscal-profile-schema.json` schemas are missing an `href` (or equivalent) attribute/property.

CC @wendellpiez 

Related to #202

**Comment by david-waltermire-nist** [comment]
@wendellpiez Has this been fixed?

**Comment by wendellpiez** [comment]
Yup it has.

**Comment by anweiss** [comment]
Closing.
