### ISSUE TITLE
Comparing JSON examples produced from the metaschema using multiple tools

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#244]
In support of #197 and #242, below are JSON examples of a catalog and profile which were both produced from `oscalkit` via the metaschema. These can be compared to the examples produced from the XSLT for validating and fine-tuning the metaschema. Any JSON consolidation constructs embedded into the metaschema as a result of #241, #224 and #202 will also be reflected in future example production runs of `oscalkit`.

- [`NIST_SP-800-53_rev4_catalog.json`](https://gist.github.com/anweiss/f42061630dde788976475c697a0b87aa)
- [`FedRAMP_HIGH-baseline_profile.json`](https://gist.github.com/anweiss/410897e19d80ab94ee0bc442f2672d2e)

CC @wendellpiez 

This issue is meant purely for JSON example comparisons and can be closed once the metaschema is functioning as desired.

**Comment by anweiss** [comment]
FWIW, `oscalkit` automatically generates its own code from the metaschemas in ~200 lines of code. The core Go templating logic is contained at https://github.com/opencontrol/oscalkit/blob/master/metaschema/types.tmpl. It's relatively straightforward to enhance this to generate types from the metaschemas for other programming languages.

**Comment by david-waltermire-nist** [comment]
@anweiss Should this issue be transfered to oscalkit?

**Comment by anweiss** [comment]
@david-waltermire-nist TBH I think we can actually close this in favor of the metaschema tests that have been implemented as part of CI/CD. Over time, other tools will naturally be able to implement similar tests within their own context.

Closing as such.
