### ISSUE TITLE
Requesting more Object_id's

### ISSUE THREAD

**Issue by bsilberberg** [usnistgov/OSCAL#248]
# User Story:

I love that you guys starting adding more object id's to things, but wanted to have them on the other major elements ( that I am working on right now at least). For example. Assessments, and Assessment objects, Each <p> in my schema is its own sub object. So there would be N number of Objects under Examine, N amount under Interview's and N amount under Tests etc. This allows for each element to be "referenced" when documenting the results of each assessment, or sub element / object of an assessment. a user might not pass all of the objects, but maybe 1. <br>

## Goals:

Be able to cross reference any of the major objects inside the catalog, by an object_id. 
Being able to tie them all to a revision would be even greater. I have noticed that just because its 800-53 v4. there are many "sub" versions depending on when you access the current policy. My implementation on something may have meet the control when it was rev 4.1 but not rev 4.2.  <br>

## Dependencies:
Having micro versioning, might be a bigger ask then is achieve able. It would require NIST proper, to set micro versioning on the main policies. 

## Acceptance Criteria

Having objectname_id for all sub elements. <br>
remove `<p>` 's and turn into separate objects or sub objects.<br>
example, statements > Items. not an item with a statement id. <br>

```
<part class="statement" id="ac-2_smt">
            <p>The organization:</p>
            <part class="item" id="ac-2_smt.a">
               <prop class="label">AC-2a.</prop>
               <p>Identifies and selects the following types of information system accounts to support organizational missions/business functions: <insert param-id="ac-2_prm_1"/>;</p>
            </part>
```
"The organization:" should be the statement, which has item children of the class item. with an id of itm.

**Comment by wendellpiez** [comment]
@bsilberberg could I see small mockup please? Unless I'm mistaken your snippet shows the present arrangement, not what you're envisioning? Glad to see anything you would argue would be more rational, "transparent" or intuitive/intelligible.
