### ISSUE TITLE
Provide for referential integrity of resources referenced within OSCAL artifacts

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#250]
# User Story:

As an OSCAL content creator, I can provide a hash of a referenced resource in an OSCAL artifact. As an OSCAL content consumer, I have a means to verify that a retrieved resource is the same resource being referenced.

Building on issues #245 and #249, which focus on artifact/document integrity, we need to provide a mechanism that provides referential integrity of referenced resources within an OSCAL artifact.

For example:

Given an OSCAL artifact A, there needs to be a mechanism to provide a hash over a resource B that is referenced within A.

```
+-------------------+
| Signature of A    |
+-------------+--++ |
| Document A      | |
|            Hash | |   +------------+
| Linked data =========>| Document B |
+-----------------+-+   +------------+
```

In this example, within document A, the reference to document B has an associated hash. This hash provides a mechanism to verify the integrity of B. The signature over Document A allows the integrity of document A to be verified, allowing the hash in the reference to also be trusted.

Something like the following would provide a solution for this.
```
<link rel="related" ref="https://path/to/B">
  <hash type="SHA512" bytes="ABC"/>
</link>
```

## Goals:

1. Create a referential integrity mechanism for all external references within an OSCAL artifact. This includes direct references between OSCAL artifacts, document references, and other links.
1. Incorporate all new features into the metadata model for Catalog, Profile, and Implementation models.
1. Document the use of this new feature on the OSCAL pages.nist.gov site.

## Dependencies:

None. This issue can be resolved separately from the related document-level integrity mechanisms provided by issues #245 and #249. Combined with this issue, these issues provide a full integrity mechanism.

## Acceptance Criteria

1. The metamodels for the Catalog, Profile, and Implementation layers have been updated to incorporate this referential integrity mechanism.
1. All related model features are fully documented in each metamodel.
1. Examples of using this new feature are provided in each metamodel.

**Comment by anweiss** [comment]
Here's an interesting framework that might be able to address this -> https://github.com/in-toto/in-toto (https://in-toto.github.io/) ...

**Comment by david-waltermire-nist** [comment]
10/25/2018 Status
---
@david-waltermire-nist and @wendellpiez will meet to discuss this next week.

**Comment by iMichaela** [comment]
## 11/08/2018 ##
@wendellpiez has a model sketched in the branch https://github.com/wendellpiez/OSCAL/tree/feature-metadata-schema/schema/metaschema. He created sample data.

**Comment by wendellpiez** [comment]
**Sprint 15 Progress Nov 15 2018**

These requirements are addressed by the draft metadata metaschema of PR #264  (in the `schema/metaschema` directory) and samples (in the contents/metadata directory). This is a first cut and needs to be refined. More real and realistic examples are needed.

Further integration into catalog and profile schemas (at least) does *not* depend on having a final version, and could (perhaps should) proceed even while we solicit feedback and refine the model.

**Comment by david-waltermire-nist** [comment]
11/15/2018
---
@wendellpiez has provided elements to address this in #264. Needs to be reviewed by the team. @david-waltermire-nist will review and provide feedback.

**Comment by akarmel** [comment]
**12/6/2018 - Sprint 16 Progress Notes**
- Per Dave/Wendell, recommend closing this issue as part of the merge of PR #264

**Comment by brianrufgsa** [comment]
12/20/2018 PR #64 was accepted. This is being closed.
