### ISSUE TITLE
BUG: Profile XSD shows lapse in XSD production from metaschema

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#251]
# User Story:

Some correct profile instance documents (XML) cannot be validated against the Profile XSD while its model does not permit `choice` inside `select`. This lapse is happening because the declaration is not being imported correctly into the profile metaschema (from the catalog metaschema) when the XSD is generated.

## Goals:

Correct the schema so that the profile schema matches the catalog schema with regard to `set-param` and its descendants including `select` and `choice`.

Consider renaming `choice` to `value` for consistency.

## Dependencies:

Either metaschema production must be stable for this to be corrected in a separate branch, or the correction should be declared in scope for another issue related to metaschema development.

## Acceptance Criteria

1. A document that uses `set-param`, `select` and `choice` (or `value`) must be shown to be valid to the new XSD
1. Ideally, testing of a pathological data instance against the schema would also validate against similar problems elsewhere

**Comment by wendellpiez** [comment]
**Update Nov 28**

Current work on the metaschema in branch https://github.com/wendellpiez/OSCAL/tree/feature-metaschema-d2-next will address this issue.

The mechanism for importing definitions from other metaschemas is being overhauled to be more robust.

**Comment by wendellpiez** [comment]
This was addressed in work in PR #339 and is now working in `master`. Issue is closable.

**Comment by david-waltermire-nist** [comment]
Ok. Closing.
