### ISSUE TITLE
Identification of OSCAL Artifacts

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#254]
# User Story:

As an OSCAL content consumer, I need to be able to identify:
1. Individual OSCAL artifacts by a unique artifact-specific identifier.
1. That two OSCAL artifacts represent minor revisions of the same data set (e.g., SP 800-53 rev4 published today vs SP 800-53 rev4 published tomorrow with minor bug fixes)
1. That two OSCAL artifacts represent different distinct data sets (e.g., SP 800-53 rev4, SP 800-53 rev5)

I need to be able to use a generalized approach to support the above, that is portable across different data sets, use cases, etc.

## Goals:

1. A simple, easy to use set of data elements must be defined that allows for a tool to mechanically differentiate between the 3 cases above. This approach must not rely on the tool understanding the semantics of a specific data set. 
1. The solution must use a generalized set of data elements to identify OSCAL artifacts to include:
    - The unique OSCAL instance.
    - The identification of a specific data set which may be revised multiple times to address bug fixes, content clarifications, and other minor changes that do not affect the core subject matter being conveyed.
    - The differentiation of major changes to a data set that significantly change the underlying meaning of the data.

## Dependencies:

None. Related work has been started with issues #220 and #221.

## Acceptance Criteria

| Document  | Type of Change |
| ------------- | ------------- |
| OSCAL Artifact A revision 1  | Original Version of A  |
| OSCAL Artifact A revision 2  | Bugfix version of A |
| OSCAL Artifact B revision 1 | Original version of B |
| OSCAL Artifact C revision 1| Original version of C |

1. The solution must be able to address the following test cases:
  a. Identify that A rev 1 and A rev 2 represent the same data set.
  a. Identify that A rev 1, A rev 2, B rev 1, and C rev 1 are different OSCAL artifacts,
  a. Identify that A rev 1, B rev 1, and C rev 1 represent different data sets.
1. All data elements used to support this solution are defined in the Catalog, Profile, and Implementation metamodels, along with corresponding documentation.

**Comment by bsilberberg** [comment]
I think this plus having the concept of originator of the artifacts should help keep track and consistency. 
One thing we talked about  alot, was revisions, more specifically on the profile / playbook side. If someone takes Rev A V1, and then modifies it, would it become Rev B V1? or Rev A V2.? Then, what if the orginator of that playbook changes it. Do they become Rev A V1.1?

**Comment by wendellpiez** [comment]
**Sprint 15 Progress Report Oct 25**

I'm starting to sketch this out better in my head. Progress: 5%.

This is a difficult modeling problem. Suggest I need to schedule a work session with @david-waltermire-nist to make progress, maybe by making some mockups of ideas (I have a couple).

Also: https://niso-sts.org/TagLibrary/niso-sts-TL-1-0-html/index.html

**Comment by david-waltermire-nist** [comment]
10/25/2018 Status
---
@david-waltermire-nist and @wendellpiez will meet to discuss this next week.

**Comment by iMichaela** [comment]
## 11/08/2018 ##
@wendellpiez has a model sketched in the branch https://github.com/wendellpiez/OSCAL/tree/feature-metadata-schema/schema/metaschema. He created sample data.

**Comment by wendellpiez** [comment]
**Sprint 15 Progress Nov 15 2018**

These requirements are addressed by PR #264. Testing and feedback is needed. See the related Issue #250, covered by the same PR.

**Comment by david-waltermire-nist** [comment]
11/15/2018
---
@wendellpiez has provided elements to address this in #264. Needs to be reviewed by the team. @david-waltermire-nist will review and provide feedback.

**Comment by akarmel** [comment]
**12/6/2018 - Sprint 16 Progress Notes**
- Per Dave/Wendell, recommend closing this issue as part of the merge of PR #264

**Comment by brianrufgsa** [comment]
12/20/2018 PR #264 was accepted. Closing issue.
