### ISSUE TITLE
Finalize the draft SSP model design for sections 1-13

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#268]
# User Story:

As an OSCAL content consumer, I have a SSP model design for NIST 800.53-based SSP's in OSCAL format encompassing sections 1-13.

## Goals:

    - Support components for section 13
    - Include support for attachments (embedded)
    - Align with the component approach

## Dependencies:

#257 and #267 

## Acceptance Criteria

1) Well documented, OSCAL draft SSP model exists for NIST 800.53-based SSP's in OSCAL format encompassing sections 1-13.

**Comment by brianrufgsa** [comment]
1/31/2019 - All of these items are reflected in the current draft of the Metaschema. Moving to review.

**Comment by brianrufgsa** [comment]
2/7/2019 - still pending review for close-out.

**Comment by david-waltermire-nist** [comment]
Closing this issue in favor of documenting new issues to define what needs to be done next.
