### ISSUE TITLE
Document the SSP model in the metaschema

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#269]
# User Story:

As an OSCAL content consumer, I have access to a well documented SSP model as reflected in the metaschema.

## Goals:

Document the SSP model in the metaschema

## Dependencies:

#267, #268 

## Acceptance Criteria

1) A well documented SSP model exists in the metaschema

**Comment by brianrufgsa** [comment]
12/20/2018 - @brianrufgsa has added some documentation content while drafting the Metaschema. Will flesh out fully in Sprint 17.

**Comment by brianrufgsa** [comment]
1/31/2019 - Complete first cut of documentation will be complete with the SSP Metaschema. Completion by end of 17-B sprint.

**Comment by wendellpiez** [comment]
**Progress Feb 7 2019**

Not much progress to report as this Issue is dependent on #267, producing an SSP metaschema. We are documenting as we go but things are still in flux.

**Comment by brianrufgsa** [comment]
2/14/2019 - Key aspects of the metaschema were documented in-line. Due to the likelihood of change, we agreed in today's meeting the documentation is sufficient for now and will be revisited once the model has been vetted and is more stable.

**Comment by david-waltermire-nist** [comment]
Let's close this issue in favor of creating new issues that document what needs to be done going forward.
