### ISSUE TITLE
Develop a single, draft real-world SSP in OSCAL format

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#270]
# User Story:

As an OSCAL content consumer, I have an example of a real-world SSP in OSCAL format.

## Goals:
- Develop a "flat SSP"
- Pick a sample of the controls that cross multiple families
- Selectively enhance the component data where possible

## Acceptance Criteria

1) A real-world SSP exists in OSCAL format.

**Comment by brianrufgsa** [comment]
12/20/2018 Have live real-world SSP. Front matter is 80% converted. Controls, @wendellpiez is working on a process to automatically convert the Word SSP to OSCAL. That effort 70%.  Add to sprint 17.

**Comment by brianrufgsa** [comment]
1/31/2019 - Working concurrently with the Metaschema. 
Initial priority is an incomplete, but minimum viable conversion to XML enough to develop demonstrations. 
Targeting minimum-viable by end of Sprint 17-B. Full conversion in next sprint.

**Comment by brianrufgsa** [comment]
2/7/2019 - We continue to make progress o this, and are on-track for end of 17-B sprint.
The SSP metaschema work is being refined as we go, and the two are better aligned now.

**Comment by david-waltermire-nist** [comment]
2/7/2019 - @wendellpiez is making good progress on the data extraction of controls from the prose SSP. @brianrufgsa has been working on the frontmatter. A draft of this is expected to be "completed" by 2/14/2019. Will provide a summary by 2/14/2019 describing what has been completed and what issues remain.

**Comment by brianrufgsa** [comment]
2/14/2019 - We have converted the bulk of the ssp to OSCAL. More than enough to achieve our goal of "minimum viable". We have started building demos from the data. This issue can be closed.

**Comment by brianrufgsa** [comment]
This was completed in February. Recommend closing out this issue.

**Comment by trevor-vaughan** [comment]
Is there output from this published somewhere? I'd like to be able to see how to dig into the component level materials as a reference.

I know that #329 and #363 are still open but I'm trying to see how this will play out if possible.

**Comment by wendellpiez** [comment]
@trevor-vaughan we had a draft we were unable to share (data we were not authorized to publish), so work continues with (I hope) something to show by mid-August. It will probably look quite a bit different from that draft.

**Comment by brianrufgsa** [comment]
@wendellpiez to compare prior work on this to current work.

**Comment by iMichaela** [comment]
@iMichaela is working on developing a sample SSP of a small network for us to excercise the OSCAL SSP, and the OSCAL component when needed.

**Comment by david-waltermire-nist** [comment]
This work has not been completed yet. Adding to sprint 25.

**Comment by david-waltermire-nist** [comment]
We have some synthetic [examples](https://github.com/usnistgov/oscal-content/tree/master/ssp-example) in the OSCAL content GitHub repository. There are also templates [available](https://github.com/GSA/fedramp-automation/tree/master/templates/ssp) in the FedRAMP automation repository. These will suffice until more contributions are made. Closing.
