### ISSUE TITLE
Develop a more complete outline of the pages.nist.gov site

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#273]
# User Story:

As an OSCAL stakeholder, I can navigate to pages.nist.gov and see a complete outline of the different components of the project.

## Goals:

Develop a complete outline for the pages.nist.gov/OSCAL site that accurately reflects the different components of the project for various OSCAL stakeholders.
    - XML, JSON, YAML model sections (with only appropriate example tabs)
    - Where XML and JSON signing will live?
    - Integrate the implementation models alongside the catalog and profile models
    - Describe the HTML <-> markdown mapping for style; this supports translations between XML/XHTML, JSON/markdown, YAML/markdown

## Dependencies:

#148

## Acceptance Criteria

1) An outline exists that clearly and accurately reflects the different components of the project for each OSCAL stakeholder

**Comment by brianrufgsa** [comment]
12/18/2018 - No meetings on this topic so far in sprint 16. Some suggestions made by @anweiss on Gitter. Need to push to Sprint 17.

**Comment by brianrufgsa** [comment]
Bridget developed and presented a site map on 1/31/2019.
Bridget to post outline to this issue.
Moving to close.

**Comment by bbattaglini** [comment]
Attached the site map to the issue. Closing the issue with attachment of the site map deliverable.

[Site_Map_Deliverable_Sprint17-A_Issue273.pdf](https://github.com/usnistgov/OSCAL/files/2821420/Site_Map_Deliverable_Sprint17-A_Issue273.pdf)
