### ISSUE TITLE
Automate the production of documentation on pages.nist.gov using metaschema and a CI/CD pipeline

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#274]
# User Story:

As an OSCAL content consumer, I have access to documentation that is continuously up-to-date via an automated CI/CD pipeline.

## Goals:

Develop a NIST CI/CD pipeline to automate the production of documentation on pages.nist.gov using the metaschema (@david-waltermire-nist)

## Dependencies:
#273 

## Acceptance Criteria

1) Documentation is automatically developed for pages.nist.gov using a NIST CI/CD pipleline from the OSCAL metaschema

**Comment by anweiss** [comment]
This is dependent on support for some sort of "staging" endpoint on NIST Pages so documentation changes can be verified before pushing into prod ...  i.e. `https://pages-staging.nist.gov/OSCAL`. According the NIST Pages [wiki](https://github.com/usnistgov/pages-root/wiki), NIST Pages is based off of 18F's old [pages-server](https://github.com/18f/pages-server) project which had support for multi-branch publishing. However, @david-waltermire-nist would probably have to do some digging to see if this capability carried over into NIST Pages.

**Comment by wendellpiez** [comment]
There is also a dependency here, or at least a relation to #273, the Issue regarding (re)structuring the Pages site -- when the pages site changes, the CI/CD will also have to.

**Comment by david-waltermire-nist** [comment]
This is done.
