### ISSUE TITLE
Import NIST SP 800-53 rev5 controls (from public draft) into OSCAL Catalog Format

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#275]
# User Story:

As an OSCAL catalog maintainer, I have access to a NIST 800-53 rev5 catalog in OSCAL format. 
 
## Goals:

1) Generate the NVD XML from the PDF/Word content
1) Update the pipeline to produce the updated OSCAL catalog
1) Generate a human-readable form for review
1) Review the resulting OSCAL catalog for accuracy against the original
1) Update documentation on the examples page

## Dependencies:

Access to NIST SP 800-53 rev5 controls from public draft

## Acceptance Criteria

1) A NIST 800.53 rev5 catalog exists in OSCAL catalog format
2) The OSCAL NIST 800.52 rev5 catalog is feature complete and equivalent to the public draft PDF version

**Comment by wendellpiez** [comment]
Working on this in the NIST Gitlab "OSCAL Tools" repo.

**Comment by david-waltermire-nist** [comment]
PR #636 published final public draft catalogs in XML, JSON, and YAML formats.
