### ISSUE TITLE
Triage and cleanup issue backlog in GitHub

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#276]
# User Story:

As an OSCAL project member, I have a clear list of issues in GitHub tied to OSCAL milestones, ready for assignment to future sprints.

## Goals:

1) Triage OSCAL issues in GitHub and make recommendations on what issues should be decomposed, combined or closed (@akarmel @bbattaglini)
1) Review OSCAL issue analysis and apply recommendations to issues in GitHub (@david-waltermire-nist @iMichaela)

## Acceptance Criteria

1) A list of OSCAL issues exists with recommendation on what issues should be decomposed, combined or closed

**Comment by david-waltermire-nist** [comment]
This has been completed.
