### ISSUE TITLE
NIST Pages site re-design

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#279]
# User Story:

To support #273, a complete re-design of the documentation site at https://pages.nist.gov/OSCAL should be in order. As such, I propose we take advantage of the [U.S. Web Design System](https://designsystem.digital.gov/), which is developed by GSA, in combination with the well-documented and well-maintained [Jekyll](https://jekyllrb.com/) static site generator framework to build a completely new landing page for OSCAL. Below are some screenshots for what a re-design might look like. If you'd like to get an idea of what the source code looks like, feel free to check out https://github.com/anweiss/OSCAL/tree/docs-redesign/docs_jekyll_uswds. It is based on GSA's [Jekyll template](https://github.com/18F/uswds-jekyll) for the USWDS. I won't push up any PRs until I get a bit more feedback on this. There's also a great opportunity for us to design our own custom, hero graphic for the homepage which accurately depicts the challenges OSCAL aims to solve and in a fun, illustrative manner.

![screen shot 2018-12-14 at 3 00 50 pm](https://user-images.githubusercontent.com/2326106/50024713-49f6b780-ffb1-11e8-9800-c634ab9ec3c2.png)
![screen shot 2018-12-14 at 3 00 59 pm](https://user-images.githubusercontent.com/2326106/50024714-49f6b780-ffb1-11e8-8faf-6d7cd8b696e0.png)
![screen shot 2018-12-14 at 3 01 04 pm](https://user-images.githubusercontent.com/2326106/50024715-4a8f4e00-ffb1-11e8-814d-cffc746b0229.png)
![screen shot 2018-12-14 at 3 01 14 pm](https://user-images.githubusercontent.com/2326106/50024716-4a8f4e00-ffb1-11e8-8e0f-6350bde36fd7.png)
![screen shot 2018-12-14 at 3 01 25 pm](https://user-images.githubusercontent.com/2326106/50024719-4a8f4e00-ffb1-11e8-819b-0456d0ab4c66.png)
![screen shot 2018-12-14 at 3 01 33 pm](https://user-images.githubusercontent.com/2326106/50024720-4a8f4e00-ffb1-11e8-8003-966c30a0051f.png)
![screen shot 2018-12-14 at 3 01 38 pm](https://user-images.githubusercontent.com/2326106/50024721-4b27e480-ffb1-11e8-9938-3a7ae7baebaa.png)
![screen shot 2018-12-14 at 3 01 42 pm](https://user-images.githubusercontent.com/2326106/50024722-4b27e480-ffb1-11e8-9fc2-4cbbee911609.png)
![screen shot 2018-12-14 at 3 01 46 pm](https://user-images.githubusercontent.com/2326106/50024723-4bc07b00-ffb1-11e8-93e2-507a5fca1d4d.png)
![screen shot 2018-12-14 at 3 01 52 pm](https://user-images.githubusercontent.com/2326106/50024724-4bc07b00-ffb1-11e8-90ad-2131f598dd12.png)

CC @akarmel @bbattaglini 

## Goals:

Provide users with a clean, easy-to-consume experience for learning about OSCAL. Leverage the recommended design guidance for government websites provided by GSA.

## Dependencies:

Definitely need to fix #148. Also dependent on #274.

## Acceptance Criteria

An intuitive website is built for OSCAL.

**Comment by brianrufgsa** [comment]
@david-waltermire-nist wants to ensure the appropriate NIST header/footer is included per the information here:
[https://github.com/usnistgov/nist-header-footer](https://github.com/usnistgov/nist-header-footer)

**Comment by anweiss** [comment]
Updated the prototype to use the NIST header/foot. Screenshots below:

<img width="1552" alt="screen shot 2018-12-20 at 4 33 00 pm" src="https://user-images.githubusercontent.com/2326106/50312033-10bcbc80-0475-11e9-848c-f49f5a104adf.png">
<img width="1552" alt="screen shot 2018-12-20 at 4 33 12 pm" src="https://user-images.githubusercontent.com/2326106/50312034-11555300-0475-11e9-8794-9caa2f155a1d.png">

**Comment by anweiss** [comment]
@david-waltermire-nist @wendellpiez we need to figure out if NIST pages supports some sort of "staging" endpoint .. e.g. https://pages-staging.nist.gov/OSCAL ... according to the NIST Pages [wiki](https://github.com/usnistgov/pages-root/wiki), it is based on 18F's old [pages-server](https://github.com/18f/pages-server) project which seems to indicate support for [multiple publishing branches](https://github.com/18f/pages-server#multiple-publishing-branches). However, it's likely that one would have to get a hold of the individuals that manage the NIST Pages server.

**Comment by brianrufgsa** [comment]
1/31/2019 - @bbattaglini to enter related issues, which will then be linked to this issue. Then we will close this issue.

**Comment by david-waltermire-nist** [comment]
The work has been done on this. We are reviewing the site in #311. The current site content is in PR #326. I am going to close this issue.
