### ISSUE TITLE
Portability of Linked OSCAL Files

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#281]
# User Story:

As an OSCAL user who needs to work with OSCAL files without an Internet connection, I need a way to keep linked files together and still have the links function as intended.

## Goals:

Analyze the problem and design an approach that ensures related catalogs, profiles, implementation files (components, SSPs), and assessment content can be packaged and transported to other IT environments without losing linked functionality.

This should work without loss of original link pointers and locations.

## Dependencies:

Mature metadata schema.

## Acceptance Criteria

1. The defined approach has solves the problem.
1. The defined approach has enough detail to implement under a separate issue.

**Comment by david-waltermire-nist** [comment]
This may use the same solution for addressing #282, if referenced catalogs, profiles, implementation files are treated as attachments.

**Comment by david-waltermire-nist** [comment]
This is supported by OSCAL backmatter. Closing.
