### ISSUE TITLE
Portability of Attachments

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#282]
# User Story:

As an OSCAL user, I need to ensure linked attachments, such as documents and graphics, can easily move OSCAL content to alternate locations while ensuring the attachment links remain valid.
This applies to "local" content, such as an image intended to be presented with the OSCAL content, or artifacts related to assessment activities.

## Goals:

Analyze the problem and design an approach that ensures attachments (such as images and assessment artifacts) can be packaged and transported to other IT environments without losing linked functionality.

## Dependencies:

Mature SSP metaschema. (Issue #269, #268)

## Acceptance Criteria

1. The defined approach has solves the problem.
1. The defined approach has enough detail to implement under a separate issue.

**Comment by david-waltermire-nist** [comment]
The current OSCAL backmatter model supports attachments, which can be referenced from within OSCAL documents. I believe this issue is addressed.
