### ISSUE TITLE
Assign distinct namespaces to catalog and profile

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#285]
# User Story:

As an OSCAL user and tool developer, I can use XML namespaces to distinguish between different formats defined by metaschemas. With PR #277 this is now possible, but the catalog and profile schemas themselves still use the same namespace (the original OSCAL namespace).

## Goals:

The catalog and profile layers have distinct namespaces. Demonstration tooling has been adapted to work with the new namespaces, and OSCAL data in the repository uses them correctly.

## Dependencies:

* Accept PR #277 or a functional equivalent (so that XML namespace support is available in tooling)
* Define the respective namespaces for catalog and profile. Such as `http://csrc.nist.gov/ns/oscal/catalog/1.0`?

## Acceptance Criteria

* We have new XSD for catalog and profile layers, produced via OSCAL Metaschema, with their respective namespaces wired in
* Extant examples (both actual catalogs and profiles, and samples) validate to the new schemas
* Tooling has been demonstrated to work with the new examples

NB not all tooling needs to be migrated for this Issue to be acceptable. However, for it to be functional with the new namespaces, we need to address any XSLT and Schematron designed for catalogs and profiles, as serious regression bugs will afflict code that has not been migrated. This includes Schematron for OSCAL declarations, resolution of profiles against catalogs, display XSLT and the rest.

**Comment by wendellpiez** [comment]
See #351 on addressing policy questions related to namespaces.

Similar questions apply here. Given agreement on what the namespaces should be (which includes whether they should be the same), expediting this will not be difficult.

FWIW, the Metaschema layer should make maintaining separate namespaces - if that's what we want to do - much easier than it would be without it.

If the current namespace `http://csrc.nist.gov/ns/oscal/1.0` is good for both Catalog and Profile layers, this Issue can be closed with no further action.

**Comment by iMichaela** [comment]
## 5/23/2019
This issue needs more discussion.

**Comment by david-waltermire-nist** [comment]
Discussed this with @wendellpiez and we are going to keep with a single namespace for at least catalog and profile. Closing this issue.
