### ISSUE TITLE
Discrepancies between profile metaschema and FedRAMP profile examples

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#287]
There are a few discrepancies between the [profile metaschema](https://github.com/usnistgov/OSCAL/blob/master/schema/metaschema/oscal-profile-metaschema.xml) and the [FedRAMP profile examples](https://github.com/usnistgov/OSCAL/tree/master/content/fedramp.gov).

The FedRAMP profile examples use the `param-id` attribute in a `set-param` element like so:

```xml
<set-param param-id="ac-1_prm_2">
...
</set-param>
```

However, the profile metaschema sets the ID attribute name to just `id` rather than `param-id` per https://github.com/usnistgov/OSCAL/blob/master/schema/metaschema/oscal-profile-metaschema.xml#L284; hence the discrepancy.

In addition, the FedRAMP profiles have an `id` attribute, but the profile metaschema doesn't define any `id` flag in the root profile assembly -> https://github.com/usnistgov/OSCAL/blob/master/schema/metaschema/oscal-profile-metaschema.xml#L31.

Furthermore, the [profile assembly definition](https://github.com/usnistgov/OSCAL/blob/master/schema/metaschema/oscal-profile-metaschema.xml#L19) is missing a `title` field in the model.

These should all be fixed in either the metaschema or the examples, depending on which model is what we intended.

**Comment by david-waltermire-nist** [comment]
Will close this once the following is addressed:
- Make sure that profile ids are properly used (to be addressed by #348).
- the title will be addressed by #334.

**Comment by iMichaela** [comment]
## 5/23/2019
@brianrufgsa addressed it to the current metaschema, but he will need to address it again when @wendellpiez will be done with the current metaschema updates (#243 #172)

**Comment by wendellpiez** [comment]
Being addressed in PR #379, including the data changes, here:

https://github.com/usnistgov/OSCAL/pull/379/commits/754ebcde3123ade6b5947d3ca0865181da1148c5

**Comment by david-waltermire-nist** [comment]
Done.
