### ISSUE TITLE
NIST Pages Site Header and Footer

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#290]
# User Story:

As an OSCAL website content owner, I want all project website pages to contain the standard NIST header and footer so that the site is consistent and easily recognizable as a NIST asset.

## Goals:

Website page consistency.

## Dependencies:
Issue #294 is set as an epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934

Issue #279 is set as an epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934

## Acceptance Criteria

All website pages contain the standard NIST header and footer. <Note: Need to verify where to get the standard header/footer graphics.>

Review and confirm that all website pages include the standard NIST header and footer.

**Comment by anweiss** [comment]
Linking #279

**Comment by david-waltermire-nist** [comment]
This has been addressed in our prototype website.
