### ISSUE TITLE
NIST Pages Website Template

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#291]
# User Story:

As an OSCAL website content owner, I want the website to utilize a standard template for the pages.

## Goals:
Template design for the OSCAL project website.

## Dependencies:
Issue #294 is set as an epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934

Issue #279 is set as an epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934

## Acceptance Criteria
Using the site map, review and confirm that a standard template is defined for the Landing Page.
Using the site map, review and confirm that a standard template is defined for the Content Page.
Using the site map, visit the Landing Page and confirm the defined template is used.
Using the site map, visit each Content page and confirm the defined template is used.

**Comment by anweiss** [comment]
Linking #279

**Comment by david-waltermire-nist** [comment]
2/7/2019 - This was addressed on 2/6/2019.

**Comment by howieavp76** [comment]
Updated to the splash page to have specific hero text.  Also, added a Home page link to the navigation to make it more intuitive to return to the main page.
