### ISSUE TITLE
Create script walk through tutorials for Producers

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#293]
# User Story:

As an OSCAL Producer, I want a walk through code tutorial for the OSCAL examples.

## Goals:

Provide a hands-on tutorial style walk through of the OSCAL examples for the Producers audience.

## Dependencies:

#279 and #294 

This is an epic story that will be placed in the Sandbox pipeline. Detailed user stories must be written against this epic for work during a sprint cycle.

## Acceptance Criteria

Define and create hands-on tutorial style walk through of the OSCAL examples for the Producers audience.

**Comment by bbattaglini** [comment]
[OSCAL_Code_Tutorial_Walk throughs_Sandbox_Item.pdf](https://github.com/usnistgov/OSCAL/files/2821894/OSCAL_Code_Tutorial_Walk.throughs_Sandbox_Item.pdf)

**Comment by anweiss** [comment]
Another really good example of this is [Katacoda](https://www.katacoda.com/), which even offers a service for embedding these directly into the site.
