### ISSUE TITLE
Implement the plan for the redesign of Pages.NIST website.

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#294]
# User Story:

As an OSCAL Content Owner, I want the plan for the redesign of the Pages.NIST website to be implemented.

## Goals:

Redesign of the Pages.NIST website based upon the plan. The plan is included in Issues #273 and #279.

## Dependencies:

Review and acceptance of Issues #273 and #279.

## Acceptance Criteria

Implemented website for Pages.NIST based upon the plan outlined in issues #273 and #279.

**Comment by david-waltermire-nist** [comment]
The work is mostly done on this. We are reviewing the site in #311. The current site content is in PR #326.

**Comment by david-waltermire-nist** [comment]
This has been completed, minus the walkthrough (#293), which is deferred for now.
