### ISSUE TITLE
NIST Pages Site Navigation

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#295]
# User Story: 
  
As an OSCAL website content owner, I want the website to define and utilize a standard navigation for the pages so the target audience can easily navigate the site. 
  
## Goals: 
Navigation design for the OSCAL project website based on the site map. 
  
## Dependencies: 
Issue #294 is set as an epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 

Issue #279  is set as an epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934

Issue #273 establishes the site map for the web site. See: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934
  
## Acceptance Criteria 
Using the site map, review and confirm that standard navigation is defined for the Landing Page. 
Using the site map, review and confirm that a standard navigation is defined for the Get Involved Page. 
Using the site map, review and confirm that a standard navigation is defined for the Content Pages.

**Comment by anweiss** [comment]
Ongoing work is being scaffolded in https://github.com/anweiss/OSCAL/tree/docs-redesign. We'll continue gathering commits in this feature branch and submit a PR against `master` once some of the nuances are addressed.

**Comment by david-waltermire-nist** [comment]
This has been completed.

**Comment by howieavp76** [comment]
Added a "Home" page link to make it more intuitive to return to the main splash page.
