### ISSUE TITLE
NIST Pages Hero Graphic

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#297]
# User Story: 
  
As an OSCAL website content owner, I want the website landing page to contain a hero graphic so the target audience can easily identify the project and site. 
  
## Goals: 
Reach core team consensus on the hero graphic for the Landing page. 
Establish the hero graphic for the website Landing page. 
  
## Dependencies: 
Issue #279 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 

Issue #294 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 
  
## Acceptance Criteria 
Using the site map, review and confirm that the Hero Graphic is incorporated into the Landing Page.

**Comment by howieavp76** [comment]
Purchased a hero logo denoting the current paper-based approach.  When combined with the new hero callout, it helps show the problem ATLAS is trying to solve.

**Comment by howieavp76** [comment]
Recommend closing

**Comment by anweiss** [comment]
@howieavp76 let's wait until this is pushed up before closing.

**Comment by howieavp76** [comment]
@anweiss - just tagging the ones I view as ready for closing (pending NIST acceptance).  Flagging that the work is done.  As soon as we can resolve the Git issues, I can push the code up.

**Comment by iMichaela** [comment]
The website landing page contains a hero graphic. The review of the graphic will be done under #311
