### ISSUE TITLE
NIST Pages Learn More

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#298]
# User Story: 
  
As an OSCAL website content owner, I want the website to include a Learn More content page to provide the target audience with overview information for the project. 
  
## Goals: 
Learn More content page created for the website that contains information for the target audience to receive more information about the project. 
  
## Dependencies: 
Issue #279 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934

Issue #294 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934
  
## Acceptance Criteria 
Using the site map, review and confirm the Learn More content page exists within the site. 
Describe what must be completed for this issue to be resolved.

**Comment by howieavp76** [comment]
Rewrote and improved some of the content, reformatted and fixed some links.

Recommend closing

**Comment by iMichaela** [comment]
The website contains a Learn More page. The review of the page will be done under #311
