### ISSUE TITLE
NIST Pages Contact

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#299]
# User Story: 
  
As an OSCAL website content owner, I want the website to include a Contact content page to provide the target audience with contact information for the project. 
  
## Goals: 
Contact content page created for the website that contains project contact information for the target audience. 
  
## Dependencies: 
Issue #279 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934

Issue #294 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 
  
## Acceptance Criteria 
Using the site map, review and confirm the Contact content page exists within the site.

**Comment by howieavp76** [comment]
Contact page created but it is pretty basic.  If we have additional requirements, we can build it out to be more robust.

**Comment by howieavp76** [comment]
Also, added call to action sections throughout the site that link back to the contact page.

**Comment by iMichaela** [comment]
The website contains a Contact page. The review of the page will be done under #311
