### ISSUE TITLE
NIST Pages Get Involved

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#300]
# User Story: 
  
As an OSCAL website content owner, I want the website to include a Get Involved content page to provide the target audience with a definition of the Producer and Consumer audience types, an option to select their user type and a hyperlink to a Producer or Consumer content page. 
  
## Goals: 
Get Involved content page created for the website that provides the target audience with a definition of the Producer and Consumer audience types, an option to select their user type and hyperlink to a Producer or Consumer content page. 
  
## Dependencies: 
Issue #279 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 

Issue #294  is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 
  
## Acceptance Criteria 
Using the site map, review and confirm the Get Involved content page exists within the site. Verify the page provides the target audience with a definition of the Producer and Consumer audience types, an option to select their user type and a hyperlink to a Producer or Consumer content page.

**Comment by iMichaela** [comment]
The website contains a Get Involved page. The review of the page will be done under #311
