### ISSUE TITLE
NIST Pages Scenario

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#303]
# User Story: 
  
As an OSCAL website content owner, I want the website to include a Scenario content page to provide the target audience with a generic government agency scenario for using OSCAL. 
  
## Goals: 
Scenario content page created for the website that provides the target audience with a generic government agency scenario for using OSCAL. 
  
## Dependencies: 
Issue #279 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 

Issue #294 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 
  
## Acceptance Criteria 
Using the site map, review and confirm the Scenario content page exists within the site. Verify the page provides the target audience with a generic government agency scenario for using OSCAL.

**Comment by howieavp76** [comment]
Initial development environment setup with Jekyll running locally and a successful build with the "Hello World" template

**Comment by howieavp76** [comment]
Rewrite the first scenario.  Created a second scenario around unlocking security plan data.  Issue should be closed.

**Comment by iMichaela** [comment]
The website contains a Scenario page. The review of the page will be done under #311
