### ISSUE TITLE
NIST Pages Case Study

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#304]
# User Story: 
  
As an OSCAL website content owner, I want the website to include a Case Study content page to provide the target audience with a FedRAMP case for using OSCAL. 
  
## Goals: 
Case Study content page created for the website that provides the target audience with a FedRAMP case for using OSCAL. 
  
## Dependencies: 
Issue #279 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 

Issue #294 is set as an Epic for this user story in ZenHub. To view the hierarchy, see: https://app.zenhub.com/workspaces/oscal-5b4e5f99c417015bdfbefa03/boards?repos=68406934 
  
## Acceptance Criteria 
Using the site map, review and confirm the Case Study content page exists within the site. Verify the page provides the target audience with a FedRAMP case for using OSCAL.

**Comment by howieavp76** [comment]
Verified case studies page works.  Fixed some formatting errors and made the link to the GCN story active.  

Added another case study for Docker with a link to their announcement.

Story is closed.

**Comment by iMichaela** [comment]
The website contains a Case Study page. The review of the page will be done under #311
