### ISSUE TITLE
Create Datasheets to Support OSCAL Website

### ISSUE THREAD

**Issue by bbattaglini** [usnistgov/OSCAL#305]
# User Story:

As an OSCAL content owner, I want to create datasheets of defined OSCAL content for the target audiences.

## Goals:

The datasheets support OSCAL content for marketing and training purposes with the target audiences. Datasheet content must first be defined and then datasheets will be created against the design.

## Dependencies:

This is an epic story that will be placed in the Sandbox pipeline. Detailed user stories must be written against this epic for work during a sprint cycle. Development will most likely be part of Phase 1B or Phase 2 of the website redesign.

## Acceptance Criteria

Definition and creation of datasheets that support OSCAL content for marketing and training purposes with the target audiences.

**Comment by david-waltermire-nist** [comment]
This is not a focus area right now. Instead, we have focused on providing useful information on the website at various levels of detail to support different stakeholder groups. Closing this. We can revisit later.
