### ISSUE TITLE
Migrating catalog and profile schemas to their own namespaces

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#306]
# User Story:

Currently, all the OSCAL schemas share a single XML namespace. The latest metaschema design supports each schema having its own namespace. This is probably a good idea on balance -- while we need to take care not to contract namespace-itis (a painful inflammation of your XML).

## Goals:

Put catalog and profile into different namespaces. Update data and tools to work with these namespaces. Test and solidify namespace support in OSCAL metaschema.

On an earlier Issue #7 @david-waltermire-nist suggests:

* http://csrc.nist.gov/ns/oscal/catalog/1.0
* http://csrc.nist.gov/ns/oscal/profile/1.0
* http://csrc.nist.gov/ns/oscal/implementation/1.0

## Dependencies:

None at this time. However, when namespaces are changed, all data instances must be revised accordingly. All sample data will be impacted, and all (XML-based, namespace-aware) tools must be updated and tested.

## Acceptance Criteria

* New updated schemas have been deployed for catalog and profile formats at least, with their own namespaces.
* All data instances valid to these schemas have been updated and can be shown to be valid to the new schemas.
* Tools under maintenance have been shown to work with the new data.

**Comment by anweiss** [comment]
@wendellpiez what's the difference between this one and #285. Also, should we close #7 in favor of new namespace-related issues?

**Comment by wendellpiez** [comment]
@anweiss this one is essentially a follow-on to #285, also some of this work has been done and integrated cf PR #277.

the old Issue #7 contains useful info. I'm copying it here, so we can close that ticket.

**Comment by wendellpiez** [comment]
This Issue requires discussion. Currently the Metaschema supports declaring a namespace for the entire model it describes (all they way down to prose), but the Catalog and Profile schemas share a namespace. If it's the way we want it we can close this Issue.

**Comment by wendellpiez** [comment]
Note this is also being tracked (with more detail) in #285. Marking this as closable on that basis alone.

**Comment by david-waltermire-nist** [comment]
Ok. Closing.
