### ISSUE TITLE
Assess declarations model in SSP/implementation context

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#310]
# User Story:

Current work on SSP and its metaschema (#268, #269, #270) would benefit greatly from validations additional to what its metaschema imposes, to ensure data integrity. This especially concerns validations regarding key properties that must be managed (`implementation-status` and `control-origination` in particular) to ensure the integrity of downstream processes.

We have a prototype model for such validations in the declarations model. However, the declarations model has not been updated since recent improvements in the metaschema, and requires attention. For example at present it assumes a namespace for OSCAL, but in the current metaschema, each OSCAL format has its own namespace.

## Goals:

Test the validations model and the Schematron that supports it in the context of requirements for the implementation layer. Assess whether and how the declarations model should be updated to the current (metaschema-based) architecture and possibly integrated with other processes (or not).

## Dependencies:

This work items requires enough reliable SSP data to make a realistic determination. This implies that the corresponding metaschema be at least mostly stable.

## Acceptance Criteria

We have a strategy for what to do next with the declarations model. As appropriate, new Issues have been created to track work in this area.

**Comment by david-waltermire-nist** [comment]
This is being worked in #363, #364, and #329. Closing.
