### ISSUE TITLE
OSCAL Website Review

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#311]
# User Story:

As an OSCAL web content owner, I want the content of the OSCAL website to be clear, concise and well descriptive of the OSCAL concepts and elements.

## Goals:

- Website content is reviewed by the team.
- Language and terminology use is consistent throughout the site.

## Dependencies:
 None

## Acceptance Criteria

- Using the temporary site: http://nist-oscal.s3-website-us-east-1.amazonaws.com, review and confirm that the OSCAL website is clear, concise and well descriptive of the OSCAL concepts and elements.
- All content has been reviewed by the OSCAL co-leads (@david-waltermire-nist and @iMichaela), and by NIST web staff.

**Comment by iMichaela** [comment]
# 02/19/2019 # 
The following issues were addressed by the current site and if #311 is closed (review completed), the following issues should be also closed:
# 297: Pages Hero Graphic,
#298: Pages Learn More,
#299 Pages Contact
#300 Pages Get Involved
#301 Pages Producers Overview
#302 Pages Consumer Overview

Also, the following issues could be considered to be addressed for now, if there are pages created for “Scenario” and “Case Study”. The content will need to be developed and maintained later on:
#303 Pages Scenario
#304 Pages Case Study
#305 (Epic) Datasheets to support OSCAL Website.

**Comment by iMichaela** [comment]
# 02/28/2019
@iMichaela and @wendellpiez did a partial review and proposed some changes. @howieavp76 and @wendellpiez will work on it on Monday, March 4.

**Comment by wendellpiez** [comment]
The web site contents are starting to come together but there are still holes. For example, there is a link "Learn More / Relationships ..." results in a 404.

**Comment by howieavp76** [comment]
@wendellpiez - looks like somewhere in a Git merge this page got deleted.  This was the content you sent me to work in.  Going to try and fix now.  Will go back in Git history and see if I can find it.

**Comment by howieavp76** [comment]
Latest version ready for review

http://nist-oscal.s3-website-us-east-1.amazonaws.com/ 

Still awaiting feedback on changing out the Hero graphic, suggested graphic attached.  My only concern is that the color schemes on left and right don’t tie well.  It also breaks the color ties to the icons on the bottom.  Will your communications/branding folks approve that?
 
If you think it is ok, I am happy to swap out.
![oscal_hero_graphic](https://user-images.githubusercontent.com/33614714/53750661-6a2f6780-3e78-11e9-9eee-9a74e2c33ab4.png)

**Comment by brianrufgsa** [comment]
3/7/2019 - Current work is in Andrew's branch. 
Wendell and Michaela have started performing reviews, but need to make more progress to ensure the site structure is complete. They also need to review the documentation pages. 
Needs to be merged into Master. Andrew to create the PR. The decision as to when we merge it will depend on the review.

**Comment by david-waltermire-nist** [comment]
3/14/2019
--
@iMichaela and @wendellpiez will meet early the week of 3/18 to fix any major issues and to identify what work remains in a separate issue to be worked on in the next sprint. We will be able to publish the existing content after it has then been reviewed by the NIST web team.

**Comment by david-waltermire-nist** [comment]
3/18/2019
--
@iMichaela and @wendellpiez still need to meet.

**Comment by wendellpiez** [comment]
**Progress March 20 2019**

Today @iMichaela and I met with Jim Foti (NIST), who had many excellent suggestions, now tracked on #332.

**Comment by iMichaela** [comment]
# 3/21/2019 # 
Closing the issue as the site was reviewed and the issues found are documented in #332

**Comment by david-waltermire-nist** [comment]
I made some changes based on mu review that have been committed to @wendellpiez branch.

I also had the following additional comments:
- Clicking the "GeT Involved" link on the homepage results in a 404
- Under "How OSCAL Supports Your Role", the text doesn't seem to render right. --- title: is not rendered.

- The page on "Relations to Documentary Encoding Standards" drops to a very different conceptual level as compared to the rest of the "learn more" section. What are we trying to accomplish here?

- The case studies page needs some editorial work.

- The examples pages should be focused on catalog and profile examples. Lose the "role" specific examples, which have no content.

- The "github repo" link can be removed under resources.

- The "roadmap" should be moved to the "about" section.

- Under "community" the roles should link to the same sections under "learn more".

**Comment by david-waltermire-nist** [comment]
04-19-19
---
@wendellpiez, @anweiss, and @david-waltermire-nist are meeting later today to process changes related to all the feedback received. The site will need one additional round of review, although a "lighter" review will probably work.

**Comment by wendellpiez** [comment]
** Progress April 23 2019 **

In my `docs-redesign` branch, all of items noted above have been corrected.

More attention could be given to copy on "Case Studies" and "Scenarios" pages (under "Learn More").

**Comment by wendellpiez** [comment]
**Note April 30**

The site still has a CSRC favicon. This is one of the items that came up in review internally.

@david-waltermire-nist @iMichaela any idea what the best favicon would be? (Wishing there were a better name for the tiny little icon designated to float into your browser tab.)

**Comment by iMichaela** [comment]
## 5/1/2019 ##
We could use the following image as favicon 
![Screen Shot 2019-05-01 at 10 08 48 PM](https://user-images.githubusercontent.com/13984545/57053702-ca1a7280-6c5d-11e9-8894-fc4df5fb75ae.png)

**Comment by iMichaela** [comment]
## 5/1/2019 ## 
Few small suggestions:
1. Enlarge the font size to 16px. https://www.modularscale.com/?16,95&px&2 provides good scale for website font sizes
1. Learn more -> Why OSCAL: We might want to rephrase the "To provide assurance of a system’s compliance posture, the implementation of security systems must be both correctly described, and validated against relevant security controls. This is resource-intensive and often infeasible within budget constraints given the complexity of the problem." to eliminate the pointer to 'compliance'.
2. Resources-> Examples: The “example page is empty – then when clicking on Catalog, the catalog example opens OK but the left navigation changes (closes) and Example and Profile disappear. Is this a desired feature?
3. On Documentation-> Components: A similar behavior with the one described above (navigation details ‘close’ /disappear).
4. Documentation -> Schema Reference is a redirect to top navigation ‘Schema Reference’, and the Documentation left navigation is replaced with the Schema Reference navigation. In this way Documentation-> Relation to Industry Standards vanishes
5. When navigating /clicking to Documentation-> Relation to Industry Standards there is no left navigation.
6. Right top corner reads “Contact” , I think it used to be “Contact Us”, same with the page title.

**Comment by iMichaela** [comment]
## 5/2/2019 ##
@wendellpiez and @iMichaela will work on it today.

**Comment by brianrufgsa** [comment]
# 5/9/2019
Done, per @david-waltermire-nist review.
