### ISSUE TITLE
Documentation: Control catalogs and OSCAL as 'standard of standards'

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#312]
# User Story:

As an OSCAL user, developer and advocate, I can find on the Pages site a good explanation of OSCAL's role within the landscape of security catalogs more broadly, including but not limited to ISO 20017, COBIT, FISMA, you-name-it, as well as NIST SP800-53. What is a "catalog" and how is it useful to encode it using OSCAL? (The same might apply to profiles or baselines.)

The idea might be stressed that OSCAL is an "enabling standard" that permits the organization and integration of this information (with other catalogs, in systems for compliance/assessment etc.) without otherwise constraining how it is created, managed, used and published. OSCAL provides an interface but does not otherwise introduce dependencies.

This could be put together with coverage on OSCAL's relation to other documentary encoding standards such as JATS/BITS, STS, DITA, HTML etc. and/or with coverage on the open-source-based controls/compliance community.

There is already some language on this question, which could probably be edited and foregrounded.

## Goals:

Readers of the OSCAL Pages site will be enlightened and reassured.

## Dependencies:

This copy needs to be reviewed for accuracy and tact before it is published.

## Acceptance Criteria

Language has been drafted, discussed and added to the NIST Pages site as necessary.

**Comment by wendellpiez** [comment]
I think our current site covers this pretty well (cf PR #326); the Issue is closable.

**Comment by david-waltermire-nist** [comment]
Ok. Considering this closed.
