### ISSUE TITLE
Documentation: OSCAL and community initiatives

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#313]
# User Story:

As an OSCAL user, developer and advocate, I can find on the Pages site a good explanation of how OSCAL relates to open-source initiatives and community initiatives in this space. We need to convey both what OSCAL is, how it is intended to be useful, and how it can enable tools developers and service providers in the open source and "community" spaces, as well as other constituents.

## Goals:

Readers of the OSCAL Pages site will be enlightened and encouraged.

## Dependencies:

#75 is on this issue. Related is #312 .

This copy needs to be reviewed for accuracy and tact before it is published.

## Acceptance Criteria

Language has been drafted, discussed and added to the NIST Pages site as necessary.

**Comment by david-waltermire-nist** [comment]
This is done in PR #326.
