### ISSUE TITLE
Determine a permanent hosting strategy for staging the OSCAL Website

### ISSUE THREAD

**Issue by howieavp76** [usnistgov/OSCAL#319]
# User Story:

As an OSCAL Content Owner, I wish to finalize a decision on the staging strategy to use for interim website hosting for review/comment prior to finalization.

## Goals:

Decision on permanent hosting strategy for the staging environment

## Dependencies:

N/A

## Acceptance Criteria

NIST approval of the staging strategy/location.

**Comment by howieavp76** [comment]
@iMichaela - needs to be assigned to @david-waltermire-nist and moved into this sprint

**Comment by iMichaela** [comment]
# 02/28/2019 #322 @iMichaela and @david-waltermire-nist are working on finding a suitable solution. We have several options that are investigated.

**Comment by brianrufgsa** [comment]
3/7/2019 - Still under discussion. Michaela continues to explore solutions through NIST.
David contacted Pages Team. May be able to leverage a staging feature.
We are the first to ask, so progress is slow.

**Comment by david-waltermire-nist** [comment]
3/14/2019
--
Use of an S3 bucket will not work given how NIST allows use of S3. @david-waltermire-nist will follow up with the NIST Github team () that supports pages.nist.gov.

**Comment by iMichaela** [comment]
# 3/21/2019 # 
No update. @david-waltermire-nist deals with it and he is on travel

**Comment by iMichaela** [comment]
# 03/28/2019 # 
@iMichaela is still working with the management to obtain a staging server. She learned pages.nist.gov will ALL be reviewed by NIST and a decision will be made if the service will be kept. A backup plan is prepared.

**Comment by brianrufgsa** [comment]
4/4/2019 - Still evaluating options. EC2 is the likely best long-term choice.

**Comment by shawndwells** [comment]
Why not use GitHub pages and have a nist.gov CNAME record created?

**Comment by iMichaela** [comment]
@shawndwells - thank you for the suggestion - we have it as part of the 'short-term plan', in addition to other changes/updates

**Comment by iMichaela** [comment]
# 04/11/2019 # 
No update

**Comment by iMichaela** [comment]
# 04/25/2019 # 
Staging server is not resolved yet @david-waltermire-nist is working on it. The short URL for the projet Https://www.nist.gov/oscal is live and currently redirects to https://pages.nist.gov/OSCAL

**Comment by brianrufgsa** [comment]
# 5/9/2019
No change.

**Comment by david-waltermire-nist** [comment]
## 5/16/19
The team discussed this issue and decided to park it (leaving it open , but unassigned) for now.

**Comment by david-waltermire-nist** [comment]
We are using the https://pages.nist.gov/OSCAL site. Closing this.
