### ISSUE TITLE
Prototype CI/CD Process for deploying OSCAL website to staging

### ISSUE THREAD

**Issue by howieavp76** [usnistgov/OSCAL#320]
# User Story:

As an OSCAL developer, I need to be able to deploy updated website content to a staging server for review/comment in a repeatable manner with no manual touch.

## Goals:

Automated deployment (future phases will automate testing)

## Dependencies:

N/A

## Acceptance Criteria

CI/CD configured and automated deployment process demonstrated and documented

**Comment by david-waltermire-nist** [comment]
This is dependent on #319.

**Comment by david-waltermire-nist** [comment]
This has been working for a long time. Closing.
