### ISSUE TITLE
Printing pages from the web site

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#322]
# User Story:

As an OSCAL user and developer, I would like to be able to print pages from the web site, especially the schema documentation. (I am one of those people.)

## Goal:

Useful printed pages from the Pages site, or an alternative strategy for acquiring OSCAL documentation in print or "printed" form (i.e. with page layout).

PDF or other 'print surrogate' formats are not goals for this issue: only reasonably-printed web pages.

## Dependencies:

* Final decisions on architecture of site and framework(s) see Issue #279
* Analysis of the best remedy for this issue.
* Tracking whether print support in usdws v2 will be better

USWDS, with link to v2: https://designsystem.digital.gov/

FWIW the pages on this site look reasonable for the page, which suggests the problem is *not* the USWDS CSS but something about our preview site configuration (maybe the Bootstrap?).

## Acceptance Criterion

Printing from the web site including schema documentation provides legible, useful printed pages.

**Comment by howieavp76** [comment]
Cross-referenced the OSCAL source code to the USWDS-Jekyll template.  Added missing CSS and JS files to test printing with updated CSS/JS includes.

**Comment by howieavp76** [comment]
All Bootstrap has been removed but the printing format is still not ideal.

**Comment by howieavp76** [comment]
CSS import made the print view much more readable.  Working to resolve Table formatting issues now.

**Comment by howieavp76** [comment]
Finally got it fixed.  There was a Jekyll script that was overriding my CSS setting and putting the media type to "Screen" for all CSS.  I removed that piece of the script and it is working consistent with a normal USWDS site.

Recommend closing.

**Comment by brianrufgsa** [comment]
3/7/2019 - Moved to Needs Review as team agrees this was ready to proceed.

**Comment by iMichaela** [comment]
## 03/14/2019 ##
OSCAL website pages render better and printed versions are decent.

**Comment by david-waltermire-nist** [comment]
This work is out in the WIP PR #326.
