### ISSUE TITLE
Constraints over dates in metaschema

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#323]
# User Story:

As an OSCAL developer, I would like to constrain certain values in my metaschema to represent dates. As an OSCAL user I would like to be able to benefit from the enforcement of such constraints in appropriate application logic.

This feature request was first documented on #267.

## Goals:

1. Define the boundaries around expected metaschema support for date fields or values, in view of the capabilities of both XSD and JSON schema for validating dates.

2. Subject to those definitions, implement support for dates in OSCAL metaschema.

To be consistent with the metaschema design, this typing might be made available on flags (which support a range of data types), but not fields.

## Dependencies:

XSD offers support for date types, including dates with time zones, using a standard notation (ISO 8601) that includes `YYYY-MM-DD` notation. JSON Schema supports no value-space typing for dates, only lexical typing for strings that look like dates (without forbidding `2015-12-32` or `2019-04-31`).

## Acceptance Criteria

Date-related functionality in the metaschema, and in schemas thereby produced, has been defined, implemented, demonstrated and documented.

**Comment by david-waltermire-nist** [comment]
This will be addressed by #436. Closing.
