### ISSUE TITLE
Developing a 'back matter' metaschema module

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#325]
# User Story:

As an OSCAL {stakeholder}, I can find and use a consistent model across the catalog and profile schemas - suitable for use in an SSP/implementation schema - that encodes common **back matter** such as reference lists and attachments.

## Goals:

Develop a metaschema module for back matter that addresses known requirements. Deploy this module where it is needed, such as in catalog or profile schemas.

## Dependencies:

- #316, since the Metaschema infrastructure must be stable again for this work to proceed
- (informative) #267, since the implementation/SSP work presents good raw material

For requirements gathering: see `references` in the catalog schema plus draft material in provisional SSP metaschema work. We know we have both references and attachments.

This model should be minimal (it can grow later) and should have no submodules of its own.

## Acceptance Criteria

A useful 'back matter' module has been developed, demonstrated and deployed. It is used by any schemas that need it. Extant data has been adjusted, if necessary, to be valid to updated schemas. These documents do not include materials that should be in back matter, but are not encoded that way (i.e. they must be not only valid but also correct to the schema's intent).

**Comment by brianrufgsa** [comment]
# 5/9/2019
@wendellpiez reports back matter is implemented in the metaschema per PR #338, which has been merged.
@david-waltermire-nist is OK with closing this, but will create new issue around refactoring the references in back matter.
