### ISSUE TITLE
Updating catalog and profile schemas to new modularity design

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#327]
# User Story:

With work responding to Issue #316 we have a new, simpler metaschema modularity model. At least catalog and profile metaschemas need to be updated to this model.

## Goals:

* Implement the modularity approach defined in the notes of #316,
* Bring metaschemas to a stable point with the new modularization mechanism.
* Complete implementation wrt docs production, integrating definitions from imported modules
* Test all components using the new metaschemas
* Confirm that documents are (still) valid to their schemas

## Dependencies:

#325 is a dependency.

## Acceptance Criteria

* Catalog and profile metaschemas are valid to the new metaschema schema and Schematron?
* Production pipelines are correctly integrating schema modules in production of artifacts, including:
   * XML and JSON schemas (to which examples must be valid)
   * Conversion utilities (XSLTs) supporting XML<->JSON conversion
   * Docs production
* A PR has been submitted and reviewed with all the metaschema changes.

NB: Correcting newly found bugs is not an acceptance criterion.

**Comment by wendellpiez** [comment]
NB: agreed in Sprint Review meeting March 18 that we will *exclude* the `declarations` element and support for it from the RC catalog and profile models. It can be commented out as a tbd.

**Comment by wendellpiez** [comment]
**Sprint Progress March 21 2019**

Not much progress on this, but about to turn back to it now that documentation is more stable.

**Comment by iMichaela** [comment]
# 03/21/2019 # 
@wendellpiez will get back to this issue on Monday next week.

**Comment by howieavp76** [comment]
Latest version posted to S3:

http://nist-oscal.s3-website-us-east-1.amazonaws.com/

**Comment by wendellpiez** [comment]
**Sprint 19 Progress March 28 2019**

Drafts of the new schemas are available in my branch, here: https://github.com/wendellpiez/OSCAL/tree/feature-metaschema-d3/schema/metaschema

There are revised, stable versions of `catalog` and `profile` schemas along with WIP for a new "resources" module providing structures for references, attachments and other resources.

Small adjustments have also been made to catalogs and profiles in this branch to keep them in line.

Also, both docs and tools generation as well as schema generation must be refreshed when this is stable.

**Comment by iMichaela** [comment]
# 03/28/2019 # 
See @wendellpiez 's note above. Feedback from @david-waltermire-nist, @brianrufgsa @anweiss, and @redhatrises is needed.

**Comment by brianrufgsa** [comment]
4/4/2019 - Wendell has completed work, and needs to create a PR for review and acceptance. Also, see comment in Issue #314. PR expected by COB Tuesday 4/9.

**Comment by wendellpiez** [comment]
Made a PR, then closed it for wonkiness. Too many commits, hard to trace.

@anweiss has helped me clean up; trying again tomorrow.

**Comment by iMichaela** [comment]
# 04/11/2019 # 
Ready for review and acceptance. Team - please review.

**Comment by david-waltermire-nist** [comment]
4-19-19
---
This work looks good and has been reviewed.

The following follow-on work is needed:
- Refactor the meta model to allow attachments to be referenced from references.
- Make meta required in all models, and @title required in meta.
