### ISSUE TITLE
Update Implementation/SSP Metaschema 

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#330]
# User Story:

As an OSCAL developer, I need to bring the Implementation/SSP Metaschema into alignment with the revised modular approach and syntax for Metaschema development.

## Goals:

- SSP Metaschema reflects new syntax
- Ssp Metaschema is adjusted to reflect changes to the component definition

## Dependencies:

Issue #216, #327, and #333.

## Acceptance Criteria

- [ ] - SSP Metaschema reflects new syntax
- [ ] - Ssp Metaschema is adjusted to reflect changes to the component definition

**Comment by brianrufgsa** [comment]
We should change the root element from 'system-security-plan' to 'implementation' as part of this effort. 

It started out as 'system-security-plan', when I believed there would be a separate schema for components. Assuming we find it works to manage component and ssp content with the same schema, this change would bring the root name into alignment with the Catalog and Profile layers.

**Comment by david-waltermire-nist** [comment]
This issue is being worked in #363, #364, and #329. Closing.
