### ISSUE TITLE
Refactor repository directory structure for usability

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#331]
# User Story:

As a developer and user, I would like a more rational directory structure in the repo. The current  organization is difficult to work with; in particular it is difficult to distinguish between source artifacts, and resources that are generated from sources in a build process such as schema or documentation generation.

Users include at least the following:
  * OSCAL model and tool developers
  * OSCAL users/researchers
  * CI tooling

## Goals:

The repo directory structure should be more rational and more conformant with the expectations of users.

## Dependencies:

Testing frameworks as well as production pipelines should be stable when we do this, because scripts must be updated.

The attached zip file contains a draft directory structure for discussion.

[OSCAL-directories.zip](https://github.com/usnistgov/OSCAL/files/2983841/OSCAL-directories.zip)

## Acceptance Criteria

1. Stakeholders including our development team having been consulted
1. A new directory structure is agreed to by interested parties
1. OSCAL resources have been reallocated into the structure in a branch in Github
1. This branch has been tested including CI, generation of artifacts (schemas utilities docs etc.), testing framework etc.
1. A PR has been submitted

**Comment by brianrufgsa** [comment]
This capability must accommodate draft releases and/or releases for public comment in addition to formal release. There must be a way to clearly differentiate these release types, even if they all come through the same CI/CD pipeline.

**Comment by howieavp76** [comment]
As another note, the testing scripts use relative paths to find files to test.  If they move, the test scripts will need to be updated.  As the testing coverage has expanded, will be a moderate amount of rework to update the paths and tests.  If we integrate testing into CI/CD, we may want to start with an informational report versus blocking action until everything stabilizes.

**Comment by iMichaela** [comment]
@howieavp76 I suggest we look into repalcing the relative path with variables read from a configuration file. In this way the amount of work is minimised when we refactor the repo's directory structure.

**Comment by howieavp76** [comment]
@iMichaela - good suggestion, done.  There isn't a whole lot of re-use of variable paths between scripts but it doesn't make the code cleaner and more maintainable.  As the test coverage grows, this will pay greater dividends.

**Comment by iMichaela** [comment]
## 5/2/2019 ##
The team discussed the draft proposed by @wendellpiez (attached as zip), but we need to further discuss the requirements and implement the solution.

**Comment by david-waltermire-nist** [comment]
Here is my understanding of the directory structure proposed by @wendellpiez:

- build: Produced by CI/CD; able to be deleted at-will
  - catalog/profile/ssp: Layer specific files
    - json/xml: format specific
      - examples: generated examples from content
      - lib: generated scripts (e.g., transcoding XSLTs)
      - schema: generated schema (from the metaschema)
- content:
  - FedRAMP: FedRAMP profiles
  - NIST: NIST SP 800-53 content
- docs: Jekyll site source
- lib: 
  - CI: CI/CD scripts
  - metaschema: metaschema schema
- src:
  - catalog/profile/ssp: metaschema for each layer; correspond to build/json and build/xml directories
  - demo: ???

While I like everything that is generated being placed in one directory, I don't like naming that directory "build". I don't see an average visitor going to build as their first stop. I'd rather name directories using topical names that will peak a visitor's interest.

IMHO, we can group our users into 2 major camps:
  - Users: interested in content.
  - Tool Developers: interested in XML and JSON format support

I think we can better align our directory structure to support these groups. Something like the following might work better, which is closer to our current organization:

- content: (generated) location of all supporting OSCAL content
  - FedRAMP: FedRAMP profiles
  - NIST: NIST SP 800-53 content
  - demo: other examples
    - xml/json: the proceeding directories will have subdirectories corresponding to specific formats.
- xml: (generated)
  - css: stylesheets for XML content authoring
  - schema: XML schema and schematron for each layer; flat organization
  - convert: XSLTs for json-to-xml
  - resolve: profile resolution; current contents of util/resolve
  - publish: document generation; current contents of util/publish
- json: (generated)
  - schema: generated JSON schema for each layer; flat organization
  - convert: XSLTs for xml-to-json
- src:: Location for all static content
  - metaschema: metaschema for each layer; flat organization
  - utils:
    - css: source for CSS to be published in xml/css
  - content: all pre-converted content
    - FedRAMP: FedRAMP profiles
    - NIST: NIST SP 800-53 content
    - demo: other examples
      - xml/json: the proceeding directories will have subdirectories corresponding to specific formats, but only if source content in that format exists.
- build: all scripting supporting validation, schema, transcoding, and content generation
  - ci-cd: CI/CD scripts
  - metaschema: metaschema XSLTs for generating schema, docs, and content transcoding
- docs: Jekyll site source

**Comment by iMichaela** [comment]
@david-waltermire-nist - I like the approach, but 'resolve' does not appear to me as being very intuitive name. Also @brianrufgsa pointed out we need to have a place for releases (official releases) and one for internal "builds" (not officially released for public consumption). @david-waltermire-nist - Where do you see those fitting into the structure you proposed?

**Comment by howieavp76** [comment]
@iMichaela @david-waltermire-nist I would propose that we have a sub-directory structure under David's.  Something like the following:

Content
    ->Release
        ->Version 1
        -> Version 2
    ->WIP

That structure would allow collaborators to grab stable release files as appropriate while giving us autonomy to change the Work in Progress folders at will.

**Comment by david-waltermire-nist** [comment]
@iMichaela and @howieavp76 Github has a [releases tab](https://github.com/usnistgov/OSCAL/releases) for actual releases. We need to remove the sprint 10 release, but this is the way to do it. We will tag releases as well, to show the current state of the repo at the point of release.

I am open to other suggestions for "resolve".

**Comment by wendellpiez** [comment]
@iMichaela and I discussed what to call this process. The best word we can come up with is **compose**.

We would like to hear reactions and suggestions from the group. The process we are naming is the one whereby a profile is converted into a full representation in which it can be handled and displayed to show its controls as sourced from its catalog(s). So a "composed" profile (what I have been calling "resolved") will look like a catalog with all the changes and (parameter) insertions all made -- possibly (not necessarily) in a "traceable" view that shows the changes next to the original.

"Compose" is probably at least as good as "resolve" in my view, and avoids the (incorrect) connotation of "resolve" as "correcting a problem". (I was thinking more "resolved" as in following a link, but I can't control what goes through people's brains.)

But is it sticky enough for this? @david-waltermire-nist @anweiss @brianrufgsa @howieavp76 @redhatrises opinions welcome.

**Comment by brianrufgsa** [comment]
# 5/9/2019
@wendellpiez will move forward with the design as specified in @david-waltermire-nist May 7th comment above.
Further agreed to ensure readme files appropriately describe the new structure for those unfamiliar with it.
@wendellpiez needs to write an issue to implement this as part of the next sprint.

**Comment by david-waltermire-nist** [comment]
## 5/16/2019
The WIP PR #358 contains the completed directory restructure. Some cleanup of files that did not exactly fit is still needed. This issue can be closed once the PR is approved.

**Comment by david-waltermire-nist** [comment]
PR #358 has been merged, which addresses 99% of this issue. All that remains is some minor file cleanup and creation/review of readme.md files. I need to talk with @wendellpiez about some of this cleanup. I'll close this issue once I can confirm that the team can run the CI/CD scripts and once unneeded files are removed.

**Comment by iMichaela** [comment]
## 5/23/2019
The majority of the work is done. @david-waltermire-nist will discuss with @wendellpiez and finalize it.

**Comment by david-waltermire-nist** [comment]
This has been completed.
