### ISSUE TITLE
SSP Schema Validation

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#333]
# User Story:

As an OSCAL consumer, I need to understand the degree to which the draft Implementation Layer (SSP and Component) Schema meets the needs of the user community and the goals of OSCAL.

A review should include the following:

- **Completeness**: Does the Implementation Layer schema capture all the data elements require at this level?

- **Organization**: Is the organization of the Layer schema intuitive and logica?. 

- **Tagging/Syntax**: Is the syntax and tag name choices intuitive and logical?

- **Scope**: What portions of the syntax should be part of the core OSCAL specification, and what portions should be treated as an extension? 

NOTE: This issue is to "collect" the feedback. Analysis, consensus building, and resulting changes will e handled in Issue #330 (Update Implementation/SSP Metaschema).

## Goals:

- Receive enough feedback to finalize the draft Implementation Layer specification in the pursuit of a milestone release.

## Dependencies:

Issue #329 (Build Sample Component Definitions) - which will be a great way to know how well the component portion of the schema is working.

## Acceptance Criteria

- [ ] Review feedback from as many sources as possible.
- [ ] Feedback is clear and actionable

**Comment by brianrufgsa** [comment]
working sessions set for Monday and Tuesday (9/23 & 9/24).

**Comment by david-waltermire-nist** [comment]
We released milestone 2. This issue will be ongoing to address any feedback received.

**Comment by david-waltermire-nist** [comment]
Issue #597 is tracking all of our open feedback issues. I don't think we need to keep this issue open anymore.
