### ISSUE TITLE
Allowable Title Placement in OSCAL Files

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#334]
# User Story:

As an OSCAL user, I need to clearly understand where and how to specify a title for an OSCAL file. 

We currently allow the title of the document to appear at the root (original placement) and within the metadata element (logical expansion when metadata was added). 

For the milestone release, the team needs to clarify whether a document's title can be specified:
A. only at the root
B. only within the metadata element
C. Both places
D. Either place

NOTE: There is also a title element related to people and roles. That is a separate context and outside the scope of this issue. This is just about the document title.

## Goals:

Reach consensus and clearly articulate the allowable title placement.

## Dependencies:

None.

## Acceptance Criteria

 - [ ] The correct placement and use of title is clearly identified.

**Comment by wendellpiez** [comment]
Currently I am leaning towards inside `metadata` only. I am very interested in hearing arguments for any of the choices here.

This does mean that a catalog document might be valid to its XSD without a title -- if it has no metadata at all. Except for works in progress, I would expect this to violate a business rule in almost any system checking for completeness/correctness (notwithstanding XSD validation).

An alternative would be to permit `title` in both places but encourage Schematron-reporting if both are present and have different contents (string values). And note this in docs.

BTW, shouldn't amending the model to reflect the decision here also be part of this Issue?

**Comment by brianrufgsa** [comment]
I am also inclined to having it just inside metadata.
I'm on the fence as to whether it should be required by XSD or downstream business rules. 

In my opinion, any well-formed OSCAL file should include a title, so I think it should be required by the XSD file, but I can see an argument for enforcing it downstream as needed.

Finally, I believe this issue is related to Issue #327, which is about updating the catalog and profile metaschemas for the milestone release, and could be addressed there once a decision is made here.

**Comment by iMichaela** [comment]
## 5/2/2019 ##
This is linked to #325 . We need to bring #325 into the sprint 20. No progress was made on this issue. Once the decission is made, implementation will be very quick.

**Comment by brianrufgsa** [comment]
## 5/9/2019
@david-waltermire-nist, @wendellpiez, and @brianrufgsa all prefer option B.
@wendellpiez to implement.

**Comment by wendellpiez** [comment]
This is actionable, but a remaining question on #243 might also be answered: allowing `assembly` to be required (to support a required `metadata` element), should we also make it possible to declare `fields` or `assemblies` as required (cardinality `1-*` instead of `0-*` ?) Input welcome @david-waltermire-nist @brianrufgsa @anweiss -- noting we have no actual use cases as we do in the case of the `metadata` assembly.

**Comment by david-waltermire-nist** [comment]
We need to remove the title on [catalog](https://pages.nist.gov/OSCAL/docs/schemas/oscal-catalog-xml/#catalog), profile, etc. The metaschema enhancement suggested above by @wendellpiez also needs to be addressed to close this issue.

**Comment by brianrufgsa** [comment]
Created issue #359 to implement the decision made here.
Closing this issue per direction from @david-waltermire-nist during 5/16/2019 status meeting.
