### ISSUE TITLE
OSCAL element maps for schema documentation

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#337]
# User Story:

As an OSCAL user and developer, I need to understand the content models of the various elements (objects) in OSCAL. An XSLT now in a dev branch can produce an element map from a metaschema, showing a map of element containment.

Maps can be created from the root of a metaschema or from any element. Mini-maps per element could be used on the element's page.

Here's a screen shot of a smaller element map, rooted at `part`:

![image](https://user-images.githubusercontent.com/1588228/55570151-d3510780-56d0-11e9-80e5-4d23ab6f0517.png)

## Goals:

1. Consider and determine whether and how element maps can be used in the schema documentation.
2. Produce a JSON version.

## Dependencies:

Stable schema documentation as described in #314.

Where CSS is involved and perhaps Javascript (maybe we wish the maps to expand/collapse as well as link), we need to determine how to integrate with Jekyll/USWDS in a way that is robust across upgrades.

## Acceptance Criteria

1. Element maps are integrated according to our determination
1. A JSON version has been produced, or another Issue has been created for this work item

**Comment by david-waltermire-nist** [comment]
Closing this in favor of issue #439.
