### ISSUE TITLE
Integrate support for XMLDSig into OSCAL models

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#345]
# User Story:

As an OSCAL XML content creator, I need to be able to use XML Digital Signatures (XMLDSig) to provide integrity and source authentication over OSCAL XML artifacts I produce.

## Goals:

1. Build support into XML formats for all OSCAL models to support [XML Digital Signatures (XMLDSig)](https://www.w3.org/TR/xmldsig-core1/) (XMLDSig).
2. Document usage of XMLDsig in OSCAL XML model documentation.
3. Demonstrate signing and validating OSCAL XML artifacts using open source tooling or create a user story for doing this.

## Dependencies:

Based on design work performed in #249.

## Acceptance Criteria

1. Use of signature algorithms must follow NIST cryptographic guidelines (e.g., FIPS 186-4, FIPS 180-4, FIPS 202).
1. Documentation on the OSCAL usage of XMLDsig must be sufficient for interoperable implementation.
1. Examples illustrate signed OSCAL XML artifacts that can be verified using open source tooling, or an issue to develop examples has been created.

**Comment by nikitawootten-nist** [comment]
Signature solutions such as XMLDSig and JWS have merit but add additional complexity and break format conversion guarantees. The team's general guidance in the past has been to use envelope solutions (sending a signature file separately, etc) rather then relying on format-specific inline signatures.
