### ISSUE TITLE
Adjust SP 800-53rev4 "appendix J" references as external document references.

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#346]
# User Story:

As an OSCAL content consumer, I need useful references within the SP 800-53rev4 catalog.

## Goals:

 The "appendix J" references need to point to the SP 800-53rev4 document, using the [DOI resource link](https://doi.org/10.6028/NIST.SP.800-53r4).

## Dependencies:

None.

## Acceptance Criteria

All appendix J references have been fixed in the SP 800-53rev4 catalog.

**Comment by iMichaela** [comment]
## 5/23/2019
@wendellpiez is working on it. It will be done at the same time with #349 and it depends on #235

**Comment by david-waltermire-nist** [comment]
Done
