### ISSUE TITLE
Document OSCAL Markdown

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#357]
# User Story:

As an OSCAL User building interfaces, I may need to know how OSCAL's flavor of Markdown  works and what it permits.

## Goals:

1. Update documentation for prose on pages.nist.gov.
    - Document use of OSCAL markdown syntax.
    - Show examples of prose in HTML and markdown based on OSCAL subsets
    - Create a table showing the HTML <> Markdown correspondences

## Dependencies:

#343 must be finished so we have confidence that OSCAL Markdown works as currently designed.
#452 needs to be completed to ensure that the prose documentation page is in sync with the actual content generation behavior.
#451 needs to be fixed to ensure parameter insertion is handled as expected.

## Acceptance Criteria

Users can find some help on using OSCAL Markdown on the Pages site.

**Comment by iMichaela** [comment]
## 5/23/2019
#283 is nearly done so we can start working on this issue.

**Comment by david-waltermire-nist** [comment]
@wendellpiez It would be good to update the website [prose](https://pages.nist.gov/OSCAL/docs/schemas/oscal-prose/) page to include a mapping between HTML and Markdown features that are supported. This can be bumped to sprint 22, as it is not a blocker for the M1 release.

**Comment by david-waltermire-nist** [comment]
#452 needs to be completed before this is closed.

**Comment by david-waltermire-nist** [comment]
#451 needs to be fixed to ensure parameter insertion is handled as expected before this is closed.

**Comment by david-waltermire-nist** [comment]
This documentation is currently located in [my branch](https://github.com/david-waltermire-nist/OSCAL/blob/issue357-document-markdown/docs/content/documentation/schemas/oscal-prose.md).

**Comment by david-waltermire-nist** [comment]
This has been completed in PR #449.
