### ISSUE TITLE
Adjust Title Placement in Pipeline and Content

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#359]
# User Story:

As an OSCAL implementer, I need the use of title to be correctly reflected in the NIST OSCAL CI/CD pipeline process as well as in existing NIST-generated OSCAL content.

Title fix
Title required (issue #243)
metaschema
metaschema processing
content

Put comment on #334 (and close it) that points to this issue

## Goals:

- Update the metaschema for catalog and profile layers to implement title as described in Issue #334 (no title at the root, required title in metadata). 
- Ensure the CI/CD pipeline properly updates this requirement in generated schema validation, translation, and documentation.
- Update existing NIST 800-53 catalog, as well as NIST and FedRAMP profiles to reflect the change in title.

## Dependencies:

Decision in Issue #334, which has been made.

## Acceptance Criteria

- [ ] Catalog and Profile metaschema updated
- [ ] Schema validation, translation, and documentation updated
- [ ] 800-53 r4 catalog, and related NIST/FedRAMP profiles updated

**Comment by iMichaela** [comment]
## 5/23/2019
@wendellpiez is working on it. Estimates to be done in a few days.

**Comment by wendellpiez** [comment]
Addressed in PR #379.

**Comment by wendellpiez** [comment]
@brianrufgsa if you want I can also make the necessary adjustment to the FedRAMP examples in the branch being committed ...

**Comment by brianrufgsa** [comment]
@wendellpiez - that would be great. Thank you!
I'll still update the tool so it produces future versions without the title.

**Comment by david-waltermire-nist** [comment]
Done.
