### ISSUE TITLE
Further validations on profiles

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#38]
We currently have validation logic that checks a profile to ensure that all controls, subcontrols and parameters referenced, correspond to elements of the same type with the same ID value, in the catalog in which they appear.

There are a couple of more refined validations we might also want:

* Validate that any controls included in the profile that have parameters (in the catalog), have the 'same' parameters in the profile
* Same for points of insertion in the catalog - included controls do not have `insert` elements that don't have corresponding parameters. (Note this is a warning inasmuch as controls can provide default values for parameters so a profile not including one, is not actually an error.)
* Validate that parameters named in the profile, are used (actually inserted) in controls included in the profile

Alternatively/additionally, maybe a "cleanup" transformation would insert parameters needed, and remove parameters not needed, in the included controls.

**Comment by wendellpiez** [comment]
The issue I raised here is probably premature and arguably out of scope (until we start dealing with approaches to content creation).

It describes a number of useful validations that could be performed on profiles in reference to the catalogs they call. If performed, these would prevent certain kinds of errors in processing; but we since we do not yet have a scenario for the production of profile data (and many such scenarios are possible), we do not know for certain whether there are actual problems to be solved.

Suggest the Issue be either closed, or labeled to come back to later.

**Comment by david-waltermire-nist** [comment]
Closing this issue an adding this to #400.
