### ISSUE TITLE
Schema documentation enhancements

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#387]
# User Story:

Current schema docs are not yet perfect. There are some useful bits of information missing.

**For example, they do not clearly indicate where and when text is permitted (for example, in fields).**

Examples will also help.

## Goals:

Improve the schema docs with features such as the above, along with any other significant features.

## Dependencies:

If we decide to include it, #337 (element maps for navigation) could be folded in.

Alternatively, the scope could be kept narrow to expedite the work.

## Acceptance Criteria

* The next set of enhancements to auto-generated schema documentation has been defined
* A design has been implemented and tested, and a PR is ready

**Comment by wendellpiez** [comment]
We need links from "prose" or for that matter any field permitting mixed content, to say what this means and to link to documentation on the prose model (block or inline). See #357.

**Comment by david-waltermire-nist** [comment]
This is covered by the suite of Metaschema enhancements/refactoring issues recently created. Closing.
