### ISSUE TITLE
Update web site coverage of OSCAL scope.

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#389]
# User Story:

As an OSCAL adopter, I need a clear understanding of what kinds of data OSCAL encoding is good for. In particular, I need to know that (at the lower levels) OSCAL is not intended for full text transcription of documents in general - only of the control portions of catalogs. So the catalog model (for example) is not intended to support (for example) all of NIST SP800-53.

## Goals:

Clarification for ourselves and our users of our intended scope. Help finding others working in neighbor domains to help with problems we do not help with.

The page at https://pages.nist.gov/OSCAL/docs/relations/ requires revision, at least.

## Dependencies:

While I can draft this copy I will need input from others to ensure it is correct.

## Acceptance Criteria

At least the page mentioned has been revised.

**Comment by wendellpiez** [comment]
For some reason the "Relations" page also has an empty side nav.

**Comment by david-waltermire-nist** [comment]
The content for this is in the site under `/OSCAL/docs/relations/`. The team should review these changes.

**Comment by david-waltermire-nist** [comment]
This has been completed in PR #464.
