### ISSUE TITLE
Rectifying ID format in SP800-53 rev4 extraction

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#39]
XML IDs must follow some arcane naming rules inherited from SGML (and shared with HTML). These include rules such as no punctuation apart from `.` and `_`. No brackets, parentheses etc.

Consequently, the auto-extracted SP800-53 (rev4) has some odd ID syntax, where IDs have been interpolated for components (parts) with formal identifiers (**name** properties) such as `SA-15 (4)(a)`. The syntax presently is a very ad-hoc reduction intended only to maintain uniqueness, in this case `s_smm_sa-15.4.a.` because it is sa-15.4.a as a statement subitem inside a subcontrol.

As long as IDs are kept behind the scenes this is okay. But if IDs are to be a "public face" of even granular components inside controls, we could probably develop a better cleaner mapping (which we could install into the current extraction pipeline).

**Comment by anweiss** [comment]
@david-waltermire-nist should this be closed in favor of #218?

**Comment by david-waltermire-nist** [comment]
Yes. Closing.
