### ISSUE TITLE
Small content corrections

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#399]
# User Story:

Two content corrections are required to catalogs and profiles (see #385):

### Rev 4 Catalog

In the rev 4 catalog, where it has (line 1235)

```
<rlink href="NIST_SP-800-53_rev4_catalog.xml" media-type="application/oscal.metaschema+xml"/>
```

The media type should be `application/oscal.catalog+xml`.

### Anywhere `publication-date` is used

Switch the value to a string conformant to an ISO 8601 date-time including Time Zone.

Document this usage in the schema docs until Schematron can be applied to validate it and/or Metaschema can be extended to support `xsd:dateTime`.

For this element (and check on any/all date elements) the requirement should be a valid ISO 8601 value *with time zone expressed*.

## Goals:

Correct errors or lapses as described above.

## Dependencies:

In connection with PR #385, make these changes in the branch `wendellpiez:issue166-ref-refactoring`, permitting it to be merged.

Then, rebase the later branch `issue172-renaming-class-flag` over the merged branch.

## Acceptance Criteria

1. We have consensus on handling dates
1. We have made the changes noted above, and a PR is produced to merge these changes in.

**Comment by david-waltermire-nist** [comment]
This is complete.
