### ISSUE TITLE
Generate examples leveraging OSCAL

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#40]
As a new user of OSCAL, I can quickly find on GitHub simple, well organized and relevant examples of how to represent a control catalog and profile in OSCAL.

Goals:
- Provide a complete catalog for 800.53 rev 4
- Provide examples of FedRAMP [low](https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/482/2016/07/FedRAMP-Low-HHH-Baseline-Controls-2016-05-18.xlsx), [moderate](https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/482/2016/07/FedRAMP-Moderate-HHH-Baseline-Controls-2016-05-18.xlsx) and [high](https://s3.amazonaws.com/sitesusa/wp-content/uploads/sites/482/2016/07/FedRAMP-High-HHH-Baseline-Controls-2016-05-18.xlsx) baselines as catalog profiles based on these linked spreadsheets on FedRAMP.gov
- Develop both XML and JSON representations of the above
- Update documentation to direct visitors to these examples

Acceptance Criteria:
- Complete draft of all examples are provided under an examples folder in GitHub
- All examples validate according to OSCAL schema
- Top level and example readme files are created/updated to point users toward appropriate examples

**Comment by anweiss** [comment]
Can we update this issue to include documenting a general conversion methodology as well? As in, what are the properties of the raw source data that would best map to features 'A', 'B' and 'C' of OSCAL. @wendellpiez essentially taking the approach you've been taking to create the 800-53 and FedRAMP profile examples today and documenting it, but skipping the specifics around XSLT, XProc and other tooling.

**Comment by anweiss** [comment]
@wendellpiez we should revisit https://github.com/usnistgov/OSCAL/issues/40#issuecomment-393993014 and make a new issue tied to it ... it would be great to give folks a general understanding as to how one can go from an original data source to OSCAL ... it also helps to open the door for contributors looking to use the metaschema (or those building external tools) to generate XML and JSON examples but that don't necessarily have knowledge of XSLT and XPath

**Comment by wendellpiez** [comment]
Closing. (a) FedRAMP examples are under control. (b) Detailing conversion strategies is important but out of scope for now.
