### ISSUE TITLE
OSCAL pages - typo on 'Assessors' page.

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#402]
Last bullet on the ( [Assessors](https://pages.nist.gov/OSCAL/learnmore/assessors/) ) page reads:

> Enables mapping standard catalogs of controls and common baselines, to system **implmentations**, reducing the number of assessments required to ensure compliance with multiple frameworks.

The bold word need to read **implementations**.

**Comment by wendellpiez** [comment]
Can fix with #389

**Comment by david-waltermire-nist** [comment]
Fixed.
