### ISSUE TITLE
OSCAL pages - typo on the Roadmap page

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#403]
In the first statement under "The OSCAL approach" section of the page https://pages.nist.gov/OSCAL/learnmore/roadmap/, the word 'invitation' is misspelled.

 _OSCAL is being developed leveraging an incremental and agile approach. Through a series of development sprints, increased value is provided with a focus on an 80% solution (Minimally Viable Product (MVP)) that can be implemented in 20% of the time. OSCAL is a community-driven, NIST-led project, with an open **invition** to the community to participate in the framing and development of OSCAL._

**Comment by wendellpiez** [comment]
Can fix with #389

**Comment by david-waltermire-nist** [comment]
Fixed.
