### ISSUE TITLE
OSCAL pages - typo on Catalog page

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#404]
On the 'Catalogs' page of OSCAL pages, see the page [here](https://pages.nist.gov/OSCAL/resources/examples/catalogs/), the subtitle NIST 800-53, is missing "SP" in the "NIST 800-53".
So, the subtitle should read "NIST **SP** 800-53"

**Comment by wendellpiez** [comment]
Can fix with #389

**Comment by david-waltermire-nist** [comment]
Fixed.
