### ISSUE TITLE
Building out new metaschema features in docs production

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#423]
# User Story:

With other issues (especially #388) we are enhancing the metaschema to support more condensed JSON production.

These features are not yet reflected in the documentation. Especially the JSON-oriented documentation will be impacted.

## Goals:

Align the schema documentation production with the latest metaschema design.

The elements `key` (inside `define-field` and `define-assembly`, replacing the old `@address` attribute) and `value-key` (inside `define-field`) are new.

Any reference in docs to older `@address` functionality (no longer supported) will need rewiring.

## Dependencies:

The Metaschema design must be stable again for this to proceed. Impacted metaschemas (catalog and profile) must be up to date with this design along with their produced artifacts (including XSD and JSON Schema).

## Acceptance Criteria

1. New Metaschema semantics bearing on JSON expression are reflected in schema docs
2. A PR is posted with this work including a fresh run of schema documentation from current best sources.

**Comment by david-waltermire-nist** [comment]
This has been completed in PR #464.
