### ISSUE TITLE
Updating docs production for 'key' and 'value-key' functionality

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#428]
# Describe the bug

We have extended Metaschema with features to support renaming and sometimes promotion of JSON objects. They are "key" and "value-key" as described in the Metaschema XSD and as examples show.

However, the generated documentation does not describe these features or reflect their use. Because the production pipeline is out of synch with the current Metaschema model, it shows holes and lapses.

On the XML side, a key produces an attribute (like a flag), which must be documented - so the key must be documented as a special kind of flag. On the JSON side, both keys and value keys need to be described since they directly affect the JSON representation.

Note that these features may also be redesigned for simplicity but this Issue does not depend on that redesign.

# Who is the bug affecting?

Anyone who tries to read the documentation and understand the data on that basis.

# What is affected by this bug?

Users won't have an accurate understanding of OSCAL features.

# When does this occur?

Anytime the documentation is consulted.

# How do we replicate the issue?

Run the documentation pipeline including schema documentation production.

# Expected behavior (i.e. solution)

At least two informed readers should agree the documentation is complete and accurate with respect to these features.

**Comment by david-waltermire-nist** [comment]
We have addressed most of the issues. More refactoring can happen in Sprint 22.

**Comment by wendellpiez** [comment]
Making progress. Latest is XSD validation to ensure that values to be promoted to keys in the JSON, are distinct within the scope of the parent object (element).

**Comment by david-waltermire-nist** [comment]
This has been completed in PR #464.
