### ISSUE TITLE
Use of numbers as control IDs

### ISSUE THREAD

**Issue by bradh** [usnistgov/OSCAL#434]
I'm converting a set of controls that are numbered (e.g. "0714").

https://github.com/usnistgov/OSCAL/issues/349 suggests that is a common case.

However that isn't valid in the current schema.

```
xmlschema.validators.exceptions.XMLSchemaValidationError: failed validating '0714' with XsdPatternFacets(['[\\i-[:]][\\c-[:]]*']):

Reason: value doesn't match any pattern of ['[\\i-[:]][\\c-[:]]*'].
```

The schema definition `<xs:attribute name="id" type="xs:ID" use="required">` means that it has to be an XSD ID (which is NCName - must start with a character or underscore).

Is that the intent, or can we have something a bit looser?

**Comment by oscalbuilder** [comment]
In the 800-53 examples we use a combination of id and label as follows:

```
<control class="SP800-53" id="ac-1">
         <title>Access Control Policy and Procedures</title>
         <prop name="label">AC-1</prop>
</control>
```
The intent is to use a NCName compatible name for the @id attribute, and the human-readable form as the "label" property.

Could you do something like the following?
```
<control class="SP800-53" id="control-0714">
         <prop name="label">0714</prop>
</control>
```

**Comment by bradh** [comment]
I can do that.
