### ISSUE TITLE
Schema documentation should link to the schema location

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#438]
# User Story:

As an OSCAL schema user, I need to be able to find the XML or JSON schema that corresponds to the [schema documentation](https://pages.nist.gov/OSCAL/docs/schemas/) I am reading.

## Goals:

The Metaschema-based schema documentation generation pipeline needs to allow for a link to the actual schema to be provided in the format-specific schema docs. Ideally, this link can be passed in as a parameter to the documentation generator. This will allow for the CI/CD pipeline to choose a suitable location.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All generated XML and JSON schema documentation created by the CI/CD pipeline include a link to their respective schema.
- [ ] A single PR is approved that contains the above changes.

**Comment by wendellpiez** [comment]
This is presently hard wired to work for catalog and profile schemas (only), both XML and JSON.

To complete this feature request, the dynamic assignment of `$schema-path` in the XSLT `produce-and-run-either-documentor.xsl` should be removed, and the values passed in at runtime instead (in the script `build/ci-cd/generate-model-documentation.sh`).

**Comment by david-waltermire-nist** [comment]
This will be closed once PR #464 is pulled.

**Comment by david-waltermire-nist** [comment]
This has been addressed in PR #464.
