### ISSUE TITLE
Rename reference mechanic in the Metaschema

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#442]
# User Story:

As an OSCAL model developer, I need a clear indicator that a ```flag``` specified in a ```define-field``` or ```define-assembly``` is defined locally or globally. I would also like the feature used to reference global ```define-assembly```, ```define-field```, and ```define-flag``` to be consistent.

## Goals:

- [ ] Rename ```@named``` to ```@ref``` in all ```assembly```, ```field```, and ```flag``` references. Also, use ```@name``` for locally defined ```flag``` elements within a ```define-field``` or ```define-assembly```.
- [ ] Update all XSLTs used to generate schema, documentation, and content converters.

## Dependencies:

#435 is related to this issue.

## Acceptance Criteria

- [ ] All generated XML and JSON schema, content converters, and document generators are updated to reflect these changes.
- [ ] The Metaschema definitions are updated in a way that result in no changes to associated content.
- [ ] [Documentation](https://github.com/usnistgov/OSCAL/blob/master/src/metaschema/readme.md) on the use of Metaschema is updated to fully document use of the ```@ref``` and ```@name``` features.
- [ ] No content is changed as a result of these changes.
- [ ] A single PR is approved that contains the above changes.

**Comment by wendellpiez** [comment]
Done in branch here; https://github.com/wendellpiez/OSCAL/tree/sprint22-metaschema

**Comment by iMichaela** [comment]
## 7/11/2019
This issue and the related ones (noted in #435 ) for the metaschema need to be reviewed together and unitested. However, more unit tests need to be created for the other features.

**Comment by david-waltermire-nist** [comment]
This will be closed once PR #464 is pulled.

**Comment by david-waltermire-nist** [comment]
This has been completed in PR #464.
