### ISSUE TITLE
Search bar misaligned with top-right nav links on website

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#443]
# Describe the bug

The search bar is not aligned with the nav links on the top-right side of the website.

# Who is the bug affecting?

Visitors to the website.

# What is affected by this bug?

Aesthetics are not ideal when viewing the website

# When does this occur?

When viewing the website.

# How do we replicate the issue?

Screenshot below:

<img width="1409" alt="Screen Shot 2019-06-20 at 10 54 36 AM" src="https://user-images.githubusercontent.com/2326106/59858946-dfe91180-9349-11e9-8c06-31c0395d92f0.png">

# Expected behavior (i.e. solution)

The search bar is aligned with the sub-nav text.

**Comment by david-waltermire-nist** [comment]
This is fixed in PR #653 and will be posted once the PR is reviewed.
