### ISSUE TITLE
OSCAL Website Review Findings

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#445]
# Describe the bug
![image](https://user-images.githubusercontent.com/13984545/59957936-9e9d5280-946c-11e9-8021-c2211357c832.png)
![image](https://user-images.githubusercontent.com/13984545/59958175-45372280-9470-11e9-97cb-4c6d3c30e261.png)
![image](https://user-images.githubusercontent.com/13984545/59958280-03a77700-9472-11e9-8221-6a4515f800e4.png)
# Who is the bug affecting?
The website reader may be confused

# What is affected by this bug?
Describe the impact the bug is having.
n/a

# When does this occur?
n/a

# How do we replicate the issue?
n/a

# Expected behavior (i.e. solution)

# Other Comments

**Comment by david-waltermire-nist** [comment]
@iMichaela I reviewed the titles, and from what I can tell the case is consistent. Can you provide some examples of pages that are inconsistent?

I have addressed the rest of your comments. They will be available in PR #464.

**Comment by david-waltermire-nist** [comment]
This has been completed in PR #464.
