### ISSUE TITLE
OSCAL "linting" for the SSP and 'required fields' etc

### ISSUE THREAD

**Issue by aaronlippold** [usnistgov/OSCAL#446]
The idea here would be that we should be able to ensure that some data in the OSCAL yml is 'not nil' or labeled as 'required' etc. 

aka - System Owner, System Categorization etc. or other things etc.

**Comment by david-waltermire-nist** [comment]
In theory, JSON and XML schema can be used to check for this. We may need to enhance the Metaschema to support this type of validation. We already have the capability to support required, but I don't believe we currently check for empty contents.

**Comment by trevor-vaughan** [comment]
You'd have to be able to switch each of these checks off as required since a lot of places might decide that a lot of the information is optional.

**Comment by david-waltermire-nist** [comment]
@trevor-vaughan Would a solution here be to make the key optional and require that the value be non-nil? So if no value can be provided, the key would not be provided. This is the pattern that we have been modeling in most places.

**Comment by david-waltermire-nist** [comment]
The Metaschema work to support this is documented in issue #633.

**Comment by david-waltermire-nist** [comment]
Further work on constraint checking will be addressed in #803, #805, and #856. Closing this issue in favor of these more specific issues.
