### ISSUE TITLE
Additional Metaschema Details in Schema

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#448]
# User Story:

As an OSCAL developer, I would prefer to use the schema rather than the "complete" metaschema for form generation, and to programmatically "know" where to insert new data in the OSCAL structure. 

Most of the metaschema content is available in the generated schema files for this; however, a few additional items are helpful. In particular, it would be very helpful if the schema file provided the following in a machine-readable format:

- clear identification of the OSCAL root element (catalog, profile, ssp, component, etc.)
- the metaschema file description, which is currently only reflected in the schema file as a comment
- separate "formal names" for each field, rather than (or in addition to) being bundled with its description in the "description" field.
- separate "description" for each field rather than (or in addition to) being bundled with the formal name in the "description" field.  

## Goals:

Ensure the requested data elements are generated from the meatadata as machine readable content in the schema files.

## Dependencies:

None.

## Acceptance Criteria

- [x] The OSCAL root element is consistently represented in the generated schema in a machine-readable format
- [x] The metadata file description is consistently represented in the generated schema in a machine-readable format
- [x] Each field's formal name is consistently represented in the generated schema in a machine-readable format
- [x] Each field's description is consistently represented in the generated schema in a machine-readable format

**Comment by wendellpiez** [comment]
Addressed in my **sprint22-metaschema** branch, PR to come.

To review, look at the latest schemas produced from the XSD pipeline.

Follow-on work could include enhancing the documentation injection into the JSON Schema as well. @davidwaltermire and @anweiss any ideas?

**Comment by iMichaela** [comment]
## 7/11/2019
This issue and the related ones (noted in #435 ) for the metaschema need to be reviewed together and unitested. However, more unit tests need to be created for the other features.

**Comment by david-waltermire-nist** [comment]
This will be closed once PR #464 is pulled.

**Comment by david-waltermire-nist** [comment]
This has been completed in PR #464.
