### ISSUE TITLE
Profile Resolution Capability

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#455]
# User Story:

As an OSCAL implementer using catalogs and profiles, I need to perform profile resolution, which is a mechanism that resolves a profile to a stand-alone catalog using the profile's import statements.

Profile resolution can happen in two forms:
1. **Result only**: Any intermediate replacements are lost, and only the final result appears in the catalog.
1. **Result plus Traceability**: All original values and intermediate replacements appear in the catalog as well as the final result. This allows for full traceability back to the source catalog(s), through all intermediate profiles.

## Goals:

Establish a capability, such as an XSLT file, which performs profile resolution. There may be several XSLT files for different scenarios. For example, there may be separate XSLT files for "result only" and "results plus traceability". There may also be separate XSLT files or similar files for each format type (XML, JSON, YAML). 

## Dependencies:

None.

## Acceptance Criteria

For each supported OSCAL format type (XML, JSON, YAML):
- [ ] Ability to resolve a profile with results only.
- [ ] Ability to resolve a profile with results plus traceability.

- [ ] Results must be consistent across formats
- [ ] Capability must flag broken links in import statements

**Comment by brianrufgsa** [comment]
It would be great if this was generated and published as part of our CI/CD pipeline, similar to our validation and conversion capabilities.

**Comment by david-waltermire-nist** [comment]
@brianrufgsa I think I understand `Result Only`, which will create a tailored catalog based on the customizations and selections in the profile. All add and remove actions will be resolved as part of this.

I am not sure that `Result plus Traceability` is entirely possible as (loosely) defined, since the catalog format does not support the constructs defined in a profile. It may be possible to do some of this using properties in the catalog, but we need to do some design work to define how this would be expressed. Can you sketch out a design? or at minimum provide a small example of what you are thinking?

**Comment by brianrufgsa** [comment]
@david-waltermire-nist - I may have miss-understood in conversations with @wendellpiez - I thought OSCAL was designed with the ability to trace back, and that profiles were designed to be resolved either way. Perhaps I read more into those features than intended. 

For practical purposes, if we can only perform profile resolution for "results only", and traceability is achieved by traversing the original links, I can certainly live with it. 

If that is how we achieve traceability, we may want an optional feature in profile resolution that captures the original links used to perform the resolution as a means of preserving the traceability, or we could possibly attach the original profile(s) and catalog(s), including the "root" profile that formed the basis for the resolution.

**Comment by david-waltermire-nist** [comment]
This work has been completed in PR #624.
