### ISSUE TITLE
Documenting declarations model

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#46]
The declarations model, whereby an OSCAL catalog developer can stipulate certain constraints over OSCAL data to be checked (validated) externally, is an optional feature of OSCAL. It remains to be seen whether it will prove to be useful to developers of catalogs or profiles. However, in principle it may be useful, if only as a demonstration of how implementors and developers of OSCAL applications (not to say "users") may wish to structure, regularize and document (expose) controls through the use of external "contracts" (constraint sets) of this form or some other. (Basically, the declarations model represents a way of extension-through-restriction, or subsetting, something achievable in a number of ways.)

Suggestion: we edit `oscal-oscal.xml` to make it clear that OSCAL can be used without the declarations model (that is, without making or using declarations) and that the functionality provided by OSCAL declarations can also be provided by other means. (And indeed that an application might wish for such extra validations in any case since the declarations model doesn't do everything either.)

Also, in explaining the declarations model, examples will be extremely helpful, and we have examples of declarations for all our samples so far, plus `oscal-oscal.xml` itself. The documents describing the mappings of each of the reference documents into OSCAL should also describe how the declarations work in each case.

**Comment by david-waltermire-nist** [comment]
We no longer use the declarations model in OSCAL. We can revisit this later in a new issue.
