### ISSUE TITLE
Profile Group Element Should Match Catalog

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#463]
# User Story:

As an OSCAL Profile Creator, I should be able to carry groups forward from catalogs with the same information. Currently in a profile, the group element has no attributes, and only "call" and "match" elements, leaving no way to carry forward the group class, id or title; nor to assign new ones. A profile grouping has far more value if it can be named.

## Goals:

Expand the profile syntax to allow the group element to have class and id attributes as well as a title element.

## Dependencies:

None

## Acceptance Criteria

- [ ] The metaschema for OSCAL profiles defines @class and @id flags for group, as well as a title field for group.

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
In the profile model, `merge/custom/group` is for making a new grouping of controls selected from catalog(s). Presumably a title, class and id for such a group would also be new. This is different from copying a grouping from a source catalog, which is done by using the profile mechanism `merge/as-is` , which designates that the selected controls should be grouped as they are in the source catalogs.

The solution described here is reasonable, but not a solution for the problem as stated, but rather for a different problem -- that currently, new groupings of controls in a resolved catalog cannot have titles, class assignments or IDs.

We should also document the use of `merge/custom` and `merge/as-is` better to help profile producers.

**Comment by wendellpiez** [comment]
I will move forward with this with help from @david-waltermire-nist on final decisions.

**Comment by iMichaela** [comment]
## 9/5/2019 ##
Issue was implemented and is part of the PR #484, waiting to be reviewed. @wendellpiez will do a sanity check first.

**Comment by wendellpiez** [comment]
In my branch behind PR #484 I am providing for flags `id` and `class` and field `title` to appear on `group` in the profile model.

We can call this done if:
  * This doesn't break the build
  * @david-waltermire-nist agrees we need nothing more on `group` in profile, for now, such as properties or parts. (My own feeling is if you need these, you might be writing a catalog not making a profile of someone else's. But I could be shown to be wrong.)

**Comment by wendellpiez** [comment]
The content model for profile groups now has `(title?, param*, prop*, part*, (group* | call* | match*))`. This is the same as groups in catalog except for `call` or `match` instead of `control`.

I am not sure of the use case for `param` inside profiles, but the patching mechanism permits adding new parameters, so why not here as well, for consistency.

@david-waltermire-nist please review. This is in the `issue-468-364-478-integration` working branch.

**Comment by brianrufgsa** [comment]
@wendellpiez reports the work is complete, and in a branch ready for merge. @brianrufgsa to perform peer review and provide feedback. @david-waltermire-nist still needs to review as well.

**Comment by wendellpiez** [comment]
Here is the branch in my repo: https://github.com/wendellpiez/OSCAL/tree/issue-468-364-478-integration

**Comment by david-waltermire-nist** [comment]
This was completed in PR #492.
