### ISSUE TITLE
Renamed `json-behavior' and 'xml-behavior'

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#467]
# Describe the bug

Presently the metaschema has attributes defined on `group-as` named `json-behavior` and `xml-behavior`. This would be fine except names starting with the characters 'x','m','l' (lower or upper case) are reserved by the XML Recommendation (both version 1.0 and 1.1):

https://www.w3.org/TR/xml/#sec-common-syn
https://www.w3.org/TR/xml11/#sec-common-syn

Effectively, this means the name `xml-behavior` is illegal (like `xml-is-the-best`).
 
# Who is the bug affecting?

Potentially anyone using XML tools with strict conformance will hit an error processing any metaschema using this attribute.

# What is affected by this bug?

Potentially a conformant processor could refuse to process such a document (Draconian error handling). This would not be good.

# When does this occur?

Many tools today appear to ignore this rule but it is still in the formal specifications, so it could emerge unexpectedly.

# Expected behavior (i.e. solution)

Preventing this issue requires renaming `xml-behavior`. For symmetry, renaming `json-behavior` as well.

Potential names include `configure-xml` and `configure-json`.

**Comment by iMichaela** [comment]
## 9/5/2019 ##
Issue was implemented and is part of PR #484. It is waiting for review and approval.

**Comment by wendellpiez** [comment]
For names, we settled on `@in-xml` and `@in-json`, as in `<group-as in-xml="GROUPED"/>`.

**Comment by david-waltermire-nist** [comment]
This was completed in PR #492.
