### ISSUE TITLE
Syntax Modification: control/subcontrol

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#473]
# User Story:

Most OSCAL users treat subcontrols as controls. Each is actually a functional requirement statement. The use of subcontrol clarifies a logical grouping of related controls. Treatment of control and subcontrol is nearly identical in documentation and automation; however, the use of different syntax requires constant adjustment/alignment of the correct reference (control vs. subcontrol). 

We already allow groups within groups, and parts within parts. OSCAL would be simplified, if control enhancements were simply treated as controls within controls, thus replacing the subcontrol element with a nested control element.  

This would also allow any depth of nested controls, similar to the way we allow any depth of nested parts. 

## Goals:

- Simplify OSCAL catalog syntax by allowing "control" within "control", and using this construct instead of "subcontrol". 
- Update all models to remove/replace the subcontrol concept with a similar control concept.
- Update all documentation to remove the concept of a control. Discuss parent and child controls instead.

## Dependencies:

None

## Acceptance Criteria

- [x] Metaschemas are adjusted to allow control within control.
- [x] Metaschemas are adjusted to remove subcontrol.
- [x] 800-53 catalog and associated baselines are adjusted to replace "subcontrol" with "control".
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
The model changes have been merged in PR #476. The documentation changes remain undone.

**Comment by david-waltermire-nist** [comment]
We also need to complete updating the new SSP and component models.

**Comment by iMichaela** [comment]
## 9/5/2019 ##
Issue was implemented and is part of PR #476, waiting for @david-waltermire-nist and @brianrufgsa. Schema documentation needs to be reviewed.

**Comment by wendellpiez** [comment]
Worked through documentation yesterday. References to subcontrols still appear in WIP SSP and Component models, to be resolved. Otherwise things are looking more reasonable. The changes are now in the `issue-468-364-478-integration` working branch.

Suggest we do one more grep for `subcontrol` once the models are stable for this Sprint.

**Comment by david-waltermire-nist** [comment]
This was completed in PR #492.
