### ISSUE TITLE
Add support for date and date-time without timezones

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#480]
# User Story:

As a Metaschema user I may have a need for datatypes not yet supported, including date-time (dateTime) and date, without time zone. We need to add them.

## Goals:

New data types for time and date-time without time zone can be referenced and validated. Unit tests for datatypes demonstrate this support. Sample schemas and data show how they can be used.

## Dependencies:

None known

## Acceptance Criteria

- [ ] New datatypes supporting date and date-time (without requiring time zone) can be demonstrated to work in testing
- [ ] All applicable documentation has been updated including web site docs on datatypes
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Implemented in PR #484, with (light) unit tests.

Incidentally in testing this I discovered JSON Schema regex patterns are not anchored for testing. So all our regexes have start-string `^` and end-string `$` anchors now.

to do: update documentation.

**Comment by wendellpiez** [comment]
FWIW - a time zone is *permitted but not required* on the new 'date' and 'dateTime' types.

**Comment by david-waltermire-nist** [comment]
This was completed in PR #492.
