### ISSUE TITLE
Tidying up naming convention for schema files

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#49]
Would be great to come up with a solid naming convention for schema files. For example, the OSCAL core schemas, `oscal-documented.xsd` and `oscal-working.rnc`, could probably be better named `oscal-core.xsd` and `oscal-core.rnc`.

**Comment by david-waltermire-nist** [comment]
This should follow something close to #105.

**Comment by iMichaela** [comment]
## 5/23/2019
#105 convention is used for the names of the content artifacts, but a convention is needed for the metaschema and schemas and generated tooling.

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #391. Issue #57 will be handled in a separate PR.
