### ISSUE TITLE
Removing placeholder elements for 'prose'

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#495]
# User Story:

Now we have metaschema syntax for controlling the appearance of wrapped or unwrapped groups, specifically `field[@as-type='markup-multiline']`, there are a couple of metaschema constructs we can remove, namely (at least) the fields 'prose', 'note' and any similar.

This will simplify the schemas and make them more intelligible. We can do this anyplace that markup-multline fields appear alone, without siblings of other types.

## Goals:

Remove placeholder constructs such as 'prose' or 'note' from appearing in schema documentation by making them implicit; we do this by making their parents into markup-multiline fields (no longer assemblies) with 'in-xml' set to 'WITH-WRAPPER` (or the equivalent).

## Dependencies:

Double check to see that this can be done without actually affecting the resulting models in XML and JSON

## Acceptance Criteria

- [x] Verify that placeholder dummies have been removed by showing them missing from schema documentation
- [x] Verify that all documents expected to be valid, remain valid against schemas (XSD and JSON)
- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
This was addressed in PR #492.
