### ISSUE TITLE
Build out XSD production unit tests

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#501]
# User Story:

We need to be able to validate XSD production in the same way we are validating JSON Schema production. XSpec may offer an easy way to get this started.

## Goals:

- Ensure Metaschema semantics in XSD production via unit tests, as we are on the JSON side

## Dependencies:

* XSD production is actually a pipeline, starting with metaschema composition. We need to validate it end to end as well as by steps. This will potentially involve some kind of wrapper functions or templates; short term it might be accomplished with document-level rather than template-level matches for the XSpec. (As we have on the JSON side.)
* Examine potentials for running the XSpec tests both inside IDE and from the CL for CI/CD.

## Acceptance Criteria

TBD (2010-10-09)

- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [x] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
PR usnistgov/metaschema#4 added expected XSDs to the unit tests.
