### ISSUE TITLE
Document OSCAL profile resolution

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#509]
# User Story:

As an OSCAL user and developer, I can find reasonably complete and accurate documentation describing how a profile is processed (resolved) against its catalogs to produce a set of controls from that catalog, complete as emended by the profile, and organized as specified.

This documentation can include both the schema docs for the Profile model, and additional documentation such as a walkthrough with examples.

## Goals:

Documentation of profile semantics, including profile resolution (how to represent a profile in the form of a modified catalog), can be found on the web site. Users of OSCAL can see how profile resolution works and confirm their understanding by looking at examples.

## Dependencies:

Insofar as an implementation is useful to test and validate functionality, there is a mutual dependence on #508. Additionally, any unit tests built for that Issue must demonstrate profile semantics as described in the docs.

## Acceptance Criteria

- [ ] At least two knowledgeable project participants have reviewed and approved any new or revised documentation.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Outline / stub docs "top down view" are now here:

https://github.com/wendellpiez/OSCAL/blob/profile-resolution-ng/src/utils/util/resolve/oscal-profile-semantics.md

As a synopsis, this is intended to supplement the schema (reference) docs.

@brianrufgsa I wonder if you would be able to offer critique or assistance? (I plan to continue on this as well.)

@david-waltermire-nist another question is where in the web site this could go.

Also in scope for this issue: reviewing schema docs for consistency.

**Comment by wendellpiez** [comment]
** Oct 24 Progress **

Work on this is proceeding in my repo branch here: https://github.com/wendellpiez/OSCAL/tree/profile-resolution-ng

Planning to meet Tue Oct 28 to plan how to finalize this.

**Comment by wendellpiez** [comment]
Update @david-waltermire-nist there's an XML document with supporting apparatus in my branch, with ~9500 words of draft specification. Apparatus includes authoring CSS plus lightweight XSLT for a couple of different transformations including a preview version. The XML has support for links to unit tests and examples as well as internal cross-references and auto numbering. (Designed with feeding to Hugo in mind fwiw.) If there is any interest, there are also oXygen settings I could make available.

The text is quite far from finished. Mostly, examples must be sketched out and validated. The question of "control identity" has not been discussed.

https://github.com/wendellpiez/OSCAL/tree/profile-resolution-ng/src/specifications/profile-resolution

Happy travels --

**Comment by wendellpiez** [comment]
**Sprint 26 Update Jan 30 2020**

See my repo branch here: https://github.com/wendellpiez/OSCAL/tree/profile-resolution-ng-repaired

This Issue is tightly coupled to #508.  Also there is an end-to-end dependency on #561.

**Comment by smichelotti** [comment]
We'd like to better understand how this profile resolution process is intended to work - and make sure we concretely understand the semantics of the terms "Catalog" and "Profile". When we look at [FedRAMP_HIGH-baseline_profile.json](https://github.com/usnistgov/OSCAL/blob/master/content/fedramp.gov/json/FedRAMP_HIGH-baseline_profile.json) we essentially see a bunch of id-selectors being imported from 2 different **catalogs**. However, when we look at [FedRAMP_HIGH-baseline-resolved-profile_catalog.json](https://github.com/usnistgov/OSCAL/blob/master/content/fedramp.gov/json/FedRAMP_HIGH-baseline-resolved-profile_catalog.json), the document we see basically matches exactly to the schema for a "catalog" - no id-selectors, but we have the control "groups".

This makes the distinction between a "catalog" and a "profile" murky. Is a "profile" a "catalog"? Like a square is a rectangle but a rectangle is not a square. :) 

I *think* I'm interpreting the process to be something like this:

Base **Catalog** (e.g., nist) -> (inherited by) NIST High baseline **Profile** -> (inherited by) some other custom **Profile** -> (produces) final **Catalog** of controls used by SSP

Any clarification provided would be appreciated.

**Comment by wendellpiez** [comment]
Hi Steve,

Exactly. "Resolution" is what we call the transformation that produces a fully-tailored catalog -- controls selected and perhaps modified -- that is represented by a profile.

We intend the semantics of the profile’s representation to be deterministic, so two conformant implementations can reliably produce the same (tailored) catalog from the same profile.

Of course we might wish to tailor (or otherwise reference) not the base catalog but a tailored catalog at some level (not SP800-53 nor even the NIST HIGH baseline, but maybe a baseline made from that) – which indeed, can take the form of a profile. OSCAL supports this by stipulating that a profile can import a profile in the same way as it imports a catalog, by applying the resolution rules to it. The semantics are designed to be the same – the importing profile sees a full “catalog” at the other end of the import, because it sees what the resolver gives it (a catalog). A resolver may “cascade” to do this -- resolving an imported profile into a catalog so that it can resolve the profile that has imported it, etc. It should make no difference functionally if a profile imports a profile, or imports the catalog (a catalog baseline published explicitly as a catalog) that is produced by resolving that profile.

Yet in practice we expect it will be useful to cache and perhaps reference the intermediate results, which is why we have also published the profiles in resolved (catalog) form. This also helps to stopgap the problem that profile resolvers are not exactly ubiquitous. Indeed we are just getting to the point where we can properly test our own. This is necessary to test the specification as well as demonstrated the concept, of course – so we are also working on unit tests.

At you imply on Issue #567, however, the exact representation and semantics of this referencing are not fully baked. I wonder if a specialized URI protocol or some analogous notation (maybe even an alternative to plain `href` that means "traverse but also resolve", would not be helpful and even necessary at some level.
