### ISSUE TITLE
Remove 'part' from profile 'set' (parameter)

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#519]
# Describe the bug

`set` inside the profile model is used to set parameters, which is done by a combination of overwriting (labels and values) or supplementing the parameter description (with constraints, guidelines or remarks) as given in a catalog.

Currently it permits `part`, which cannot be resolved into a valid catalog since (unlike siblings) `part` is not valid inside the catalog `param`.

Without a use case, we don't need `part` inside `profile/modify/set`. It should be removed.

# Who is the bug affecting?

Potentially, anyone who tries to use this element only to be disappointed.

# What is affected by this bug?

Profile resolution semantics.

# Expected behavior (i.e. solution)

Let's remove `part` from the profile model's definition of `set`.

# Other Comments

While this change is not formally backward-compatible, we have no data that uses the element we plan to remove. So it should be innocuous and have no effect as long as we do it soon.

**Comment by wendellpiez** [comment]
Made this change in PR #516 please review

**Comment by david-waltermire-nist** [comment]
This was addressed in PR #516.
