### ISSUE TITLE
Placement of loose parameters in profile resolution

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#523]
# Describe the bug

Valid catalogs cannot now be produced from profiles with 'loose' parameters, under the "no merge" rule (everything comes out flat), because the catalog model does not permit parameters to appear at the top. This means that profile resolution cannot work in some cases.

# How do we replicate the issue?

1. A catalog contains a parameter not inside a control.
1. A profile without a merge instruction (so, "no merge") calls a control containing an `insert` instruction referencing this parameter.
1. The catalog resulting from profile resolution contains controls at the top level, ungrouped. But a parameter placed next to or before the controls, is invalid.

# Expected behavior (i.e. solution)

Either of two possible solutions:

* Extend the catalog model to permit `param` to appear wherever `control` appears. (The only place it is now missing is at the top, as a child of `catalog` directly after `metadata`.)
* Or - remove `control` from the top level of `catalog` and require there be at least one group.

The advantage of the second solution is that by requiring a group, we have a way of dealing with sibling imports -- they can go into separate groups even under "no merge"). A disadvantage is that it is not obvious why a group should always be required ... docs could say that this is so that parameters always have a place to live....

**Comment by wendellpiez** [comment]
Currently implementing profile resolution, I need to emit valid catalogs potentially with loose parameters (outside controls).

This argues perhaps the best solution here is to change the catalog model (leaving out metadata and back matter) from `(group* | control*)` to `(param*, control*, group*)`. This is a backward-compatible change.

**Comment by david-waltermire-nist** [comment]
@wendellpiez Can you make this change in PR #559 with regards to issue #508?

**Comment by wendellpiez** [comment]
Yes, now rolled in to PR #559. When it is merged this Issue can be closed.

**Comment by david-waltermire-nist** [comment]
Will close this when PR #559 is completed.

**Comment by wendellpiez** [comment]
**Sprint 26 Update Jan 30 2020**

If the catalog metaschema has changed in another branch, there might be a merge conflict with PR #559. Fortunately the change is small and should be okay to manage.
