### ISSUE TITLE
Qualifying IDs in profiles referencing catalogs

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#524]
# User Story:

Presently, an assumption is made that if a profile imports more than one catalog, the IDs for controls and parameters in each catalog are distinct, except for the case that "the same" control is being called more than once, for example in a profile that calls another profile calling a catalog, along with a separate call to the same catalog. Under merge combine[@method='merge']. this is not an error.

However, this presents an issue when more than one catalog is called and the controls are actually distinct, despite clashing IDs, and should not be considered "the same" for merging purposes.

Parameters, which are referenced using their IDs, present similar issues.

## Goals:

Sketch out use cases and a solution for IDs clashing across distinct catalogs. Some kind of scope-definition for ID matching is called for, either optional or mandatory. One class of solutions offers a feature to support this, without requiring its use in cases where (for example) a single 'base' catalog is called.

## Dependencies:

Profile resolution must be stable and functional enough to demonstrate and test the problem and possible solutions. (#508.)

This task also has implications for the Profile Resolution Spec (#509).

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
I think this Issue duplicates #538.

**Comment by david-waltermire-nist** [comment]
Closing the duplicate.
