### ISSUE TITLE
Should `control-id` be required on `call`?

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#527]
# Describe the bug

In profile documents, element `call` is used in include and exclude directives to identify  controls by their IDs.

But the `control-id` flag is optional on `call`. Should it be required? By definition, the element must be a no-op without it.

# Proposed remedy

Make `control-id` required on `call`. This change is not formally backward compatible but we have no data that will break, either. And data that exercises the option to omit `control-id` is arguably in error.

**Comment by bradh** [comment]
Looks like this was fixed as part of https://github.com/usnistgov/OSCAL/pull/516 

Recommend closure if @wendellpiez concurs.

**Comment by wendellpiez** [comment]
LGTM
