### ISSUE TITLE
Review in-xml wrapper settings on (all) markup-multiline elements

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#528]
# Describe the bug

In the SSP XML schema map, the first field under <authorization-boundary> should appear like this:
```
      <authorization-boundary>
         **<description>Markup multiline</description>**
         <prop name="NCName" id="string" ns="string" class="NCName">string</prop>
      </authorization-boundary>
```
Instead it appears like this, without the <description> tag around the Markup multiline annotation:
```
      <authorization-boundary>
         **Markup multiline**
         <prop name="NCName" id="string" ns="string" class="NCName">string</prop>
      </authorization-boundary>
```
# Who is the bug affecting?
Everyone who relies on this documentation for correct OSCAL XML SSP syntax.

# What is affected by this bug?

Documents will be rendered incorrectly.
Also, it creates a discrepancy between what is published here and what is published in the SSP XML Schema Reference.

# When does this occur?

It was generated and published this way by the CI/CD pipeline's automated mechanisms.

# How do we replicate the issue?

{What are the steps to reproduce the behavior?
1. Visit this link: [https://pages.nist.gov/OSCAL/documentation/schema/ssp/xml-model-map/](https://pages.nist.gov/OSCAL/documentation/schema/ssp/xml-model-map/)
1. Look for the <authorization-boundary> tag under the <system-characteristics> section of the model map.
1. Observe "Markup multiline" without enclosing <description> tags.

Screenshot: 
![Annotation 2019-11-03 142817](https://user-images.githubusercontent.com/28259895/68090816-62302900-fe46-11e9-90b1-14ae4c5695fa.png)

# Expected behavior (i.e. solution)

This should appear as &lt;description&gt;Markup multiline&lt;/description&gt;

# Other Comments
None

**Comment by brianrufgsa** [comment]
Discovered the same issue with the <remarks> element at the end of <metadata> while looking at the XML SSP Schema Map.

**Comment by wendellpiez** [comment]
@brianrufgsa and @david-waltermire-nist this appears to be happening because `description` is not marked everywhere in the SSP schema as `in-xml='WITH-WRAPPER`. At present, the default handling is to unwrap a markup-multiline field. Where it is not marked to be wrapped, it doesn't get an element.

We can query the metaschema and repair those places where it should have this setting, but doesn't.

We can also consider changing the default behavior (which we have discussed in the past), as well as adding a check to the Metaschema Schematron to detect when the 'in-xml' handling on markup multiline fields is consistent. To address this compehensively, we probably also need to confirm that this feature is properly implemented in the XML schema (unit tests).

**Comment by wendellpiez** [comment]
Suggest this Issue be combined with #478. Essentially what is called for is a review of all markup-multiline fields to ensure they have wrapping set properly in the XML (for usability and consistency).

**Comment by david-waltermire-nist** [comment]
Here is an XPath that can find all cases of this: `//define-field[@as-type =  'markup-multiline' and (empty(@in-xml) or @in-xml  = 'UNWRAPPED')]`. We need to audit where this is occuring and fix the cases where with should be set to `@in-xml="WITH_WRAPPER`.

**Comment by david-waltermire-nist** [comment]
@wendellpiez Will write a XQuery to find the model locations where this issue is present. We can use the list generated from this query to discuss where we need to make changes.

**Comment by wendellpiez** [comment]
Determined that this could be done in XPath after all, which is better since it delivers pointers to the locations, not just copies (XPath 2.0):

```
for $n in (//define-field[@as-type='markup-multiline']/@name)
return //field[@ref=$n]
```

NB: best when run over composed metaschema instances.
