### ISSUE TITLE
Define a machine-readable framework format

### ISSUE THREAD

**Issue by kscarfone** [usnistgov/OSCAL#53]
As a content or tool developer, I can define frameworks in a common machine-readable OSCAL format.

Required Resources:
- Two frameworks in machine-ingestible formats (e.g., NIST CSF text, PCI DSS text)

Goals:
1. Create an OSCAL instance document for two frameworks.
2. Create XSD for framework content validation purposes.
3. Create Schematron to validate framework-specific requirements.
4. Create CSS/XSLT for human readability and data entry.
5. Test both frameworks using the CSS for data entry into oXygen using Author mode.

Acceptance Criteria:
1. Validate that the OSCAL instance documents have been created as defined in Goal 1.
2. Validate that all framework information from the sources was transformed (no loss of information).
3. Validate that all information types common to both frameworks are formatted the same way.
4. Evaluate Schematron to ensure framework-specific requirements have been included.
5. Evaluate CSS/XSLT for human readability/data entry.
6. Validate that textboxes, pick lists, etc. work as defined in the oXygen interface.

**Comment by aj-stein-nist** [comment]
Is this still needed? The goals and AC here sound like the core requirements of `catalog` and `profile` designs. They are largely stable. This is very broad in scope, even as an epic, so it is not clear if there is remaining work to do here.

**Comment by aj-stein-nist** [comment]
As discussed when I first joined, this appears to be obsolete and covers original project requirements. I will close for now and open if it needs to be revisited.
