### ISSUE TITLE
Should method and status prop names be part of control?

### ISSUE THREAD

**Issue by bradh** [usnistgov/OSCAL#541]
https://pages.nist.gov/OSCAL/documentation/schema/catalog/xml-schema/#prop shows examples for `prop` `name` values that have semantics that are heavily `control` oriented:

> method: An assessment method.
>  status: The status of a control. For example, a value of 'Withdrawn' can indicate that the control has been withdrawn and should no longer be used

Those are syntactically valid inside any of `part`, `metadata`, `party`, `person`, `org`, `resource`, `role`, `responsible-party`, `citation` and `group` as well as `control`. That is messy - what would the meaning of an assessment method be for `metadata` or `role`? 

I think it could be clearer if those were removed as valid values for `prop` and made elements under `control`, something like:

```xml
   <xs:element name="control">
      <xs:annotation>...</xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="oscal-catalog:title" minOccurs="1" maxOccurs="1"/>
+            <xs:element ref="oscal-catalog:status" minOccurs="0" maxOccurs="1"/>
+            <xs:element ref="oscal-catalog:method" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="oscal-catalog:param" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="oscal-catalog:prop" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="oscal-catalog:link" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="oscal-catalog:part" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="oscal-catalog:control" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
```

**Comment by wendellpiez** [comment]
As I understand it, the work we plan on extra-schema constraint definition and enforcement will enable a better approach to this. So, for example, permissible values for `prop/@name` could be different for `control/prop`, `metadata/prop`, etc.

This is not the solution proposed but it would help to relieve the problem. Unfortunately I'm afraid there is no absolutely perfect answer, just a best balance among tradeoffs.
