### ISSUE TITLE
In the schema map, attributes are not linked to parent

### ISSUE THREAD

**Issue by bradh** [usnistgov/OSCAL#549]
# Describe the bug

See https://pages.nist.gov/OSCAL/documentation/schema/catalog/xml-schema/#oscal-catalog-xml_name for an example - note the `This attribute appears on: .` part. That should provide the list of elements that the attribute applies to.

# Who is the bug affecting?

Users of the schema map.

# What is affected by this bug?

Documentation / situational understanding.

# When does this occur?

Always.

# How do we replicate the issue?

See above.
# Expected behavior (i.e. solution)

Attributes in the docs pages include the parent element, ideally "hot-linked".

# Other Comments

Relatively low priority - by the time you're looking at an attribute, you've probably already found the relevant parent.

**Comment by wendellpiez** [comment]
This was working in the past. A repair will probably follow easily on a diagnosis of why it is happening now.

**Comment by bradh** [comment]
I backed out https://github.com/usnistgov/OSCAL/commit/84fc96278c3c69acb1ba7cb506dc08894f0d6f54 and that gave me back the links. However it obviously results in duplicate entries.

**Comment by wendellpiez** [comment]
Thanks @bradh for sniffing this out it will be helpful.

**Comment by wendellpiez** [comment]
So #560 is the PR to correct this.

**Comment by david-waltermire-nist** [comment]
The fix for this has been merged and verified. Closing.
