### ISSUE TITLE
Add documentation for recognized part names

### ISSUE THREAD

**Issue by bradh** [usnistgov/OSCAL#550]
# User Story:

As an OSCAL producer or consumer, I want to know what the "recognized names" for the `name` within a `part` are, so that I can used shared understanding, or know if I need to add a `ns`.

The documentation for `name` includes:
> The definition of a name is subject to its namespace, offered by an ns flag (q.v.). When ns is not given, the namespace is assumed to be "oscal" and the name should be one of the recognized values for names in OSCAL.

However I don't see what the "recognized values" are.

## Goals:

Update the documentation to include those recognized values - link to this part of the documentation, if (already) included somewhere else.

As a possible enhancement, add validation checks that either the name is one of the recognized values, or a distinct `ns` is provided for the `part`.

## Dependencies:

None identified.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by bradh** [comment]
From : `$ ack --no-filename \<part content/nist.gov/SP800-53/rev4/xml/*.xml | ack -v party | cut -d \" -f 2,4 | rev | cut -d \" -f 1 | rev | sort | uniq` I see:

>assessment
guidance
item
objective
objects
statement

"objects" appears to be only used within "assessment" for identifying parts of the assessment process. That might be less than ideal for the "INTERVIEW" part, where we're talking about groups of people.

Similarly, "item" appears to be only used within "statement" for identifying sub- (and sub-sub-) parts of the control requirement.

"objective" appears to be used for higher level outcome goals (including within other "objective" `part`s). Distinction between "statement" and "objective" isn't yet clear.

"guidance" is used for informative ("scene setting" or background) text.

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #758.
