### ISSUE TITLE
Data types for control id and profile call control-id don't match 

### ISSUE THREAD

**Issue by bradh** [usnistgov/OSCAL#551]
# Describe the bug

https://pages.nist.gov/OSCAL/documentation/schema/profile/xml-schema/#control-id says:
> Value of the 'id' flag on a target control
An attribute (NCName)

https://pages.nist.gov/OSCAL/documentation/schema/catalog/xml-schema/#oscal-catalog-xml_control says:
> The control element has the following contents (in order):
> - id attribute (string) [required]

# Who is the bug affecting?

Probably only tool makers, possibly profile writers. Limited impact because control id used to be a NCName.

# What is affected by this bug?

Not known.

# When does this occur?
Always

# How do we replicate the issue?

See above.

# Expected behavior (i.e. solution)

Update `profile` `call` `control-id` to be a `string` instead of an `NCName`.

**Comment by bradh** [comment]
https://pages.nist.gov/OSCAL/documentation/schema/component/xml-schema/#implemented-requirement says:
> control-id attribute (NCName) [optional]

So it looks like the same problem might exist between the component `implemented-requirement` `control-id` type and the `control` `id` type.

**Comment by wendellpiez** [comment]
@david-waltermire-nist possibly these have fallen between the cracks since we have planned to remove traces of DTD-legacy, but not actually done so comprehensively?

In any case, we could perform a survey of datatypes top-down to put this issue to bed.
