### ISSUE TITLE
Clarify published / version vs last-modified in metadata

### ISSUE THREAD

**Issue by bradh** [usnistgov/OSCAL#552]
# User Story:

As an OSCAL producer or consumer, I would like clearer definition of what the differences between `published`, `version` and `last-modified` in metadata are. 

## Goals:

Make it clear that:
> Published and Version are intended to be formal published and version numbers synonymous with a document version and publication date. 

## Dependencies:

Nil identified

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
@bradh Here are the documented semantics for these elements:

- published: The date and time this document was published. [definition](https://pages.nist.gov/OSCAL/documentation/schema/catalog/xml-schema/#oscal-catalog-xml_published)

  > This value represents the point in time when the OSCAL document was published. The date value must be an ISO 8601 formatted date with full time and time zone indicated. Ordinarily, a date value will be machine generated at time of creation or modification.

  > In some cases, an OSCAL document may be derived from some source material in a different format. In such a case, the last-modified-date value should indicate the modification time of the OSCAL document, not the source material. (The nominal publication date of the original source material can be captured as a named property or custom metadata construct.)

     > A publisher of OSCAL content can use this data point along with its sibling last-modified to establish commonality across OSCAL instances that are intended to be considered as successive "current versions" of a given publication.

- last-modified: Date and time of last modification.  [definition](https://pages.nist.gov/OSCAL/documentation/schema/catalog/xml-schema/#oscal-catalog-xml_last-modified)

  > This value represents the point in time when the OSCAL document was last updated. The date value must be an ISO 8601 formatted date with full time and time zone indicated. Ordinarily, a date value will be machine generated at time of creation or modification.

  > In some cases, an OSCAL document may be derived from some source material in a different format. In such a case, the last-modified value should indicate the modification time of the OSCAL document, not the source material.

- version: The version of the document content. [definition](https://pages.nist.gov/OSCAL/documentation/schema/catalog/xml-schema/#oscal-catalog-xml_version)

  > A string indicating the document's version, by release number, date, or other identifier. This version is typically set by the document owner or by the tool used to maintain the content.

Can you help me understand where we need to clarify the meaning? Is there specific text that is confusing or unclear?

**Comment by david-waltermire-nist** [comment]
This is addressed by PR ##614.
