### ISSUE TITLE
Stand up unit testing for profile resolution

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#561]
# User Story:

Profile resolution - specification and a prototype implementation for testing -- is nearing completion: see Issues #508 and #509. But this and any implementation needs to be tested. The branch for current WIP is here: https://github.com/wendellpiez/OSCAL/tree/profile-resolution-ng-repaired

A set of files for testing is also under development in that branch:
https://github.com/wendellpiez/OSCAL/tree/profile-resolution-ng-repaired/src/specifications/profile-resolution/profile-resolution-examples. In addition to a pile of test files, there are subdirectories:
* `catalogs` contains catalogs used in the examples
* `output-expected`, containing the expected (catalog) results of profile resolution of all examples
* `output-actual`, where results of a profile resolution runtime can be written

This needs to be built out and provided with logic so that the unit tests can be run under CI/CD. The testing logic can be the same as we are using to test other XSLT-based transformations, such as schema generation: run the transformation, compare the results to a set of expected results, and report significant differences between them.

## Goals:

We need to be able to run a common set of unit tests for profile resolution
  * from a command line
  * also in CI/CD
  * which is easily configurable for testing new profile resolvers
  * and has a rational and intelligible file arrangement / directory structure for long-term maintenance of the test suite

These can use the scripting for the schema-generation unit testing as a basis.

Passing the unit tests is *not* a goal for this Issue. Neither is an exhaustive set of unit tests.

## Dependencies:

None currently. The implementation of profile resolution in its working branch (linked above) is mature enough to test.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.
- [ ] The repo has been cleaned up and resources we no longer need for testing have been removed - see for example `src/content/mini-testing`.
- [ ] Further Issues have been created, as necessary, for further development and validation of unit tests for profile resolution.

**Comment by david-waltermire-nist** [comment]
Talked with @wendellpiez and the script will need to do the following:

1. For a given profile in src/specifications/profile-resolution/profile-resolution-examples, run src/utils/util/resolver-pipeline/oscal-profile-RESOLVE.xsl using XSLT to generate a temp resolved catalog
1. Validate the temp resolved catalog as a valid catalog.
1. Compare the temp resolved catalog against the similar named catalog in src/specifications/profile-resolution/profile-resolution-examples/output-expected. Append the "_RESOLVED" suffix.

**Comment by david-waltermire-nist** [comment]
This work was slated for [Sprint 26](https://github.com/usnistgov/OSCAL/projects/25), but the other metaschema-related refactoring of the build process was a dependency. This work will be done in [Sprint 27](https://github.com/usnistgov/OSCAL/projects/26) instead.

**Comment by wendellpiez** [comment]
**March 12 Update**

Still pending integration work.
