### ISSUE TITLE
Rename set-param in SSP model

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#568]
# Describe the bug

An element `set-param` is defined in the SSP schema.

Probably it is meant to be the same as `set` in the Profile schema.

# Who is the bug affecting?

Anyone developing to the tag set who may be confused.

# What is affected by this bug?

Implementations are more complex and bug-prone when models show this kind of inconsistency.

# Expected behavior (i.e. solution)

Assuming they are both the same, both elements should be named `set`. And maybe even if they are not perfectly the same, if their semantics are very close.

# Other Comments

Other issues tracing possible changes to SSP Metaschema: #333, #535

**Comment by wendellpiez** [comment]
See note to PR #609, tracking this issue. After discussion, we are naming the element `set-parameter` in both profile and SSP models, with `parameter-settings` as a group name.

**Comment by wendellpiez** [comment]
I am committing the changed metaschemas. However this commit will break the build until the data catches up.

I also have an XSLT transformation, which when applied to the data, will update it by changing `set` to `set-parameter` in XML source. It will also (isn't this best practice?) update the document ID with a new UUID identifier as well as a new timestamp (tested in SaxonHE):

[oscal-update-issue568.zip](https://github.com/usnistgov/OSCAL/files/4110850/oscal-update-issue568.zip)

To make a clean build, either I need to run this and update the affected files; or someone else must run this (or do the same task by other means) and provide me with the results to patch in; or they need to provide me with a PR to accept with the modifications in place. Let me know what works best.

**Comment by wendellpiez** [comment]
@david-waltermire-nist before we close this, it occurred to me ... we should be sure to spin off the Issue(s) we will need for propagating recent model changes, including settling on `set-parameter` as well as changes to back matter (folding `citation` into `resource` #612), into downstream processing.

Specifically, profile resolution and rendering /production pathways will both be impacted by these changes. It will make a good test of the integrity of our validation stack in the unit tests.

**Comment by david-waltermire-nist** [comment]
This has been addressed by PR #609.
