### ISSUE TITLE
Should we move resources to be before use?

### ISSUE THREAD

**Issue by bradh** [usnistgov/OSCAL#578]
As of milestone-2, we have the option of the target of a resource link to be defined after its used. For example, in profile resolution, you can have something that looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<profile xmlns="http://csrc.nist.gov/ns/oscal/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://csrc.nist.gov/ns/oscal/1.0 ../../../../xml/schema/oscal_profile_schema.xsd"
    id="base2-test_profile">
    <!-- Like base-test_profile, except references the catalog in a resource.   -->
    <metadata>
...
    </metadata>
    <import href="#catalog">
....
    </import>
    <back-matter>
        <resource id="catalog">
            <rlink href="abc-simple_catalog.xml"/>
        </resource>
    </back-matter>
</profile>
```

That is obviously a trivial example, but it demonstrates that you need to parse the whole file to find out what `#catalog` is pointing to.

It might be cleaner if the references had to occur before use. This probably means moving `resource` out of `back-matter` or moving / renaming `back-matter`.

I'm not sure if I want this to apply only to `resource` - maybe citations should still be at the end?

**Comment by wendellpiez** [comment]
I am afraid this is one of those rules that does not relieve a burden so much as move it from one set of constituents (in this case, developers who must incur parsing overhead) to another (in this case users who must understand, follow and enforce the rule). It would probably also seem like more of a problem to me if there were not plenty of ways one could  run into this - after all, not only resources and citations, but also controls can be targets of cross-references, effectively requiring random access to entire documents.

Indeed we currently have no rule that says a parameter must be declared before it is referenced for insertion. (Does this make the problem worse not better?) An argument can be made that not constraining this ordering is a feature, not a bug.

**Comment by bradh** [comment]
I can see that. Happy to leave it the way it is for now.
