### ISSUE TITLE
In component implemented-requirement, what is requirement-id for?

### ISSUE THREAD

**Issue by bradh** [usnistgov/OSCAL#584]
[`implemented-requirement`](https://pages.nist.gov/OSCAL/documentation/schema/component/xml-schema/#implemented-requirement) has a `requirement-id` attribute and a `control-id` attribute (among other attributes and elements). 
> requirement-id attribute (NCName) [optional] A reference to a requirement defined on another requirement set that should be included here.

and

> control-id attribute (NCName) [optional]

`implemented-requirement` appears inside [`can-meet-requirement-set`](https://pages.nist.gov/OSCAL/documentation/schema/component/xml-schema/#can-meet-requirement-set), which:
> Defines what sets of controls are supported by the component.

I think I'm having trouble understanding what a `requirement-id` would be if it isn't a reference to a control.

**Comment by david-waltermire-nist** [comment]
@bradh This syntax is outdated and needs to be synced with the structures in the SSP model. I believe it was a way to reference a previously defined set of requirements by id.
