### ISSUE TITLE
SAP, SAR and PO&M Information Inventory

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#588]
# User Story:

As an OSCAL syntax modeler, I need to quantify the information needs of a security assessment plan (SAP), security assessment report (SAR), and plan of actions and milestones (POA&M), so that I can create preliminary OSCAL syntax for these artifacts.

## Goals:

- Review and analyze the FedRAMP SAP, SAR, and POA&M, including attachments, such as the Test Case Workbook. 
- Create an inventory of the data elements in the above artifacts.
- Where data elements appear in more than one artifact or in other portions of the OSCAL stack, clarify the one "source of truth" for each data element, and the intended path for reaching that element from other OSCAL layers.

## Dependencies:

None.

## Acceptance Criteria

_As this is a planning and analysis activity, it should not result in changes to the OSCAL web site or CI/CD pipeline, nor should it result in any pull requests. Follow-up tasks will result in those activities._
- [N/A] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ N/A] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ N/A] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

- [x] All data elements in the SAP, SAR, and POA&M are identified in the inventory.
- [x] All identified elements have a defined carnality.
- [x] All identified elements have a defined data type.
- [x] All identified data elements have a clear "source of truth".
- [x] The inventory is sufficient to commence modeling using the OSCAL metaschema in a follow-up activity.

**Comment by brianrufgsa** [comment]
## 16-Jan-2020 Status:
Have performed a first-pass analysis on the Initial SAP and Annual SAP templates, and am about 90% finished going through the initial SAR template. 
[_Analysis-DRAFT-03.xlsx](https://github.com/usnistgov/OSCAL/files/4072080/_Analysis-DRAFT-03.xlsx)


## Up next 
is to finish the Initial SAR, then move on to the Annual SAR and the POA&M.
Although there are different versions of the SAP and SAR templates, there will be only one SAP model and one SAR model. Each model will handle both the initial and annual versions of those templates.

Once this pass of the analysis is complete, I will mock up three models in YAML,

**Comment by brianrufgsa** [comment]
# 23-Jan-2020 Status:
Finished analyzing Initial SAR, Annual SAR and a newly discovered Draft Combined SAR Template (which is still pending JAB Review). Currently analyzing POA&M, including deviation requests.

# Up next:
Mock up SAP, SAR, and POA&M syntax in YAML. Create diagrams to illustrate organization and relationships.

**Comment by david-waltermire-nist** [comment]
@brianrufgsa Where do I find your latest analysis? Maybe provide a link to a google sheet, which will be a permanent link to the latest?

**Comment by brianrufgsa** [comment]
Snapshot as of today, while I try to find a better sharing solution.
[_Analysis-DRAFT-05.xlsx](https://github.com/usnistgov/OSCAL/files/4103777/_Analysis-DRAFT-05.xlsx)

**Comment by brianrufgsa** [comment]
# 30-Jan-2020 Status:
Have a complete information inventory of the following FedRAMP Templates:
- Initial SAP
- Annual SAP
- Initial SAR
- Annual SAR
- DRAFT Combined SAR
- POA&M
- Deviation Request Form (FP, OR, and RA)

By COB today, I should be finished identifying source model for each, and make a recommendation as to whether each should be part of core OSCAL or is a FedRAMP extension.

**Comment by brianrufgsa** [comment]
# 6-Feb-2020 Status:
Completed information inventory, including cardinality and data type.
Identified the source model for each item in the inventory and made recommendations as to which belong in the core OSCAL syntax or as a FedRAMP extension. 

### NOTE: The assignment of core OSCAL syntax or FedRAMP extension will be revisited several times during this process. Some assignments may change. 

### This issue is complete and should be closed.

**Comment by david-waltermire-nist** [comment]
This work has been completed and is available in the `INFORMATION INVENTORY` link above. Closing.
