### ISSUE TITLE
Develop Tutorial #2: Creating a simple OSCAL profile

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#593]
# User Story:

As an OSCAL content developer, I need a clear and concise tutorial that illustrates how I can create a simple OSCAL profile based on the catalog produced in tutorial #1
## Goals:

Document how to generate an OSCAL profile by generating a simple example of a baseline based on the catalog produced in tutorial #1 while explaining, in the process, the syntax.

## Dependencies:

none

## Acceptance Criteria

- [ ] The tutorial is clear and concise.
- [ ] The example is representative, covering the most significant syntax.

**Comment by bradh** [comment]
I'd like to see this incorporated into the CI flow, including validation of the example output(s). That will ensure it says up to date as the schema evolves. Common for #592, #593, #594.

**Comment by wendellpiez** [comment]
**Update March 12**

Work is proceeding along with #592 (now to be reviewed).

**Comment by david-waltermire-nist** [comment]
The scope of the profile tutorial will be focused on control selection only. The following scenarios will be covered:

- Selecting all controls in the catalog.
- Selecting specific controls (1 or two) from the catalog. Should demonstrate include and exclude.

**Comment by iMichaela** [comment]
## 03/26/2020
Profile tutorials for select all controls and select specific controls were created - see PR #626.
I will review soon the Profile files and tutorials to make sure they are free of typos and errors.

**Comment by david-waltermire-nist** [comment]
Will continue this work in #645.
