### ISSUE TITLE
Merge Citation with Resource in Back Matter

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#612]
# User Story:

This was discussed in #587. Opening a separate issue to provide better transparency and tracking.

As an OSCAL content creator, I find ```citation``` and ```resource``` to be similar enough that they can be merged into a single assembly.

## Goals:

Simplify the OSCAL syntax by expanding the ```resource``` assembly, such that it can also serve to capture citations, thus eliminating the need for a separate ```citation``` assembly.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.
- [ ] I am able to model citations using the resource assembly.

**Comment by brianrufgsa** [comment]
# Examples from FedRAMP
To meet FedRAMP's needs, I added extensions to ```citation``` and ```resource```. Some may be useful as we merge these two assemblies.

To citation, I added the following ```prop name=""``` extensions:
- **publication**: Publication date
- **version**: Version number
- **type**: Document Type (law, regulation, standard, guidance, pii)

The above enabled me to fully model SSP Table 12-1 Laws and Regulations, as well as SSP Table 12-2 Standards and Guidance. Both tables have the following columns:
- Identification Number
- Title
- Date
- Link

To resource I added the following ```prop name=""``` extensions:
- **title**: Document Title
- **publication**: Publication date
- **version**: Version number
- **type**: Document Type (policy, procedure, guide, pia, rob, plan)

This enabled me to fully address various attachments needs for FedRAMP. For example, multiple policies are typically attached, and it helpful to differentiate policy attachments from other attachments when reviewing. Likewise for procedures and plans.

# If we were to merge
Title already existed in citation. I needed to add it to resource.
The other three extensions are identical for both (version, publication, and type).

# Recommendation
I believe a complete OSCAL resource assembly (after merging with citation) should look something like this:
```
<resource id="NCName">
   <title>markup-line</title> [0 or 1]
   <published>dateTime-with-timezone</published> [0 or 1]
   <version>string</version> [0 or 1]
   <descr>string</desc> [0 or 1]
   <doc-id type="string">string</doc-id> [0 to ∞]
   <prop name="NCName" id="NCName" ns="string" class="NCName">string</prop> [0 to ∞]
   <rlink href="uri-reference" media-type="string"> [0 to ∞]
      <hash algorithm="string">string</hash> [0 to ∞]
   </rlink>
   <base64 filename="uri-reference" media-type="string">base64Binary</base64> [0 or 1]
   <remarks>Markup multiline</remarks> [0 or 1]
</resource>
```

**Comment by brianrufgsa** [comment]
# 30-Jan-2020 Status
Metaschema updated in @david-waltermire-nist branch.
@wendellpiez will need to address data alignment issues before this can be pulled and merged.

**Comment by wendellpiez** [comment]
Work to consolidate the models is almost but not quite complete:

* `back-matter` still permits `citation`, although the latter has been remodeled to work instead in the context of `resource` (which now also permits it)
* It also still has an `id` flag, implying it should be addressable on its own
* But `citation` without `resource` has no way to capture a link without going into the 'any' extension

If `citation` is to be permitted outside `resource` maybe it needs an `href` or `target` after all.

Alternatively, if it is not to be permitted outside `resource`, we should remove it from `back-matter`, and probably also remove its `id` flag.

For now, I am assuming the latter as I think that is in line with yesterday's work.

Yet I also note that the data will be more heavyweight if every citation is also wrapped as a resource. If this seems like a problem we should revisit. Will discuss with @david-waltermire-nist.

**Comment by david-waltermire-nist** [comment]
This is addressed by PR #614.

**Comment by brianrufgsa** [comment]
@david-waltermire-nist @wendellpiez I'm only seeing part of this implemented.

For:
- **publication**: Publication date
- **version**: Version number
- **type**: Document Type (policy, procedure, guide, pia, rob, plan)

... must I still use extensions, or are these recognized as valid @name values in prop now?

**Comment by wendellpiez** [comment]
@brianrufgsa I can’t say I remember specifically, but in my view this model is still a little soft; we can adjust if it isn’t right.

I think we wanted to keep it clean and simple but it is also possible there is a loose end. (These come out in stress testing.) Depending on what @david-waltermire-nist says this could become a new Issue. FWIW, next-gen Metaschema will also make it easier for us to customize `allowed-values` per context.

**Comment by david-waltermire-nist** [comment]
We need to get a handle on all the allowed values for prop, part, and annotation. We can do this as we work to add constraints to the existing models. As a personal goal, I’d like to minimize the need for as many extensions as is possible.

We can start this work as soon as Wendell has a working PR with the new constraint checking ready for XML. We can work through the models, while he is completing the JSON support.

Regards,
Dave

**Comment by brianrufgsa** [comment]
@david-waltermire-nist should I open a new issue for the collection/identification of @name usage across OSCAL? 

We can collect the actual usage as comments in the issue. Just to have them all in one place, plus allow others to contribute. I have a list from my SSP work, which I'm refining for my SAP and SAR work. It would help to have an early read on which will be part of core OSCAL and which I need to address as extensions.
