### ISSUE TITLE
Little schema docs bug(s)

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#613]
# Describe the bug

1. When formatting a model including a choice, the docs production erroneously terminates it with a period, as if it were inline.

In the model for **param** (catalog XML schema):

![image](https://user-images.githubusercontent.com/1588228/73282376-88ecca00-41bf-11ea-94dd-3d4819299a25.png)

**See also the JSON docs, which have a similar bug.**

# Who is the bug affecting?

Anyone with sensitivity to graceful formatting or the lack thereof

# Expected behavior (i.e. solution)

Add some sort of conditional logic to prevent (avoid) a period here.

If there are any other issues bearing on docs production, they can be addressed with these.

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #758.
