### ISSUE TITLE
SAP, SAR, and POA&M Syntax Modeling in Metaschema

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#621]
# User Story:

As an OSCAL syntax modeler, I need to represent the information models using the OSCAL metaschema for the security assessment plan (SAP), security assessment report (SAR), and plan of actions and milestones (POA&M), so that the syntax can be published, including creation of XML and JSON validation tools and format translation tools (XML-to-JSON and JSON-to-XML)

## Goals:

- Model syntax for the [Information Inventory](https://docs.google.com/spreadsheets/d/1cUAuy7ellnWXktlDPW0fHhLeA7L7COFMWQiA46mkhDE/edit?usp=sharing) created in issue #588, based on analysis performed in issue #617. 
- Include sufficient documentation an examples in the metaschema files for publication.
- Publish metaschema for use.
 
## Dependencies:

Issue #588 
Issue #617

## Acceptance Criteria

- [ ] SAP metaschema file exists, is complete, and is pushed to the OSCAL repo. 
- [ ] SAR metaschema file exists, is complete, and is pushed to the OSCAL repo. 
- [ ] POA&M metaschema file exists, is complete, and is pushed to the OSCAL repo. 
- [ ] All metashema files are recognized as valid by the OSCAL CI/CD pipeline.

**Comment by brianrufgsa** [comment]
The syntax modeling is happening in my [sap-sar-poam](https://github.com/brianrufgsa/OSCAL/tree/sap-sar-poam) branch.

I will push commits periodically through this process. Typically at least a few times a week during March 2020.

The metaschema files are [HERE](https://github.com/brianrufgsa/OSCAL/tree/sap-sar-poam/src/metaschema), and are the following files:

- **oscal_assessment-common_metaschema.xml** - The core file with most of the syntax. The other three files import what they need from this file.
- **oscal_sap_metaschema.xml** - The Security Assessment Plan model.
- **oscal_sar_metaschema.xml** - The Security Assessment Results model.
- **oscal_poam_metaschema.xml** - The Plan of Action and Milestones model.

Also, I will often generate XSD files from the metaschema to test the schema as I work. These will also be found here, and include:
- **oscal_sap_metaschema.xsd** - The Security Assessment Plan schema.
- **oscal_sar_metaschema.xsd** - The Security Assessment Results schema.
- **oscal_poam_metaschema.xsd** - The Plan of Action and Milestones schema.

**Comment by brianrufgsa** [comment]
# 12-Mar-2020 Status

Performed initial rough-in of most top-level assemblies for the SAP and SAR. Hope to finish roughing in the SAR and POA&M Evidence and Results Assemblies by the end of this week. 

Need to perform a second pass to focus on cardinality, ensure the accuracy of formal names and descriptions, and focus on placement of standard elements such as title, description, prop, annotation, and remarks. The prop and annotation additions are especially important for ensuring the model can be extended in all appropriate places.

After that, I will begin building out example SAP, SAR, and POA&M files, which will likely generate further refinements to the model, including tweaks to cardinality, sequencing, and element names. I intend to do this in alignment with the FedRAMP SAP, SAR and POA&M templates. 

Also, I have made several refinements to the metaschema model, and updated the diagrams and mock-ups (in issue #617)  to reflect these refinements. At a high-level, this includes:
- Changed the title of the model "Security Assessment Report" to "Security Assessment **Results**", which is more appropriate for NIST and OSCAL.
- Changed the top-level Scope assembly to Subject, which defines the aspects of the system to be assessed. This offers a cleaner separation from Activities, since both Subject and Activities have in-scope and out-of-scope aspects to them.
- Separated Controls and Control Objectives into a separate Objectives top-level assembly. OSCAL is control-oriented at its core. This assembly clarifies which controls and control objectives are to be assessed as a separate context from the system aspects (subject) or the activities.

**Comment by brianrufgsa** [comment]
# Updates 
To better align with previously published OSCAL content, the Security Assessment Plan (SAP) model has been renamed "Assessment Plan", and the Security Assessment _Report_ (SAR) Model has been renamed "Assessment _Results_"

Also, the Evidence assembly has been renamed "Evidence-Inventory", which better reflects its intended function, since actual evidence is attached or cited via the back-matter assembly.

# Here is the revised high-level diagram:
![SAP_ SAR_POAM_Scope_and_High_Level_Sections (v06)](https://user-images.githubusercontent.com/28259895/76798312-b9a3b580-67a5-11ea-906d-c1a040ce5bd6.png)


# Here is the more detailed, second-level diagram:
![_SAP, SAR, POAM Relationship Diagrams  (draft-07)](https://user-images.githubusercontent.com/28259895/76798289-aee92080-67a5-11ea-8adb-44d61ea66483.png)

**Comment by brianrufgsa** [comment]
# 19-Mar-2020 Status

- The three models will be at 100% draft by COB today. Some quality review has been performed; however, more quality review is required - primarily to focus on formal names, descriptions, and cardinality.

- Diagrams have been updated to reflect modeling changes
- Changed model names to better reflect OSCAL's goal of being agnostic to any specific framework. The "Security Assessment Plan" model is now "Security Plan". The "Security Assessment Report" model is now "Security Results".
- Moved controls and control-objectives from the "Subject" assembly to a new "Objectives" assembly. The "Subject" assembly is now more purely focused on the system itself.

**Comment by brianrufgsa** [comment]
# 26-Mar-2020 Status

#### This is ready for review.

The three models are complete, have been quality reviewed, and are available in the ```sap-sar-poam``` [branch of my OSCAL fork.](https://github.com/brianrufgsa/OSCAL/tree/sap-sar-poam/src/metaschema)

**Comment by brianrufgsa** [comment]
# 2-April-2020 Status
The metaschema for all three models passed all CI-CD checks, including successful generation of the schema validation and format conversion resources, as well as successful creation of the syntax documentation. 
All has been published to the repo and the web site.
Recommend closing this issue as complete.

**Comment by david-waltermire-nist** [comment]
This was completed in PR #644.
