### ISSUE TITLE
Update and align profile resolution unit tests with latest schemas

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#622]
# User Story:

When #561 is done, and working files are rebased against recent updates to schemas and models, profile resolution will break in a couple of particulars. This is additional to any bugs or feature gaps exposed by unit testing itself.

Profile resolution will not be stable until unit tests are conformant to recent models.

## Goals:

* Update all extant profile resolution unit tests for validity to current models (schemas) in `master`
* Address any emergent bugs or shortfalls in profile resolution using the current reference implementation (in `resolver-pipeline`).

## Dependencies:

#614 and #619 must be merged, and any working branches for profile resolution must be rebased, for updated schemas.

#561 must be completed so that unit testing can be run on files once corrected to current models. ("Unit testing can be run" does not mean that tests pass.)

## Acceptance Criteria

- [ ] Unit tests for profile resolution in the branch to be pulled can be shown to be valid to their respective schemas (current versions).
- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
@david-waltermire-nist this is the Issue I couldn't find yesterday, for the Sprint -- follow-on to #619 --

**Comment by wendellpiez** [comment]
@david-waltermire-nist I think this is just about ready to clear don't you?

**Comment by david-waltermire-nist** [comment]
This issue is addressed in PR #624 and will be completed once that is done.
