### ISSUE TITLE
Align current profile resolution with latest schemas

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#625]
# User Story:

Issue #577 tracks the current state of profile resolution.

A new/better implementation of profile resolution is nearly ready to integrate, as a prototype for further development. However there have been schema changes that may impact the correctness of examples in the work in progress.

All examples in the working branch need to be validated to current models, so a clean PR can be made.

## Goals:

Integrate (rebase) latest-greatest schemas into working branch for profile resolution here, addressing and resolving any conflicts:

https://github.com/wendellpiez/OSCAL/tree/profile-resolution-ng-repaired

Then, validate all profile resolution samples (including all sources and targets for testing) against latest schemas.

Run the unit tests to see that they run without error.

Passing the unit tests is *not* a goal for this Issue.

## Dependencies:

None known. We may discover interesting things in this rebase however.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Oops. This Issue appears to duplicate #622. (Take your pick, whichever is clearer.)

**Comment by david-waltermire-nist** [comment]
Closing this duplicate.
