### ISSUE TITLE
Production of HTML and PDF (rendered) catalogs - maintenance

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#630]
# User Story:

In #574 we produced basic rendering capability for HTML and PDF versions of OSCAL catalogs.

However, since then models have also changed somewhat especially respecting back matter, resulting in poor rendering of some sections.

XSLTs need to be updated accordingly.

## Goals:

Updated rendering logic will not be perfect, but it will be better. To accomplish this:

- Assemble a range of valid and reasonable OSCAL catalog examples including especially the Rev 4 and Rev 5 versions to be published.
- Run them through HTML and PDF production and check to see where there are lapses.
- Adjust the stylesheets as appropriate.
- Refer to #614 and #619 for model changes

## Dependencies:

- The working branch where these XSLTs are being developed should be rebased to all the current models.
- The catalog model should be stable when this is addressed.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
**Update March 19**

Adding this to Sprint 28 since it has advanced this week. (Prompted by work producing the SP800-53 rev 5 OSCAL.)

In fact this is nearly ready to go -- see usnistgov/oscal-tools#4 and related PR.

**Comment by wendellpiez** [comment]
@david-waltermire-nist Let's look at what is in my branch currently and discuss the problem of supporting Apache FOP?

Our most pressing issue is that while FOP can be integrated with an XSLT 2.0/3.0 transformation easily enough (calling Saxon inside various runtimes such as XProc or the IDE) -- this is *not* supported by FOP as packaged by their script. This means users cannot just download and run.

**Comment by david-waltermire-nist** [comment]
This has been addressed by usnistgov/oscal-tools#5.
