### ISSUE TITLE
JSON files for FedRamp catalog/resolved profiles not updated as part of updated schema

### ISSUE THREAD

**Issue by SParekh** [usnistgov/OSCAL#634]
# Describe the bug
Fix to change use of in-json=SINGLETON_OR_ARRAY to ARRAY in https://github.com/usnistgov/OSCAL/pull/627 merged to Master fails validations for FedRamp catalog and resolved profiles as they have not been updated to newer schema.
Files with issues
https://github.com/usnistgov/OSCAL/blob/be0e908f0e3be2cb36942a900d1c1f368176374f/content/fedramp.gov/json/FedRAMP_HIGH-baseline-resolved-profile_catalog.json
https://github.com/usnistgov/OSCAL/blob/be0e908f0e3be2cb36942a900d1c1f368176374f/content/fedramp.gov/json/FedRAMP_LOW-baseline-resolved-profile_catalog.json
https://github.com/usnistgov/OSCAL/blob/be0e908f0e3be2cb36942a900d1c1f368176374f/content/fedramp.gov/json/FedRAMP_MODERATE-baseline-resolved-profile_catalog.json
https://github.com/usnistgov/OSCAL/blob/be0e908f0e3be2cb36942a900d1c1f368176374f/content/fedramp.gov/json/FedRAMP_LI-SaaS-baseline-resolved-profile_catalog.json
https://github.com/usnistgov/OSCAL/blob/be0e908f0e3be2cb36942a900d1c1f368176374f/content/fedramp.gov/json/FedRAMP_catalog.json
 
# Who is the bug affecting?
Anyone refencing latest JSON Schema  
https://github.com/usnistgov/OSCAL/blob/be0e908f0e3be2cb36942a900d1c1f368176374f/json/schema/oscal_catalog_schema.json

and trying to validate FedRamp base catalog and resolved profiles against JSON schema would get errors 

# Expected behavior (i.e. solution)
Listed catalogs/resolved profiles to be regenerated to be compliant with new Schema.

# Other Comments
Corresponding NIST Catalogs validates as expected.
https://github.com/usnistgov/OSCAL/blob/be0e908f0e3be2cb36942a900d1c1f368176374f/content/nist.gov/SP800-53/rev4/json/NIST_SP-800-53_rev4_catalog.json

**Comment by david-waltermire-nist** [comment]
@SParekh Thanks for identifying this. I'll fix this in PR #624.
