### ISSUE TITLE
Update Website with Assessment Layer Information

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#646]
# User Story:

As an OSCAL user, I need information about the assessment layer.

## Goals:

The following updates are needed for the OSCAL website:
- [x] The architecture [page](https://pages.nist.gov/OSCAL/learnmore/architecture/)
    - [x] Descriptions are needed for the assessment plan, assessment results, and plan of actions and milestones models.
    - [x] The "Status of the OSCAL Layers needs to be updated to provide links to the format documentation, and the state should be listed as "Early Access (2.0.0)".
- [x] The diagrams for the OSCAL layers need to be added to the front matter for each schema in "Schema Reference" [pages](https://pages.nist.gov/OSCAL/documentation/schema/). The diagram and image map needs to be updated.
- [ ] Update the layers diagram on the OSCAL repo [README.md](https://github.com/usnistgov/OSCAL) to use a SVG version of the layers diagram.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
Progress is being made towards this issue. I am currently working on cleaning up some stray content that is littered across the "Leanr More" and "Documentation" sections of the website. I am working on the layers starting from the catalog layer and working up.

**Comment by brianrufgsa** [comment]
Created Issue #710 to address this more uniformly with the other layers. Recommend closing this issue and merging remaining work into that one, if not already covered.

**Comment by brianrufgsa** [comment]
# Status 23-July-2020
@brianrufgsa and @david-waltermire-nist met to plan web site content updates for all layers. We agreed on required topic areas for each level and model. Created the following issues to track this work:
- #706 
- #707 
- #708 
- #709 
- #710 
- #711

**Comment by david-waltermire-nist** [comment]
Still need to update the OSCAL layers SVG.This will be handled in the next sprint.

**Comment by david-waltermire-nist** [comment]
The remainder of this work will be done in issue #685.
