### ISSUE TITLE
Utilize Metaschema and Catalog in Ionic/Angular/Node Application

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/OSCAL#650]
As an OSCAL Catalog developer and/or maintainer, I need to be able to:

1. Instantiate OSCAL catalog model
2. Edit OSCAL catalog model
3. Review OSCAL catalog model
4. Download (save locally outside of the browser) OSCAL catalog model
5. Upload(load from locally saved) OSCAL catalog model
 
## Goals:

1. Prove the concept of working with OSCAL representations in TypeScript
2. Specify and substantiate expected catalog selection workflow
3. Perform validations based on the OSCAL meta-schema
4. Allow single user to perform workflow walk-through and save results in OSCAL form

## Dependencies:

Partially depends on #649, but the dependency is only partial 

## Acceptance Criteria

1. Allows to select catalog or set of catalogs
2. Enables selection of controls and control fragments
3. Allows augmentation and reduction of controls from the catalog version
4. Working browser-based and local persistence

**Comment by aj-stein-nist** [comment]
Per usnistgov/OSCAL-CAT#118, we are pausing development on OSCAL-CAT. Will close this issue for now.
