### ISSUE TITLE
SSP Tutorials - Planning

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#654]
# User Story:

As an OSCAL tutorial developer, I need to identify which features are most important to be explained in a tutorial, and in how many tutorials should the SSP explanation be split to make each tutorial simple enough to understand the issues,  but comprehensive enough to be useful.
## Goals:

A list of the tutorials necessary to explain the SSP model and how to create a system's OSCAL SSP and the features that need to be highlighted in each SSP tutorial.

## Dependencies:

None

## Acceptance Criteria

The list of tutorials and features is clear and complete.

**Comment by david-waltermire-nist** [comment]
We need to create a strawman outline illustrating the quantity of tutorials and which SSP model features will be covered in each tutorial..

**Comment by iMichaela** [comment]
Below is an outline of a set of mini-tutorials:

## Tutorial #3.1: SSP - Expressing the Roles, Parties, Responsibilities 

## Tutorial #3.2: SSP - Importing the Profile

## Tutorial #3.3: SSP - System Characteristics 
### Tutorial #3.3.1: SSP - System IDs
### Tutorial #3.3.2: SSP - System Description                     
### Tutorial #3.3.3: SSP - System Information, Impact Level
### Tutorial #3.3.4: SSP - Authorization Boundary  
 ]]### Tutorial #3.3.5: SSP - Network Architecture and Data Flow            
 ### Tutorial #3.3.6: SSP - Responsible parties

## Tutorial #3.4: SSP - System Implementation 
### Tutorial #3.4.1: SSP - Users, Components and Services
                      ### Tutorial #3.4.2: SSP - Interconnectos and Inventory     

## Tutorial #3.11: SSP - Controls Implementation

**Comment by david-waltermire-nist** [comment]
@Rene2mt We should discuss the way forward on this issue which outlines a few tutorials. Once we have a solid outline, I'd like to have you start working on a tutorial in this series.

**Comment by Rene2mt** [comment]
SSP Tutorials Plan (Issue #654)
===

SSPs have a lot of content.  We'll want to develop a series of tutorials that incrementally walks readers through the process of developing and SSP in OSCAL without overwhelming them.  The following is a proposed series of SSP related tutorials (e.g., try to follow the [Model Overview & Key Concepts](https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/ssp/#model-overview)).

**Tutorial 1: Metadata** - Metadata syntax is identical and required in all OSCAL models. It includes information such as the document's title, publication version, publication date, and OSCAL version. Metadata is also used to define roles, parties (people, teams and organizations), and locations.
   * *Not sure this would be too valuable sinc we'll already have a generic "metadata" tutorial, but would it be valuable to walk through a short, simple example with metadata for an SSP?*
    
**Tutorial 2: Import Profile** - Identifies the applicable control baseline for the system. This baseline is represented as an OSCAL profile.
   * Import baseline profile
   
**Tutorial 3: System Characteristics**: Represents attributes of the system, such as its name, description, models, and information processed.  A lot to cover here so maybe split into several smaller chunks
   * **Tutorial 3 (Part 1)** - (e.g., system-id, system-name & system-short-name, description, date-authorized,any SSP specifice prop & link examples).  This is probably a good place to cover roles, parties, responsibilities.
   * **Tutorial 3 (Part 2)** - (e.g., security-sensitivity-level, system-information, security-impact-level, status)
   * **Turorial 3 (Part 3)** - (e.g., authoriztion-boundary, network-architecture, data-flow) 

**Tutorial 4: System Implementation**: Represents relevant information about the system's deployment, including user roles, interconnections, services, and system inventory.
   * **Tutorial 4 (Part 1)** - leveraged-authorization, user
   * **Tutorial 4 (Part 2)** - components. This tutorial could really help clarify the difference between component definition componets, vs SSP components.  
      * *would this be the place to also show how component definitions are used in the SSP?* 
   * **Tutorial 4 (Part 3)** - inventory

**Tutorial 5: Control Implementation**: Describes how each control in the baseline is implemented within the system.
   * description, set-parameter, implemented-requirement


**Tutorial 6: Back Matter**: Back matter syntax is identical in all OSCAL models. It is used for attachments, citations, and embedded content such as graphics.
   * resources




Overall, that would total 10 relatively small tutorials (8 if we exclude tutorials 1 and 6).  We can create separate issues for each or link back to existing issues (e.g., issues #862 & #819).

**Comment by david-waltermire-nist** [comment]
@Rene2mt  Thanks for creating the new issues for this. Since these issues will be used for the tutorial development, I am going to close this issue.
