### ISSUE TITLE
Enhance Location Model in Metadata

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#655]
# User Story:

As an OSCAL user, I need more information in the location assembly within metadata. 

For example, an OSCAL-based FedRAMP SSP must specify the location of primary and backup data centers for a system. 

These must be location entries, however, the current syntax does not provide a consistent mechanism to designate which location is the primary and which is the alternate. There is neither a machine-readable nor human-readable mechanism.

## Goals:

Enhance the location assembly to provide:
- [x]  a human readable label, such as a ```title``` field.
- [ ] machine-readable content that can enable advanced processing of the location information, such as a type field or prop field with "type" as the @name flag value.

## Dependencies:

None

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
PR #758 adds the following, resolving this issue:
A `title` was added to support the human-readable label.
A prop of `name="type"` was added to support the data center use case.
