### ISSUE TITLE
Use of @name across OSCAL syntax

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#656]
# User Story:

As an OSCAL stakeholder, I need to understand all of the acceptable values for the ```@name``` flag in ```prop``` fields as well as ```part``` and ```annotation``` assemblies.

## Goals:

- [ ] Collect a list of all currently intended values for ```@name```, including those that are part of the core OSCAL syntax, and those that have been used in extensions, such as the FedRAMP extensions.
- [ ] Review the list to determine which should become part of core OSCAL syntax and which should be framework-specific extensions.
- [ ] Publish the list as an authoritative source for OSCAL users.
- [ ] Incorporate the list of identified core OSCAL syntax name values into the published OSCAL schema files.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #758.
