### ISSUE TITLE
Update and improve metaschema documentation of models and syntax 

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#657]
# User Story:

Documentation of OSCAL models and syntax in the metaschemas is due for maintenance.

This includes formal names, descriptions and remarks on assemblies, fields, flags and their constraints. It does not include embedded or linked samples, which will require a bit more development to support in the new Metaschema (see usnistgov/metaschema#48).

See #363, which encompasses this work item along with work on the web site.

## Goals:

Documentation of models, syntax, constraints and semantics of the OSCAL models -- especially at the Implementation layer, but also throughout -- needs to be up to date.

To this end, for this Issue, we should revise, update and improve documentation embedded in the metaschemas.

## Dependencies:

Since it happens in the metaschema files, this work needs to be coordinated with parallel work on the models.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] Issues have been created for follow-on work such as examples in the metaschema.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #758.
