### ISSUE TITLE
Website enhancement - Use Cases and Case Studies pages updates

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#659]
# User Story:

As an OSCAL user, I  would benefit from updated/current use cases (https://pages.nist.gov/OSCAL/learnmore/use-cases/)  of OSCAL use, including links to FedRAMP's guidance documents under their use case, as opposed to outdated case studies (https://pages.nist.gov/OSCAL/learnmore/case-studies/ ) which could be deleted.

## Goals:

Delete https://pages.nist.gov/OSCAL/learnmore/case-studies/ and move the FedRAMP and Docker stories as use cases, with updated information and links to their OSCAL-meaningful developments.

## Dependencies:

none

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.
{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire-nist** [comment]
Progress is being made towards this issue. I am currently working on cleaning up some stray content that is littered across the "Leanr More" and "Documentation" sections of the website. I am starting to turn the case studies into use cases.

**Comment by david-waltermire-nist** [comment]
This was completed a long time ago.
