### ISSUE TITLE
Website - Accessibility issue on "Contribute" page

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#663]
# Describe the issue/feature

The background colors for the navigation tabs for all "Lunch with the devs" meetings are too dark and within the same shade spectrum with the text, making the text almost invisible.

# Who is the issue affecting?
People using the website

# What is affected by this issue?
Readability/accessibility issue

# When does this occur?
All the time

# How do we replicate the issue?
Open the page

# Expected behavior (i.e. solution)
remove the debugging and with it the dark background color of the tabs

# Other Comments
none

**Comment by david-waltermire-nist** [comment]
This was addressed by PR #681.
