### ISSUE TITLE
Design Metadata Component

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/OSCAL#664]
# Metadata Component Design Story:

As an OSCAL Ionic/Angular developer, I need to decompose the JSON/XML object/document representation into smaller UI-tied pieces (called components in Ionic/Angular)

- The application heeds 4 Screens:

1. Metadata Input Screen

   - Has to contain all the authoring information (required and optional) in the metadata schema

## Goals:

To have smaller, dynamically renderable UI representation of the repeatable catalog elements that allow single and group validation.

## Dependencies:

Finalized JSON/XML catalog descriptions

## Acceptance Criteria

- [ ] Catalog->Profile Metadata page is composable of the designed components, covering all the JSON/XML elements in UI.
- [ ] Some elements should have user-driven auto-fill properties. E.g. last edit date-time.
- [ ] The elements validators have to be clearly specified as two types: group validation, and required field/format-matching field for applicable data elements.

**Comment by JustKuzya** [comment]
### 2020-06-18
The control is almost ready, except the "Address" structure needs some work

**Comment by JustKuzya** [comment]
### 2020-07-16
NgRX integrating the metadata elements hook-up to allow easier testing of the services and decoupling the meta component part of the UI from the application's store/state

**Comment by aj-stein-nist** [comment]
Per usnistgov/OSCAL-CAT#118, we are pausing development on OSCAL-CAT. Will close this issue for now.
