### ISSUE TITLE
Design Controls' Families Component 

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/OSCAL#666]
# Control Families Component Design Story:

As an OSCAL Ionic/Angular developer, I need to decompose the JSON/XML object/document representation into smaller UI-tied pieces (called components in Ionic/Angular)

## Goals:

To have smaller, dynamically renderable UI representation of the repeatable catalog Control Families selection elements that allow single and group validation and Catalog Control linking.

## Dependencies:

Finalized JSON/XML catalog descriptions

## Acceptance Criteria

- [ ] Catalog->Profile Control Families page is composable of the designed components, covering all the JSON/XML elements in UI.
- [ ] Some elements should have user-driven auto-fill properties. E.g. last edit date-time.
- [ ] The elements validators have to be clearly specified as two types: group validation, and required field/format-matching field for applicable data elements.

**Comment by JustKuzya** [comment]
### 2020-06-18
Underlying service works with generic metaschema groups and uses "Family" label as a schema-driven field only for the schemas using the "Families", e.g. 800-53

**Comment by JustKuzya** [comment]
### 2020-06-25
Working on Tree-View component to represent  families/groups in an uniform way across catalogs

**Comment by JustKuzya** [comment]
### 2020-07-16
NgRX integrating the families/groups elements hook-up to allow easier testing of the services and decoupling the UI from the application's store/state

**Comment by david-waltermire-nist** [comment]
![profile-tool-ui-flow](https://user-images.githubusercontent.com/9871976/89317137-f84de580-d64a-11ea-9d13-4667ea8085ca.png)

This is a rough sketch of the workflow for creating/editing a profile.

**Comment by aj-stein-nist** [comment]
Per usnistgov/OSCAL-CAT#118, we are pausing development on OSCAL-CAT. Will close this issue for now.
