### ISSUE TITLE
Design control representation UI element

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/OSCAL#667]
# Control UI Representation Component Design Story:

As an OSCAL Ionic/Angular developer, I need to decompose the JSON/XML object/document representation into smaller UI-tied pieces (called components in Ionic/Angular)

## Goals:

To have smaller, dynamically renderable UI representation of the repeatable catalog elements that allow single and group validation.

## Dependencies:

Finalized JSON/XML catalog descriptions

## Acceptance Criteria

- [ ] Catalog->Profile Control UI Representation page that is composable of the designed components, covering all the JSON/XML elements in UI.
- [ ] Some elements should have user-driven auto-fill properties. E.g. last edit date-time.
- [ ] The elements validators have to be clearly specified as two types: group validation, and required field/format-matching field for applicable data elements.

**Comment by JustKuzya** [comment]
### 2020-06-25
Finished layout of the oscal-control component. Still needs a hook-up into the baseline.

**Comment by aj-stein-nist** [comment]
Per usnistgov/OSCAL-CAT#118, we are pausing development on OSCAL-CAT. Will close this issue for now.
