### ISSUE TITLE
Dynamic UI Representation of Control Parameters

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/OSCAL#668]
# Control Parameters Component Design Story:

As an OSCAL Ionic/Angular developer, I need to decompose the JSON/XML object/document representation into smaller UI-tied pieces (called components in Ionic/Angular). This particular Issue describes Control-Parameters component

## Goals:

To have smaller, dynamically renderable UI representation of the Control-Parameters elements that allow single and group validation and rendering controls of different intrinsic types with appropriate validation.

## Dependencies:

Finalized JSON/XML catalog descriptions that are parsed by the Ionic/Angular application

## Acceptance Criteria

- [ ] Catalog->Profile Control-Parameters UI representation that allows to build composable Control page consisting of the components, covering the corresponding JSON/XML elements in UI.
- [ ] Control-Parameters elements should have user-driven auto-fill properties (if needed). E.g. last edit date-time.
- [ ] Control-Parameters elements should have appropriate type-specific representations and value validation performed before mounting the UI-input values into the final JSON/XML representation.
- [ ] The elements validators have to be clearly specified as two types: group validation for Control-Parameters, and required field/format-matching field for applicable data elements.

**Comment by aj-stein-nist** [comment]
Per usnistgov/OSCAL-CAT#118, we are pausing development on OSCAL-CAT. Will close this issue for now.
