### ISSUE TITLE
Design Control-Parts Component 

### ISSUE THREAD

**Issue by JustKuzya** [usnistgov/OSCAL#669]
# Control-Parts Component Design Story:

As an OSCAL Ionic/Angular developer, I need to decompose the JSON/XML object/document representation into smaller UI-tied pieces (called components in Ionic/Angular). This issue describes Control-Parts component that represents arbitrarily (JSON/XML-driven) sized number of control parts that are selectable/editable/includable into the profile.

## Goals:

To have smaller, dynamically renderable UI representation of the repeatable Control-Parts elements that allow single and group validation of the control editing, selection, inclusion/exclusion, and modification at the Control-Parts level.

## Dependencies:

Finalized JSON/XML catalog descriptions

## Acceptance Criteria

- [ ] Catalog->Profile Control page is composable of the designed components Control-Parts and Control-Parameters  covering all theControl-related JSON/XML elements in UI.
- [ ] Some elements should have user-driven auto-fill properties. E.g. last edit date-time.
- [ ] The elements validators have to be clearly specified as two types: group validation, and required field/format-matching field for applicable data elements.

**Comment by aj-stein-nist** [comment]
Per usnistgov/OSCAL-CAT#118, we are pausing development on OSCAL-CAT. Will close this issue for now.
