### ISSUE TITLE
location of file "profile-resolution-spec-xpr.zip"

### ISSUE THREAD

**Issue by garik-pilot** [usnistgov/OSCAL#673]
Following readme I tried to lookup for this file in OSCAL master folders to open it with oXygen but no luck. Could you advise where I can find or download it from?

**Comment by iMichaela** [comment]
The specification you are looking for is available here: https://pages.nist.gov/OSCAL/documentation/specification/processing/profile-resolution/
The team generates the website automatically from data on GitHub

**Comment by garik-pilot** [comment]
I am looking for this specific file in repo   "profile-resolution-spec-xpr"

**Comment by david-waltermire-nist** [comment]
@garik-pilot It looks like you are refering to the instructions at https://github.com/usnistgov/OSCAL/tree/master/src/specifications/profile-resolution#setup.

I don't think this file exists and these instructions are out-of-date,

@wendellpiez Can you update the instructions to be in sync with the latest in the repo?

**Comment by wendellpiez** [comment]
@garik-pilot yes, with apologies, we stopped sharing the oXygen setup when it became clear it was not needed (while it takes effort to maintain).

If for whatever reason you do find you need to edit the (draft) profile resolution spec let me know and we may be able to make arrangements - however our editorial workflow is now such that only one person is editing this resource at a time. (It turns out we are only able to do so many things at once.)

The current draft profile resolution is however also rendered for public view through our CI/CD, and posted here: https://pages.nist.gov/OSCAL/documentation/specification/processing/profile-resolution/ and we gratefully welcome feedback through these channels and others. Thanks!

**Comment by garik-pilot** [comment]
Hi Wendell, yes, I understood the concept of profile resolution to generate
the various profiles from the catalog. How I can practically use it? Let's
say I selected the list of controls for a specific environment. Is it
possible to publish the example of end-to-end process of how to configure
the profile and which commands I need to run to generate the desired
profile in xml format?

**Comment by wendellpiez** [comment]
@garik-pilot this is super helpful, I will also edit the readme here: https://github.com/usnistgov/OSCAL/tree/Issue673-readme-update/src/utils/util/r: esolver-pipeline

This is our prototype profile resolver in XSLT, not complete, but underway.

The readme will say something about applying the XSLT either from the command line or in a tool or IDE. It probably won't say anything about how to create your profile XML (many ways to do that), but it could point to examples. (As we proceed we also expect to be able to offer more tutorials, etc. but that is longer-term.)

FWIW the current profile resolver XSLT can be invoked directly over the Internet as a raw file off Github: https://raw.githubusercontent.com/usnistgov/OSCAL/master/src/utils/util/resolver-pipeline/oscal-profile-RESOLVE.xsl although I would probably get a local copy. (Indeed the transformation at the end there is only a shell for others, all in the repository.)

With the XSLT as input, this process requires only a profile document (nominal 'profile source document'), which contains links to (and imports) a catalog document, as shown in examples.

It does not do everything yet, but we think it basically works.

As for running this in oXygen, that is not difficult to do ... but it wasn't what that missing file was for either, that was for running the spec production. To run profile resolution or indeed other XSLT transformations such as in the tools repo, I am not sure we are ready to put an oXygen configuration out there ... but it's not hard to set up.

tools XSLT repo is here: https://github.com/usnistgov/oscal-tools/tree/master/xslt

**Comment by iMichaela** [comment]
@garik-pilot - There must be some misunderstanding. You wrote: "Let's say I selected the list of controls [...] how to configure the profile and which commands I need to run to generate the desired
profile in xml format ". The profile is a collection of selected controls, and there are several ways of doing so using the tool of your choice. Until we have an official tutorial on our website, you can see one (and examples) here: https://github.com/iMichaela/OSCAL/tree/master/docs/tutorials/profile. 
The **resolved profile** is the one that requires the use of the pipeline (and the XSLT, the profile (non-resolved one) and the catalog), to generate the **resolved profile** which is like a stand-alone customized catalog and needs to be validatable by the catalog schema. I do not have yet a tutorial for this case. The readme Wendell pointed to can be used. When you say you want to "configure the profile" I assume you would like to make changes to the controls imported from the catalog. If **not**, please elaborate.

**Comment by garik-pilot** [comment]
yes, Wendell explained to me in the previous email how the series of
transformations work to operate with profiles. I will do my hands-on
exercise to play with it. thanks
