### ISSUE TITLE
Milestone 3 Metaschema enhancements: uuid datatype; validation at root

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#678]
# User Story:

For Milestone 3 schemas we have a couple of functional requirements:

* Support a 'uuid' datatype to validate UUIDs as a structured data type (regex pattern)
* Revise schema generation so resulting schemas validate from the correct (single) root
  * See Metaschema repo WIP for this code

These extensions need to go in the Metaschema `toolchains/oscal-m2` stack or a clone of it.

## Goals:

Extend Metaschema capabilities to reflect requirements for Milestone 3 OSCAL.

## Dependencies:

* Unit tests to show UUID usage
* Review UUID usage in the data and discuss present use of the `id` flag (maybe it should be `uuid` in some places)

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
This was addressed by PR #681.
