### ISSUE TITLE
Create YAML representation of OSCAL

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#68]
Goals:
- Andrew will fill in 

Dependencies:
- Andrew will fill in

Acceptance Criteria:
- Andrew will fill in

**Comment by iMichaela** [comment]
## 11/09/2018 ##
#262 generates YAML equivalent from JSON.  (goal 1 of this issue). None of the other goals listed in #68 are addressed.  @david-waltermire-nist and @iMichaela will discuss the other goals and make a decision if the issue should stay opened or if it can be closed.

**Comment by david-waltermire-nist** [comment]
Metaschema support for YAML can be built to support this.

**Comment by david-waltermire-nist** [comment]
This has been addressed as part of the CI/CD pipeline.
