### ISSUE TITLE
Website information update (mailing lists)

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#688]
# Describe the proposed updates:

OSCAL website requires few updates:

1. On the page [Contribute](https://pages.nist.gov/OSCAL/contribute/), the subsection **Tools**  needs to be updated with the new mailing list: oscal-dev@list.nist.gov.

1. On the page [Contribute](https://pages.nist.gov/OSCAL/contribute/), the list of topics at the bottom of the page should include the information about the new Friday, biweekly meetings for feedback on the models, either bundled with "Lunch with the devs", under a different title (e.g. OSCAL Community of Interest Forums) or as a separate page.

1. On the page: [Contact Us](https://pages.nist.gov/OSCAL/contact/), The mailing lists information needs to be updated to oscal-dev@list.nist.gov and oscal-updates@list.nist.gov.
To subscribe, send an email to oscal-dev+subscribe@list.nist.gov and an email with the link to join. Self-subscription requires an existing Google account or registration of the existing email with Google. To unsubscribe, send an email to oscal-dev+unsubscribe@list.nist.gov or edit your Google Group settings and select "Leave this group". 

Additional information is available here: [https://support.google.com/groups/answer/1067205?hl=en&ref_topic=2458614](https://support.google.com/groups/answer/1067205?hl=en&ref_topic=2458614)

**Comment by david-waltermire-nist** [comment]
This issue was completed long ago.
