### ISSUE TITLE
Update OSCAL preview/rendering XSLTs to Milestone 3 models

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#689]
# User Story:

In the repository usnistgov/oscal-tools we have a distribution of XSLTs for processing OSCAL.

These need to be updated in view of recent changes to the models for Milestone 3.

## Goals:

The XSLTs should work at least as well on data valid to the latest schemas, as they do on earlier schemas.

## Dependencies:

TBD: whether the XSLTs should continue to support data valid to earlier models.

For this work, any samples made available for demo must also be updated.

## Acceptance Criteria

- [x] A Pull Request (PR) is submitted to the repository at https://github.com/usnistgov/oscal-tools that fully addresses the goals of this User Story. This issue is referenced in the PR.

**Comment by wendellpiez** [comment]
This update was made in the `oscal-tools` repo so it actually doesn't require a PR or any change in the main OSCAL repo.

**Comment by aj-stein-nist** [comment]
Agreed, @wendellpiez, I was reviewing open issues and notice this obsolete issue. I am closing this one now.
