### ISSUE TITLE
readme of "https://github.com/usnistgov/OSCAL/tree/master/build" should be corrected  

### ISSUE THREAD

**Issue by garik-pilot** [usnistgov/OSCAL#693]
# Describe the bug
Following to steps I couldn't set up the environment, someone needs to review and re-test the steps and add more details. 
 Issue 1: Step 2 in  "Manual Setup of the Build Environment"
from cmd (Windows) should run the following cmd before apt-get  
docker exec --user="root" -it build_cli_run_419da495469b /bin/bash
Issue2: Nodejs can not be installed by npm install, there are the error msgs of dependencies
Issue3: From "Running the Build Scripts": "From the root directory of the repository,..."  could you explicitly add the path? I tried to run but there are a lot of error msgs "No such file or directory" or "command not found".  
 

{A clear and concise description of what the bug is.}

# Who is the bug affecting?
It is impossible to use  
# What is affected by this bug?

{Describe the impact the bug is having.}

# When does this occur?
every build/run 
{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?
see above 
{What are the steps to reproduce the behavior?
1. Do this...
1. Then this...
1. See error

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}
The steps to build/use should be cleaner and validated before publishing for public usage.

**Comment by david-waltermire-nist** [comment]
@garik-pilot I just reran this setup on a fresh WSL install of Ubuntu 20.04 and I am not experiencing the same issue. What version of Linux are you running? Also, can you provide some screenshots of each issue?
