### ISSUE TITLE
Missing image in README.md

### ISSUE THREAD

**Issue by WallabyCurtis** [usnistgov/OSCAL#696]
On README.md the linked image labelled "OSCAL diagram" (https://github.com/usnistgov/OSCAL/raw/master/docs/content/learnmore/architecture/oscal-components.png) does not exist.

**Comment by iMichaela** [comment]
This issue, reporting missing diagram at : 

https://github.com/usnistgov/OSCAL/raw/master/docs/content/learnmore/architecture/oscal-components.png

is identical to issue #704. The diagram exists (but only in Visio format) [here](https://github.com/usnistgov/OSCAL/blob/master/src/assets/OSCAL_Layers_Diagram.vsdx). The diagram appears to be up to date. 
Suggest closing one of the two issues even before the updated information is pushed.

**Comment by david-waltermire-nist** [comment]
This diagram is old and needs to be updated. In PR #714, I removed the image and the "architecture" section of the page until something more suitable can be found. I also updated the out-of-date milestone 1 info.

**Comment by david-waltermire-nist** [comment]
This work is complete in PR #714.
