### ISSUE TITLE
Pipeline Schema Generation Refactoring

### ISSUE THREAD

**Issue by avdouglas-nist** [usnistgov/OSCAL#699]
# User Story:

As an OSCAL developer, I would like to refactor the existing Continuous Integration (CI) and Continuous Deployment (CD) script, for generating schema, to Typescript.

## Goals:

- [ ] To improve code design, structure, and/or implementation of the CI/CD Pipeline (its non-functional attributes), while preserving its functionality.
- [ ] To continue the improvement of code design to simplify code structure, make it easier and easier to work with and improve maintainability.
- [ ] All dependencies are managed by npm (the Node.js package manager). Need to make sure all the declaration packages you depend on are marked appropriately in the "dependencies" section in your package.json. 

## Dependencies:

None.

## Acceptance Criteria
- [ ] Confirm that Typescript performs the same functionality and produces similar output as the current script.
- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
## Schema Generation Workflow

Original Script: https://github.com/usnistgov/OSCAL/blob/master/build/ci-cd/generate-schema.sh

The following workflow is used to generate XML and JSON schemas from the OSCAL Metaschema.

Commandline arguments:
- Verbose (" -v" argument) or Minimal Output (default)
- Working directory: ("-w") which defines where the produced files are generated
- Help ("-h") display help for the script

Load configuration file (https://github.com/usnistgov/OSCAL/blob/master/build/ci-cd/config/metaschema) (see line 82)

Resolve file match pattern to determine the specific files to process (e.g. *-metaschema.xml; will match a-metaschema.xml and b-metaschema.xml - glob syntax or equivalent)

For each configured OSCAL metaschema, the following build steps will be performed:

1. Call the `/build/metaschema/scripts/generate-schema.sh` script with the following arguments:
    - schema format: xml or json
    - absolute path to the metaschema file
    - path to where to store the generated schema result
    - "--validate" to ensure the generated schema is validated

**Comment by aj-stein-nist** [comment]
Per usnistgov/OSCAL-CAT#118, we are pausing development on OSCAL-CAT. Will close this issue for now.
