### ISSUE TITLE
Namespace update

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#7]
The namespace now assigned to OSCAL elements, http://scap.nist.gov/schema/oscal, doesn't conform with current guidelines (I am told) for NIST namespaces. It is essentially a placeholder.

What will the namespace of OSCAL be?

**Comment by wendellpiez** [comment]
This Issue can be closed in favor of #306, which picks up on this issue. TL;DR: a mechanism now supports this but the namespaces have not actually been assigned.

**Comment by david-waltermire-nist** [comment]
Closing this issue, and will address in #306.
