### ISSUE TITLE
Datatype Content Issues on pages.nist.gov/OSCAL

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#702]
# Describe the bug

The following issues exist on the pages.nist.gov/OSCAL site:
1. The datatypes is no longer accessible from the menus. If you have a bookmark, or other known-good URL, you can still reach the datatype content.
1. When clicking a datatype in the modelmap, a page not found error is experienced. Upon inspection, the URL incorrectly includes the model name. For example, the link for "Markup-multiline" is https://pages.nist.gov/OSCAL/documentation/schema/assessment-layer/datatypes/#markup-multiline. The "assessment-layer/" portion is erroneous. If removed, the link is valid.
1. While the Markup Data Types summary mentions tables, and there is a section about the use of tables, the summary at the top of [markup-multiline](https://pages.nist.gov/OSCAL/documentation/schema/assessment-layer/datatypes/#markup-multiline) does not mention tables. Also (ironically) tables are not an included markup type in the table.

# Who is the bug affecting?

OSCAL practitioners trying to find critical content about implementing OSCAL.

# Other Comments

This is more of a tracker ticket and may need to be moved to the metaschema repository.

**Comment by wendellpiez** [comment]
We should review all these issues with a fresh set of eyes (@brianrufgsa @david-waltermire-nist ) *after* I complete the current work on the pages as tracked in #725 and #750.

- [ ] Description of data types including `markup-line` and `markup-multiline` in docs (both XML and JSON)
- [ ] Link integrity of all links to data types
- [ ] Completeness of coverage e.g. wrt tables in `markup-multiline`
- [ ] Anything else noted above

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #758.
