### ISSUE TITLE
Update Website Content - Assessment Results Layer

### ISSUE THREAD

**Issue by brian-ruf** [usnistgov/OSCAL#711]
# User Story:

As an OSCAL practitioner, I need to rely on the content at [https://pages.nist.gov/OSCAL/documentation](https://pages.nist.gov/OSCAL/documentation) for understanding the OSCAL Assessment Results layer, and the Assessment Results and POA&M models.

## Goals:

For the catalog model, provide the following content:
- **Purpose**
  - What is the significance? 
  - What does it do for OSCAL users?
- **User Base** 
  - Who typically authors this model? 
  - Who typically consumes this model?
- **Core Concepts**
  - What are the core concepts for this model?
- **Organization**
  - How is the model organized?
- **Relationships**
  - How do the layers and models relate to other layers and models? 
  - What other models consumes this model?
  - What models are consumed by this model?
- **Walk Through**
  - A brief/high-level tutorial for this model

For the catalog layer, provide a summary of the catalog model.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

- [ ] Assessment Results Model Purpose Content Complete
- [ ] Assessment Results Model User Base Content Complete
- [ ] Assessment Results Model Core Concepts Content Complete
- [ ] Assessment Results Model Organization Content Complete
- [ ] Assessment Results Model Relationships Content Complete
- [ ] Assessment Results Model Walk Through Complete

- [ ] POA&M Model Purpose Content Complete
- [ ] POA&M Model User Base Content Complete
- [ ] POA&M Model Core Concepts Content Complete
- [ ] POA&M Model Organization Content Complete
- [ ] POA&M Model Relationships Content Complete
- [ ] POA&M Model Walk Through Complete

- [ ] Assessment Results Layer Summary Complete

**Comment by david-waltermire-nist** [comment]
This was addressed in PR #748 and later commits.
