### ISSUE TITLE
Profile Resolution Overlays

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#716]
# User Story:

As an OSCAL framework author, it would be helpful for OSCAL profile resolution to overlay rather than merge in some instances.
For example, DoD has Control Correlation Identifiers (CCIs), which maps their own additional control content, objectives, and assessment methods to the NIST SP 800-53 revision 4 controls (among other source mappings). 
These CCIs are referenced in Security Technical Implementation Guides (STIGs).

For a Moderate-baseline systems subject to CCI, it would be helpful for the system to have a profile which imports both a FISMA Moderate profile and the CCI profile as an overlay.

Under the current profile resolution capabilities, this would merge the two. The result would be all controls being applied (by virtue of the CCI to 800-53 profile). In this scenario, the desired result is for all of the FISMA moderate controls are imported, but only the CCIs which map to the moderate controls are imported. 

## Goals:

- Provide a merge directive to specify whether an import should be merged as normal (default) or overlayed onto other imported controls. 
- Enhance profile resolution capabilities to enable this directive.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by brianrufgsa** [comment]
I see a simple profile syntax addition and simple profile resolution business logic satisfying this enhancement. 

First, this only applies where there are two or more import statements, and does not make sense with a single import statement.

In the ```import``` field, add an additional/optional ```overlay``` flag. When the value of this flag is set to ```'yes'```, the following business logic is applied:

1. Perform all profile import functions under current processing mechanisms for all ```import``` assemblies _except_ for those with ```@overlay='yes'```. This includes all merge rules.

1. For each ```import``` where ```@overlay='yes'```, only merge those controls with IDs that match existing controls in the resolved profile resulting from the step above.
   - The ```include``` and ```exclude``` assemblies within the overlay import further limit which controls are available for overlay.  

1. Process alter statements as normal.

---
## EXAMPLE 1
The CCI profile includes extra information for every 800-53 control; however, it is only intended to be applied to in-scope controls. 

The following would:
1. Import all the controls from the 800-53 moderate profile, plus import AC-6(3) from the 800-53 catalog, while ignoring the CCI profile. It would follow all of the merge directives, just as it does today. 
1. Further import only the CCI controls that match the moderate controls or AC-6(3), and ignore all other CCI controls. Merge directives are irrelevant as this definitionally introduces no additional controls. It only modifies existing controls. 
1. Perform all alter statements as normal on the complete set of controls. 

```
<import href="800-53-moderate_profile.xml">
   <include>
      <all />
   </include>
</import>

<import href="80-53_catalog.xml">
   <include>
      <call control-id="ac-6.3" />
   </include>
</import>

<import href="cci_profile.xml" overlay="yes">
   <include>
      <all />
   </include>
</import>

<merge />
<alter />
```
---
## EXAMPLE 2

The following would:
1. Import all the controls from the 800-53 moderate profile, plus import AC-6(3) from the 800-53 catalog, while ignoring the CCI profile. It would follow all of the merge directives, just as it does today. 
1. Import only the CCI control overlay for AC-6(3), since only AC-6(3) and AC-6(4) were specified in the include statement, but AC-6(4) doesn't exist in the controls resulting from the previous step. 
1. Perform all alter statements as normal on the complete set of controls. 

```
<import href="800-53-moderate_profile.xml">
   <include>
      <all />
      <!-- This profile contains AC-6(1), AC-6(2), and AC-6(5), but not AC-6(3) or AC-6(4) -->
   </include>
</import>

<import href="80-53_catalog.xml">
   <include>
      <call control-id="ac-6.3" />
   </include>
</import>

<import href="cci_profile.xml" overlay="yes">
   <include>
      <call control-id='ac-6.3' />
      <call control-id='ac-6.4' />
   </include>

</import>

<merge />
<alter />

```

**Comment by david-waltermire-nist** [comment]
@brianrufgsa I believe that the use case of mapping to CCIs or anything else is is a misuse of the Profile model, which is intended to support definitions of baselines for downstream consumption by components and SSPs. Rather than going this route, I believe we should develop some user stories around enhancing mapping capabilities in catalogs and to also support an external mapping model.

Thoughts?

**Comment by david-waltermire-nist** [comment]
We want to create a mapping model that allows for this, instead of using profiles. Closing this.
