### ISSUE TITLE
Capability to identify differences between revisions of OSCAL documents that follows control identifier changes

### ISSUE THREAD

**Issue by AdamOlineDOJ** [usnistgov/OSCAL#718]
# User Story:

As an OSCAL tool developer, I would like the deep diff capability for OSCAL document comparisons to accommodate the scenario where a control identifier has changed from one revision to the next.

## Goals:

Enabling the the deep diff tool to compare revisions of OSCAL documents in a way that can "follow" control identifier changes (i.e. "moves") would help OSCAL tool developers use the deep diff output to more completely map existing control implementation and assessment requirements and data from a prior revision of an OSCAL document to the next one.

For example, this would be useful in a GRC application that has an inventory of systems which have control implementation and assessment data based on the NIST 800-53 Rev4 catalog, and are ready to begin migrating to the NIST 800-53 Rev5 catalog. The GRC application developers may want to display the control implementation and assessment requirement changes to the end users, based on the output of the deep diff tool, so end users can determine how much of their prior implementation and assessment content for a given control under Rev4 can be re-used in the Rev5 catalog, and what requirement modifications they need to address under the Rev5 catalog.

Some controls in the NIST 800-53 Rev5 Final Public Draft catalog have had their control identifier changed from Rev4, and it would be helpful if the deep diff tool could "follow" these moves. For example, control AR-2 in Rev4 appears to have changed to RA-8 in Rev5, as part of NIST's effort to integrate the Privacy Controls more fully into the main catalog. The requirements are similar, but have also changed:

**NIST 800-53 Rev4:** AR-2 PRIVACY IMPACT AND RISK ASSESSMENT

> The organization:
>
> a. Documents and implements a privacy risk management process that assesses privacy risk to
> individuals resulting from the collection, sharing, storing, transmitting, use, and disposal of
> personally identifiable information (PII); and
>
> b. Conducts Privacy Impact Assessments (PIAs) for information systems, programs, or other
> activities that pose a privacy risk in accordance with applicable law, OMB policy, or any
> existing organizational policies and procedures.

**NIST 800-53 Rev5:** RA-8 PRIVACY IMPACT ASSESSMENTS

> Conduct privacy impact assessments for systems, programs, or other activities before:
>
> a. Developing or procuring information technology that processes personally identifiable
> information; and
>
> b. Initiating a new collection of personally identifiable information that:
>    1. Will be processed using information technology; and
>    2. Includes personally identifiable information permitting the physical or online contacting
> of a specific individual, if identical questions have been posed to, or identical reporting
> requirements imposed on, ten or more persons, other than agencies, instrumentalities,
> or employees of the federal government.

## Dependencies:

Mapping of NIST 800-53 Rev4 control identifiers to their equivalent in NIST 800-53 Rev5, for those that have changed (in order to support the use case for the specific example involving the NIST 800-53 catalogs).

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
This was discussed during the 9/10 Lunch with the Devs.

Appendix J controls are a dependency (#347) for making a full comparison.

We discussed starting with an approach that compares the control content at the statement level. This would allow statement changes to be identified as:

- Added statement
- Removed statement
- Unchanged statement
- Minor changes to statement, with "minor" being based on some compassion operation.

For string comparison, there are many algorithms to apply (e.g.,, word distance, etc.).

We could produce a mapping of rev4 statement ids to rev5 statement ids as a start along with the type of change above.

**Comment by david-waltermire-nist** [comment]
This issue is addressed by the [OSCAL Deep Diff Tool](https://github.com/usnistgov/oscal-deep-diff/). Closing.
