### ISSUE TITLE
Bi-Weekly Modeling Meeting Doesn't Say When

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#719]
# Describe the bug

The new website page providing information on the bi-weekly modeling session does not state when the meetings are held.
(Every other Friday at 10:00 AM Eastern Time)

# Who is the bug affecting?

Anyone looking at the web site interested in joining the modeling sessions.

# What is affected by this bug?

Meeting participation.

# When does this occur?

Prevalent. 

# How do we replicate the issue?

1. Visit: https://pages.nist.gov/OSCAL/contribute/model-review/
1. Look for meeting day/time

# Expected behavior (i.e. solution)

A statement that the meetings are every other Friday, 10:00 - 11:00 AM Eastern Time

**Comment by david-waltermire-nist** [comment]
@brianrufgsa I don't have a good way to list the actual day since this is a reoccurring meeting. The ICS file that is linked to will setup the right dates on a calendar. What else do you want done to fix this?

**Comment by brianrufgsa** [comment]
@david-waltermire-nist when I created this issue, the page did not list "DAY and TIME" stating "Every other Friday at 10 am". 
That is what I was saying was missing in this issue. The page has apparently been updated since then to include this information, so this issue can be closed.
