### ISSUE TITLE
Integrating XSLT-M4 Metaschema into OSCAL repo

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#721]
# User Story:

As an OSCAL user and developer, I would like to be able to use and enjoy all the great new features available in the new XSLT-M4 pipeline implementation in the usnistgov/metaschema repository.

In particular, I would like to be able to do all of these with the new resources, stylesheets and scripts:
  - [x] metaschema validation
  - [x] schema generation
  - [x] converter generation and testing

Resources including pipelines supporting these transformations are now behind a PR in the Metaschema repo, here: usnistgov/metaschema#61.

For testing the functionality and finding bugs, a reasonable approach could be to work from the CI/CD scripts starting at the top, and proceed through.

## Goals:

By completing integration of the new Metaschema XSLT-M4 implementation, we aim to be able to take advantage of its features in OSCAL schemas, including new constraints validation features.

Related to this: we will bring the Metaschema design to a stable point. No Issues in the OSCAL repo should now depend on Metaschema features planned but not yet built and testable.

Note that redesigning documentation generation is tracked elsewhere (#725) and is not a goal for this Issue. Refreshing the documentation, however (even with an old design) is a goal.

## Dependencies:

This Issue is closely coupled with #724, updating the metaschemas themselves. The old metaschemas will not process successfully through the new version, but the new metaschemas should.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by brianrufgsa** [comment]
# Status 3-Sept-2020
@david-waltermire-nist is wrapping up and stabilizing dependent repo work, which is nearly complete.

**Comment by david-waltermire-nist** [comment]
@wendellpiez I need to understand the XSLT targets for schema generation, schematron generation, converter generation, and docs gneration. Can you sumarize the file paths and any parameters that are needed to execute these targets?

**Comment by wendellpiez** [comment]
In these examples, `abc` is the short name or code of a metaschema.

For each of these transformations, the source is a metaschema (e.g. `abc_metaschema.xml`) and the XSLT will be located at `toolchains/xslt-M4` in the metaschema repository (not `xslt-proto-v04` as formerly).

I have not yet been able to confirm the target subdirectory for generated HTML documentation - `docs/layouts/partials`?

| Process | Transformation | Result | Parameters |
|--|--|--|--|
| **XML Schema** | `nist-metaschema-MAKE-XSD.xsl` | `xml/schema/abc-schema.xsd` | none |
| **JSON Schema** | `nist-metaschema-MAKE-JSON-SCHEMA.xsl` | `json/schema/abc_schema.json` | `indent=yes\|no`*
| **XML-to-JSON converter** | `nist-metaschema-MAKE-XML-TO-JSON-CONVERTER.xsl` | `xml/converter/abc_xml-to-json-converter.xsl` | none |
| **JSON-to-XML converter** | `nist-metaschema-MAKE-JSON-TO-XML-CONVERTER.xsl` | `json/converter/abc_json-to-xml-converter.xsl` | none |
| **XML docs generation** | `nist-metaschema-MAKE-XML-DOCS.xsl` | `docs/{...}/generated/abc-xml-schema.html` | none |
| **XML map** | `nist-metaschema-MAKE-XML-MAP.xsl` | `docs/{...}/generated/abc-xml-map.html` | none |
| **JSON docs generation** | `nist-metaschema-MAKE-JSON-DOCS.xsl` | `docs/{...}/generated/abc-json-schema.html` | none |
| **JSON map** | `nist-metaschema-MAKE-JSON-MAP.xsl` | `docs/{...}/generated/abc-json-map.html` | none |
| **Schematron generation** | `nist-metaschema-MAKE-XML-METATRON.xsl` | `{ tbd }/abc-metatron.sch` | none |

\* Note: It appears the 'indent' parameter has not yet been exposed in this shell; the value presently defaults to "yes". In the past we have created a minified version with a JSON tool.

**Comment by david-waltermire-nist** [comment]
I created a [metaschema-m4-integration](https://github.com/david-waltermire-nist/OSCAL/tree/metaschema-m4-integration) branch where we can stage all changes.

**Comment by david-waltermire-nist** [comment]
The [metaschema-m4-integration](https://github.com/david-waltermire-nist/OSCAL/tree/metaschema-m4-integration)  integration branch has a working version of this.
