### ISSUE TITLE
Update OSCAL schemas to latest (M4) Metaschema models

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#724]
# User Story:

The new Metaschema implementation (XSLT-M4) brings new features and capabilities, but current OSCAL schemas in the OSCAL repo are not valid to its models in several respects (for example, syntax of local definitions).

Updated versions of all the OSCAL schemas have been produced in the Metaschema repo, here:

https://github.com/wendellpiez/metaschema/tree/issue39-pipeline-refactor/test-suite/oscal

These can serve as a basis for further editing.

## Goals:

The main OSCAL metaschemas in the OSCAL repo should be updated. While reflecting new syntax and working with new tools, the new metaschemas should be functionally equivalent (describe the same models) as the schemas they replace, and any data valid to the Milestone 3 model should still be valid.

The refreshed metaschemas must run successfully through the (new) XSLT-M4 infrastructure, validating to its copies of Metaschema XSD and Schematron, and producing useful outputs when run through production pipelines.

All current OSCAL schemas and schema modules must be accounted for.

## Dependencies:

Stable scripting from CL and under CI/CD, to run all necessary integrations and validation checks against XSLT-M4.

Also, the Metaschema branch to be targeted as a submodule of an OSCAL branch must be identified so correct (XSLT-M4) resources are available, if not as `usnistgov/metaschema/master` then something else.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by brianrufgsa** [comment]
# Status 3-Sept-2020

This is dependent on the work in issue #721, which is just starting.

**Comment by wendellpiez** [comment]
**Update Sep 24**

@david-waltermire-nist has been making progress on this Issue, not only confirming M4 syntax but enhancing and improving the metaschemas, starting with the metadata metaschema module.

**Comment by brianrufgsa** [comment]
# Status 8-Sept-2020
Significant progress has been made. 
@david-waltermire-nist is focused on catalog, profile, an implementation layers including common models (metadata and back-matter).
@brianrufgsa is focused on assessment and assessment results layers.

**Comment by brianrufgsa** [comment]
# Status 15-Oct-2020
Completed initial pass on assessment and assessment results layers. 
Compiled schemas and using them to test/adjust sample files.

Working out some issues, especially where inheriting from other metaschemas. Working toward fully valid files by making only intended file changes and ensuring the schemas still validate the files.

**Comment by brianrufgsa** [comment]
# Status 22-Oct-2020

Made some progress validating existing sample files against sample files. Need to make another pass now that other aspects of the metaschema are updated, plus evaluate additional opportunities to add constraints.

**Comment by david-waltermire-nist** [comment]
This work is complete in PR #758. This issue will be closed when the PR is processed.
