### ISSUE TITLE
OSCAL schema documentation revamp (main schema docs pages) for Metaschema M4.

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#725]
# User Story:

With changes and new features in Metaschema (see #721) come new requirements for documentation.

Enhancements in two areas need to be reflected in usable documentation:

* Capability to write local definitions overriding global (general) definitions
* Capability to define constraints to be enforced with "precision targeting" i.e. nested and conditional constraints
  * Enumerated value testing, but also
  * Key/keyref (index) checking ("am I related to one of those?"); uniqueness requirements
  * Regex pattern matching
  * Cardinality checking (there must be at least one, two, no more than eight, 20, x)
  * Value comparison ("this should be greater than that other thing")

Splitting this further into Issues could make sense.

## Goals:

- [ ] Integrate new production pipeline for generated schema documentation into Hugo
- [ ] Extend documentation (see usnistgov/metaschema#48):
  - [ ] Local definitions
  - [ ] `use-name`? (Hasn't been well tested yet: tbd.)
  - [ ] Constraints (various types, indexed to targets)
  - [ ] Various mop up / tbd

It might be necessary to triage these features and/or refactor design, to achieve usable results. (For example, break out constraints descriptions into a separate page.)

## Dependencies:

#721, #724

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Refactored this Issue to exclude the model maps, now in Issue #750.

**Comment by wendellpiez** [comment]
**Update Sep 24**

Next step on this is to create a mockup of the target for focusing design work.

**Comment by wendellpiez** [comment]
# Update Nov 5

Work proceeds here: https://github.com/wendellpiez/metaschema/tree/issue48-m4-schemadocs

**Comment by wendellpiez** [comment]
**Update Dec 3 2020**

Work continues; much progress. 85% done on revamp.

Need a little help from @david-waltermire-nist on git alignment.

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #758.
