### ISSUE TITLE
Validating extra-schema constraints (requirements) over JSON (JSONatron) under XSLT-M4 Metaschema

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#726]
# User Story:

One feature is still not implemented in the new Metaschema toolkit, namely the capability to generate a Schematron that will function to enforce constraints declared in the Metaschema, over JSON data.

An XSLT exists that can produce this Schematron to work over XML conformant to a given metaschema. Other logic exists that will perform the path mapping from such a Schematron, to an alternative version that should work equivalently over equivalent JSON. Applying this logic to the XSLT operative over the XML, its logical equivalent can be produced programmatically.

This is experimental, has not been tested, and may (in testing) expose small glitches or anomalies between the way XML and JSON are addressed, which require resolution or workarounds.

On the other hand, demonstrating this capability will be _unreal_, especially with a live example illustrating meaningful constraints.

## Goals:

Complete and demonstrate functionality of enforcing Metaschema constraints over JSON.

The goal of #725 (docs revamp), including documentation of constraints, is _not_ a goal or dependency for this Issue, although documenting the constraints is key to demonstrating them.

Helping to make error messages as clear as possible to work operationally (in either/both XML or JSON, with any necessary adjustments) _is_ a goal, as this is part of JSONatron functionality.

## Dependencies:

This issue is also tracked here:  usnistgov/metaschema-xslt#12

Part of this work entails copying or contriving a Schematron shell that can consume JSON and put it through a transformation pipeline, delivering SVRL. @david-waltermire-nist has one of these.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by shaila309** [comment]
How to get access of the Schematron shell that can consume JSON to validate extra-schema constraints?

**Comment by wendellpiez** [comment]
@shaila309 this is work under development. We have a Schematron fork at https://github.com/usnistgov/schematron where we intend to address this. @david-waltermire-nist can update you as to its current status. In any case, Schematron can be wrapped in a pipeline that can parse the JSON into an XML structure. We know both how to convert this into analogous XML OSCAL (that is what the format converters do) and also how to address it for purposes of rules assertion (Schematron). But we have not yet fielded the capability.

**Comment by aj-stein-nist** [comment]
Because this issue pertains to the Metaschema Framework and the XSLT implementation at a layer below OSCAL and not the OSCAL models itself, I will leave usnistgov/metaschema-xslt#12 for now.
