### ISSUE TITLE
Create SP 800-53B Baselines in OSCAL

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#727]
# User Story:

As an OSCAL user, I need the Special Publication 800-53B baselines in OSCAL format. These baselines are currently [published](https://csrc.nist.gov/publications/detail/sp/800-53b/draft) as draft.

## Goals:

Generate OSCAL Profiles for the following SP 800-53B baselines:

- [ ] Low baseline
- [ ] Moderate baseline
- [ ] High baseline

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by wendellpiez** [comment]
**Update Aug 13 2020**

Control lists for the baselines have been extracted from the Word doc. Reusing an old XSLT to produce OSCAL profiles from these. Nearly done. Need some feedback from @david-waltermire-nist on finalizing requirements

* `priority` properties?
* Privacy baseline?

**Comment by wendellpiez** [comment]
**Update August 26**

See WIP in branch linked above.

**Comment by wendellpiez** [comment]
Just made #733 for review.
