### ISSUE TITLE
Review the SP 800-53B Baselines (rev5) in OSCAL

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#730]
# User Story:

As an OSCAL user, I need to ensure the Special Publication 800-53B baselines represented in OSCAL format are accurate. These baselines are currently [published](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53B-draft.pdf) as a draft.
 
## Goals:

Review the OSCAL Profiles for the following SP 800-53B baselines:

 -[ ] Low baseline
 -[ ] Moderate baseline
 -[ ] High baseline

## Dependencies:

#727 

## Acceptance Criteria

All three profiles of the OSCAL SP800-53B baselines have been reviewed and are accurate.

**Comment by wendellpiez** [comment]
**Update Aug 13 2020**

Circulating initial extraction (lists of controls and enhancements, cf #727) with FISMA team.

**Comment by iMichaela** [comment]
## 8/27/2020

The review was completed and the PR #733 approved. This issue can be closed.
