### ISSUE TITLE
Broken "Improve this page" link and timestamp at bottom of Profile Resolution documentation page

### ISSUE THREAD

**Issue by joshualubell** [usnistgov/OSCAL#739]
# Describe the bug

Clicking on "Improve this page" link results in a 404. Also "last updated" timestamp is January 1, 0001.

# Who is the bug affecting?

Readers of the Profile Resolution documentation.

# What is affected by this bug?

https://pages.nist.gov/OSCAL/documentation/processing/profile-resolution/

# When does this occur?

When a user wants to suggest improvements to the page or wants to know when the page was last updated.

# How do we replicate the issue?

1. Go to https://pages.nist.gov/OSCAL/documentation/processing/profile-resolution/
2. Scroll to the bottom of the page.
3. Look at "last updated"
4. Click on "Improve this page" link.

# Expected behavior (i.e. solution)

Correct timestamp and functioning "Improve this page" link

**Comment by david-waltermire-nist** [comment]
Closed by merging PR #995 with modifications.
