### ISSUE TITLE
Build errors pushing to master on forks of repositories under CI/CD

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#747]
# Describe the bug

See an example (hope it works) at https://github.com/wendellpiez/fedramp-automation/runs/1062394081

We get an authentication error because pushing to `master`. This should only happen in the "home" repository (in this case, the fedramp repo not the wendellpiez fork).

# Who is the bug affecting?

Anyone forking a repository using this CI/CD logic, who wishes to keep their master branch in synch with upstream.

# What is affected by this bug?

Not able to push a clean build.

# When does this occur?

Anytime pushing to `master` (e.g. after a rebase).

# Expected behavior (i.e. solution)

Make the operation conditional on the repository as well as the branch, so forks do not execute it?

**Comment by david-waltermire-nist** [comment]
This has been fixed in https://github.com/usnistgov/oscal-content (PR usnistgov/oscal-content#18) and https://github.com/GSA//fedramp-automation (PR GSA/fedramp-automation#57).
