### ISSUE TITLE
Typescript implementation of XSLT transformation under SaxonJS / node JS

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#749]
# User Story:

Working forward to Typescript support of Metaschema operations (as well as OSCAL operations such as profile resolution), we need the capability to apply XSLT 3.0 transformations. The SaxonJS processor supports this. A simple script to invoke Saxon, apply a transformation to an XML document, and save the result, can serve as a prototype for any such operation.

## Goals:

A script implemented in Typescript under nodeJS that can accept a Metaschema as input and produce an XSD using the Metaschema XSD-generation transformation (in the Metaschema submodule).

This script can be hard-coded with respect to the transformation it applies. For the operator, it is a black box (not readily apparent that it calls Saxon), accepting a valid Metaschema as input, and producing the corresponding XSD as result.

To run in SaxonJS, an XSLT transformation must first be compiled into `SEF` format. For simplicity, this operation can be out of scope for this work - let's assume the SEF file representing the transformation has been produced and is available in the same location as the XSLT from which it is derived.

## Dependencies:

@wendellpiez has some hello-world work in a repo which will be pushed to a branch and linked.

We also need to address (longer-term) the issue of producing and maintaining the SEF files for any XSLT -- ideally from SaxonJS under nodeJS as well (or alternatively SaxonHE, since it can be done once at commit time for any XSLT).

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by brianrufgsa** [comment]
# Status 3-Sept-2020

@wendellpiez and @avdouglas-nist to schedule initial meeting for 4-Sept. 
@nikitawootten-nist may join unless/until assigned other tasking.

**Comment by wendellpiez** [comment]
We've made significant progress on this but we have also encountered problems.

@avdouglas has a working branch with WIP. It includes some testing infrastructure that I have provided to help support debugging failures.

At least one failure is due to a bug in SaxonJS, which is a blocker, insofar as it disables some of our (conformant) XSLT. Specifically, the XSLT `key()` function (which we use widely) can fail as reported at https://saxonica.plan.io/issues/4624. At time of writing a repair has been made but not released.

How and whether to work around this may depend on time lines.

**Comment by wendellpiez** [comment]
**Update Sep 24**

We need to discuss how to stabilize and retain the tests we have developed, which include useful basis for further work. See https://github.com/avdouglas-nist/OSCAL/tree/issue749-xslt-ts (also in my repo).

Then we need to discuss the longer-term strategy for running XSLTs within Typescript, since SaxonJS remains non-viable at least until their bug fix is deployed in the next release.

**Comment by david-waltermire-nist** [comment]
Can you post the code in this issue before I close this?

**Comment by wendellpiez** [comment]
Zipped copy here: [typescript-xslt.zip](https://github.com/usnistgov/OSCAL/files/5312860/typescript-xslt.zip)
