### ISSUE TITLE
OSCAL Model Review meeting summary to be posted

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#752]
# User Story:

As an OSCAL user, I would like to have the slides used for the Leveraging Authorization presentation and the summary of the conversation posted on the OSCAL website.

## Goals:

Have the presented Leveraged Authorization slides and the summary of the discussion posted on the OSCAL website.

===========

## Agenda for the OSCAL Model Review Teleconference (9/4/2020)
- Review the updated approach for leveraging existing authorizations when the leveraging system’s owner has access to the leveraged system’s SSP.
- Open discussion.

## Note
Brian Ruf presented the slides

## Topics Discussed
- The issue of getting access to the leveraged system’s assessment methods (examine, interview, test) information was raised and the need of providing this information in the customer responsibility matrix was discussed. This information will be used by the owner of the leveraging system to review the assessment methods used for the assessment of the leveraged system. 
- The leveraged system and leveraging system will have their own profiles that will indicate which assessment methods were to be used but being able to display possible deltas between these profiles was discussed and highlighted as being important. 
- The issue of a leveraging system occasionally requiring a higher rigor for the assessment of a particular control implementation than the documented assessment method for that inherited control implementation from the leveraged system was also discussed.
- System audit and continuous assessment require other assessment methods, different than the ones listed in SP800-53A (e.g. inspection, inquiry, observation, reperformance for audit or atteestation for FedRAMP tailored baselines). The need for supporting additional assessment methods, different than the ones mentioned in SP800-53A, was highlighted.
- Questions were asked regarding the UUIDs and how to use them (globally or in the scope of a document). The conversation on this topic continued on Gitter after the meeting.

==========

## Dependencies:

none

## Acceptance Criteria:

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
Several very interesting topics related to (but also going beyond) leveraged authorization were discussed in this call. Summary above gives more details.

Some of these issues, such as the transparency required to integrate resources (SSPs) that do not share a baseline, or the need to share assessment plan-level info (regarding how a leveraged system's implementation is assessed) as well as component info in the context of the CRM, may be addressed by current capabilities or by simple ad-hoc extensions. Examples will help determine this.

**Comment by jasswalkjr** [comment]
I can't believe I missed this discussion!! Looking forward to the slides and additional information.
