### ISSUE TITLE
Git submodules unnecessarily use ssh increasing the difficulty to use CICD tools.

### ISSUE THREAD

**Issue by butler54** [usnistgov/OSCAL#753]
# Describe the bug
OSCAL submodules today are authenticating over ssh. This requires the context of a system that is performing `git clone --recursive https://github.com/usnistgov/OSCAL.git cannot be anonymous. It must have an ssh key and an account in github.

This is less about 
# Who is the bug affecting?
- End users who wish to remain anonymous and clone OSCAL including sub-modules
- CI/CD systems where you typically do NOT want to rely on users ssh keys if possible (for example travis-ci).

# What is affected by this bug?
Ability to clone over https w/o requiring ssh keys. Work around would be to individually clone the sub-modules.

# When does this occur?
When executing the following commands when there is no ssh key available which will authenticate with github.
`git clone --recursive https://github.com/usnistgov/OSCAL.git`
or 
```shell
git submodule add https://github.com/usnistgov/OSCAL.git nist-source-location
git submodule update --init --recursive
```

# How do we replicate the issue?
Move your github ssh key outside of the search path of ssh (e.g. move from `~/.ssh/id_rsa` to almost anywhere else and execute either of the commands above.

# Expected behavior (i.e. solution)
Ideally the git submodules in the OSCAL repo will be cloned over https as opposed to ssh.

# Other Comments
This is a tiny bug / improvement.

**Comment by david-waltermire-nist** [comment]
We use git over SSH, for development. I can see where this may be an issue for users that are using HTTP.

I can update these submodules to use https.

In the mean time, you can configure your git client to use HTTP in place of SSH using the following:
```
# using https in place of git
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```

Once I make the change, we can use SSH instead of HTTP as follows:

```
# using git in place of https
git config --global url."git@github.com:".insteadOf https://github.com/
git config --global url."git://".insteadOf https://
```

**Comment by butler54** [comment]
Thanks - much appreciated and agree there are multiple methods around this. There is no clean approach for every use-case.

**Comment by david-waltermire-nist** [comment]
Added instructions in CONTRIBUTING.md in PR #759 on how to use SSH instead of HTTP. This PR now will default submodules to use HTTP.
