### ISSUE TITLE
JSON schema gaps in "implementation" layer

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#77]
To support #74, below is a list of gaps identified in JSON schema that will need to be addressed:

- "Implementation" will require one to reference specific controls included in a "profile"
  - JSON schema has no way of validating a particular controlId/subcontrolId value against a list of controlId/subcontrolId values specified elsewhere (i.e. a "profile")
  - this will be addressed in a future JSON schema spec via the proposed `$data` element per https://github.com/json-schema-org/json-schema-spec/issues/51
  - but this also begs the question: is this validation scenario the responsibility of the OSCAL schema itself or the tooling that consumes the OSCAL "implementation" layer
- cross-referencing in any capacity as will be required in different facets of the "implementation" layer is going to result in the end user having to duplicate text
  - since this type of duplication seems to be apparent in the "catalog" and "profile" layers, should we disregard this as a concern for the "implementation" layer as well?
  - YAML solves this problem nicely via anchors, extends and reference types ... but neither JSON nor XML can address this
    - Should we allow the use of YAML, JSON schema has no way of validating YAML anchor, extends nor reference semantics

CC @gregelin

**Comment by anweiss** [comment]
@david-waltermire-nist should we move/replace this issue?

**Comment by david-waltermire-nist** [comment]
We need to meet to work out a strategy for this.

**Comment by wendellpiez** [comment]
** Sprint 23 Progress Sep 5 **

This Issue is on hold pending further work on requirements.

My $0.02 is that such validations should perhaps be accomplished using Schematron or similar application code, at least until we can define a generalized mechanism for validating referential integrity across data sets (defined dynamically and changing over time).

**Comment by david-waltermire-nist** [comment]
This is being worked on in issue #633. Some aspects that are not supported in JSON Schema, will be addressed by a JSON-based Schematron validation.
