### ISSUE TITLE
Replace remaining singleton or array with array in JSON Schemas

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#770]
# Describe the bug

Some JSON schema still use the singleton or array construct.

The following was reported by @butler54 on [Gitter](https://gitter.im/usnistgov-OSCAL/Lobby).

So quick question for the team. From my understanding some of the model updates over the last few months provided some simplifications to minimize the use of ‘anyOf’ within the json schema.

Specifically there were may cases which looked like this:

```
          "annotations" : 
          { "anyOf" : 
            [ 
              { "$ref" : "#/definitions/annotation" },

              { "type" : "array",
                "items" : 
                { "$ref" : "#/definitions/annotation" },
                "minItems" : 2 } ] },
```

which were replaced with a simpler form like this:

```
          "annotations" : 
          { "type" : "array",
            "minItems" : 1,
            "items" : 
            { "$ref" : "#/definitions/annotation" } },
`

Are the remaining cases intentional? or is that something I should raise a bug /issue on?

# Who is the bug affecting?

All users of the affected JSON schemas.

# Expected behavior (i.e. solution)

These constructs should be replaced with simple arrays.

**Comment by butler54** [comment]
Here is the current list we found against the latest release in master: 
```
assessment_plan:    objectives
assessment_results:    objectives
component:    annotations
ssp:    annotations
target:    annotations
```

**Comment by wendellpiez** [comment]
XPath to run over any metaschema instance *and* its modules (can be done in batch):

* `//group-as[empty(@in-json)]` shows `group-as` that need `in-json='ARRAY'` to avoid the default `SINGLETON_OR_ARRAY`.
* `//group-as[not(@in-json='ARRAY']` shows anything being grouped without setting 'ARRAY', including the foregoing but also those with `in-json='BY_KEY'`, which are presumably okay
* `//define-field` will pull all field definitions. Use these predicates in combination to filter them further:
  * `[exists(flag|define-flag)]` keeps only fields with flags defined
  * `[empty(json-value-key)]` shows fields with no `json-value-key` set

To execute XPath on multiple files together in oXygen:

* Ctrl-select the group of files in the Project View
* Select from right-mouse (context menu): **XPath in Files**
* An **XPath/XQuery Builder** View will open. Enter and execute the XPath there. At the top, its scope should be set to "Selected project resources" (with your files still selected in the Project View).

Also to do on this item: provide Schematron check with rules to validate these.

**Comment by david-waltermire-nist** [comment]
I used `//define-field[exists(flag|define-flag) and empty(json-value-key)]` to look for missing `json-value-key` entries.

**Comment by david-waltermire-nist** [comment]
Reviewed all schema using `//group-as[empty(@in-json) or @in-json='SINGLETON_OR_ARRAY']` and found no occurrences.
