### ISSUE TITLE
Profile Resolution Dropping Parameter Select Content

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#771]
# Describe the bug

When generating a resolved profile catalog, where the original control includes a parameter with a `select` assembly, the `select` assembly and its internal content is dropped.

For example, in the 800-53r4 OSCAL Catalog, AC-7, parameter #3 appears as follows:
```
         <param id="ac-7_prm_3">
            <select>
               <choice>locks the account/node for an <insert param-id="ac-7_prm_4"/>
               </choice>
               <choice>locks the account/node until released by an administrator</choice>
               <choice>delays next logon prompt according to <insert param-id="ac-7_prm_5"/>
               </choice>
            </select>
         </param>
```
If AC-7 is called by a profile, the resolved profile catalog incorrectly reflects the following for the above:

```
         <param id="ac-7_prm_3" />
```

# Who is the bug affecting?

Everyone using the profiler resolver transform

# What is affected by this bug?

Incorrect representation of parameters containing `select` content. 

# When does this occur?

Every time the profile resolver is used.

# How do we replicate the issue?

1. Create a profile that calls a control containing a parameter with a select statement. 
(See attached test profile - much change .txt back to .xml for processing)
[profile-test.txt](https://github.com/usnistgov/OSCAL/files/5391534/profile-test.txt)

1. Run the profiler resolver transform
1. Observe the control in the resolved profile catalog.

# Expected behavior (i.e. solution)

The profile resolver should duplicate all content from inside the parameter assembly to the resolved profile catalog, including the `select` assembly.

**Comment by david-waltermire-nist** [comment]
This issue looks like it was addressed.
