### ISSUE TITLE
Consider FedRAMP OSCAL Guidance for NIST Reuse

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#772]
# User Story:

FedRAMP developed guidance on OSCAL adoption, which could benefit NIST's online OSCAL documentation efforts.
As an OSCAL documentation content developer, it would be helpful to selectively adjust and adopt the FedRAMP content and publish it for the benefit of all OSCAL users

## Goals:

- Identify relevant portions of OSCAL guidance in the [FedRAMP Guidebooks](https://github.com/GSA/fedramp-automation/tree/master/documents)
- Modify the content as needed to apply generally to OSCAL rather than specifically to FedRAMP
- Publish to the correct portions of the [NIST OSCAL web site](https://pages.nist.gov/OSCAL)

## Dependencies:

None

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by brianrufgsa** [comment]
# Status 5-Nov-2020
@david-waltermire-nist and @brianrufgsa reviewed the Guide to OSCAL-based FedRAMP Content as well as the FedRAMP OSCAL registry and formulated changes to the OSCAL syntax resulting - in part - from that review. Many changes were included in issue #777.

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #758.
