### ISSUE TITLE
Systems

### ISSUE THREAD

**Issue by azitennis50** [usnistgov/OSCAL#773]
# Describe the bug

{A clear and concise description of what the bug is.}

# Who is the bug affecting?

# What is affected by this bug?

{Describe the impact the bug is having.}

# When does this occur?

{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?
1. Do this...
1. Then this...
1. See error

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by bradh** [comment]
Not sure what you were trying to do here, but you probably need to edit the bug report to provide details.

Or just close it if this was in error.

**Comment by david-waltermire-nist** [comment]
I am going to close this. @azitennis50 Please submit a new bug with details if you have something for us to work on.
