### ISSUE TITLE
Email for joining the oscal-updates mailing list bounces

### ISSUE THREAD

**Issue by tcorsa** [usnistgov/OSCAL#781]
Emails sent to the email address provided at https://pages.nist.gov/OSCAL/contact/ for subscribing to the oscal-updates mailing list (oscal-updates-subscribe@nist.gov) are bouncing with the following error:

"Message blocked
Your message to oscal-updates-subscribe@nist.gov has been blocked. See technical details below for more information.
The response from the remote server was:
550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [BL0GCC02FT001.eop-gcc02.prod.protection.outlook.com]"

# Who is the bug affecting?
That I know of, only me. But Michaela stated that an issue should be created for this.

# What is affected by this bug?
If this bug is impacting anyone who sends a request, people will not be able to join the mailing list.

# When does this occur?
When sending an email to the provided address.

# How do we replicate the issue?
1. Send an email to the address.
2. Wait for the response.

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)
I'd expect that I would receive an email directing me to the Google Groups subscription page (i.e. same behavior as sending an email to the developers list address provided on the same contact page).

**Comment by iMichaela** [comment]
@tcorsa Thank you for pointing it out. All NIST mailing lists were migrated to a different service. **ALL** mailing lists need to be updated from "@nist.gov" to "@list.nist.gov". 

Also the subscribing and unsubscribing information:
To subscribe from this group, send email to [oscal-updates+subscribe@list.nist.gov](mailto: oscal-updates+subscribe@list.nist.gov)
To unsubscribe from this group, send email to [oscal-updates+unsubscribe@list.nist.gov](mailto: oscal-updates+unsubscribe@list.nist.gov)

Similar changes are needed for the oscal-dev@list.nist.gov

**Comment by brianrufgsa** [comment]
# Status 12-Nov-2020

Made this change in my website-updates branch along with changes for issue #776. PR will be created as soon as one final task in that issue is finished.

**Comment by brianrufgsa** [comment]
Also fixing within the OSCAL repo CONTRIBUTING.md in follow-up PR TBD ( as part of issue #765).
