### ISSUE TITLE
Broken link on OSCAL documentation page

### ISSUE THREAD

**Issue by tcorsa** [usnistgov/OSCAL#782]
# Describe the bug
At https://pages.nist.gov/OSCAL/documentation/schema/catalog-layer/catalog/json-schema/#base64, the link provided for the type base64Binary points to a page (https://pages.nist.gov/OSCAL/documentation/schema/catalog-layer/datatypes/#base64binary) that is not found.

# Who is the bug affecting?
Anyone looking for that information.

# What is affected by this bug?
I'm designing my classes for deserializing OSCAL files and eventually need to know how I'll want to handle the type in question.

# When does this occur?
Clicking the link.

# How do we replicate the issue?
1. Click the link.
2. See the error.

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)
Direct to a valid page.

# Other Comments

{Add any other context about the problem here.}

**Comment by david-waltermire-nist** [comment]
This is similar to #702 and will be addressed by the same fix.
