### ISSUE TITLE
Metaschema Allowed Values

### ISSUE THREAD

**Issue by brianrufgsa** [usnistgov/OSCAL#783]
# User Story:

There are several locations in the metaschema where the allowed values list requires updating to ensure definitions are clear and the value list is both sane and complete.

## Goals:

- Review all models to ensure allowed value lists are complete, and each choice has an appropriate definition associated with it.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by brianrufgsa** [comment]
@david-waltermire-nist should oscal-version have allowed values for the recognized OSCAL versions?  

If so, which should we include?
We also have to consider not every model is available in every version.

**Comment by brianrufgsa** [comment]
Verbally Dave articulated that we intend to start using allowed values here with the first official OSCAL 1.0.0 release.

**Comment by brianrufgsa** [comment]
# Status 3-Dec-2020
@david-waltermire-nist and @brianrufgsa made significant progress on this. Expect to wrap up by 10-Dec.

**Comment by brianrufgsa** [comment]
# Status 10-Dec-2020
Although @david-waltermire-nist and @brianrufgsa continued to work on this, we are not quite finished, due in part to additional refactoring analysis and syntax adjustments.

The catalog and profile layers have been addressed. The implementation layer is nearly complete. The assessment layer still requires work.

The goal is to wrap up what we can this week.

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #758.
