### ISSUE TITLE
OSCAL M3->RC1 content converter

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#785]
# User Story:

The current content conversion pipeline supporting upgrades to OSCAL data needs to be updated to make changes to data from earlier Milestone versions, to the new OSCAL RC for 1.0.0 (here referred to as RC1).

This mainly entails some mapping of names, with no big changes to structures.

A transformation that supports conversion into OSCAL from earlier OSCAL also needs to be able to reassign UUIDs to elements, or not, as configured. If UUIDs are not to be assigned where they were not found, UUID reassignment could be pulled out as a separable step.

## Goals:

Enable users who have OSCAL data to update their data to current OSCAL models, as easily as possible. So far we have enabled this via XSLT transformation.

A pipeline to support this will be developed, tested and documented in the `src/release/content-upgrade` directory as previously. The basic goal is to convert M3 to M4. if it converts an earlier OSCAL into M4 (without having to convert it into M3 first), so much the better.

Retaining an ability to convert into M3 (for example, M2->M3) is *not* a goal, unless it is useful as a step on the way to M4.

- [ ] M3->RC1 content converter (nominally handles any OSCAL model)
- [ ] UUID refresher
- [ ] readme and other support materials (inline comments etc.)

## Dependencies:

In the M4 metaschemas, comments with a keyword `CHANGED` indicates where there are changes from M3.

A separate analysis must also be conducted to compare M3 and M4 models and elicit deltas, but the documented changes are easy gets. Previous work on comparing models programmatically can be found in the metaschema repository. Even though the Metaschema format has changed, this could be useful. Sample data sets will also be useful including FedRAMP examples.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
This issue was addressed by PR #758.
