### ISSUE TITLE
Differences between "Component" object in "System Security Plan" Model vs "Component Definition" Model

### ISSUE THREAD

**Issue by tcorsa** [usnistgov/OSCAL#786]
{Please enter your question.}
I'm not sure if this is intentional, but the properties described for the "Component" object differ slightly based on the context it's being referenced in. 

See the following two links:
https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/component/json-schema/#oscal-component-json_component
https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/ssp/json-schema/#component

Either way isn't a problem for me.

Regards,
Todd

**Comment by david-waltermire-nist** [comment]
The following property names are present in the SSP component, but not the component-defintion component:
- **implementation-point:** Relative placement of component ('internal' or 'external') to the system.
- **inherited-uuid:** UUID of the component as it was assigned in the leveraged system's SSP.
- **leveraged-authorization-uuid:** UUID of the related leveraged-authorization assembly in this SSP.

These are only needed in the SSP model as part of the SSPs support for leveraged authorizations. 

All other property names appear in both types of "components".

The only other difference between the two models are:
- The SSP variant has a "status" to indicate the implementation state within the system.
- The component-definition variant has "control-implementations" to define how the component implements a set of controls. This is represented in the SSP under `/system-security-plan/control-implementation` with a similar model for `implemented-requirements`. The difference here is that all requirements in the component-definition apply to the same component. In the SSP, the `by-component` syntax is used to identify which requirements are supported by a given component.

I am going to close this issue for now with this answer. If you have any additional concerns, we can reopen the issue and address them.
