### ISSUE TITLE
OSCAL Documentation page is missing a quick access menu

### ISSUE THREAD

**Issue by Ikendiken** [usnistgov/OSCAL#787]
# User Story:

When using the OSCAL Documentation and the elements on the table of contents panel on the left extend beyond the bottom of the page then the user must scroll the content panel on the right to the bottom of the page in order to pull the additional table of content elements into view. This is most apparent for the format reference documentation sections which contain a large number of items.

Additionally, after selecting a table of contents element the view resets thus moving the displayed element's table of contents navigation shortcut out of view again.

## Goals:

To improve usability, it would be nice if the table of contents panel scrolled the highlighted content item into view and there was a quick access menu for the format reference elements.

My preference would be to display the elements of the format reference sections in a popup menu where I could quickly select the item to view the detail.

**Comment by david-waltermire-nist** [comment]
This was addressed in PR #905.
