### ISSUE TITLE
Refine SP800-53 OSCAL extraction and enhancement

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#8]
The current copy of SP800-53/53A, in OSCAL, is produced programmatically by XSLT running over the NVD XML, which maps its XML format. Results are consistent but could use further enhancement, if not by extending the XSLT then by post-process. Requirements include:

  * Address duplication of 'withdrawn' data e.g. AC-13
  * Infer and tag links between controls
  * Infer and tag parameter assignments and parameter defaults
  * Infer and tag "withdrawn" entries
  * Add ID attributes everywhere
  * Add a few  'number' properties missing but implicit in the source (e.g. on top-level 'objective' features) - cross-check the data for this
    * Clean correct complete data will support strong OSCAL declarations e.g. of inherited number assignments across controls, subcontrols and (certain) features

An earlier iteration of an XSLT for (some of) this is in lib/OSCAL-adjust.xsl.

Once this is done, the method for producing  SP800-53 XML in OSCAL (the entire chain) should be documented and the results validated by close review.

In this process we may also identify needs for manual enhancement.

**Comment by anweiss** [comment]
@wendellpiez has this been addressed and can we close?

**Comment by wendellpiez** [comment]
@anweiss Yes the Issue can be closed. It will come up again in the context of the rev5 conversion, but that is only now being planned. It will go away never to return, but only when we have a production pipeline for SP800-53 data (any revision) that includes robust quality checking by subject experts.

**Comment by david-waltermire-nist** [comment]
The SP 800-53 rev5 work will be addressed by #232. Closing this issue.
