### ISSUE TITLE
Ensure that all field and flag values require a non-empty value

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#805]
# Describe the bug

For some data types, the XML and JSON schema generated for the OSCAL models allow an empty value to specified. This occurs on XML elements and attributes and JSON properties that are derived from Metaschema fields and flags.

# Who is the bug affecting?

Users of the XML and JSON schemas for the OSCAL project.

# What is affected by this bug?

All generated XML and JSON schemas for the OSCAL project.

# Expected behavior (i.e. solution)

Empty text should cause a schema validation error. To remove this error, the content creator should remove the outer attribute, element, or property.

If this attribute, element, or property is required then an empty value should not occur, since this doesn't satisfy the outer requirement.

# Other Comments

{Add any other context about the problem here.}

**Comment by wendellpiez** [comment]
Relatively lightweight ways to deal with this in the interim:

* Use `matches` constraints in a Metatron implementation for this
* Introduce a new 'charstring' datatype (for example) and call it where wanted
* Refine `markup-line` and `markup-line` with extra constraints (over what is currently enforced).

NB there are other validations one might want such as `matches(.,'\w')`: it is hard to know where to draw the line here.

**Comment by wendellpiez** [comment]
Attached is an XSLT (zipped for handling) that produces a breakout listing of all fields and flags, by assigned type, or "[string]" (in brackets) if a string type by default. It polls all the metaschema documents in a collection (line 9). To run, place the XSLT next to a pile of metaschema documents and apply it to itself. The XSLT could be enhanced to give more info (now it only produces plain text listing definitions in their modules).

[metaschema-poll.zip](https://github.com/usnistgov/OSCAL/files/6117150/metaschema-poll.zip)

We can also use paths to find fields and flags by type -- `//define-field[@as-type='uri']` `//define-field[empty(@as-type)]` etc.

**Comment by wendellpiez** [comment]
To save a step: here is the result of running against the metaschemas in OSCAL/src/metaschema.

[metaschema-field-types.txt](https://github.com/usnistgov/OSCAL/files/6117185/metaschema-field-types.txt)

**Comment by wendellpiez** [comment]
Do this with #911. Remove DTD-based datatype definitions and provide for defense against empty strings.

**Comment by david-waltermire-nist** [comment]
This was addressed by PR #936 (merged with PR #948), which refactored data typing to require non-empty values for appropriate data types..
