### ISSUE TITLE
Metaschema enhancements for OSCAL (empty elements)

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#829]
# User Story:

New Metaschema enhancements will permit improvements in the OSCAL models. We need to review and manage these feature requests, staging them for implementation.

This is a tracking issue for them, to be accompanied (for testing) by the revisions to the OSCAL metaschemas.

Issues to be considered are here (bearing on empty elements):

- [x] usnistgov/metaschema#66
- [x] usnistgov/metaschema#49
- [ ] usnistgov/metaschema#33

Also to be considered: support for "ANY" in Metaschema (connected to #792 for example).

## Goals:

Improve Metaschema design and take advantage of the improvements in OSCAL.

## Dependencies:

None (this is a tracking issue). Updating the OSCAL metaschemas is dependent on support for the enhancements.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by wendellpiez** [comment]
This Issue can be closed.

Empty fields are now empty assemblies with these PRs: usnistgov/metaschema#119 #835 

Modeling issues respecting `include/all` are being addressed in $845.

**Comment by david-waltermire-nist** [comment]
This was further addressed by #805.
