### ISSUE TITLE
Profile Remove Statement Support for @ns

### ISSUE THREAD

**Issue by brian-ruf** [usnistgov/OSCAL#833]
# User Story:

When using the remove statement, in an OSCAL profile, it may be necessary to ensure the removal of content based on the value of `@ns` on a `prop`, `part`, or `annotation`. 

The absence of the `@ns` reference on a `remove` directive should be interpreted as only performing the remove on OSCAL syntax falling within the NIST OSCAL namespace itself. 

Along with this, the functionality should have the ability to have a wildcard, such as `*` as the value to indicate the item should be removed from all appropriate namespaces.

## Goals:

- Ensure profile remove statements can be properly scoped the intended namespace.
- Avoid unintentional removal of content belonging to framework-specific extensions.

## Dependencies:

None

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

## Additional Notes

If worked, and once complete, the profile resolver should be updated to honor this update.

**Comment by david-waltermire-nist** [comment]
Talked with @wendellpiez, and we agreed to add `@ns-ref` to `remove`. I'll work on this change.
