### ISSUE TITLE
Modeling non-technical "policies", "processes" and "procedures" in "implementation" layer

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#84]
*Challenges*
- Concepts vary across the domain ... different interpretations
- Confusing for experts
- Do we have any specific examples of these concepts?
  - 18F's Project Boise -> https://boise.18f.gov/

Update this issue as needed

**Comment by anweiss** [comment]
@david-waltermire-nist should this be moved/replaced by one of the more recent "implementation" issues created?

**Comment by david-waltermire-nist** [comment]
This is being worked in #363, #364, and #329. Closing.
