### ISSUE TITLE
Missing "prose" field in XML Outline

### ISSUE THREAD

**Issue by canb227** [usnistgov/OSCAL#847]
# Describe the bug

Catalog->Control->Part is missing the "prose" element in the XML Outline

Outline:
![image](https://user-images.githubusercontent.com/23513519/110825680-4f134180-8262-11eb-89d3-7f905762d620.png)
https://pages.nist.gov/OSCAL/documentation/schema/catalog-layer/catalog/xml-model-map/
<br/>
<br/>
<br/>
Metaschema:
![image](https://user-images.githubusercontent.com/23513519/110826655-4d964900-8263-11eb-8994-d7cc3779ef0b.png)
https://github.com/usnistgov/OSCAL/blob/master/src/metaschema/oscal_control-common_metaschema.xml#L22
<br/>
<br/>
<br/>
XML Reference Doc:
![image](https://user-images.githubusercontent.com/23513519/110826748-61da4600-8263-11eb-9983-0e11ad9d6ffd.png)
https://pages.nist.gov/OSCAL/documentation/schema/catalog-layer/catalog/xml-schema/##local_part-prose_def-h3
<br/>
<br/>
<br/>

# What is affected by this bug?

Documentation  

# How do we replicate the issue?
Firefox 87.0b8 (64-bit)
https://pages.nist.gov/OSCAL/documentation/schema/catalog-layer/catalog/xml-model-map/  

# Expected behavior (i.e. solution)
Prose should appear in the outline, either as an element or through some means of making it clear that <part> supports block text.

**Comment by wendellpiez** [comment]
![image](https://user-images.githubusercontent.com/1588228/111540711-dcb0ce80-8745-11eb-83c7-8fb6224a2363.png)

@stephenbanghart @david-waltermire-nist please feel free to suggest improved wording or style.

When the model repeats from an ancestor above the parent, it says "ancestor" (but not grandparent etc).

**Comment by wendellpiez** [comment]
![image](https://user-images.githubusercontent.com/1588228/111541980-880e5300-8747-11eb-9e15-4e932d1ea6fe.png)

This is when we have an 'unwrapped' markup-multiline object in the XML ... if wrapped it looks like `param/remarks` and says only 'markup-multiline' (with a link).

Let me know what you think @stephenbanghart @david-waltermire-nist
