### ISSUE TITLE
Misleading or incorrect recursion indicators in XML Format Outline

### ISSUE THREAD

**Issue by canb227** [usnistgov/OSCAL#848]
# Describe the bug

The XML Format Outline uses the `<tagname/> [0 to inf]` format to describe a recursive element, but this format leads the reader to believe that the recursed elements have no children (they do).  

Example (See part and control tags):
![image](https://user-images.githubusercontent.com/23513519/110827883-7e2ab280-8264-11eb-9cd6-38f988522745.png)
  

# What is affected by this bug?

Documentation

# How do we replicate the issue?
Firefox 87.0b8 (64-bit)  
https://pages.nist.gov/OSCAL/documentation/schema/catalog-layer/catalog/xml-model-map/
# Expected behavior (i.e. solution)

Should probably be represented using `<tagname>...</tagname> [0 to inf]` instead, or similar.

**Comment by wendellpiez** [comment]
New concept:

![image](https://user-images.githubusercontent.com/1588228/111542431-18e52e80-8748-11eb-9243-43f24ca4e318.png)

(It says 'parent' when it's a parent and 'ancestor' for a more distant ancestor.)

Comments welcome @stephenbanghart @david-waltermire-nist
