### ISSUE TITLE
XML Reference not correctly importing globally defined allowed-values

### ISSUE THREAD

**Issue by canb227** [usnistgov/OSCAL#849]
# Describe the bug

"Reference" is an allowed-value of "ref" in the globally defined link (defined in metadata), but does not appear in the reference page for link (except where locally defined in control.

XML Reference:
![image](https://user-images.githubusercontent.com/23513519/110828510-17f25f80-8265-11eb-9655-7243ba8fe967.png)
https://pages.nist.gov/OSCAL/documentation/schema/catalog-layer/catalog/xml-schema/##local_link-rel_def-h3
<br/>
<br/>
Allowed-values of the global link definition:
![image](https://user-images.githubusercontent.com/23513519/110828799-6a338080-8265-11eb-9d86-409a4afede8e.png)
https://github.com/usnistgov/OSCAL/blob/master/src/metaschema/oscal_metadata_metaschema.xml#L681
<br/>
<br/>
Locally defined allowed-value constraints for Control (for reference):
![image](https://user-images.githubusercontent.com/23513519/110829004-a666e100-8265-11eb-9b62-72378de9cef1.png)
https://github.com/usnistgov/OSCAL/blob/master/src/metaschema/oscal_catalog_metaschema.xml#L185
<br/>
<br/>

# What is affected by this bug?

Minimally documentation, potentially a wider issue.

# Expected behavior (i.e. solution)

The reference should have a globally allowed values section which is populated by the globally defined allowed values for a given field.

**Comment by wendellpiez** [comment]
Correction is behind https://github.com/usnistgov/metaschema/pull/127 should be good ...

Currently the constraints are given in the order they appear in the composed metaschema, which is arbitrary from the point of view of the reference and not ideal. Thoughts?

![image](https://user-images.githubusercontent.com/1588228/112345631-973b5680-8c9b-11eb-87e0-10cf89bb749e.png)
