### ISSUE TITLE
ICS files for meetings with the OSCAL community are not downloaded by browsers

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#852]
# Describe the bug

OSCAL website provides ICS files for the meetings with our COI. Lately, neither of the two ICS files can be downloaded. They get opened on a separate tab.

# Who is the bug affecting?

All people interested in joining the OSCAL meetings.

# What is affected by this bug?
The community's participation to our meetings

# When does this occur?
When clicking on the ICS file

# How do we replicate the issue?
Go to [https://pages.nist.gov/OSCAL/contribute/dev-lunch/](https://pages.nist.gov/OSCAL/contribute/dev-lunch/)  and click on the  [ICS file](https://pages.nist.gov/OSCAL/contribute/dev-lunch/lunch-with-the-devs.ics)

# Expected behavior (i.e. solution)
Clicking on the file should trigged downloading of the file.

Inspecting the element on the webpage, I do not see the `target="download"` inside the `<a>` tag. 

# Other Comments

**Comment by david-waltermire-nist** [comment]
The server configuration has been updated to respond with the correct media type, which resolves this issue.
