### ISSUE TITLE
Support Application Level-Constraints

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#856]
# User Story:

As an OSCAL content creator, I need to be able to verify that all required fields are provided and that all values match those allowed by the OSCAL models. The XML and JSON schema does not sufficiently enforce all of these constraints.

This is a tracker issue for other issues in the [usnistgov/metaschema](https://github.com/usnistgov/metaschema) repo, and is continuing the unfinished work from #633.

## Goals:

- Build, test and deploy constraints enforcement model (Metatron)
   - [x] Schematron generation (for enforcing constraints over XML)
      - [x] testing
   - [ ] JSONatron generation (for enforcing constraints over JSON)
     - [ ] testing
   - [ ] Integration of Metatron production
- (Re)design, build out and deploy updated schema documentation
    - [ ] Mockup or placeholder for constraints definitions

## Dependencies:

- [ ] Following on usnistgov/metaschema#17, usnistgov/metaschema-xslt#12 works on requirements analysis and design/development of constraint-checking features

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by aj-stein-nist** [comment]
@aj-stein-nist has to review and determine how to re-organize and scope it one or more issues. That, and it may need to be transferred or closed as it pertains to Metaschema processor implementations on one hand, but also the application and integration of it into OSCAL.

**Comment by aj-stein-nist** [comment]
This appears to be an issue describing the stabilization of early Metaschema-constraints as implemented in the reference implementation processor tools. The models already have and continue to define such application level constraints in OSCAL. This could be reopened if some specific feature or use requirement changes, but they the syntax and use has been stable for at least the last year. I will close this issue. If the team or community wish to reopen it, given the lack of specific requirements to OSCAL, we would need to move it to the "Needs Refinement" status to make it workable.
