### ISSUE TITLE
Review identifier scoping and uniqueness documentation

### ISSUE THREAD

**Issue by david-waltermire-nist** [usnistgov/OSCAL#860]
# User Story:

As an OSCAL content creator and consumer, I need clear guidance on the scope and uniqueness of identifiers used within the OSCAL models.

## Goals:

- [ ] Generate a list of identifiers used in the OSCAL models
- [ ] Review model documentation related to these identifiers to ensure their scoping and uniqueness is clearly stated.
- [ ] Add constraints to enforce uniqueness where possible.

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by Rene2mt** [comment]
The following are all the OSCAL model unique identifiers and their corresponding descriptions.  NOTE: there are a few typos (e.g. "refering" and "consistantly") that need to be fixed and some descriptions that may need to be expanded.

oscal\_assessment-common\_metaschema.xml
----------------------------------------

\[\] **Assessment Method Universally Unique Identifier** \- Uniquely identifies this defined assessment method. This UUID may be referenced elsewhere in an OSCAL document when refering to this information. A UUID should be consistantly used for a given assessment method across revisions of the document.  
\[\] **Assessment Activity Universally Unique Identifier** \- Uniquely identifies this assessment activity. This UUID may be referenced elsewhere in an OSCAL document when refering to this information. A UUID should be consistantly used for a given included activity across revisions of the document.  
\[\] **Event Universally Unique Identifier** \- Uniquely identifies an assessment event. This UUID may be referenced elsewhere in an OSCAL document when refering to this information. A UUID should be consistantly used for this schedule across revisions of the document.  
\[\] **Task Universally Unique Identifier** \- Uniquely identifies this assessment task.  
\[\] **Assessment Subject Placeholder Universally Unique Identifier** \- Uniquely identifies a set of assessment subjects that will be identified by a task or an activity that is part of a task.  
\[\] **UUID Reference** \- A pointer to a component, inventory-item, location, party, user, or resource using it's UUID.  
\[\] **Observation Universally Unique Identifier** \- Uniquely identifies this observation. This UUID may be referenced elsewhere in an OSCAL document when refering to this information. Once assigned, a UUID should be consistantly used for a given observation across revisions.  
\[\] **Actor UUID Reference** \- A pointer to the tool or person based on the associated type.  
\[\] **Task Universally Unique Identifier Reference** \- References a unique task by UUID.  
\[\] **Risk Universally Unique Identifier** \- Uniquely identifies this risk. This UUID may be referenced elsewhere in an OSCAL document when refering to this information. Once assigned, a UUID should be consistantly used for a given risk across revisions.  
\[\] **Party UUID Reference** \- A pointer to the party who is making the log entry.  
\[\] **Remediation Universally Unique Identifier** \- Uniquely identifies this remediation. This UUID may be referenced elsewhere in an OSCAL document when refering to this information. Once assigned, a UUID should be consistantly used for a given remediation across revisions.  
\[\] **Part Identifier** \- A unique identifier for a specific part instance. This identifier's uniqueness is document scoped and is intended to be consistent for the same part across minor revisions of the document.  

oscal\_assessment-plan\_metaschema.xml
--------------------------------------

\[\] **Assessment Plan Universally Unique Identifier** \- Uniquely identifies this assessment plan. This UUID must be changed each time the content of the plan changes.  

oscal\_assessment-results\_metaschema.xml
-----------------------------------------

\[\] **Assessment Results Universally Unique Identifier** \- Uniquely identifies this assessment results file. This UUID must be changed each time the content of the results changes.  
\[\] **Results Universally Unique Identifier** \- Uniquely identifies this set of results. This UUID may be referenced elsewhere in an OSCAL document when refering to this information. Once assigned, a UUID should be consistantly used for a given set of results across revisions.  
\[\] **Finding Universally Unique Identifier** \- Uniquely identifies this finding. This UUID may be referenced elsewhere in an OSCAL document when refering to this information. Once assigned, a UUID should be consistantly used for a given finding across revisions.  

oscal\_catalog\_metaschema.xml
------------------------------

\[\] **Catalog Universally Unique Identifier** \- A globally unique identifier for this catalog instance. This UUID should be changed when this document is revised.  

oscal\_component\_metaschema.xml
--------------------------------

\[\] **Component Definition Universally Unique Identifier** \- A globally unique identifier for this component definition instance. This UUID should be changed when this document is revised.  
\[\] **Component Identifier** \- The unique identifier for the component.  
\[\] **Capability Identifier** \- A unique identifier for a capability.  
\[\] **Component Reference** \- A reference to a component by its identifier  
\[\] **Control Implementation Set Identifier** \- A unique identifier for the set of implemented controls.  
\[\] **Control Implementation Identifier** \- A unique identifier for a specific control implementation.  
\[\] **Control Statement Implementation Identifier** \- A unique identifier for a specific control implementation.  

oscal\_implementation-common\_metaschema.xml
--------------------------------------------

\[\] **Component Identifier** \- The unique identifier for the component.  
\[\] **Service Protocol Information Universally Unique Identifier** \- A globally unique identifier that can be used to reference this service protocol entry elsewhere in an OSCAL document. A UUID should be consistently used for a given resource across revisions of the document.  
\[\] **User Universally Unique Identifier** \- The unique identifier for the user class.  
\[\] **Inventory Item Universally Unique Identifier** \- A globally unique identifier that can be used to reference this inventory item entry elsewhere in an OSCAL document. A UUID should be consistently used for a given resource across revisions of the document.  
\[\] **Component Universally Unique Identifier Reference** \- A reference to a component that is implemented as part of an inventory item.  

oscal\_metadata\_metaschema.xml
-------------------------------

\[\] **Location Universally Unique Identifier** \- A unique identifier that can be used to reference this defined location elsewhere in an OSCAL document. A UUID should be consistantly used for a given location across revisions of the document.  
\[\] **Party Universally Unique Identifier** \- A unique identifier that can be used to reference this defined location elsewhere in an OSCAL document. A UUID should be consistantly used for a given party across revisions of the document.  
\[\] **Annotated Property Universally Unique Identifier** \- A unique identifier that can be used to reference this annotated property elsewhere in an OSCAL document. A UUID should be consistantly used for a given location across revisions of the document.  

oscal\_poam\_metaschema.xml
---------------------------

\[\] **POA&M Universally Unique Identifier** \- Uniquely identifies this POA&M. This UUID must be changed each time the content of the POA&M changes.  
\[\] **POA&M Item Universally Unique Identifier** \- Uniquely identifies the POA&M entry. This UUID may be referenced elsewhere in an OSCAL document when refering to this information. A UUID should be consistantly used for a given POA&M item across revisions of the document.  

oscal\_profile\_metaschema.xml
------------------------------

\[\] **Catalog Universally Unique Identifier** \- A globally unique identifier for this profile instance. This UUID should be changed when this document is revised.  

oscal\_ssp\_metaschema.xml
--------------------------

\[\] **System Security Plan Universally Unique Identifier** \- A globally unique identifier for this catalog instance. This UUID should be changed when this document is revised.  
\[\] **Diagram ID** \- The identifier for this diagram.  
\[\] **Control Requirement Universally Unique Identifier** \- A globally unique identifier that can be used to reference this control requirement entry elsewhere in an OSCAL document. A UUID should be consistantly used for a given resource across revisions of the document.  
\[\] **Control Statement Reference Universally Unique Identifier** \- A globally unique identifier that can be used to reference this control statement entry elsewhere in an OSCAL document. A UUID should be consistantly used for a given resource across revisions of the document.  
\[\] **Component Universally Unique Identifier Reference** \- A reference to the component that is implementing a given control or control statement.  
\[\] **By-Component Universally Unique Identifier** \- A globally unique identifier that can be used to reference this by-component entry elsewhere in an OSCAL document. A UUID should be consistantly used for a given resource across revisions of the document.

**Comment by Rene2mt** [comment]
Please see changes on my fork (https://github.com/Rene2mt/OSCAL/commit/92c7a957c7ab4c64078538f71e1e5c3480de3a14).  If all looks okay, I'll do a PR.

**Comment by david-waltermire-nist** [comment]
This is addressed by PR #860, which still needs some work to get the text right.

**Comment by Rene2mt** [comment]
- Created a new documentation page under "contents" that provides a summary narrative on identifier user, including the most common identifier types in OSCAL, their uniqueness, and scope.  This documentation also attempts to describe which identifiers may be referenced when an OSCAL document imports another (e.g., AP imports SSP).
- All metaschemas have ben updated (pending review - see #1066 ). 
- WIP: html anchor links from metaschema documentation to identifier use page.  This has been added one a few of the control layer metashcemas.  To review, run the build tools (generates OSCAL XML and JSON) and then generate model documentation (creates all the reference docs).
