### ISSUE TITLE
OSCAL's role in mappings between standards

### ISSUE THREAD

**Issue by anweiss** [usnistgov/OSCAL#87]
Issue for tracking existing mappings and what OSCAL's role in any of them should be. Some examples below:

- [CCI <-> 800-53/800-53A](https://iase.disa.mil/stigs/cci/Pages/index.aspx)
- [HIPAA Security Rule crosswalk to CSF](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-66r1.pdf)
- [ISO/IEC 27001 <-> 800-53](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf) (Appendix H)
- [ISO/IEC 15408 (Common Criteria) <-> 800-53](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf) (Appendix H)
- [PCI DSS <-> 800-53](https://www.nist.gov/sites/default/files/documents/2017/04/21/2017-04-10_-_pci_security_standards_council.pdf)
- [CIS CSC <-> 800-53](https://www.cisecurity.org/wp-content/uploads/2017/03/Poster_Winter2016_CSCs.pdf?x60581)
- [CJIS Security Policy <-> 800-53](https://www.fbi.gov/file-repository/csp-v5_5-to-nist-controls-mapping-1.pdf/view)

**Comment by flickerfly** [comment]
I'm sure some folks have worked around this not yet being implemented. What workarounds and lessons have been learned? 

Also, Is there perhaps a better understanding of the problem now that we're a few years down the road that can help provide a clear direction for completion? Maybe it can be broken into some iterations to help bulid momentum and reduce the larger overwhelming nature of it?

**Comment by flickerfly** [comment]
> I am working on the Compliance Mapper project at MITRE as a restful web service that aligns and can return mappings from one standard to another ( such as CIS CSC to 800-53 - for example ) that I chatted with the NIST folks about a few months ago. The need is clear, so my team started working the solution, the question is where should it be hosted and who would maintain it.

I'm curious if anything ever came of this? If so, where did it get hosted?

**Comment by iMichaela** [comment]
@flickerfly - No, the NIST team did not receive any contributions from MITRE around such mapping model, but @david-waltermire-nist started the mapping module in collaboration with other contributors and we planned to have it released as part of OSCAL 1.1.0 (please see the list of milestones).

**Comment by david-waltermire-nist** [comment]
Need to add a few examples to PR #1150 to help illustrate the new catalog mapping features.

**Comment by tajinders** [comment]
@iMichaela As you mentioned that @david-waltermire-nist is working on providing support for the control mapping and it would be available as part of OSCAL 1.1.0. Could you or @david-waltermire-nist please help me understand the timelines for this release and when would support for the control mapping be available and would there be any document similar to the catalog/profile model that we can refer to understand the data format. 

Thanks in advance and would greatly appreciate your help in this regard !!

**Comment by iMichaela** [comment]
@tajinders - please the PR #1150. Please provide feedback. The community's feedback on the mapping and other enhancements scheduled for OSCAL 1.1.0 will drive the release date. We hope to be in approx 2-3 months, but as we make more progress and receive the feedback, we will provide a more accurate timeline.
