### ISSUE TITLE
JSON Arrays with Size Range of 0 to Unbounded Items Require at Least 1 Item in Their Schemas

### ISSUE THREAD

**Issue by ohsh6o** [usnistgov/OSCAL#870]
# Describe the bug

Per previous conversation earlier in the week, documentation indicates many array constructs generated from `in-json` as `ARRAY` types with the default `minOccurs` when represented in the JSON Schema for validation.

# Who is the bug affecting?

Anyone trying to form objects with `minOccurs="0"` and `maxOccurs="unbounded"` as an empty array in JSON, to be explicit instead of removing `revisions` or any similar property, will get a validation error, even though the documentation suggests otherwise.

# What is affected by this bug?

OSCAL Metaschema repreesentation of empty array types in JSON.

# When does this occur?

At any time.

# How do we replicate the issue?

Review docs and schema.

Here is an example of revisions in an OSCAL component.

<img width="1142" alt="Screen Shot 2021-03-23 at 5 20 45 PM" src="https://user-images.githubusercontent.com/61464190/112220436-a4553880-8bfc-11eb-8c1d-86d33171da4d.png">

<img width="1051" alt="Screen Shot 2021-03-23 at 5 18 13 PM" src="https://user-images.githubusercontent.com/61464190/112220440-a4edcf00-8bfc-11eb-89c4-0b8e1e930519.png">

OSCAL JSON Schema:
https://github.com/usnistgov/OSCAL/blob/d53cb8780862bc5b29fbda8d7acc3a9271001f8b/json/schema/oscal_component_schema.json#L25-L29

OSCAL XML Schema appears to be correct with a `minOccurs="0"` and not like the JSON:
https://github.com/usnistgov/OSCAL/blob/d53cb8780862bc5b29fbda8d7acc3a9271001f8b/xml/schema/oscal_component_schema.xsd#L63-L72

# Expected behavior (i.e. solution)

Allow explicit defining OSCAL objects in JSON with an array as expected, but with an empty array notation like `[]`.

# Other Comments

{Add any other context about the problem here.}

**Comment by david-waltermire-nist** [comment]
@wendellpiez I believe this is a JSON documentation bug,

The correct behavior we should see for `group-as in-json=ARRAY`:
- If the metaschema definition has a field or assembly with `min-occurs=0` then:
   -  the property should be optional
   - The array should require at least 1 item
- If the metaschema definition has a field or assembly with `min-occurs=x` (where X>0) then:
   -  the property should be requiredl
   - The array should require at least x items

This enforces the expected cardinality and allows the property to be omitted in the  `min-occurs=0` case if there is no data to provide.

The documentation should follow this same logic.

**Comment by wendellpiez** [comment]
@david-waltermire-nist have we confirmed that the JSON Schema (as opposed to the docs) does this correctly?

Either way I can add this to the PR in progress at usnistgov/metaschema#127

**Comment by wendellpiez** [comment]
Nix the question I see @ohsh6o has shown us most of the relevant JSON Schema snip up higher.
