### ISSUE TITLE
"subject" and/or "assessment-subject" ?

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#871]
In the assessment-plan schema, a single object "assessment-subject" is used three times, twice named **subject** (inside **task** and **associated-activity** ) and  once with the name (tag) **assessment-subject** (inside **assessment-plan**).

https://pages.nist.gov/OSCAL/documentation/schema/assessment-layer/assessment-plan/xml-schema/#global_assessment-subject_h2

This might not be a bug, as it's just a use of the `use-name` feature in two cases, but not the third.

However, it might be that the element should look the same wherever it appears.

@brian-ruf may have insight as to whether there is a design intention. Calling it (more explicitly) "assessment-subject" that one time may make the intended use clearer - while it complicates the docs and hides the commonality (Law of Conservation of Complexity).

Even if not a bug, a metaschema-checker (see #839) could report such incidences for cross-checking as they should be a deliberate decision, not a result of omission.

**Comment by brian-ruf** [comment]
In December, @david-waltermire-nist and I had a focused conversation on this as we refactored the assessment models.

In general, we tried to simplify to `subject`; however, I think we had some concerns with the root level assembly being simply `subject`. For that we settled on `assessment-subject`. This better also matched `assessment-assets` (for which where was a similar conversation).

I recommend leaving as-is unless there is a compelling reason to change it.

**Comment by wendellpiez** [comment]
@david-waltermire-nist @brian-ruf partly since this is a feature we have gone to some trouble to implement and test, I too think we should leave this as is -- the documentation is unwieldy, but we already knew that. Really what I think this shows is that the XML documentation as well as the JSON documentation needs to be reorganized to work cleanly from the user's point of view. (I am working on this.)

Meanwhile a Schematron check is not a bad idea either.

**Comment by david-waltermire-nist** [comment]
@wendellpiez and @brian-ruf I agree. Closing this issue.
