### ISSUE TITLE
More quickly finding elements in reference documentation

### ISSUE THREAD

**Issue by stephenbanghart** [usnistgov/OSCAL#872]
# User Story:

As an OSCAL user, I want to be able to quickly look up the definitions of various OSCAL elements in the reference documentation. For example [SSP Reference](https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/ssp/xml-schema/)

The navigation sidebar on the left lists the issues but scrolling is currently broken (Firefox 88.0b2 (64-bit)). See left sidebar in image below: 
![image](https://user-images.githubusercontent.com/13455523/112526479-5bc28a00-8d78-11eb-8821-0d78280351ee.png)

Additionally, the sidebar is not text searchable, so quickly jumping to an element is not possible.

## Goals:

I can find the definition pane for a given element without searching the text of the page and hoping I stumble onto the particular element.

## Dependencies:

A text searchable index or some way of text searching only the names of elements would solve this issue. Other solutions possible.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
This relates to #787.

**Comment by david-waltermire-nist** [comment]
PR #905 partially addresses this issue.

We are also working on an index page, and a list of common shared definitions, which will be submitted as separate PRs.

**Comment by david-waltermire-nist** [comment]
PR #948 adds an index to the documentation which will be posted to the website when 1.0.0 is released. This is a step towards addressing this issue. We need to look into search functionality next.
