### ISSUE TITLE
Easy access to OSCAL workshop recordings from the OSCAL pages

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#874]
# User Story:

As a new OSCAL user, I would benefit from having easy access to OSCAL recorded presentations.

## Goals:

Provide access to the latest recorded OSCAL presentations available here: [https://www.nist.gov/news-events/events/2021/02/2nd-open-security-controls-assessment-language-oscal-workshop](https://www.nist.gov/news-events/events/2021/02/2nd-open-security-controls-assessment-language-oscal-workshop) .  Probably, the best page would be the top  page for tutorials so people can watch first the videos before diving deeper into the existing tutorial for catalog and future tutorials for all types of OSCAL content.

## Dependencies:

none

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
Currently the workshop is posted on the [related resources](https://pages.nist.gov/OSCAL/downloads/other-resources/#videos-and-presentations) page. We can add this to the tutorial pages as well.

**Comment by david-waltermire-nist** [comment]
This was addressed in PR #906.
