### ISSUE TITLE
Typos and glitches in metaschema sources

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#875]
# Describe the bug

Renovation of the docs with the new sources is helping to reveal small errors.

So far, here is a list:

## oscal_assessment-common_metaschema.xml

- `/METASCHEMA/define-assembly[7]/model[1]/define-assembly[2]/model/define-field[1]/formal-name` is **Control Ojectives Description**

## implementation-common-metaschema.xml

- `//*[formal-name='title field']` shows there are two **title** fields given this (same) formal name. They should each have their own formal name and description.

NB alternatively many or all the **title** definitions inline could be consolidated into a global, as it appears there is no operational or semantic distinction among them. Possibly the same with **description**.

(Should we run spell check on the metaschema sources?)

**Comment by david-waltermire-nist** [comment]
Addressed by [commit](https://github.com/usnistgov/OSCAL/commit/dc0bffcb5459b17dca047565bf3075af5028dad5).
