### ISSUE TITLE
Links to oscal-content repository?

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#876]
# User Story:

As an OSCAL user and developer I would naturally like to know about (and show off) the [oscal-content repository](https://github.com/usnistgov/oscal-content).

Somewhat surprisingly, there is no link to this repo currently on the OSCAL site.

One potential location would be the "Related Resources" page at http://localhost:1313/OSCAL/downloads/other-resources/

We might also wish to have links to the [metaschema](https://github.com/usnistgov/metaschema), [oscal-tools](https://github.com/usnistgov/oscal-tools) and [hugo-uswds](https://github.com/usnistgov/hugo-uswds) repositories.

## Goals:

Help people find OSCAL data, especially but not only the current best OSCAL SP800-53.

## Dependencies:

None known.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by iMichaela** [comment]
@wendellpiez would it make sense to have an OSCAL content tab near documentation tab? We could explain the content and, for exemplar,  highlight the specifics of privacy baseline. Later we might need to include additional information on this page.

**Comment by wendellpiez** [comment]
@iMichaela I think the docs on the content repo should be kept there, and whatever the value of adding or rearranging tabs or menus, I think an easy short-term fix would be just to drop in the links. 🚀

**Comment by iMichaela** [comment]
@wendellpiez -I agree that OSCAL content documentation needs to remain in the GitHub repo. I was proposing to have pages for the OSCAL content linked to the pages.nist.gov/OSCAL through a tab on top that redirects to the OSCAL-content pages. In this way they can be maintaining separately, but will appear to the public as connected.

**Comment by wendellpiez** [comment]
Sure, not opposed to that idea! However, it requires a higher level of effort (significantly higher in my view).

**Comment by iMichaela** [comment]
@wendellpiez - on the OSCAL-content site it needs a change in the settings , a nist-pages branch (or point the pages to the master branch) and an index.md file with the proper information. To keep the same style as OSCAL, might need more work. We can ask @david-waltermire-nist what he prefers. Anything is better than nothing.

**Comment by wendellpiez** [comment]
👍 Agreed. We might need two work items, one for oscal-contents repo, one for OSCAL site (pointing to it). I am not sure we wish to stand up Hugo for oscal-contents; there may also more lightweight options available.

**Comment by david-waltermire-nist** [comment]
We have lots of links from the site to the oscal-content repo. I did a quick grep and found over 100 links.  I think based on this discussion we need to add a few new strategic links in a few places, to include the top navigation. I don't think creating a new site for content is worth it. Creating a site is a large amount of work for a small incremental amount of value.

**Comment by david-waltermire-nist** [comment]
The OSCAL site points to the the OSCAL content repository in the following locations:
- https://pages.nist.gov/OSCAL/downloads/#sources-of-oscal-content
- https://pages.nist.gov/OSCAL/documentation/schema/catalog-layer/catalog/#nist-sp-800-53-revision-4-annotated-example
- https://pages.nist.gov/OSCAL/documentation/schema/profile-layer/profile/#content-examples
- https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/ssp/#content-examples
- https://pages.nist.gov/OSCAL/documentation/examples/

The [metaschema](https://github.com/usnistgov/metaschema) repo is linked here:
- https://pages.nist.gov/OSCAL/documentation/schema/overview/#modeling-approach

The [oscal-tools](https://github.com/usnistgov/oscal-tools) repo is linked here:
- https://pages.nist.gov/OSCAL/tools/#oscal-project-open-source-tools-and-libraries

The [hugo-uswds](https://github.com/usnistgov/hugo-uswds) repo is not linked.

We will continue to improve the linking to these resources going forward.
