### ISSUE TITLE
uuid-ref Consistency

### ISSUE THREAD

**Issue by SilentEsper** [usnistgov/OSCAL#898]
# User Story:

As an OSCAL Application developer, I would like consistency in the structure of fields named uuid-ref

## Goals:
_uuid-ref_  fields usually have a type associated. There are cases such as _select-subject-by-id_ where the type is contextual. The type is likely expecting only subject uuids, so I suggest this be renamed to subject-uuid-ref , subject-ref or _subject-uuid_  to be more clear , I also suggest assuring that _uuid-ref_ is always paired with a _type_ so the references can be found/captured easily.  optionally, _uuid-ref_ could be an object that contains type & uuid together as a single object, for instance :
    `{"uuid-ref":{type:"component",uuid:v4()}}.`
 This however, may be too drastic of a change.
 I believe assuring that _uuid-ref_ fields always have a _type_ on the same level would be enough for developers resolve uuid-refs easily.

## Acceptance Criteria

- [ ] All _uuid-ref_ fields are paired with a _type_ field

**Comment by david-waltermire-nist** [comment]
@SilentEsper Can you give PR #928 a review?

**Comment by david-waltermire-nist** [comment]
Addressed by PR #928.
