### ISSUE TITLE
Stabilize schema and maintenance model

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/OSCAL#9]
The core schema is now in RNC but developers will want a stable XSD.

We need to build and use, at least once, a bridge. The XSD produced by Trang looks good. An XSLT stylesheet can be applied that injects documentation for use by tools. Both these steps could potentially be run in an XProc or "by hand" in oXygen.

The documentation injection XSLT can also take responsibility for schema boilerplate that needs to be added to the schema Trang produces from our upstream source. (Note however that Schematron rules will not be injected, at least for now.)

**Comment by anweiss** [comment]
@david-waltermire-nist @wendellpiez suggest closing this in favor of the newer related tracking items.

**Comment by david-waltermire-nist** [comment]
Agreed. Closing.
