### ISSUE TITLE
OSCAL documentation  wrong description for `entry` under `risk-log`

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#907]
# Describe the bug
In the OSCAL documentation, the `entry` under `risk-log` is described using the same statement from `entry` under `assessment-log`

The statement used is: "Identifies the result of a task that occurred as part of executing an assessment plan or an assessment event that occurred in producing the assessment results."

# Who is the bug affecting?
All users of the documentation

# What is affected by this bug?
The reference documentation

# When does this occur?
When reading it ...

# How do we replicate the issue?
go to: [https://pages.nist.gov/OSCAL/documentation/schema/assessment-results-layer/assessment-results/xml-schema/#global_risk](https://pages.nist.gov/OSCAL/documentation/schema/assessment-results-layer/assessment-results/xml-schema/#global_risk) or to its JSON counterpart.

**Comment by david-waltermire-nist** [comment]
@iMichaela Can you give PR #927 a review?

**Comment by david-waltermire-nist** [comment]
This has been addressed in PR #927. Some further refinement of the text may still occur.
