### ISSUE TITLE
Extra files (images) in the nist-pages branch need to be removed

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#908]
# Describe the bug
The `nist-pages` branch has images like `hero.png` that should not be there. There are also many icons that might not be free and not being used in the OSCAL website. Identifying all unused images and icons (in particular if not free) would be strongly recommended.

# Who is the bug affecting?

# What is affected by this bug?

# When does this occur?

# How do we replicate the issue?

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

# Other Comments

**Comment by david-waltermire-nist** [comment]
There is only one file named [hero.png](https://github.com/usnistgov/OSCAL/blob/nist-pages/img/hero.png). This file is from the United States Web Design System (USWDS) [Hugo theme](https://github.com/usnistgov/hugo-uswds/blob/master/static/img/hero.png). The image is provided as [part](https://github.com/uswds/uswds/blob/develop/src/img/hero.png) of the USWDS distribution, which is licensed under the [CC0 1.0 Universal public domain dedication](https://creativecommons.org/publicdomain/zero/1.0/). As a result, there is no intellectual property-related issue.

Some of the other files (e.g., icons, CSS, etc) are also distributed by the USWDS. These are licensed according to the [USWDS license](https://github.com/uswds/uswds/blob/develop/LICENSE.md) or another referenced license which permits our free use.

You indicate that there are other files too. It would be nice to pare the files published down to just the files used by the site, but there isn't a good automatic way to do this given the current state of the CI/CD process that builds the site.

Given the above, this is not a bug per se, although it would be useful to reduce the clutter some. Can you resubmit this as a feature request or provide a solution?

**Comment by iMichaela** [comment]
@david-waltermire-nist . Created the feature request. I am glad the files spotted are not left from the first implementation of the website when we had contractual support. Closing this bug
