### ISSUE TITLE
Metadata Section Tutorial

### ISSUE THREAD

**Issue by stephenbanghart** [usnistgov/OSCAL#909]
## User Story:

As an OSCAL content creator, I need to understand how to use the common Metadata Section.

## Goals:

Create a tutorial that explains the Metadata section and how to create/parse one.    

Related to #654.

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
This will be addressed by PR #940.
