### ISSUE TITLE
OSCAL reference documentation - empty `Constraints` 

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#912]
# Describe the bug

In the OSCAL reference documentation, there are empty `Constraints` with statements reading:
 _> Constraints that may apply to the data value of this element (in context):_ 
which expand to nothing, leaving the statement incomplete.

# Who is the bug affecting?

# What is affected by this bug?

# When does this occur?

# How do we replicate the issue?

Go to any 'reference' page and use browser search to find the statements listed above.

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

# Other Comments

**Comment by david-waltermire-nist** [comment]
@iMichaela I did an XPath search of the metaschemas using `//(*:constraints|*:constraint)[not(*)][not(normalize-space())]`. I found 3 instances, which might be causing this, but its hard to tell without more specifics.

Can you provide a few specific examples of where you are seeing this?

**Comment by iMichaela** [comment]
@david-waltermire-nist There are multiple instances of this error on each reference page for the XML formats (see bottom of the image below).

![image](https://user-images.githubusercontent.com/13984545/117189995-d71e4f00-adac-11eb-860a-e63e5bf0688e.png)

assessment results model: 16 instances (the first one is under `addr-line` - see above)
poa&m: 15 instances
assessment plan: 14
component definition model: 12
ssp: 19
profile model: 14
control model: 13

**Comment by wendellpiez** [comment]
@david-waltermire-nist is probably correct as to the upstream cause. However the data anomaly should be tolerated (and not produce the empty stub). Removing placeholders from the data then becomes an option.

Let's see to it this is corrected with usnistgov/metaschema#120.

**Comment by wendellpiez** [comment]
Provision to prevent the unwanted output for 'stub' content has been made in PR usnistgov/metaschema/#135.

**Comment by david-waltermire-nist** [comment]
The reference documentation on the website has been completely revamped. This new documentation will be released with OSCAL 1.0.0. This issue was addressed by PR #948.
