### ISSUE TITLE
Automatic cleanup of `nist-pages` branch

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#913]
# User Story:

The `nist-pages` branch has images like `hero.png` and others provided by the United States Web Design System (USWDS) [Hugo theme](https://github.com/usnistgov/hugo-uswds/blob/master/static/img/hero.png). 

There are also many icons not used on OSCAL website and cleaning the repo of unused files would be desirable.

## Goals:

It would be beneficial to find an automatic way of paring the files published down to just the files used by the site, and remove the not used ones

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-nist** [comment]
This issue appears to be obsolete and can now be closed.
