### ISSUE TITLE
Remove requirement to have at least one Assessment Results Finding

### ISSUE THREAD

**Issue by degenaro** [usnistgov/OSCAL#918]
# User Story:

As an OSCAL tool developer, I would like Assessment Results to have Findings be an optional value.

## Goals:

In one case during a first phase we accumulate Observations from validation points into a "partial" Assessment Results, meaning no Findings can be made with the data available. Later in a second phase we employ Assessment Plan and Security Plan to make Findings based on the first phase Observations. 

Currently to produce valid OSCAL during the first phase we create a "placeholder" Finding to satisfy the at least one Finding requirement of the Assessment Results. Preferable would be to remove the requirement.

## Dependencies:

N/A

## Acceptance Criteria

- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
@degenaro I think this gets to a philosophical point about the OSCAL models that have usage implications.

In your view do the OSCAL schemas represent:

1. any valid interim state of information aligned with an OSCAL model. e.g., a less than complete assessment is ok,
2. A complete set of information aligned with an OSCAL model to satisfy the model's intended purpose. e.g., an assessment without a finding is not a completed assessment.

I believe item 1 is at odds with item 2. If you want to verify that you have a complete assessment (item 2), you can't do that if we make the schema loose to support item 1.

Today, the schemas are built to support item 2. I think we need to talk with the community about this before moving forward.

**Comment by degenaro** [comment]
I think 0 findings supports both cases. I think 0 observations does not. That is, how can you have a finding without an observation? Conversely, you can have observations without findings. For example, say you have 1 observation which is "not applicable". There would be no finding in that case, since neither satisfied nor not satisfied is known.

That said, the specific case I had in mind is indeed partial results as indicated in the original text. I think intermediate results (e.g observations only) are valid and will be a usual case for us. To have to use either an illegal or "misused"  OSCAL or some non-OSCAL document is much less desirable.

Forcing at least one does not really make a document more valid. Perhaps you should have had 100 findings, but you only have 1. Legal, yes. Worth anything, no so much.

The utility for us is greatly increased by relaxing the at least one finding requirement. I see little harm. If there is real worry, then add a flag that says this is a partial results which permits 0 findings in that case.

**Comment by david-waltermire-nist** [comment]
@degenaro We are working on tooling that would allow for constraint-based schema customizations, which would provide a perfect solution here. It would allow an "OSCAL complete", which could check for at least one finding, and an "OSCAL lite" variant which could be more permissive. We are not quite ready for that yet though.

Regarding my previous breakdown (item 1 and 2), we need to decide as a community what the OSCAL schemas represent. I will argue that they represent a point of data agreement when data is handed off between two different parties. This is because OSCAL is a "data exchange" format. This is where item 2 is most important. It can be used as a "data persistence" format, which is more of the item 1 case.

**Comment by degenaro** [comment]
Nevertheless, it seems "OSCAL complete" can comprise 0 findings. A request may be: give me SAR with AC-3 Finding for inventory item X, and the answer may be there is no such Finding.

**Comment by david-waltermire-nist** [comment]
@degenaro Would you please review PR #931?

**Comment by degenaro** [comment]
Just did!  Thx.

Lou.

**Comment by david-waltermire-nist** [comment]
This was addressed in PR #931.
