### ISSUE TITLE
No Binding for `predecessor-version` and `successor-version` on `/o:metadata/o:revision/o:link/@rel`

### ISSUE THREAD

**Issue by ohsh6o** [usnistgov/OSCAL#919]
# Describe the bug

The current OSCAL Metaschema definitions, or perhaps just the documentation, suggest that a developer can implement OSCAL model instances with `predecessor-version` and `successor-version` in `/o:metadata/o:link/@rel`, but not on `/o:metadata/o:revision/o:link/@rel`.

# Who is the bug affecting?

Developers who wish to follow [@stephenbanghart's  guidance in his document ID and modeling presentation in March 2021](https://raw.githubusercontent.com/usnistgov/OSCAL/f44426e0ec14431b88833dbd381b5434d0892403/docs/content/contribute/model-review/document-id.pdf).

# What is affected by this bug?

Cross-reference of document versions.

# When does this occur?

Those who want to add version information to the revision data as recommended.

# How do we replicate the issue?

Create an OSCAL object model instance and not add link `@rel` data and not the general link metadata, but at `/o:metadata/o:revision/o:link/@rel`.

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

Allows its use in both.

# Other Comments

Gitter threads: https://gitter.im/usnistgov-OSCAL/Lobby?at=6090340dff705616c76dde40

**Comment by david-waltermire-nist** [comment]
@ohsh6o Checkout PR #922. I think this addresses this issue.
