### ISSUE TITLE
Refine OSCAL Implementation Model

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#92]
Goals:
- Stabilize the OSCAL Implementation Model and ensure all necessary features are implemented
- Based off #91, evaluate feedback and prioritize changes to the model

Dependencies:
- #91 

Acceptance Criteria: 
- Stable OSCAL Implementation Model
- Additional criteria TBD based on feedback

**Comment by david-waltermire-nist** [comment]
This is being worked in #363, #364, and #329. Closing.
