### ISSUE TITLE
links in https://github.com/usnistgov/OSCAL/tree/main/src/metaschema#readme produce 404 errors

### ISSUE THREAD

**Issue by chris-day** [usnistgov/OSCAL#926]
# Describe the bug

The links in the readme.md here https://github.com/usnistgov/OSCAL/tree/main/src/metaschema#readme produce 404 errors in this section of the text 

The Metaschema syntax (an XML application) is also described and constrained with its own schema, and with a Schematron constraints set. The latter is able to enforce some of the rules described below.

# Who is the bug affecting?
Those reading the readme.md and wanting to know more about the metaschema

# What is affected by this bug?
Dissemination of information about the metaschema

{Describe the impact the bug is having.}
404 errors

# When does this occur?
When you try and follow the links

{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?
Click on https://github.com/usnistgov/OSCAL/tree/main/src/metaschema#readme
At the bottom of the first section, click on either "own schema" or  "Schematron constraints set."

# Expected behavior (i.e. solution)

The links take you to the correct pages for the metaschema and the Schematron constraints set

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by david-waltermire-nist** [comment]
@chris-day Can you give PR #930 a review?

**Comment by david-waltermire-nist** [comment]
Fixed by PR #930.
