### ISSUE TITLE
Request for Comment: Updates for Landing Page

### ISSUE THREAD

**Issue by ohsh6o** [usnistgov/OSCAL#938]
# User Story:

As a novice OSCAL user with limited background and no prior experience, in order to best understand how OSCAL applies to my current environment and practices to meet compliance and cybersecurity needs, I would like a revised landing page that better explains the upfront benefit.

## Goals:

Per last week's developer meeting, @david-waltermire-nist had requested an issue be created as a request for comment from the OSCAL community regarding changes to the landing page to better introduce OSCAL to novice users and adopters, separate of the technical content.

Dave and the NIST OSCAL dev team asked that feedback be provided by issues such as this to make it easier to track feedback and accepted recommendations.

**Comment by aj-stein-nist** [comment]
Given the age of this one and the limited feedback, need to go back to the team and ask if this is serviceable or not, perhaps we move to close.

**Comment by david-waltermire-nist** [comment]
@aj-stein-nist We can do this at any point once we get some input. I'd say keep this in the backlog until we are prepared to move forward.

**Comment by guyzyl** [comment]
IMO adding a "quick start guide" to the landing page would better introduce new users to OSCAL.
It'll help new users understand how they can start using OSCAL, and how can it be introduced into their organization.

**Comment by aj-stein-nist** [comment]
> IMO adding a "quick start guide" to the landing page would better introduce new users to OSCAL. It'll help new users understand how they can start using OSCAL, and how can it be introduced into their organization.

I guess that is a good point. I think the hard implied question is: who is the "new user" to OSCAL? You might be [a security assessor, a security professional, or a developer writing security software that could use OSCAL](https://pages.nist.gov/OSCAL/about/stakeholders/). All of them are a little or significantly different as new users. Does that mean one quick start guide or multiple? What would be the right quick start if we wanted to somehow unify all of them?

Definitely interested in feedback here!

**Comment by guyzyl** [comment]
> > IMO adding a "quick start guide" to the landing page would better introduce new users to OSCAL. It'll help new users understand how they can start using OSCAL, and how can it be introduced into their organization.
> 
> I guess that is a good point. I think the hard implied question is: who is the "new user" to OSCAL? You might be [a security assessor, a security professional, or a developer writing security software that could use OSCAL](https://pages.nist.gov/OSCAL/about/stakeholders/). All of them are a little or significantly different as new users. Does that mean one quick start guide or multiple? What would be the right quick start if we wanted to somehow unify all of them?
> 
> Definitely interested in feedback here!

I think the fastest one to get off the ground would be a quick start that assumes knowledge in security, introduces the reader to OSCAL and gives concrete examples on how to get started using it.
Slides 58-110 [here](https://pages.nist.gov/OSCAL/learn/presentations/OSCAL-workshop-20191105.pdf) do a great job of introducing the model's layers alongside XML examples to show what they look like in reality.

**Comment by iMichaela** [comment]
> Slides 58-110 [here](https://pages.nist.gov/OSCAL/learn/presentations/OSCAL-workshop-20191105.pdf) do a great job of introducing the model's layers alongside XML examples to show what they look like in reality
