### ISSUE TITLE
Develop Profile layer documentation that is edited and ready for public review

### ISSUE THREAD

**Issue by akarmel** [usnistgov/OSCAL#94]
Goals:
- Develop usable Profile layer documentation targeted towards Profile creators for public review

Dependencies:
- Issue #93 
- Issue #95 

Acceptance Criteria:
- Documentation developed to a sufficient level of detail for a technical user to understand the profile layer (XML and JSON)
- Documentation should be edited and ready for public review

**Comment by anweiss** [comment]
**June 21 Status:** No updates on my end.

**Comment by anweiss** [comment]
## 09/27/2018 ##

Discussed metaschema nuances with @wendellpiez. Refactoring oscalkit to automatically generate its own types based on the metaschema. This will enable oscalkit to generate profile documentation per the requirements of this issue; in addition to the XSLT being crafted to do the same.

**Comment by wendellpiez** [comment]
This Issue can be closed and/or reallocated in view of the current status of the site. See also #131. We now have auto-generated documentation of the Profile model as of the Catalog model. So we are ahead of where we were but much remains to be done.

**Comment by david-waltermire-nist** [comment]
I agree that we have documentation for Profiles, although I am sure it can be improved. We can address those improvements in the future, while considering any public feedback.
