### ISSUE TITLE
OSCAL website - Component Definition page is referring to 'profile' instead of 'component definition'

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#946]
# Describe the bug

![Screen Shot 2021-06-02 at 5 01 23 PM](https://user-images.githubusercontent.com/13984545/120551841-7d696e80-c3c4-11eb-8938-d830c574d960.png)

# Who is the bug affecting?

# What is affected by this bug?

{Describe the impact the bug is having.}

# When does this occur?

{Describe the conditions under which the bug is occurring.}

# How do we replicate the issue?

{What are the steps to reproduce the behavior?
1. Do this...
1. Then this...
1. See error

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

{A clear and concise description of what you expected to happen.}

# Other Comments

{Add any other context about the problem here.}

**Comment by david-waltermire-nist** [comment]
This is fixed in PR #950 and will be deployed with the OSCAL 1.0.0 website updates.
