### ISSUE TITLE
OSCAL pages scrolling enhancement

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#967]
# User Story:

As an OSCAL user, I need an easier way to scroll up and down the large reference pages, in particular, the ALL models reference pages 

## Goals:

A sticky widget allowing to jump to the top or to the bottom, or to scroll up/down skipping several pages at a time will be very useful.

## Dependencies:

none

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by david-waltermire-nist** [comment]
We added the sticky right navigation to the reference pages. I believe this is sufficient to address this issue.

@iMichaela please confirm or provide some additional requirements.

**Comment by iMichaela** [comment]
@david-waltermire-nist The right side sticky navigation bar improves the page's navigation and allows the reader to jump up and down. We can close the issue.
