### ISSUE TITLE
Add optional ns attribute to Parameter

### ISSUE THREAD

**Issue by degenaro** [usnistgov/OSCAL#982]
# User Story:

As an OSCAL tool developer, I would like `Parameter` to have an optional `ns` attribute in order to differentiate the associated instance from other Parameters.

Example:
```
"params": [
      {
        "id": "mycorp_minimum_password_length",
        "ns": "http://mycorp.github.io/compliance-trestle/schemas/oscal/cd/mycorp_id"
        "label": "Minimum Password Length",
        "usage": "Ensure mycorp_id password policy requires minimum length of 12 characters",
        "guidelines": [
          {
            "prose": "The first listed value option is set by default in the system unless set-parameter is used to satisfy a control requirements. Type Integer."
          }
        ],
        "values": [
          "12,8"
        ]
      },
      ...
```

## Goals:

There may be more than one instance of a Parameter each applicable in a different context.

## Dependencies:

N/A

## Acceptance Criteria

- [x] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [x] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by iMichaela** [comment]
@degenaro Could you please elaborate more on the use case? A parameter is set by the organization (policy-driven) but is set at the system level in the SSP. In a component definition, MAYBE one can specify different implementations of the same control to satisfy different baselines (e.g. FedRAMP for cloud components vs NIST SP 800-53 for on-premises components).

**Comment by david-waltermire-nist** [comment]
@degenaro I'd like to better understand the use case as well.

As far as adding the namespace to parameters, this would also require adding a namespace to all parameter references as well. I am concerned that this is a big change to do in a minor revision, since it changes the way that cross references are handled.

**Comment by degenaro** [comment]
We use `ns` and `class` for ontologies. Presently this is possible with `Property`, since it has ns + class but not possible with `Parameter` since it has class but not ns.

**Comment by iMichaela** [comment]
@degenaro Thank you for the additional information. Could you please present a larger picture/scenario and highlight the impact of the missing `ns` under `parameter` on the adoption of OSCAL in general not only for the IBM/trestle so we can assess the request with the community during the next OSCAL meeting (hopefully this Friday)? Your participation in the meeting, to discuss your request, is greatly appreciated and helps us understand and assess its importance and need for OSCAL adoption, in particular when the request triggers cascading updates/changes.
 Thank you.

**Comment by david-waltermire-nist** [comment]
There hasn't been a response on the question from @iMichaela. There also hasn't been support for this issue from others. Closing this issue due to the lack of discussion and support.
