### ISSUE TITLE
RFC: Feedback on Constraint Values for Digital Identity AAL, IAL, FAL

### ISSUE THREAD

**Issue by ohsh6o** [usnistgov/OSCAL#985]
# User Story:

As an OSCAL developer, in order to have more ergonomic definition and use of constraint allowed values around digital identity requirements.

## Goals:

Currently, FISMA RMF-baseed authorizations more generally will optionally encode digital identity standards per 800-63. FedRAMP system security plans require them and previously encoded them as FedRAMP values or FedRAMP extension constraints. In the interim, OSCAL has [encoded these constraints directly into NIST OSCAL for the SSP model](https://github.com/usnistgov/OSCAL/blob/6244d44b5a0aacb270d7fc4054130e3b3f0e6ab6/src/metaschema/oscal_ssp_metaschema.xml#L120-L136). 10x developers have stated a preference we modify the generalized supported values of `1`, `2`, and `3` for `FAL1`, `AAL1`, `IAL1`, `FAL2`, et cetera. Whether or not FedRAMP PMO opts for this change explicitly, this will conflict in a minor or more significant way if we do opt to do so.

See GSA/fedramp-automation#112 for details.

Per discussion for @david-waltermire-nist and @wendellpiez, I would like to discuss modifying these in "upstream" OSCAL through open RFC here and subsequent model review meeting, if applicable.

## Dependencies:

None

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by ohsh6o** [comment]
@wendellpiez and @GaryGapinski, per ongoing conversation, I updated the values to be capital for legibility. Is this a better suggestion for now?

**Comment by GaryGapinski** [comment]
I think capital letters for each of the SP 800-6303 assurance levels (thus matching the 800-63-3 parlance) is optimal.

**Comment by david-waltermire-nist** [comment]
To implement this in OSCAL 1.1, we would need to deprecate the existing `1`.`2`, and `3` values and add the new values. This does mean than both the old and new values need to be supported by parsers.

**Comment by david-waltermire-nist** [comment]
Not hearing any additional feedback on this, I am going to close this issue for now. We can reopen it at a future date if anyone feels strongly that this should be addressed.
