### ISSUE TITLE
OSCAL Website/Tools update with new information

### ISSUE THREAD

**Issue by iMichaela** [usnistgov/OSCAL#993]
# User Story:

As an OSCAL user/consumer, I would like to learn about all available OSCAL tools.

## Goals:

Maintain on ht OSCAL website a list of all OSCAL tools vendors submitted to us for posting.
Include on the Tools page the following information (formated as needed:

| Name | Provider/Developer | Description | URL |
|-------| ---------------------|:------------------------------------------:|---------------------------------------|
| OSCAL React Component Library | Easy Dynamics | A library of reusable React components that, when assembled, can render catalogs, profiles, components, and SSPs. | [https://github.com/EasyDynamics/oscal-react-library](https://github.com/EasyDynamics/oscal-react-library) |
| OSCAL REST API |  Easy Dynamics | A REST API that describes how systems might manipulate catalogs, profiles, components, and SSPs. |  [https://github.com/EasyDynamics/oscal-rest ](https://github.com/EasyDynamics/oscal-rest )|
| OSCAL Content Viewer | Easy Dynamics | A sandbox/demo viewer or OSCAL content | [https://oscal-viewer.msd.easydynamics.com/catalog](https://oscal-viewer.msd.easydynamics.com/catalog) |

## Dependencies:

none

## Acceptance Criteria

- [ ] All [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes in this issue have been updated. Changes to the OSCAL website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by butler54** [comment]
@iMichaela -> Can we add Compliance trestle to this list:
**Name**|**Provider/Developer**|**Description**|**URL**
|:-----:|:-----:|:-----:|:-----:|
| Compliance trestle | IBM | A python SDK and command line tool which manipulates oscal structures and supports tranformation of data into oscal. |https://github.com/IBM/compliance-trestle |

**Comment by iMichaela** [comment]
@butler54 Thank you for allowing us to list Compliance Trestle on OSCAL Tools page!

**Comment by rgauss** [comment]
@david-waltermire-nist, should we look at creating a PR for this?
